/-
Copyright Supranational LLC (the routines, transcribed from Semolina v0.1.4).
Copyright (c) 2026 the pasta-asm contributors (the transcription and the proofs).
Released under the Apache License, Version 2.0, as described in the file LICENSE.
-/
import PastaAsm.AArch64.Spec.Add
import PastaAsm.AArch64.Spec.Sub
import PastaAsm.AArch64.Spec.Mul
import PastaAsm.AArch64.Spec.Square

/-!
# Correctness of the transcribed Pasta Montgomery blocks

Each theorem under this module is proved over the transcription in `Transcription.lean`, instruction
by instruction. The proof of a block begins by unfolding it in the hypothesis that names its
result; then, for every instruction, its `let`s are extracted from that hypothesis under unique
names, the defining equation of its result (by `rfl`, in `%`/`/` form) and the linear facts that
follow from it (each an instance of one lemma) are recorded, and the locals' values are cleared.
Those lines are generated by `lean/scripts/gen.py --skeleton <routine>` and must not be edited;
the hand-written parts are the theorem statements and the `-- BEGIN ... -- END` blocks, which
supply what the instruction stream alone does not: the Montgomery round invariants where they
hold, the contract of a called round, and the final case analysis. `lean/scripts/check.sh`
strips the blocks and checks that what remains is the current skeleton.

The moduli are assumed in the shape the code hard-codes: limbs `[p0, p1, 0, 2^62]`, with
`inv * p0 ≡ -1 (mod 2^64)`.

Every module of the spec is imported here, so that a build of the root builds all of
them and the nanoda re-check (`lean/scripts/check_nanoda.sh`) exports all of them.
-/
