import PastaCurves.Fields

/-!
# The field types' constants

GENERATED by `lean/scripts/gen.py` from `src/fields/fp.rs` and `src/fields/fq.rs`; do not edit by
hand. Each example states one constant of a field type, with its limbs as the Rust source writes
them. The modulus and `INV` are checked against the fields of `Fields.lean`, and `R`, `R2`, `R3`,
and `V0` against their definitions at the field's modulus, by kernel evaluation.
`lean/scripts/check.sh` regenerates this file and fails if it differs, so a constant changed in
the field types is checked here too.
-/

namespace PastaCurves.FieldTypes

-- `fp::MODULUS`: the modulus limbs of `pallasBase`.
example : pallasBase.modulus =
    ⟨0x992d30ed00000001, 0x224698fc094cf91b, 0x0000000000000000, 0x4000000000000000⟩ := by
  decide

-- `fp::INV`: the Montgomery constant of `pallasBase`.
example : pallasBase.inv = 0x992d30ecffffffff := by
  decide

-- `fp::R`: `R mod p`.
example : let p := pallasBase.modulus.toNat
    let x := Limbs.toNat
      ⟨0x34786d38fffffffd, 0x992c350be41914ad, 0xffffffffffffffff, 0x3fffffffffffffff⟩
    x = R % p := by
  decide +kernel

-- `fp::R2`: `R^2 mod p`.
example : let p := pallasBase.modulus.toNat
    let x := Limbs.toNat
      ⟨0x8c78ecb30000000f, 0xd7d30dbd8b0de0e7, 0x7797a99bc3c95d18, 0x096d41af7b9cb714⟩
    x = R^2 % p := by
  decide +kernel

-- `fp::R3`: `R^3 mod p`.
example : let p := pallasBase.modulus.toNat
    let x := Limbs.toNat
      ⟨0xf185a5993a9e10f9, 0xf6a68f3b6ac5b1d1, 0xdf8d1014353fd42c, 0x2ae309222d2d9910⟩
    x = R^3 % p := by
  decide +kernel

-- `fp::V0`: `2^562 mod p`.
example : let p := pallasBase.modulus.toNat
    let x := Limbs.toNat
      ⟨0x9a5f583ce5084635, 0x4f417e233776c195, 0x74634b1a733f7785, 0x1c51de5ea66f0f25⟩
    x = 2^562 % p := by
  decide +kernel

-- `fq::MODULUS`: the modulus limbs of `vestaBase`.
example : vestaBase.modulus =
    ⟨0x8c46eb2100000001, 0x224698fc0994a8dd, 0x0, 0x4000000000000000⟩ := by
  decide

-- `fq::INV`: the Montgomery constant of `vestaBase`.
example : vestaBase.inv = 0x8c46eb20ffffffff := by
  decide

-- `fq::R`: `R mod p`.
example : let p := vestaBase.modulus.toNat
    let x := Limbs.toNat
      ⟨0x5b2b3e9cfffffffd, 0x992c350be3420567, 0xffffffffffffffff, 0x3fffffffffffffff⟩
    x = R % p := by
  decide +kernel

-- `fq::R2`: `R^2 mod p`.
example : let p := vestaBase.modulus.toNat
    let x := Limbs.toNat
      ⟨0xfc9678ff0000000f, 0x67bb433d891a16e3, 0x7fae231004ccf590, 0x096d41af7ccfdaa9⟩
    x = R^2 % p := by
  decide +kernel

-- `fq::R3`: `R^3 mod p`.
example : let p := vestaBase.modulus.toNat
    let x := Limbs.toNat
      ⟨0x008b421c249dae4c, 0xe13bda50dba41326, 0x88fececb8e15cb63, 0x07dd97a06e6792c8⟩
    x = R^3 % p := by
  decide +kernel

-- `fq::V0`: `2^562 mod p`.
example : let p := vestaBase.modulus.toNat
    let x := Limbs.toNat
      ⟨0xa3efbd8ee5083303, 0xfbadea62cefef7a1, 0xd6418abb493f6cf9, 0x2aa5feb88c401333⟩
    x = 2^562 % p := by
  decide +kernel

end PastaCurves.FieldTypes
