import PastaCurves.Fields

/-!
# The backend tests' known answers

GENERATED by `lean/scripts/gen.py` from the `Field` constants of `src/asm/tests.rs`; do not edit by
hand. The tests take each field's modulus and Montgomery constants from its field type, and write
their other expected values as literals. Each example here states one such literal, with its limbs
in the tests' order, and checks it against its definition at the field's modulus, by kernel
evaluation. `lean/scripts/check.sh` regenerates this file and fails if it differs, so a literal
changed in the tests is checked here too.
-/

namespace PastaCurves.KnownAnswers

-- `FP.two_r`: `2R mod p`.
example : let p := pallasBase.modulus.toNat
    let x := Limbs.toNat
      ⟨0xcfc3a984fffffff9, 0x1011d11bbee5303e, 0xffffffffffffffff, 0x3fffffffffffffff⟩
    x = (2*R) % p := by
  decide +kernel

-- `FP.three_r`: `3R mod p`.
example : let p := pallasBase.modulus.toNat
    let x := Limbs.toNat
      ⟨0x6b0ee5d0fffffff5, 0x86f76d2b99b14bd0, 0xfffffffffffffffe, 0x3fffffffffffffff⟩
    x = (3*R) % p := by
  decide +kernel

-- `FP.r4`: `R^4 mod p`.
example : let p := pallasBase.modulus.toNat
    let x := Limbs.toNat
      ⟨0x1dfc65f6ad0492ae, 0x84379b4cc10e927b, 0x710d6cd04c692c97, 0x21cce888a6cab566⟩
    x = R^4 % p := by
  decide +kernel

-- `FP.r7`: `R^7 mod p`.
example : let p := pallasBase.modulus.toNat
    let x := Limbs.toNat
      ⟨0x7a3a1c29d1d1bd45, 0x17023e5920bb6157, 0x9004eaaf35c21e06, 0x007efbf9151076fc⟩
    x = R^7 % p := by
  decide +kernel

-- `FP.pm1_sq`: the Montgomery square of `p-1`, `(p-1)^2 R^-1 mod p`.
example : let p := pallasBase.modulus.toNat
    let x := Limbs.toNat
      ⟨0xcf3f8e8753a769a9, 0xac9fba6a4077fc57, 0x70cb2996efc89a65, 0x21f1c4ff1e2278d5⟩
    x < p ∧ (x*R) % p = ((p-1) * (p-1)) % p := by
  decide +kernel

-- `FP.pm2`: `p - 2`.
example : let p := pallasBase.modulus.toNat
    let x := Limbs.toNat
      ⟨0x992d30ecffffffff, 0x224698fc094cf91b, 0x0000000000000000, 0x4000000000000000⟩
    x = p - 2 := by
  decide +kernel

-- `FP.from_mont_ones`: the conversion of the all-ones input, `(2^256 - 1) R^-1 mod p`.
example : let p := pallasBase.modulus.toNat
    let x := Limbs.toNat
      ⟨0xc9eda265ac589659, 0x75a6de91c8d4fcc3, 0x8f34d6691037659a, 0x1e0e3b00e1dd872a⟩
    x < p ∧ (x*R) % p = (2^256 - 1) % p := by
  decide +kernel

-- `FP.e0`: `2^562 mod p`, the starting `e` of `invert`.
example : let p := pallasBase.modulus.toNat
    let x := Limbs.toNat
      ⟨0x9a5f583ce5084635, 0x4f417e233776c195, 0x74634b1a733f7785, 0x1c51de5ea66f0f25⟩
    x = 2^562 % p := by
  decide +kernel

-- `FQ.two_r`: `2R mod p`.
example : let p := vestaBase.modulus.toNat
    let x := Limbs.toNat
      ⟨0x2a0f9218fffffff9, 0x1011d11bbcef61f1, 0xffffffffffffffff, 0x3fffffffffffffff⟩
    x = (2*R) % p := by
  decide +kernel

-- `FQ.three_r`: `3R mod p`.
example : let p := vestaBase.modulus.toNat
    let x := Limbs.toNat
      ⟨0xf8f3e594fffffff5, 0x86f76d2b969cbe7a, 0xfffffffffffffffe, 0x3fffffffffffffff⟩
    x = (3*R) % p := by
  decide +kernel

-- `FQ.r4`: `R^4 mod p`.
example : let p := vestaBase.modulus.toNat
    let x := Limbs.toNat
      ⟨0x569bba29179df5c1, 0xf7abe57547cfa14c, 0x8d0f36071632bdab, 0x2c37a71489ba6088⟩
    x = R^4 % p := by
  decide +kernel

-- `FQ.r7`: `R^7 mod p`.
example : let p := vestaBase.modulus.toNat
    let x := Limbs.toNat
      ⟨0x56244c6793e8be1f, 0xbe518f1c2a1b26e6, 0xb6c73001c86b2b65, 0x1b7d3aff1b7fd420⟩
    x = R^7 % p := by
  decide +kernel

-- `FQ.pm1_sq`: the Montgomery square of `p-1`, `(p-1)^2 R^-1 mod p`.
example : let p := vestaBase.modulus.toNat
    let x := Limbs.toNat
      ⟨0x6119a3dd8e1a6f7f, 0xc68de1279dc601eb, 0x5790be58c050df13, 0x1f7a89dd17647953⟩
    x < p ∧ (x*R) % p = ((p-1) * (p-1)) % p := by
  decide +kernel

-- `FQ.pm2`: `p - 2`.
example : let p := vestaBase.modulus.toNat
    let x := Limbs.toNat
      ⟨0x8c46eb20ffffffff, 0x224698fc0994a8dd, 0x0000000000000000, 0x4000000000000000⟩
    x = p - 2 := by
  decide +kernel

-- `FQ.from_mont_ones`: the conversion of the all-ones input, `(2^256 - 1) R^-1 mod p`.
example : let p := vestaBase.modulus.toNat
    let x := Limbs.toNat
      ⟨0x2b2d474371e59083, 0x5bb8b7d46bcea6f2, 0xa86f41a73faf20ec, 0x20857622e89b86ac⟩
    x < p ∧ (x*R) % p = (2^256 - 1) % p := by
  decide +kernel

-- `FQ.e0`: `2^562 mod p`, the starting `e` of `invert`.
example : let p := vestaBase.modulus.toNat
    let x := Limbs.toNat
      ⟨0xa3efbd8ee5083303, 0xfbadea62cefef7a1, 0xd6418abb493f6cf9, 0x2aa5feb88c401333⟩
    x = 2^562 % p := by
  decide +kernel

-- `FP.inversions[0]`: `invert` maps `x` to `z`, the Montgomery inverse.
example : let p := pallasBase.modulus.toNat
    let x := Limbs.toNat
      ⟨0xd83bd700ffffffe5, 0x628ddd6b04e1ba16, 0xfffffffffffffffc, 0x3fffffffffffffff⟩
    let z := Limbs.toNat
      ⟨0x8398bdd8b6db6db7, 0xbbc0f148939d4828, 0xdb6db6db6db6db6d, 0x2db6db6db6db6db6⟩
    z < p ∧ (x*z) % p = (if x = 0 then 0 else R^2 % p) := by
  decide +kernel

-- `FP.inversions[1]`: `invert` maps `x` to `z`, the Montgomery inverse.
example : let p := pallasBase.modulus.toNat
    let x := Limbs.toNat
      ⟨0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000⟩
    let z := Limbs.toNat
      ⟨0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000⟩
    z < p ∧ (x*z) % p = (if x = 0 then 0 else R^2 % p) := by
  decide +kernel

-- `FP.inversions[2]`: `invert` maps `x` to `z`, the Montgomery inverse.
example : let p := pallasBase.modulus.toNat
    let x := Limbs.toNat
      ⟨0x0000000000000001, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000⟩
    let z := Limbs.toNat
      ⟨0x8c78ecb30000000f, 0xd7d30dbd8b0de0e7, 0x7797a99bc3c95d18, 0x096d41af7b9cb714⟩
    z < p ∧ (x*z) % p = (if x = 0 then 0 else R^2 % p) := by
  decide +kernel

-- `FP.inversions[3]`: `invert` maps `x` to `z`, the Montgomery inverse.
example : let p := pallasBase.modulus.toNat
    let x := Limbs.toNat
      ⟨0x992d30ed00000000, 0x224698fc094cf91b, 0x0000000000000000, 0x4000000000000000⟩
    let z := Limbs.toNat
      ⟨0x0cb44439fffffff2, 0x4a738b3e7e3f1834, 0x886856643c36a2e7, 0x3692be50846348eb⟩
    z < p ∧ (x*z) % p = (if x = 0 then 0 else R^2 % p) := by
  decide +kernel

-- `FP.inversions[4]`: `invert` maps `x` to `z`, the Montgomery inverse.
example : let p := pallasBase.modulus.toNat
    let x := Limbs.toNat
      ⟨0xfc962fc962fc9630, 0x369d0369d0369cd2, 0x0000000000000000, 0x0000000000000000⟩
    let z := Limbs.toNat
      ⟨0x33912c173eb52b5e, 0x8094d7a33b979988, 0x4c1c894cf5cc5f05, 0x2d05c75a616fc8d4⟩
    z < p ∧ (x*z) % p = (if x = 0 then 0 else R^2 % p) := by
  decide +kernel

-- `FQ.inversions[0]`: `invert` maps `x` to `z`, the Montgomery inverse.
example : let p := vestaBase.modulus.toNat
    let x := Limbs.toNat
      ⟨0x34853384ffffffe5, 0x628ddd6afd5230a2, 0xfffffffffffffffc, 0x3fffffffffffffff⟩
    let z := Limbs.toNat
      ⟨0x81c0fd04b6db6db7, 0xbbc0f14893a785d6, 0xdb6db6db6db6db6d, 0x2db6db6db6db6db6⟩
    z < p ∧ (x*z) % p = (if x = 0 then 0 else R^2 % p) := by
  decide +kernel

-- `FQ.inversions[1]`: `invert` maps `x` to `z`, the Montgomery inverse.
example : let p := vestaBase.modulus.toNat
    let x := Limbs.toNat
      ⟨0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000⟩
    let z := Limbs.toNat
      ⟨0x0000000000000000, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000⟩
    z < p ∧ (x*z) % p = (if x = 0 then 0 else R^2 % p) := by
  decide +kernel

-- `FQ.inversions[2]`: `invert` maps `x` to `z`, the Montgomery inverse.
example : let p := vestaBase.modulus.toNat
    let x := Limbs.toNat
      ⟨0x0000000000000001, 0x0000000000000000, 0x0000000000000000, 0x0000000000000000⟩
    let z := Limbs.toNat
      ⟨0xfc9678ff0000000f, 0x67bb433d891a16e3, 0x7fae231004ccf590, 0x096d41af7ccfdaa9⟩
    z < p ∧ (x*z) % p = (if x = 0 then 0 else R^2 % p) := by
  decide +kernel

-- `FQ.inversions[3]`: `invert` maps `x` to `z`, the Montgomery inverse.
example : let p := vestaBase.modulus.toNat
    let x := Limbs.toNat
      ⟨0x8c46eb2100000000, 0x224698fc0994a8dd, 0x0000000000000000, 0x4000000000000000⟩
    let z := Limbs.toNat
      ⟨0x8fb07221fffffff2, 0xba8b55be807a91f9, 0x8051dceffb330a6f, 0x3692be5083302556⟩
    z < p ∧ (x*z) % p = (if x = 0 then 0 else R^2 % p) := by
  decide +kernel

-- `FQ.inversions[4]`: `invert` maps `x` to `z`, the Montgomery inverse.
example : let p := vestaBase.modulus.toNat
    let x := Limbs.toNat
      ⟨0xfc962fc962fc9630, 0x369d0369d0369cd2, 0x0000000000000000, 0x0000000000000000⟩
    let z := Limbs.toNat
      ⟨0xe5c6fb7bddd0cf4b, 0x65ee805e3b7d0d89, 0x7562671be840d861, 0x1253ce66fd1d1868⟩
    z < p ∧ (x*z) % p = (if x = 0 then 0 else R^2 % p) := by
  decide +kernel

end PastaCurves.KnownAnswers
