# Known-answer vectors for the GLV scalar multiplications in `src/glv.rs`
# and `src/glv_eisenstein.rs`.
#
# The property tests in those modules check both recodings against the
# crate's own `Mul`, and against each other. That catches a recoding that
# disagrees with the reference, but not a base-field or curve-arithmetic
# fault shared by all three. These vectors close that gap: the expected
# points are computed here, by Sage's own curve arithmetic, and hard-coded,
# so a wrong answer has to be wrong in the same way in two implementations
# that share no code.
#
# Run: `uv run --locked sage glv_test_vectors.sage`, and paste the output
# into the `vectors` module of `src/glv.rs`.

p = 0x40000000000000000000000000000000224698fc094cf91b992d30ed00000001
q = 0x40000000000000000000000000000000224698fc0994a8dd8c46eb2100000001

# Fixed so the table is reproducible: "LUPUSETAGNUS" as ASCII, in hex.
SEED = 0x4C55505553455441474E5553

# Lanes in the batch vectors.
BATCH = 12

Fp = GF(p)
Fq = GF(q)
Pallas = EllipticCurve(Fp, [0, 5])
Vesta = EllipticCurve(Fq, [0, 5])
assert Pallas.order() == q and Vesta.order() == p
Gp = Pallas(-1, 2)
Gv = Vesta(-1, 2)

# The scalar-field cube root of unity, as `src/fields/{fq,fp}.rs` define it.
zeta_q = int(Fq(5) ^ ((q - 1) // 3))
zeta_p = int(Fp(5) ^ ((p - 1) // 3))


def limbs(v):
    v = int(v)
    return [(v >> (64 * i)) & 0xFFFFFFFFFFFFFFFF for i in range(4)]


def arr(v):
    return "[%s]" % ", ".join("0" if l == 0 else "0x%x" % l for l in limbs(v))


def scalars(n, zeta):
    """Scalars worth pinning: the small cases, the ones that sit on a
    boundary of the decomposition, then a seeded random spread.

    The spread is drawn from Sage's own generator under a fixed seed, so
    regenerating reproduces the same table. Note this does tie the scalars
    to Sage's RNG: a future version could draw differently, which would
    show up as a changed table rather than as a failure.
    """
    out = [
        ("one", 1),
        ("two", 2),
        ("minus one", n - 1),
        ("zeta", zeta),
        ("zeta squared", (zeta * zeta) % n),
        ("half the order", n // 2),
        ("2^127", 2 ^ 127),
        ("2^127 - 1", 2 ^ 127 - 1),
    ]
    set_random_seed(SEED)
    for i in range(15 - len(out)):
        out.append(("random %d" % i, int(ZZ.random_element(1, n))))
    return out


def emit(name, const, G, n, zeta):
    ks = scalars(n, zeta)
    print("        /// `k * G` on %s: `(k, x, y)` as little-endian limbs." % name)
    print("        ///")
    print("        /// Generated by `sage/glv_test_vectors.sage`; do not edit by hand.")
    # Skipped because rustfmt would give each limb its own line, four times
    # the table for nothing.
    print("        #[rustfmt::skip]")
    print("        pub(crate) const %s: [([u64; 4], [u64; 4], [u64; 4]); %d] = ["
          % (const, len(ks)))
    for label, k in ks:
        R = int(k) * G
        assert not R.is_zero(), "%s: %s gives the identity" % (name, label)
        print("            // %s" % label)
        print("            (%s," % arr(k))
        print("             %s," % arr(R[0]))
        print("             %s)," % arr(R[1]))
    print("        ];")
    print()


def emit_batch(name, const, G, n):
    """The wallet-scanning shape: many points, one shared scalar.

    The points are emitted as the scalars that produce them, `P = s*G`,
    rather than as coordinates, so the table stays the size of its answers.
    """
    set_random_seed(SEED + 1)
    k = int(ZZ.random_element(1, n))
    ss = [int(ZZ.random_element(1, n)) for _ in range(BATCH)]
    print("        /// One shared scalar for the %s batch below." % name)
    print("        ///")
    print("        /// Generated by `sage/glv_test_vectors.sage`; do not edit by hand.")
    print("        #[rustfmt::skip]")
    print("        pub(crate) const %s_K: [u64; 4] =" % const)
    print("            %s;" % arr(k))
    print()
    print("        /// A batch against that scalar: `(s, x, y)` with `P = s*G`")
    print("        /// and `k*P = (x, y)`.")
    print("        ///")
    print("        /// Generated by `sage/glv_test_vectors.sage`; do not edit by hand.")
    print("        #[rustfmt::skip]")
    print("        pub(crate) const %s: [([u64; 4], [u64; 4], [u64; 4]); %d] = ["
          % (const, BATCH))
    for i, sc in enumerate(ss):
        P = int(sc) * G
        R = int(k) * P
        assert not P.is_zero() and not R.is_zero(), "%s: lane %d degenerate" % (name, i)
        print("            (%s," % arr(sc))
        print("             %s," % arr(R[0]))
        print("             %s)," % arr(R[1]))
    print("        ];")
    print()


print("    // Generated by sage/glv_test_vectors.sage. Do not edit by hand.")
print()
emit("Pallas", "PALLAS_VECTORS", Gp, q, zeta_q)
emit("Vesta", "VESTA_VECTORS", Gv, p, zeta_p)
emit_batch("Pallas", "PALLAS_BATCH", Gp, q)
emit_batch("Vesta", "VESTA_BATCH", Gv, p)
