"""The generated data modules: the reference vectors, the backend tests' known answers, and the
field types' constants, each checked by kernel evaluation in Lean.

These are not transcriptions: each reads a data file or Rust constants and renders Lean data or
examples from them, so they do not go through the compiler.
"""

import re

from asm2lean.lean import docstring

from .paths import ROOT

VECTORS = ROOT / "test-vectors/pasta_mul-armv8-vectors.txt"


# -- reference vectors ---------------------------------------------------------------------------
# The crate's two fields, by the vectors file's key, as `Fields.lean` names them.
FIELDS = {"Fp": "pallasBase", "Fq": "vestaBase"}


# The two moduli as integers, for classifying the vectors' operands.
MODULUS_INT = {
    "Fp": 0x40000000000000000000000000000000224698FC094CF91B992D30ED00000001,
    "Fq": 0x40000000000000000000000000000000224698FC0994A8DD8C46EB2100000001,
}

VECTOR_OPERAND_COUNTS = {"MUL": 2, "SQR": 1, "FROM": 1}
HEX_VALUE = re.compile(r"[0-9a-fA-F]{64}")


def parse_vectors(lines):
    """Parse and strictly validate nonempty lines from the shared hardware corpus."""
    vectors = []
    for line_number, line in enumerate(lines, 1):
        parts = line.split()
        if not parts:
            continue
        if len(parts) < 2:
            raise ValueError(f"vector line {line_number}: malformed row")
        op, key, *vals = parts
        if op not in VECTOR_OPERAND_COUNTS:
            raise ValueError(f"vector line {line_number}: unknown operation {op}")
        if key not in FIELDS:
            raise ValueError(f"vector line {line_number}: unknown field {key}")
        expected = VECTOR_OPERAND_COUNTS[op] + 1
        if len(vals) != expected:
            raise ValueError(
                f"vector line {line_number}: {op} expects {expected} values, got {len(vals)}"
            )
        if any(HEX_VALUE.fullmatch(v) is None for v in vals):
            raise ValueError(f"vector line {line_number}: values must be 64 hexadecimal digits")
        vectors.append((op, key, vals))
    return vectors


def is_canonical(key, value):
    """Whether a 256-bit input is below the selected Pasta modulus."""
    return value < MODULUS_INT[key]


def in_public_contract(op, key, operands):
    """Whether the vector's operands are inside the public contract: for the multiplication,
    a canonical left operand, or a canonical right operand whose limbs 1 to 3 are at most
    `2^64 - 3`; for the squaring, a canonical input; for the conversion, any."""
    p = MODULUS_INT[key]
    if op == "MUL":
        lhs, rhs = operands
        limbs = [(rhs >> (64 * i)) % 2**64 for i in range(1, 4)]
        return lhs < p or (rhs < p and all(l <= 2**64 - 3 for l in limbs))
    if op == "SQR":
        return operands[0] < p
    if op == "FROM":
        return True
    raise ValueError(f"unknown operation {op}")


OUT_VECTORS = ROOT / "lean/PastaCurves/Vectors.lean"

VECTORS_INTRODUCTION = """import PastaCurves.Fields

/-!
# Reference vectors for the transcribed blocks

GENERATED by `lean/scripts/gen.py` from `test-vectors/pasta_mul-armv8-vectors.txt`; do not
edit by hand. Each vector is the output of the real AArch64 assembly (Semolina's
`mul_mont_pasta`, `sqr_mont_pasta`, and `from_mont_pasta`, as vendored by pasta_curves at
`8ad85e9fab7929f6236960e472f432a4bd9ccd74` and run on an Apple M-series machine) on the given
operands. Each backend's `Vectors.lean` checks its transcription against them through
`VectorCheck.lean`. The vectors file also records the routines' outputs on operands outside the
public contracts (multiplications with unreduced operands), where the block's dropped fifth limb
can change the result; those are left out here, with their number recorded at the end.

Each entry gives its index in its list, which a reported failure names, its field, the operands,
and the expected result. The fields are `pallasBase` and `vestaBase` from `Fields.lean`, the
crate's constants for its `Fp` (the Pallas base field) and `Fq` (the Vesta base field).
-/

namespace PastaCurves

"""

# The generated lists, by the corpus's routine key: the Lean name, its type, and its docstring.
VECTOR_LISTS = {
    "MUL": (
        "mulVectors",
        "List (Nat × PastaField × Limbs × Limbs × Limbs)",
        (
            "The multiplication vectors inside the public contract: the index, the field, `lhs`, "
            "`rhs`, and the expected result."
        ),
    ),
    "SQR": (
        "sqrVectors",
        "List (Nat × PastaField × Limbs × Limbs)",
        (
            "The squaring vectors, all of them canonical inputs: the index, the field, the input, "
            "and the expected result."
        ),
    ),
    "FROM": (
        "fromVectors",
        "List (Nat × PastaField × Limbs × Limbs)",
        "The conversion vectors: the index, the field, the input, and the expected result.",
    ),
}


def render_vector_data(lines):
    """Render the corpus rows inside the public contracts as Lean data, one list per routine."""
    rows = {op: [] for op in VECTOR_LISTS}
    skipped = {}
    for op, key, vals in parse_vectors(lines):
        *operands, r = vals
        if not in_public_contract(op, key, [int(v, 16) for v in operands]):
            skipped[op] = skipped.get(op, 0) + 1
            continue
        rows[op].append((FIELDS[key], operands, r))
    out = [VECTORS_INTRODUCTION]
    for op, (name, type_, doc) in VECTOR_LISTS.items():
        out.append(f"{docstring(doc)}\ndef {name} : {type_} := [\n")
        for i, (field, operands, r) in enumerate(rows[op]):
            # One value per line keeps every line within the repository's width.
            out.append(f"  ({i}, {field},\n")
            for v in operands:
                out.append(f"    Limbs.ofNat 0x{v},\n")
            out.append(f"    Limbs.ofNat 0x{r}),\n")
        out.append("]\n\n")
    n = sum(len(entries) for entries in rows.values())
    omitted = ", ".join(f"{k} {op}" for op, k in sorted(skipped.items())) or "none"
    out.append(
        f"-- {n} vectors; omitted as outside the public contracts: {omitted}.\n\nend PastaCurves\n"
    )
    return "".join(out)


# -- the backend tests' known answers ------------------------------------------------------------

KNOWN_ANSWERS = ROOT / "src/test_fields.rs"
OUT_KNOWN_ANSWERS = ROOT / "lean/PastaCurves/KnownAnswers.lean"

# The known answers that `src/test_fields.rs` writes as literals, by field name: what each one is,
# as a Lean proposition about its value `x` at the field's modulus `p`. A literal with any other
# name is an error, so that a new one cannot go unchecked.
KNOWN_ANSWER_SPECS = {
    "two_r": ("`2R mod p`", "x = (2*R) % p"),
    "three_r": ("`3R mod p`", "x = (3*R) % p"),
    "pm2": ("`p - 2`", "x = p - 2"),
    "r4": ("`R^4 mod p`", "x = R^4 % p"),
    "r7": ("`R^7 mod p`", "x = R^7 % p"),
    "pm1_sq": (
        "the Montgomery square of `p-1`, `(p-1)^2 R^-1 mod p`",
        "x < p ∧ (x*R) % p = ((p-1) * (p-1)) % p",
    ),
    "from_mont_ones": (
        "the conversion of the all-ones input, `(2^256 - 1) R^-1 mod p`",
        "x < p ∧ (x*R) % p = (2^256 - 1) % p",
    ),
    "v0": ("`2^562 mod p`, the starting `v` of `invert`", "x = 2^562 % p"),
}

# The `Field` constants of `src/test_fields.rs`, by Rust name, as `Fields.lean` names the field.
KNOWN_ANSWER_FIELDS = {"FP": "pallasBase", "FQ": "vestaBase"}

KNOWN_ANSWERS_INTRODUCTION = """import PastaCurves.Fields

/-!
# The backend tests' known answers

GENERATED by `lean/scripts/gen.py` from the `Field` constants of `src/test_fields.rs`; do not edit
by hand. The tests take each field's modulus and Montgomery constants from its field type, and write
their other expected values as literals. Each example here states one such literal, with its limbs
in the tests' order, and checks it against its definition at the field's modulus, by kernel
evaluation. `lean/scripts/check.sh` regenerates this file and fails if it differs, so a literal
changed in the tests is checked here too.
-/

namespace PastaCurves.KnownAnswers

"""


def parse_known_answers(text):
    """The literal limb arrays of the `Field` constants in the tests, as (constant, field name,
    limbs) triples, in source order. Fields that are not literals are skipped; an unknown field
    name among the literals is an error."""
    out = []
    for m in re.finditer(r"const (\w+): Field = Field \{(.*?)\n\};", text, re.DOTALL):
        name, body = m.group(1), m.group(2)
        if name not in KNOWN_ANSWER_FIELDS:
            raise ValueError(f"{KNOWN_ANSWERS}: unknown field constant {name}")
        for f in re.finditer(r"(\w+): \[\s*((?:0x[0-9a-fA-F]+,\s*){4})\]", body):
            field = f.group(1)
            if field not in KNOWN_ANSWER_SPECS:
                raise ValueError(f"{KNOWN_ANSWERS}: {name}.{field} has no known-answer definition")
            limbs = [int(x, 16) for x in re.findall(r"0x[0-9a-fA-F]+", f.group(2))]
            out.append((name, field, limbs))
    if not out:
        raise ValueError(f"{KNOWN_ANSWERS}: no known-answer literals found")
    return out


def parse_inversions(text):
    """The `inversions` pairs of the `Field` constants in the tests, as (constant, index, input
    limbs, output limbs) tuples, in source order."""
    out = []
    for m in re.finditer(r"const (\w+): Field = Field \{(.*?)\n\};", text, re.DOTALL):
        name, body = m.group(1), m.group(2)
        block = re.search(r"inversions: \[(.*?)\n    \],", body, re.DOTALL)
        if block is None:
            continue
        pairs = re.findall(r"\(\s*\[([^\]]*)\],\s*\[([^\]]*)\],?\s*\)", block.group(1))
        if not pairs:
            raise ValueError(f"{KNOWN_ANSWERS}: {name}.inversions has no pairs")
        for i, (x, z) in enumerate(pairs):
            limbs = [[int(v, 16) for v in re.findall(r"0x[0-9a-fA-F]+", w)] for w in (x, z)]
            if any(len(w) != 4 for w in limbs):
                raise ValueError(
                    f"{KNOWN_ANSWERS}: {name}.inversions[{i}] is not two four-limb values"
                )
            out.append((name, i, limbs[0], limbs[1]))
    return out


def render_known_answers(text):
    """One kernel-checked example per literal known answer of the backend tests."""
    out = [KNOWN_ANSWERS_INTRODUCTION]
    for name, field, limbs in parse_known_answers(text):
        what, prop = KNOWN_ANSWER_SPECS[field]
        lean_field = KNOWN_ANSWER_FIELDS[name]
        literal = ", ".join(f"0x{limb:016x}" for limb in limbs)
        out.append(f"-- `{name}.{field}`: {what}.\n")
        out.append(f"example : let p := {lean_field}.modulus.toNat\n")
        # The limbs on a line of their own keep every line within the repository's width.
        out.append(f"    let x := Limbs.toNat\n      ⟨{literal}⟩\n")
        out.append(f"    {prop} := by\n  decide +kernel\n\n")
    for name, i, x, z in parse_inversions(text):
        lean_field = KNOWN_ANSWER_FIELDS[name]
        out.append(
            f"-- `{name}.inversions[{i}]`: `invert` maps `x` to `z`, the Montgomery inverse.\n"
        )
        out.append(f"example : let p := {lean_field}.modulus.toNat\n")
        for var, limbs in (("x", x), ("z", z)):
            literal = ", ".join(f"0x{limb:016x}" for limb in limbs)
            out.append(f"    let {var} := Limbs.toNat\n      ⟨{literal}⟩\n")
        out.append(
            "    z < p ∧ (x*z) % p = (if x = 0 then 0 else R^2 % p) := by\n  decide +kernel\n\n"
        )
    out.append("end PastaCurves.KnownAnswers\n")
    return "".join(out)


# -- the field types' constants ------------------------------------------------------------------

OUT_FIELD_TYPES = ROOT / "lean/PastaCurves/FieldTypes.lean"

# The field types' source files, as `Fields.lean` names their fields.
FIELD_TYPE_SOURCES = {"fp": "pallasBase", "fq": "vestaBase"}

# The Montgomery constants of a field type: the power of `R` that each one is, mod `p`.
FIELD_TYPE_POWERS = {"R": "R", "R2": "R^2", "R3": "R^3"}

FIELD_TYPES_INTRODUCTION = """import PastaCurves.Fields

/-!
# The field types' constants

GENERATED by `lean/scripts/gen.py` from `src/fields/fp.rs` and `src/fields/fq.rs`; do not edit by
hand. Each example states one constant of a field type, with its limbs as the Rust source writes
them. The modulus and `INV` are checked against the fields of `Fields.lean`, and `R`, `R2`, and
`R3` against their definitions at the field's modulus, by kernel evaluation.
`lean/scripts/check.sh` regenerates this file and fails if it differs, so a constant changed in
the field types is checked here too.
-/

namespace PastaCurves.FieldTypes

"""


def parse_field_type(text, path):
    """The modulus limbs, `INV`, and the Montgomery constants of a field type's source, as the
    source spells them: `(modulus, inv, {name: limbs})`. A missing constant is an error."""
    limbs = {}
    for m in re.finditer(r"const (MODULUS|R|R2|R3): F[pq] = F[pq]\(\[(.*?)\]\);", text, re.DOTALL):
        words = re.findall(r"0x[0-9a-fA-F]+", m.group(2))
        if len(words) != 4:
            raise ValueError(f"{path}: {m.group(1)} does not have four limbs")
        limbs[m.group(1)] = words
    inv = re.search(r"const INV: u64 = (0x[0-9a-fA-F]+);", text)
    missing = [name for name in ("MODULUS", *FIELD_TYPE_POWERS) if name not in limbs]
    if inv is None:
        missing.append("INV")
    if missing:
        raise ValueError(f"{path}: missing {', '.join(missing)}")
    modulus = limbs.pop("MODULUS")
    return modulus, inv.group(1), limbs


def render_field_types(sources):
    """One kernel-checked example per constant of each field type; `sources` maps each module
    name of `FIELD_TYPE_SOURCES` to its source text."""
    out = [FIELD_TYPES_INTRODUCTION]
    for module, lean_field in FIELD_TYPE_SOURCES.items():
        modulus, inv, powers = parse_field_type(sources[module], f"src/fields/{module}.rs")
        out.append(f"-- `{module}::MODULUS`: the modulus limbs of `{lean_field}`.\n")
        out.append(f"example : {lean_field}.modulus =\n    ⟨{', '.join(modulus)}⟩ := by\n")
        out.append("  decide\n\n")
        out.append(f"-- `{module}::INV`: the Montgomery constant of `{lean_field}`.\n")
        out.append(f"example : {lean_field}.inv = {inv} := by\n  decide\n\n")
        for name, power in FIELD_TYPE_POWERS.items():
            out.append(f"-- `{module}::{name}`: `{power} mod p`.\n")
            out.append(f"example : let p := {lean_field}.modulus.toNat\n")
            out.append(f"    let x := Limbs.toNat\n      ⟨{', '.join(powers[name])}⟩\n")
            out.append(f"    x = {power} % p := by\n  decide +kernel\n\n")
    out.append("end PastaCurves.FieldTypes\n")
    return "".join(out)


def generated_outputs():
    """The data modules' paths and contents."""
    field_types = {m: (ROOT / f"src/fields/{m}.rs").read_text() for m in FIELD_TYPE_SOURCES}
    return [
        (OUT_VECTORS, render_vector_data(VECTORS.read_text().splitlines())),
        (OUT_KNOWN_ANSWERS, render_known_answers(KNOWN_ANSWERS.read_text())),
        (OUT_FIELD_TYPES, render_field_types(field_types)),
    ]
