"""The crate's x86-64 blocks: what to transcribe from `src/asm/x86_64.rs`, and how."""

import re

from asm2lean import lean
from asm2lean.reroll import RotatedRounds
from asm2lean.rust import GenerationError
from asm2lean.x86_64 import Block, Target, transcribe

from .conventions import CONVENTIONS
from .paths import ROOT

SOURCE = ROOT / "src/asm/x86_64.rs"
OUTPUT = ROOT / "lean/PastaCurves/X86_64/Transcription.lean"

# The high limb of both Pasta moduli, which the blocks bind as `const PASTA_HIGH_LIMB`.
PASTA_HIGH_LIMB = 1 << 62

HEADER = """/-
Copyright Supranational LLC (the routines, transcribed from Semolina v0.1.4).
Copyright (c) 2026 the pasta_curves contributors (the transcription).
-/
import PastaCurves.X86_64.Semantics

/-!
# The crate's inline x86-64 Pasta field blocks, transcribed

GENERATED by `lean/scripts/gen.py` from the six `asm!` blocks in
`src/asm/x86_64.rs`; do not edit by hand. Each source instruction occurs in a trailing
comment on the let binding that models it. Registers are lexically rebound after
each write. The two identical full internal multiplication rounds are represented by
a generated helper after their flattened IRs have been compared modulo the source's
register rotation. `cf` and `ofl` model x86 CF and OF independently; the generator
rejects a read after an instruction that invalidates the corresponding flag.

Pointer operands are represented only by reads of their four input limbs. The
generator accepts no stores, no address other than a declared read-only pointer
plus 0, 8, 16, or 24 bytes, and no register read before an input or instruction has
written it. The fixed RDX operand, 32-bit `:e` XOR-zero idiom, operand outputs, and
Rust return-tuple order are parsed from the source rather than inferred here.
-/

namespace PastaCurves.X86_64

-- A mechanical transcription intentionally retains dead architectural results.
set_option linter.unusedVariables false

"""

FOOTER = "\nend PastaCurves.X86_64\n"

BLOCKS = (
    Block(
        "add",
        "addMod",
        (("lhs", "Limbs"), ("rhs", "Limbs"), ("modulus", "Limbs")),
        "Limbs",
        4,
        "The inline `asm!` block of `add`: modular addition followed by its conditional reduction.",
    ),
    Block(
        "sub",
        "subMod",
        (("lhs", "Limbs"), ("rhs", "Limbs"), ("modulus", "Limbs")),
        "Limbs",
        4,
        "The inline `asm!` block of `sub`: modular subtraction and conditional modulus addition.",
    ),
    Block(
        "mul",
        "mulMont",
        (("lhs", "Limbs"), ("rhs", "Limbs"), ("modulus", "Limbs"), ("inv", "Nat")),
        "Limbs",
        4,
        "The inline `asm!` block of `mul`: Montgomery multiplication and conditional reduction.",
    ),
    Block(
        "square_lo",
        "squareLo",
        (("value", "Limbs"),),
        "WideLimbs",
        8,
        "The inline `asm!` block of `square_lo`: the unreduced 512-bit square.",
    ),
    Block(
        "square_hi",
        "squareHi",
        (("product", "WideLimbs"), ("modulus", "Limbs"), ("inv", "Nat")),
        "Limbs",
        4,
        "The inline `asm!` block of `square_hi`: Montgomery reduction of `squareLo`'s product.",
    ),
    Block(
        "from_mont",
        "fromMont",
        (("value", "Limbs"), ("modulus", "Limbs"), ("inv", "Nat")),
        "Limbs",
        4,
        "The inline `asm!` block of `from_mont`: Montgomery reduction of a four-limb value.",
    ),
)


def validate_high_limb(source: str) -> None:
    matches = re.findall(
        r"^\s*const\s+PASTA_HIGH_LIMB\s*:\s*u64\s*=\s*([^;]+);",
        source,
        re.MULTILINE,
    )
    if len(matches) != 1:
        raise GenerationError("expected exactly one PASTA_HIGH_LIMB declaration")
    expression = re.sub(r"\s+", "", matches[0])
    if expression != "1<<62" or PASTA_HIGH_LIMB != 0x4000000000000000:
        raise GenerationError("PASTA_HIGH_LIMB must be `1 << 62` (0x4000000000000000)")


# `mul`'s two full internal rounds agree once the accumulator registers are rotated.
MUL_ROUNDS = RotatedRounds(
    ranges=((28, 63), (64, 99)),
    rotations=(
        {"be": "r0", "ce": "r1", "de": "r2", "ee": "r3", "ae": "r4"},
        {"ce": "r0", "de": "r1", "ee": "r2", "ae": "r3", "be": "r4"},
    ),
    rhs_limb="rhs.l{i}",
    fields=("r0", "r1", "r2", "r3", "r4", "q"),
    entry=("be", "ce", "de", "ee", "ae"),
    result=("r1", "r2", "r3", "r4", "r0", "rdx"),
    round="mulMontRound",
    doc=(
        "One full internal round of `mulMont`: add `lhs * b` to the rotating five-limb "
        "accumulator, cancel its low limb with the Montgomery quotient, and shift by one limb. "
        "The source's flattened rounds 1 and 2 are checked to have this same binding IR modulo "
        "their accumulator-register rotation and RHS limb, and this round, instantiated at each "
        "of its two calls, is checked to flatten back to the source's round."
    ),
    signature="def mulMontRound (lhs modulus : Limbs) (inv b : Nat) (acc : MulMontAcc) : MulMontAcc :=",
    struct="""/-- The rotating five-limb accumulator of `mulMont`, together with the most recent
Montgomery quotient. The next round does not read `q`; retaining it exposes the round invariant
needed by the block proof. -/
structure MulMontAcc where
  /-- accumulator limb 0 -/
  r0 : Nat
  /-- accumulator limb 1 -/
  r1 : Nat
  /-- accumulator limb 2 -/
  r2 : Nat
  /-- accumulator limb 3 -/
  r3 : Nat
  /-- accumulator limb 4 -/
  r4 : Nat
  /-- the most recent Montgomery quotient -/
  q : Nat
  deriving DecidableEq, Repr

namespace MulMontAcc

/-- Every field is below `2^64`. -/
def Bounded (s : MulMontAcc) : Prop :=
  s.r0 < 2^64 ∧ s.r1 < 2^64 ∧ s.r2 < 2^64 ∧ s.r3 < 2^64 ∧ s.r4 < 2^64 ∧ s.q < 2^64

/-- The value of the five accumulator limbs. -/
def toNat (s : MulMontAcc) : Nat :=
  s.r0 + 2^64 * s.r1 + 2^128 * s.r2 + 2^192 * s.r3 + 2^256 * s.r4

end MulMontAcc
""",
)

TARGET = Target(CONVENTIONS, {"PASTA_HIGH_LIMB": PASTA_HIGH_LIMB}, rounds={"mulMont": MUL_ROUNDS})


def programs(source=None):
    """Every program of the transcription, in order."""
    source = SOURCE.read_text() if source is None else source
    validate_high_limb(source)
    return [program for block in BLOCKS for program in transcribe(source, block, TARGET)]


def text(source=None):
    """The transcription module: each definition with its comments aligned at its own column."""
    definitions = "\n".join(lean.definition(p, lean.comment_column([p])) for p in programs(source))
    return HEADER + definitions + FOOTER
