/-
Copyright Supranational LLC (the routines, transcribed from Semolina v0.1.4).
Copyright (c) 2026 the pasta-asm contributors (the transcription).
Released under the Apache License, Version 2.0, as described in the file LICENSE.
-/
import PastaAArch64Asm.Semantics

/-!
# The crate's inline Pasta field blocks, transcribed

GENERATED by `lean/scripts/gen.py` from the `asm!` blocks of `mul`, `square`, `add`, and `sub`
in `src/asm/aarch64.rs`; do not edit by hand. Each definition follows its block instruction by
instruction (the instruction is the trailing comment; the two lines that unpack an
instruction's (result, carry) pair are marked as its continuation), over the semantics of
`PastaAArch64Asm.Semantics`. Registers are rebound by the instructions that write them, `c`
is the carry flag, `s` is the (result, carry) pair of the instruction that last set both,
argument limbs are read where the block's operands bind them, and the output limbs are bound
where the block's output operands hold them. Bindings that nothing reads are left as
comments. See the generator's docstring for what it checks.
-/

namespace PastaAArch64Asm

/-- The registers that `mulMont` carries from one round to the next. -/
structure MulMontAcc where
  /-- accumulator limb 0 -/
  r0 : Nat
  /-- accumulator limb 1 -/
  r1 : Nat
  /-- accumulator limb 2 -/
  r2 : Nat
  /-- accumulator limb 3 -/
  r3 : Nat
  /-- accumulator limb 4 -/
  r4 : Nat
  /-- the round's Montgomery quotient `q` -/
  q : Nat
  /-- `low(p1 * q)`, the first term of the round's reduction -/
  t1 : Nat
  /-- `low(q * 2^62)`, the third term of the round's reduction -/
  t3 : Nat
  deriving DecidableEq, Repr

namespace MulMontAcc

/-- Every field is below `2^64`. -/
def Bounded (s : MulMontAcc) : Prop :=
   s.r0 < 2^64 ∧ s.r1 < 2^64 ∧ s.r2 < 2^64 ∧ s.r3 < 2^64 ∧ s.r4 < 2^64 ∧ s.q < 2^64 ∧ s.t1 < 2^64 ∧
      s.t3 < 2^64

/-- The accumulator's value: limbs `r0`, `r1`, `r2`, `r3`, `r4` with weights `2^0` to `2^256`. -/
def toNat (s : MulMontAcc) : Nat :=
   s.r0 + 2^64 * s.r1 + 2^128 * s.r2 + 2^192 * s.r3 + 2^256 * s.r4

end MulMontAcc

/-- One round of `mulMont`: the instructions between one `lsl t3,q,#62` and the next in each of its
3 rounds, on the round's `rhs` limb `b` and the registers `acc` carried from the previous round. -/
def mulMontRound (lhs modulus : Limbs) (inv b : Nat) (acc : MulMontAcc) : MulMontAcc :=
  let a0 := lhs.l0              -- argument
  let a1 := lhs.l1              -- argument
  let a2 := lhs.l2              -- argument
  let a3 := lhs.l3              -- argument
  let p0 := modulus.l0          -- argument
  let p1 := modulus.l1          -- argument
  let inv := inv                -- argument
  let b1 := b                   -- argument
  let r0 := acc.r0              -- argument
  let r1 := acc.r1              -- argument
  let r2 := acc.r2              -- argument
  let r3 := acc.r3              -- argument
  let r4 := acc.r4              -- argument
  let q := acc.q                -- argument
  let t1 := acc.t1              -- argument
  let t3 := acc.t3              -- argument
  let c := (subc r0 1 1).2      -- subs xzr,r0,#1
  let t0 := umulh p0 q          -- umulh t0,p0,q
  let s := addc r1 t1 c         -- adcs r1,r1,t1
  let r1 := s.1                 --   `-> r1
  let c := s.2                  --   `-> carry
  let t1 := umulh p1 q          -- umulh t1,p1,q
  let s := addc r2 0 c          -- adcs r2,r2,xzr
  let r2 := s.1                 --   `-> r2
  let c := s.2                  --   `-> carry
  let s := addc r3 t3 c         -- adcs r3,r3,t3
  let r3 := s.1                 --   `-> r3
  let c := s.2                  --   `-> carry
  let t3 := lsr q 2             -- lsr t3,q,#2
  let r4 := (addc r4 0 c).1     -- adc r4,r4,xzr
  let s := addc r1 t0 0         -- adds r0,r1,t0
  let r0 := s.1                 --   `-> r0
  let c := s.2                  --   `-> carry
  let t0 := mulLo a0 b1         -- mul t0,a0,b1
  let s := addc r2 t1 c         -- adcs r1,r2,t1
  let r1 := s.1                 --   `-> r1
  let c := s.2                  --   `-> carry
  let t1 := mulLo a1 b1         -- mul t1,a1,b1
  let s := addc r3 0 c          -- adcs r2,r3,xzr
  let r2 := s.1                 --   `-> r2
  let c := s.2                  --   `-> carry
  let t2 := mulLo a2 b1         -- mul t2,a2,b1
  let s := addc r4 t3 c         -- adcs r3,r4,t3
  let r3 := s.1                 --   `-> r3
  let c := s.2                  --   `-> carry
  let t3 := mulLo a3 b1         -- mul t3,a3,b1
  let r4 := (addc 0 0 c).1      -- adc r4,xzr,xzr
  let s := addc r0 t0 0         -- adds r0,r0,t0
  let r0 := s.1                 --   `-> r0
  let c := s.2                  --   `-> carry
  let t0 := umulh a0 b1         -- umulh t0,a0,b1
  let s := addc r1 t1 c         -- adcs r1,r1,t1
  let r1 := s.1                 --   `-> r1
  let c := s.2                  --   `-> carry
  let t1 := umulh a1 b1         -- umulh t1,a1,b1
  let s := addc r2 t2 c         -- adcs r2,r2,t2
  let r2 := s.1                 --   `-> r2
  let c := s.2                  --   `-> carry
  let q := mulLo inv r0         -- mul q,inv,r0
  let t2 := umulh a2 b1         -- umulh t2,a2,b1
  let s := addc r3 t3 c         -- adcs r3,r3,t3
  let r3 := s.1                 --   `-> r3
  let c := s.2                  --   `-> carry
  let t3 := umulh a3 b1         -- umulh t3,a3,b1
  let r4 := (addc r4 0 c).1     -- adc r4,r4,xzr
  let s := addc r1 t0 0         -- adds r1,r1,t0
  let r1 := s.1                 --   `-> r1
  let c := s.2                  --   `-> carry
  let s := addc r2 t1 c         -- adcs r2,r2,t1
  let r2 := s.1                 --   `-> r2
  let c := s.2                  --   `-> carry
  let t1 := mulLo p1 q          -- mul t1,p1,q
  let s := addc r3 t2 c         -- adcs r3,r3,t2
  let r3 := s.1                 --   `-> r3
  let c := s.2                  --   `-> carry
  let r4 := (addc r4 t3 c).1    -- adc r4,r4,t3
  let t3 := lsl q 62            -- lsl t3,q,#62
  ⟨r0, r1, r2, r3, r4, q, t1, t3⟩

/-- The inline `asm!` block of `mul`: Montgomery multiplication, `lhs * rhs * 2^-256 mod p`, with
the result in the block's output operands. Its rounds are those of Semolina's `mul_mont_pasta`; its
epilogue keeps four limbs of the final candidate. -/
def mulMont (lhs rhs modulus : Limbs) (inv : Nat) : Limbs :=
  let a0 := lhs.l0              -- argument
  let a1 := lhs.l1              -- argument
  let a2 := lhs.l2              -- argument
  let a3 := lhs.l3              -- argument
  let b0 := rhs.l0              -- argument
  let b1 := rhs.l1              -- argument
  let b2 := rhs.l2              -- argument
  let b3 := rhs.l3              -- argument
  let p0 := modulus.l0          -- argument
  let p1 := modulus.l1          -- argument
  let inv := inv                -- argument
  let r0 := mulLo a0 b0         -- mul r0,a0,b0
  let r1 := mulLo a1 b0         -- mul r1,a1,b0
  let r2 := mulLo a2 b0         -- mul r2,a2,b0
  let r3 := mulLo a3 b0         -- mul r3,a3,b0
  let t0 := umulh a0 b0         -- umulh t0,a0,b0
  let t1 := umulh a1 b0         -- umulh t1,a1,b0
  let q := mulLo inv r0         -- mul q,inv,r0
  let t2 := umulh a2 b0         -- umulh t2,a2,b0
  let t3 := umulh a3 b0         -- umulh t3,a3,b0
  let s := addc r1 t0 0         -- adds r1,r1,t0
  let r1 := s.1                 --   `-> r1
  let c := s.2                  --   `-> carry
  let s := addc r2 t1 c         -- adcs r2,r2,t1
  let r2 := s.1                 --   `-> r2
  let c := s.2                  --   `-> carry
  let t1 := mulLo p1 q          -- mul t1,p1,q
  let s := addc r3 t2 c         -- adcs r3,r3,t2
  let r3 := s.1                 --   `-> r3
  let c := s.2                  --   `-> carry
  let r4 := (addc 0 t3 c).1     -- adc r4,xzr,t3
  let t3 := lsl q 62            -- lsl t3,q,#62
  let round1 := mulMontRound lhs modulus inv b1 ⟨r0, r1, r2, r3, r4, q, t1, t3⟩  -- round 1
  let r0 := round1.r0           -- round 1 output
  let r1 := round1.r1           -- round 1 output
  let r2 := round1.r2           -- round 1 output
  let r3 := round1.r3           -- round 1 output
  let r4 := round1.r4           -- round 1 output
  let q := round1.q             -- round 1 output
  let t1 := round1.t1           -- round 1 output
  let t3 := round1.t3           -- round 1 output
  let round2 := mulMontRound lhs modulus inv b2 ⟨r0, r1, r2, r3, r4, q, t1, t3⟩  -- round 2
  let r0 := round2.r0           -- round 2 output
  let r1 := round2.r1           -- round 2 output
  let r2 := round2.r2           -- round 2 output
  let r3 := round2.r3           -- round 2 output
  let r4 := round2.r4           -- round 2 output
  let q := round2.q             -- round 2 output
  let t1 := round2.t1           -- round 2 output
  let t3 := round2.t3           -- round 2 output
  let round3 := mulMontRound lhs modulus inv b3 ⟨r0, r1, r2, r3, r4, q, t1, t3⟩  -- round 3
  let r0 := round3.r0           -- round 3 output
  let r1 := round3.r1           -- round 3 output
  let r2 := round3.r2           -- round 3 output
  let r3 := round3.r3           -- round 3 output
  let r4 := round3.r4           -- round 3 output
  let q := round3.q             -- round 3 output
  let t1 := round3.t1           -- round 3 output
  let t3 := round3.t3           -- round 3 output
  let c := (subc r0 1 1).2      -- subs xzr,r0,#1
  let t0 := umulh p0 q          -- umulh t0,p0,q
  let s := addc r1 t1 c         -- adcs r1,r1,t1
  let r1 := s.1                 --   `-> r1
  let c := s.2                  --   `-> carry
  let t1 := umulh p1 q          -- umulh t1,p1,q
  let s := addc r2 0 c          -- adcs r2,r2,xzr
  let r2 := s.1                 --   `-> r2
  let c := s.2                  --   `-> carry
  let s := addc r3 t3 c         -- adcs r3,r3,t3
  let r3 := s.1                 --   `-> r3
  let c := s.2                  --   `-> carry
  let t3 := lsr q 2             -- lsr t3,q,#2
  let r4 := (addc r4 0 c).1     -- adc r4,r4,xzr
  let s := addc r1 t0 0         -- adds r0,r1,t0
  let r0 := s.1                 --   `-> r0
  let c := s.2                  --   `-> carry
  let s := addc r2 t1 c         -- adcs r1,r2,t1
  let r1 := s.1                 --   `-> r1
  let c := s.2                  --   `-> carry
  let s := addc r3 0 c          -- adcs r2,r3,xzr
  let r2 := s.1                 --   `-> r2
  let c := s.2                  --   `-> carry
  let s := addc r4 t3 c         -- adcs r3,r4,t3
  let r3 := s.1                 --   `-> r3
  let q := 4611686018427387904  -- mov q,#0x4000000000000000
  let s := subc r0 p0 1         -- subs t0,r0,p0
  let t0 := s.1                 --   `-> t0
  let c := s.2                  --   `-> carry
  let s := subc r1 p1 c         -- sbcs t1,r1,p1
  let t1 := s.1                 --   `-> t1
  let c := s.2                  --   `-> carry
  let s := subc r2 0 c          -- sbcs t2,r2,xzr
  let t2 := s.1                 --   `-> t2
  let c := s.2                  --   `-> carry
  let s := subc r3 q c          -- sbcs t3,r3,q
  let t3 := s.1                 --   `-> t3
  let c := s.2                  --   `-> carry
  let r0 := cselLo c r0 t0      -- csel r0,r0,t0,lo
  let r1 := cselLo c r1 t1      -- csel r1,r1,t1,lo
  let r2 := cselLo c r2 t2      -- csel r2,r2,t2,lo
  let r3 := cselLo c r3 t3      -- csel r3,r3,t3,lo
  ⟨r0, r1, r2, r3⟩

/-- The inline `asm!` block of `square`: Montgomery squaring, `value^2 * 2^-256 mod p`, the squaring
loop body of Semolina's `sqr_n_mul_mont_pasta` followed by a conditional subtraction, with the
result in the block's `inout` operands. -/
def sqrMont (value modulus : Limbs) (inv : Nat) : Limbs :=
  let a0 := value.l0            -- argument
  let a1 := value.l1            -- argument
  let a2 := value.l2            -- argument
  let a3 := value.l3            -- argument
  let p0 := modulus.l0          -- argument
  let p1 := modulus.l1          -- argument
  let inv := inv                -- argument
  let z1 := mulLo a1 a0         -- mul z1,a1,a0
  let w1 := umulh a1 a0         -- umulh w1,a1,a0
  let z2 := mulLo a2 a0         -- mul z2,a2,a0
  let w2 := umulh a2 a0         -- umulh w2,a2,a0
  let z3 := mulLo a3 a0         -- mul z3,a3,a0
  let z4 := umulh a3 a0         -- umulh z4,a3,a0
  let s := addc z2 w1 0         -- adds z2,z2,w1
  let z2 := s.1                 --   `-> z2
  let c := s.2                  --   `-> carry
  let w0 := mulLo a2 a1         -- mul w0,a2,a1
  let w1 := umulh a2 a1         -- umulh w1,a2,a1
  let s := addc z3 w2 c         -- adcs z3,z3,w2
  let z3 := s.1                 --   `-> z3
  let c := s.2                  --   `-> carry
  let w2 := mulLo a3 a1         -- mul w2,a3,a1
  let w3 := umulh a3 a1         -- umulh w3,a3,a1
  let z4 := (addc z4 0 c).1     -- adc z4,z4,xzr
  let z5 := mulLo a3 a2         -- mul z5,a3,a2
  let z6 := umulh a3 a2         -- umulh z6,a3,a2
  let s := addc w1 w2 0         -- adds w1,w1,w2
  let w1 := s.1                 --   `-> w1
  let c := s.2                  --   `-> carry
  let z0 := mulLo a0 a0         -- mul z0,a0,a0
  let w2 := (addc w3 0 c).1     -- adc w2,w3,xzr
  let s := addc z3 w0 0         -- adds z3,z3,w0
  let z3 := s.1                 --   `-> z3
  let c := s.2                  --   `-> carry
  let a0 := umulh a0 a0         -- umulh a0,a0,a0
  let s := addc z4 w1 c         -- adcs z4,z4,w1
  let z4 := s.1                 --   `-> z4
  let c := s.2                  --   `-> carry
  let w1 := mulLo a1 a1         -- mul w1,a1,a1
  let s := addc z5 w2 c         -- adcs z5,z5,w2
  let z5 := s.1                 --   `-> z5
  let c := s.2                  --   `-> carry
  let a1 := umulh a1 a1         -- umulh a1,a1,a1
  let z6 := (addc z6 0 c).1     -- adc z6,z6,xzr
  let s := addc z1 z1 0         -- adds z1,z1,z1
  let z1 := s.1                 --   `-> z1
  let c := s.2                  --   `-> carry
  let w2 := mulLo a2 a2         -- mul w2,a2,a2
  let s := addc z2 z2 c         -- adcs z2,z2,z2
  let z2 := s.1                 --   `-> z2
  let c := s.2                  --   `-> carry
  let a2 := umulh a2 a2         -- umulh a2,a2,a2
  let s := addc z3 z3 c         -- adcs z3,z3,z3
  let z3 := s.1                 --   `-> z3
  let c := s.2                  --   `-> carry
  let w3 := mulLo a3 a3         -- mul w3,a3,a3
  let s := addc z4 z4 c         -- adcs z4,z4,z4
  let z4 := s.1                 --   `-> z4
  let c := s.2                  --   `-> carry
  let a3 := umulh a3 a3         -- umulh a3,a3,a3
  let s := addc z5 z5 c         -- adcs z5,z5,z5
  let z5 := s.1                 --   `-> z5
  let c := s.2                  --   `-> carry
  let s := addc z6 z6 c         -- adcs z6,z6,z6
  let z6 := s.1                 --   `-> z6
  let c := s.2                  --   `-> carry
  let z7 := (addc 0 0 c).1      -- adc z7,xzr,xzr
  let q := mulLo inv z0         -- mul q,inv,z0
  let s := addc z1 a0 0         -- adds z1,z1,a0
  let z1 := s.1                 --   `-> z1
  let c := s.2                  --   `-> carry
  let s := addc z2 w1 c         -- adcs z2,z2,w1
  let z2 := s.1                 --   `-> z2
  let c := s.2                  --   `-> carry
  let s := addc z3 a1 c         -- adcs z3,z3,a1
  let z3 := s.1                 --   `-> z3
  let c := s.2                  --   `-> carry
  let s := addc z4 w2 c         -- adcs z4,z4,w2
  let z4 := s.1                 --   `-> z4
  let c := s.2                  --   `-> carry
  let s := addc z5 a2 c         -- adcs z5,z5,a2
  let z5 := s.1                 --   `-> z5
  let c := s.2                  --   `-> carry
  let s := addc z6 w3 c         -- adcs z6,z6,w3
  let z6 := s.1                 --   `-> z6
  let c := s.2                  --   `-> carry
  let z7 := (addc z7 a3 c).1    -- adc z7,z7,a3
  let w1 := mulLo p1 q          -- mul w1,p1,q
  let w3 := lsl q 62            -- lsl w3,q,#62
  let c := (subc z0 1 1).2      -- subs xzr,z0,#1
  let w0 := umulh p0 q          -- umulh w0,p0,q
  let s := addc z1 w1 c         -- adcs z1,z1,w1
  let z1 := s.1                 --   `-> z1
  let c := s.2                  --   `-> carry
  let w1 := umulh p1 q          -- umulh w1,p1,q
  let s := addc z2 0 c          -- adcs z2,z2,xzr
  let z2 := s.1                 --   `-> z2
  let c := s.2                  --   `-> carry
  let s := addc z3 w3 c         -- adcs z3,z3,w3
  let z3 := s.1                 --   `-> z3
  let c := s.2                  --   `-> carry
  let w3 := lsr q 2             -- lsr w3,q,#2
  let cy := (addc 0 0 c).1      -- adc cy,xzr,xzr
  let s := addc z1 w0 0         -- adds z0,z1,w0
  let z0 := s.1                 --   `-> z0
  let c := s.2                  --   `-> carry
  let s := addc z2 w1 c         -- adcs z1,z2,w1
  let z1 := s.1                 --   `-> z1
  let c := s.2                  --   `-> carry
  let s := addc z3 0 c          -- adcs z2,z3,xzr
  let z2 := s.1                 --   `-> z2
  let c := s.2                  --   `-> carry
  let q := mulLo inv z0         -- mul q,inv,z0
  let z3 := (addc cy w3 c).1    -- adc z3,cy,w3
  let w1 := mulLo p1 q          -- mul w1,p1,q
  let w3 := lsl q 62            -- lsl w3,q,#62
  let c := (subc z0 1 1).2      -- subs xzr,z0,#1
  let w0 := umulh p0 q          -- umulh w0,p0,q
  let s := addc z1 w1 c         -- adcs z1,z1,w1
  let z1 := s.1                 --   `-> z1
  let c := s.2                  --   `-> carry
  let w1 := umulh p1 q          -- umulh w1,p1,q
  let s := addc z2 0 c          -- adcs z2,z2,xzr
  let z2 := s.1                 --   `-> z2
  let c := s.2                  --   `-> carry
  let s := addc z3 w3 c         -- adcs z3,z3,w3
  let z3 := s.1                 --   `-> z3
  let c := s.2                  --   `-> carry
  let w3 := lsr q 2             -- lsr w3,q,#2
  let cy := (addc 0 0 c).1      -- adc cy,xzr,xzr
  let s := addc z1 w0 0         -- adds z0,z1,w0
  let z0 := s.1                 --   `-> z0
  let c := s.2                  --   `-> carry
  let s := addc z2 w1 c         -- adcs z1,z2,w1
  let z1 := s.1                 --   `-> z1
  let c := s.2                  --   `-> carry
  let s := addc z3 0 c          -- adcs z2,z3,xzr
  let z2 := s.1                 --   `-> z2
  let c := s.2                  --   `-> carry
  let q := mulLo inv z0         -- mul q,inv,z0
  let z3 := (addc cy w3 c).1    -- adc z3,cy,w3
  let w1 := mulLo p1 q          -- mul w1,p1,q
  let w3 := lsl q 62            -- lsl w3,q,#62
  let c := (subc z0 1 1).2      -- subs xzr,z0,#1
  let w0 := umulh p0 q          -- umulh w0,p0,q
  let s := addc z1 w1 c         -- adcs z1,z1,w1
  let z1 := s.1                 --   `-> z1
  let c := s.2                  --   `-> carry
  let w1 := umulh p1 q          -- umulh w1,p1,q
  let s := addc z2 0 c          -- adcs z2,z2,xzr
  let z2 := s.1                 --   `-> z2
  let c := s.2                  --   `-> carry
  let s := addc z3 w3 c         -- adcs z3,z3,w3
  let z3 := s.1                 --   `-> z3
  let c := s.2                  --   `-> carry
  let w3 := lsr q 2             -- lsr w3,q,#2
  let cy := (addc 0 0 c).1      -- adc cy,xzr,xzr
  let s := addc z1 w0 0         -- adds z0,z1,w0
  let z0 := s.1                 --   `-> z0
  let c := s.2                  --   `-> carry
  let s := addc z2 w1 c         -- adcs z1,z2,w1
  let z1 := s.1                 --   `-> z1
  let c := s.2                  --   `-> carry
  let s := addc z3 0 c          -- adcs z2,z3,xzr
  let z2 := s.1                 --   `-> z2
  let c := s.2                  --   `-> carry
  let q := mulLo inv z0         -- mul q,inv,z0
  let z3 := (addc cy w3 c).1    -- adc z3,cy,w3
  let w1 := mulLo p1 q          -- mul w1,p1,q
  let w3 := lsl q 62            -- lsl w3,q,#62
  let c := (subc z0 1 1).2      -- subs xzr,z0,#1
  let w0 := umulh p0 q          -- umulh w0,p0,q
  let s := addc z1 w1 c         -- adcs z1,z1,w1
  let z1 := s.1                 --   `-> z1
  let c := s.2                  --   `-> carry
  let w1 := umulh p1 q          -- umulh w1,p1,q
  let s := addc z2 0 c          -- adcs z2,z2,xzr
  let z2 := s.1                 --   `-> z2
  let c := s.2                  --   `-> carry
  let s := addc z3 w3 c         -- adcs z3,z3,w3
  let z3 := s.1                 --   `-> z3
  let c := s.2                  --   `-> carry
  let w3 := lsr q 2             -- lsr w3,q,#2
  let cy := (addc 0 0 c).1      -- adc cy,xzr,xzr
  let s := addc z1 w0 0         -- adds z0,z1,w0
  let z0 := s.1                 --   `-> z0
  let c := s.2                  --   `-> carry
  let s := addc z2 w1 c         -- adcs z1,z2,w1
  let z1 := s.1                 --   `-> z1
  let c := s.2                  --   `-> carry
  let s := addc z3 0 c          -- adcs z2,z3,xzr
  let z2 := s.1                 --   `-> z2
  let c := s.2                  --   `-> carry
  let z3 := (addc cy w3 c).1    -- adc z3,cy,w3
  let s := addc z0 z4 0         -- adds a0,z0,z4
  let a0 := s.1                 --   `-> a0
  let c := s.2                  --   `-> carry
  let s := addc z1 z5 c         -- adcs a1,z1,z5
  let a1 := s.1                 --   `-> a1
  let c := s.2                  --   `-> carry
  let s := addc z2 z6 c         -- adcs a2,z2,z6
  let a2 := s.1                 --   `-> a2
  let c := s.2                  --   `-> carry
  let a3 := (addc z3 z7 c).1    -- adc a3,z3,z7
  let q := 4611686018427387904  -- mov q,#0x4000000000000000
  let s := subc a0 p0 1         -- subs z0,a0,p0
  let z0 := s.1                 --   `-> z0
  let c := s.2                  --   `-> carry
  let s := subc a1 p1 c         -- sbcs z1,a1,p1
  let z1 := s.1                 --   `-> z1
  let c := s.2                  --   `-> carry
  let s := subc a2 0 c          -- sbcs z2,a2,xzr
  let z2 := s.1                 --   `-> z2
  let c := s.2                  --   `-> carry
  let s := subc a3 q c          -- sbcs z3,a3,q
  let z3 := s.1                 --   `-> z3
  let c := s.2                  --   `-> carry
  let a0 := cselLo c a0 z0      -- csel a0,a0,z0,lo
  let a1 := cselLo c a1 z1      -- csel a1,a1,z1,lo
  let a2 := cselLo c a2 z2      -- csel a2,a2,z2,lo
  let a3 := cselLo c a3 z3      -- csel a3,a3,z3,lo
  ⟨a0, a1, a2, a3⟩

/-- The inline `asm!` block of `add`: modular addition, `lhs + rhs mod p`, as a full-width addition,
a subtraction of the modulus, and the selection of the reduced sum when that subtraction did not
borrow, with the result in the block's `inout` operands. -/
def addMod (lhs rhs modulus : Limbs) : Limbs :=
  let r0 := lhs.l0              -- argument
  let r1 := lhs.l1              -- argument
  let r2 := lhs.l2              -- argument
  let r3 := lhs.l3              -- argument
  let b0 := rhs.l0              -- argument
  let b1 := rhs.l1              -- argument
  let b2 := rhs.l2              -- argument
  let b3 := rhs.l3              -- argument
  let p0 := modulus.l0          -- argument
  let p1 := modulus.l1          -- argument
  let p3 := modulus.l3          -- argument
  let s := addc r0 b0 0         -- adds r0,r0,b0
  let r0 := s.1                 --   `-> r0
  let c := s.2                  --   `-> carry
  let s := addc r1 b1 c         -- adcs r1,r1,b1
  let r1 := s.1                 --   `-> r1
  let c := s.2                  --   `-> carry
  let s := addc r2 b2 c         -- adcs r2,r2,b2
  let r2 := s.1                 --   `-> r2
  let c := s.2                  --   `-> carry
  let r3 := (addc r3 b3 c).1    -- adc r3,r3,b3
  let s := subc r0 p0 1         -- subs t0,r0,p0
  let t0 := s.1                 --   `-> t0
  let c := s.2                  --   `-> carry
  let s := subc r1 p1 c         -- sbcs t1,r1,p1
  let t1 := s.1                 --   `-> t1
  let c := s.2                  --   `-> carry
  let s := subc r2 0 c          -- sbcs t2,r2,xzr
  let t2 := s.1                 --   `-> t2
  let c := s.2                  --   `-> carry
  let s := subc r3 p3 c         -- sbcs t3,r3,p3
  let t3 := s.1                 --   `-> t3
  let c := s.2                  --   `-> carry
  let r0 := cselCs c t0 r0      -- csel r0,t0,r0,cs
  let r1 := cselCs c t1 r1      -- csel r1,t1,r1,cs
  let r2 := cselCs c t2 r2      -- csel r2,t2,r2,cs
  let r3 := cselCs c t3 r3      -- csel r3,t3,r3,cs
  ⟨r0, r1, r2, r3⟩

/-- The inline `asm!` block of `sub`: modular subtraction, `lhs - rhs mod p`, as a full-width
subtraction and the addition of the modulus when it borrowed, with the result in the block's `inout`
operands. -/
def subMod (lhs rhs modulus : Limbs) : Limbs :=
  let r0 := lhs.l0              -- argument
  let r1 := lhs.l1              -- argument
  let r2 := lhs.l2              -- argument
  let r3 := lhs.l3              -- argument
  let b0 := rhs.l0              -- argument
  let b1 := rhs.l1              -- argument
  let b2 := rhs.l2              -- argument
  let b3 := rhs.l3              -- argument
  let p0 := modulus.l0          -- argument
  let p1 := modulus.l1          -- argument
  let p3 := modulus.l3          -- argument
  let s := subc r0 b0 1         -- subs r0,r0,b0
  let r0 := s.1                 --   `-> r0
  let c := s.2                  --   `-> carry
  let s := subc r1 b1 c         -- sbcs r1,r1,b1
  let r1 := s.1                 --   `-> r1
  let c := s.2                  --   `-> carry
  let s := subc r2 b2 c         -- sbcs r2,r2,b2
  let r2 := s.1                 --   `-> r2
  let c := s.2                  --   `-> carry
  let s := subc r3 b3 c         -- sbcs r3,r3,b3
  let r3 := s.1                 --   `-> r3
  let c := s.2                  --   `-> carry
  let t0 := cselLo c p0 0       -- csel t0,p0,xzr,cc
  let t1 := cselLo c p1 0       -- csel t1,p1,xzr,cc
  let t3 := cselLo c p3 0       -- csel t3,p3,xzr,cc
  let s := addc r0 t0 0         -- adds r0,r0,t0
  let r0 := s.1                 --   `-> r0
  let c := s.2                  --   `-> carry
  let s := addc r1 t1 c         -- adcs r1,r1,t1
  let r1 := s.1                 --   `-> r1
  let c := s.2                  --   `-> carry
  let s := addc r2 0 c          -- adcs r2,r2,xzr
  let r2 := s.1                 --   `-> r2
  let c := s.2                  --   `-> carry
  let r3 := (addc r3 t3 c).1    -- adc r3,r3,t3
  ⟨r0, r1, r2, r3⟩

end PastaAArch64Asm
