-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [pasta_curves]: function definitions
module
public import Aeneas
public import PastaCurves.Glue.Types
public import PastaCurves.Glue.FunsExternal
@[expose] public section
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace pasta_curves

/-- [pasta_curves::limbs::is_canonical_word]:
    Source: 'src/limbs.rs', lines 28:0-36:1 -/
def limbs.is_canonical_word
  (value : Array Std.U64 4#usize) (modulus : Array Std.U64 4#usize) :
  Result Std.U64
  := do
  let i ← Array.index_usize value 0#usize
  let i1 ← Array.index_usize modulus 0#usize
  let (difference, underflow) ← lift (core.num.U64.overflowing_sub i i1)
  let (_, borrow_underflow) ←
    lift (core.num.U64.overflowing_sub difference 0#u64)
  let i2 ←
    lift (core.convert.num.FromU64Bool.from (underflow || borrow_underflow))
  let borrow ← core.hint.black_box i2
  let i3 ← Array.index_usize value 1#usize
  let i4 ← Array.index_usize modulus 1#usize
  let (difference1, underflow1) ← lift (core.num.U64.overflowing_sub i3 i4)
  let (_, borrow_underflow1) ←
    lift (core.num.U64.overflowing_sub difference1 borrow)
  let i5 ←
    lift (core.convert.num.FromU64Bool.from (underflow1 || borrow_underflow1))
  let borrow1 ← core.hint.black_box i5
  let i6 ← Array.index_usize value 2#usize
  let i7 ← Array.index_usize modulus 2#usize
  let (difference2, underflow2) ← lift (core.num.U64.overflowing_sub i6 i7)
  let (_, borrow_underflow2) ←
    lift (core.num.U64.overflowing_sub difference2 borrow1)
  let i8 ←
    lift (core.convert.num.FromU64Bool.from (underflow2 || borrow_underflow2))
  let borrow2 ← core.hint.black_box i8
  let i9 ← Array.index_usize value 3#usize
  let i10 ← Array.index_usize modulus 3#usize
  let (difference3, underflow3) ← lift (core.num.U64.overflowing_sub i9 i10)
  let (_, borrow_underflow3) ←
    lift (core.num.U64.overflowing_sub difference3 borrow2)
  let i11 ←
    lift (core.convert.num.FromU64Bool.from (underflow3 || borrow_underflow3))
  core.hint.black_box i11

/-- [pasta_curves::asm::entry::mul_contract]:
    Source: 'src/asm/entry.rs', lines 15:0-20:1 -/
def asm.entry.mul_contract
  (lhs : Array Std.U64 4#usize) (rhs : Array Std.U64 4#usize)
  (modulus : Array Std.U64 4#usize) :
  Result Bool
  := do
  let i ← Array.index_usize rhs 1#usize
  let i1 ← core.num.U64.MAX - 2#u64
  let i2 ← lift (core.convert.num.FromU64Bool.from (i <= i1))
  let i3 ← core.hint.black_box i2
  let i4 ← Array.index_usize rhs 2#usize
  let i5 ← lift (core.convert.num.FromU64Bool.from (i4 <= i1))
  let i6 ← core.hint.black_box i5
  let i7 ← lift (i3 &&& i6)
  let i8 ← Array.index_usize rhs 3#usize
  let i9 ← lift (core.convert.num.FromU64Bool.from (i8 <= i1))
  let i10 ← core.hint.black_box i9
  let rhs_limbs_ok ← lift (i7 &&& i10)
  let i11 ← limbs.is_canonical_word lhs modulus
  let i12 ← limbs.is_canonical_word rhs modulus
  let i13 ← lift (i12 &&& rhs_limbs_ok)
  let i14 ← lift (i11 ||| i13)
  ok (i14 = 1#u64)

/-- [pasta_curves::limbs::is_canonical]:
    Source: 'src/limbs.rs', lines 40:0-42:1 -/
def limbs.is_canonical
  (value : Array Std.U64 4#usize) (modulus : Array Std.U64 4#usize) :
  Result Bool
  := do
  let i ← limbs.is_canonical_word value modulus
  ok (i = 1#u64)

/-- [pasta_curves::asm::entry::add_with]:
    Source: 'src/asm/entry.rs', lines 52:0-62:1 -/
def asm.entry.add_with
  {B : Type} (MontgomeryBlocksInst : asm.entry.MontgomeryBlocks B)
  (lhs : Array Std.U64 4#usize) (rhs : Array Std.U64 4#usize)
  (modulus : Array Std.U64 4#usize) :
  Result (Array Std.U64 4#usize)
  := do
  let b ← limbs.is_canonical lhs modulus
  massert b
  let b1 ← limbs.is_canonical rhs modulus
  massert b1
  MontgomeryBlocksInst.add lhs rhs modulus

/-- [pasta_curves::asm::entry::sub_with]:
    Source: 'src/asm/entry.rs', lines 66:0-76:1 -/
def asm.entry.sub_with
  {B : Type} (MontgomeryBlocksInst : asm.entry.MontgomeryBlocks B)
  (lhs : Array Std.U64 4#usize) (rhs : Array Std.U64 4#usize)
  (modulus : Array Std.U64 4#usize) :
  Result (Array Std.U64 4#usize)
  := do
  let b ← limbs.is_canonical lhs modulus
  massert b
  let b1 ← limbs.is_canonical rhs modulus
  massert b1
  MontgomeryBlocksInst.sub lhs rhs modulus

/-- [pasta_curves::asm::entry::mul_with]:
    Source: 'src/asm/entry.rs', lines 80:0-92:1 -/
def asm.entry.mul_with
  {B : Type} (MontgomeryBlocksInst : asm.entry.MontgomeryBlocks B)
  (lhs : Array Std.U64 4#usize) (rhs : Array Std.U64 4#usize)
  (modulus : Array Std.U64 4#usize) (inv : Std.U64) :
  Result (Array Std.U64 4#usize)
  := do
  let b ← asm.entry.mul_contract lhs rhs modulus
  massert b
  MontgomeryBlocksInst.mul lhs rhs modulus inv

/-- [pasta_curves::asm::entry::square_with]:
    Source: 'src/asm/entry.rs', lines 96:0-102:1 -/
def asm.entry.square_with
  {B : Type} (MontgomeryBlocksInst : asm.entry.MontgomeryBlocks B)
  (value : Array Std.U64 4#usize) (modulus : Array Std.U64 4#usize)
  (inv : Std.U64) :
  Result (Array Std.U64 4#usize)
  := do
  let b ← limbs.is_canonical value modulus
  massert b
  MontgomeryBlocksInst.square value modulus inv

/-- [pasta_curves::asm::entry::sqr_n_mul_with]: loop body 0:
    Source: 'src/asm/entry.rs', lines 119:4-121:5 -/
@[rust_loop_body]
def asm.entry.sqr_n_mul_with_loop.body
  {B : Type} (MontgomeryBlocksInst : asm.entry.MontgomeryBlocks B)
  (modulus : Array Std.U64 4#usize) (inv : Std.U64)
  (iter : core.ops.range.Range Std.Usize) (acc : Array Std.U64 4#usize) :
  Result (ControlFlow ((core.ops.range.Range Std.Usize) × (Array Std.U64
    4#usize)) (Array Std.U64 4#usize))
  := do
  let (o, iter1) ←
    core.iter.range.IteratorRange.next core.iter.range.StepUsize iter
  match o with
  | none => ok (done acc)
  | some _ =>
    let acc1 ← asm.entry.square_with MontgomeryBlocksInst acc modulus inv
    ok (cont (iter1, acc1))

/-- [pasta_curves::asm::entry::sqr_n_mul_with]: loop 0:
    Source: 'src/asm/entry.rs', lines 119:4-121:5 -/
@[rust_loop]
def asm.entry.sqr_n_mul_with_loop
  {B : Type} (MontgomeryBlocksInst : asm.entry.MontgomeryBlocks B)
  (iter : core.ops.range.Range Std.Usize) (modulus : Array Std.U64 4#usize)
  (inv : Std.U64) (acc : Array Std.U64 4#usize) :
  Result (Array Std.U64 4#usize)
  := do
  loop
    (fun (iter1, acc1) => asm.entry.sqr_n_mul_with_loop.body
      MontgomeryBlocksInst modulus inv iter1 acc1)
    (iter, acc)

/-- [pasta_curves::asm::entry::sqr_n_mul_with]:
    Source: 'src/asm/entry.rs', lines 107:0-123:1 -/
def asm.entry.sqr_n_mul_with
  {B : Type} (MontgomeryBlocksInst : asm.entry.MontgomeryBlocks B)
  (value : Array Std.U64 4#usize) (count : Std.Usize)
  (rhs : Array Std.U64 4#usize) (modulus : Array Std.U64 4#usize)
  (inv : Std.U64) :
  Result (Array Std.U64 4#usize)
  := do
  let b ← limbs.is_canonical value modulus
  massert b
  let acc ←
    asm.entry.sqr_n_mul_with_loop MontgomeryBlocksInst
      { start := 0#usize, «end» := count } modulus inv value
  asm.entry.mul_with MontgomeryBlocksInst acc rhs modulus inv

/-- [pasta_curves::asm::entry::from_mont_with]:
    Source: 'src/asm/entry.rs', lines 127:0-133:1 -/
def asm.entry.from_mont_with
  {B : Type} (MontgomeryBlocksInst : asm.entry.MontgomeryBlocks B)
  (value : Array Std.U64 4#usize) (modulus : Array Std.U64 4#usize)
  (inv : Std.U64) :
  Result (Array Std.U64 4#usize)
  := do
  MontgomeryBlocksInst.from_mont value modulus inv

end pasta_curves
