-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [pasta_curves]: function definitions
module
public import Aeneas
public import PastaCurves.Glue.Types
public import PastaCurves.Glue.FunsExternal
@[expose] public section
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace pasta_curves

/-- [pasta_curves::limbs::is_canonical_word]:
    Source: 'src/limbs.rs', lines 29:0-37:1 -/
def limbs.is_canonical_word
  (value : Array Std.U64 4#usize) (modulus : Array Std.U64 4#usize) :
  Result Std.U64
  := do
  let i ← Array.index_usize value 0#usize
  let i1 ← Array.index_usize modulus 0#usize
  let (difference, underflow) ← lift (core.num.U64.overflowing_sub i i1)
  let (_, borrow_underflow) ←
    lift (core.num.U64.overflowing_sub difference 0#u64)
  let i2 ←
    lift (core.convert.num.FromU64Bool.from (underflow || borrow_underflow))
  let borrow ← core.hint.black_box i2
  let i3 ← Array.index_usize value 1#usize
  let i4 ← Array.index_usize modulus 1#usize
  let (difference1, underflow1) ← lift (core.num.U64.overflowing_sub i3 i4)
  let (_, borrow_underflow1) ←
    lift (core.num.U64.overflowing_sub difference1 borrow)
  let i5 ←
    lift (core.convert.num.FromU64Bool.from (underflow1 || borrow_underflow1))
  let borrow1 ← core.hint.black_box i5
  let i6 ← Array.index_usize value 2#usize
  let i7 ← Array.index_usize modulus 2#usize
  let (difference2, underflow2) ← lift (core.num.U64.overflowing_sub i6 i7)
  let (_, borrow_underflow2) ←
    lift (core.num.U64.overflowing_sub difference2 borrow1)
  let i8 ←
    lift (core.convert.num.FromU64Bool.from (underflow2 || borrow_underflow2))
  let borrow2 ← core.hint.black_box i8
  let i9 ← Array.index_usize value 3#usize
  let i10 ← Array.index_usize modulus 3#usize
  let (difference3, underflow3) ← lift (core.num.U64.overflowing_sub i9 i10)
  let (_, borrow_underflow3) ←
    lift (core.num.U64.overflowing_sub difference3 borrow2)
  let i11 ←
    lift (core.convert.num.FromU64Bool.from (underflow3 || borrow_underflow3))
  core.hint.black_box i11

/-- [pasta_curves::limbs::is_canonical]:
    Source: 'src/limbs.rs', lines 41:0-43:1 -/
def limbs.is_canonical
  (value : Array Std.U64 4#usize) (modulus : Array Std.U64 4#usize) :
  Result Bool
  := do
  let i ← limbs.is_canonical_word value modulus
  ok (i = 1#u64)

/-- [pasta_curves::montgomery::mul_contract]:
    Source: 'src/montgomery.rs', lines 20:0-25:1 -/
def montgomery.mul_contract
  (lhs : Array Std.U64 4#usize) (rhs : Array Std.U64 4#usize)
  (modulus : Array Std.U64 4#usize) :
  Result Bool
  := do
  let i ← Array.index_usize rhs 1#usize
  let i1 ← core.num.U64.MAX - 2#u64
  let i2 ← lift (core.convert.num.FromU64Bool.from (i <= i1))
  let i3 ← core.hint.black_box i2
  let i4 ← Array.index_usize rhs 2#usize
  let i5 ← lift (core.convert.num.FromU64Bool.from (i4 <= i1))
  let i6 ← core.hint.black_box i5
  let i7 ← lift (i3 &&& i6)
  let i8 ← Array.index_usize rhs 3#usize
  let i9 ← lift (core.convert.num.FromU64Bool.from (i8 <= i1))
  let i10 ← core.hint.black_box i9
  let rhs_limbs_ok ← lift (i7 &&& i10)
  let i11 ← limbs.is_canonical_word lhs modulus
  let i12 ← limbs.is_canonical_word rhs modulus
  let i13 ← lift (i12 &&& rhs_limbs_ok)
  let i14 ← lift (i11 ||| i13)
  ok (i14 = 1#u64)

/-- [pasta_curves::montgomery::add_with]:
    Source: 'src/montgomery.rs', lines 50:0-60:1 -/
def montgomery.add_with
  {B : Type} (MontgomeryBlocksInst : montgomery.MontgomeryBlocks B)
  (lhs : Array Std.U64 4#usize) (rhs : Array Std.U64 4#usize)
  (modulus : Array Std.U64 4#usize) :
  Result (Array Std.U64 4#usize)
  := do
  let b ← limbs.is_canonical lhs modulus
  massert b
  let b1 ← limbs.is_canonical rhs modulus
  massert b1
  MontgomeryBlocksInst.add lhs rhs modulus

/-- [pasta_curves::montgomery::sub_with]:
    Source: 'src/montgomery.rs', lines 64:0-74:1 -/
def montgomery.sub_with
  {B : Type} (MontgomeryBlocksInst : montgomery.MontgomeryBlocks B)
  (lhs : Array Std.U64 4#usize) (rhs : Array Std.U64 4#usize)
  (modulus : Array Std.U64 4#usize) :
  Result (Array Std.U64 4#usize)
  := do
  let b ← limbs.is_canonical lhs modulus
  massert b
  let b1 ← limbs.is_canonical rhs modulus
  massert b1
  MontgomeryBlocksInst.sub lhs rhs modulus

/-- [pasta_curves::montgomery::mul_with]:
    Source: 'src/montgomery.rs', lines 78:0-90:1 -/
def montgomery.mul_with
  {B : Type} (MontgomeryBlocksInst : montgomery.MontgomeryBlocks B)
  (lhs : Array Std.U64 4#usize) (rhs : Array Std.U64 4#usize)
  (modulus : Array Std.U64 4#usize) (inv : Std.U64) :
  Result (Array Std.U64 4#usize)
  := do
  let b ← montgomery.mul_contract lhs rhs modulus
  massert b
  MontgomeryBlocksInst.mul lhs rhs modulus inv

/-- [pasta_curves::montgomery::square_with]:
    Source: 'src/montgomery.rs', lines 94:0-100:1 -/
def montgomery.square_with
  {B : Type} (MontgomeryBlocksInst : montgomery.MontgomeryBlocks B)
  (value : Array Std.U64 4#usize) (modulus : Array Std.U64 4#usize)
  (inv : Std.U64) :
  Result (Array Std.U64 4#usize)
  := do
  let b ← limbs.is_canonical value modulus
  massert b
  MontgomeryBlocksInst.square value modulus inv

/-- [pasta_curves::montgomery::sqr_n_mul_with]: loop body 0:
    Source: 'src/montgomery.rs', lines 117:4-119:5 -/
@[rust_loop_body]
def montgomery.sqr_n_mul_with_loop.body
  {B : Type} (MontgomeryBlocksInst : montgomery.MontgomeryBlocks B)
  (modulus : Array Std.U64 4#usize) (inv : Std.U64)
  (iter : core.ops.range.Range Std.Usize) (acc : Array Std.U64 4#usize) :
  Result (ControlFlow ((core.ops.range.Range Std.Usize) × (Array Std.U64
    4#usize)) (Array Std.U64 4#usize))
  := do
  let (o, iter1) ←
    core.iter.range.IteratorRange.next core.iter.range.StepUsize iter
  match o with
  | none => ok (done acc)
  | some _ =>
    let acc1 ← montgomery.square_with MontgomeryBlocksInst acc modulus inv
    ok (cont (iter1, acc1))

/-- [pasta_curves::montgomery::sqr_n_mul_with]: loop 0:
    Source: 'src/montgomery.rs', lines 117:4-119:5 -/
@[rust_loop]
def montgomery.sqr_n_mul_with_loop
  {B : Type} (MontgomeryBlocksInst : montgomery.MontgomeryBlocks B)
  (iter : core.ops.range.Range Std.Usize) (modulus : Array Std.U64 4#usize)
  (inv : Std.U64) (acc : Array Std.U64 4#usize) :
  Result (Array Std.U64 4#usize)
  := do
  loop
    (fun (iter1, acc1) => montgomery.sqr_n_mul_with_loop.body
      MontgomeryBlocksInst modulus inv iter1 acc1)
    (iter, acc)

/-- [pasta_curves::montgomery::sqr_n_mul_with]:
    Source: 'src/montgomery.rs', lines 105:0-121:1 -/
def montgomery.sqr_n_mul_with
  {B : Type} (MontgomeryBlocksInst : montgomery.MontgomeryBlocks B)
  (value : Array Std.U64 4#usize) (count : Std.Usize)
  (rhs : Array Std.U64 4#usize) (modulus : Array Std.U64 4#usize)
  (inv : Std.U64) :
  Result (Array Std.U64 4#usize)
  := do
  let b ← limbs.is_canonical value modulus
  massert b
  let acc ←
    montgomery.sqr_n_mul_with_loop MontgomeryBlocksInst
      { start := 0#usize, «end» := count } modulus inv value
  montgomery.mul_with MontgomeryBlocksInst acc rhs modulus inv

/-- [pasta_curves::montgomery::from_mont_with]:
    Source: 'src/montgomery.rs', lines 125:0-131:1 -/
def montgomery.from_mont_with
  {B : Type} (MontgomeryBlocksInst : montgomery.MontgomeryBlocks B)
  (value : Array Std.U64 4#usize) (modulus : Array Std.U64 4#usize)
  (inv : Std.U64) :
  Result (Array Std.U64 4#usize)
  := do
  MontgomeryBlocksInst.from_mont value modulus inv

end pasta_curves
