-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [pasta_curves]: type definitions
module
public import Aeneas
@[expose] public section
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace pasta_curves

/-- Trait declaration: [pasta_curves::asm::entry::MontgomeryBlocks]
    Source: 'src/asm/entry.rs', lines 26:0-41:1 -/
structure asm.entry.MontgomeryBlocks (Self : Type) where
  add : Array Std.U64 4#usize → Array Std.U64 4#usize → Array Std.U64
    4#usize → Result (Array Std.U64 4#usize)
  sub : Array Std.U64 4#usize → Array Std.U64 4#usize → Array Std.U64
    4#usize → Result (Array Std.U64 4#usize)
  mul : Array Std.U64 4#usize → Array Std.U64 4#usize → Array Std.U64
    4#usize → Std.U64 → Result (Array Std.U64 4#usize)
  square : Array Std.U64 4#usize → Array Std.U64 4#usize → Std.U64 →
    Result (Array Std.U64 4#usize)
  from_mont : Array Std.U64 4#usize → Array Std.U64 4#usize → Std.U64 →
    Result (Array Std.U64 4#usize)

end pasta_curves
