-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [pasta_curves]: function definitions
module
public import Aeneas
public import PastaCurves.Portable.Types
@[expose] public section
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace pasta_curves

/-- [pasta_curves::inversion::portable::sign_mask]:
    Source: 'src/inversion/portable.rs', lines 35:0-37:1 -/
def inversion.portable.sign_mask (x : Std.U64) : Result Std.U64 := do
  let i ← lift (UScalar.hcast .I64 x)
  let i1 ← i >>> 63#i32
  ok (IScalar.hcast .U64 i1)

/-- [pasta_curves::inversion::portable::divstep]:
    Source: 'src/inversion/portable.rs', lines 44:0-51:1 -/
def inversion.portable.divstep
  (d : Std.U64) (f : Std.U64) (g : Std.U64) :
  Result (Std.U64 × Std.U64 × Std.U64)
  := do
  let i ← lift (g &&& 1#u64)
  let odd ← lift (core.num.U64.wrapping_sub 0#u64 i)
  let i1 ← lift (core.num.U64.wrapping_sub 0#u64 d)
  let i2 ← inversion.portable.sign_mask i1
  let swap ← lift (odd &&& i2)
  let i3 ← lift (core.num.U64.wrapping_sub 2#u64 d)
  let i4 ← lift (swap &&& i3)
  let i5 ← lift (~~~ swap)
  let i6 ← lift (core.num.U64.wrapping_add d 2#u64)
  let i7 ← lift (i5 &&& i6)
  let d2 ← lift (i4 ||| i7)
  let i8 ← lift (swap &&& g)
  let i9 ← lift (~~~ swap)
  let i10 ← lift (i9 &&& f)
  let f2 ← lift (i8 ||| i10)
  let i11 ← lift (core.num.U64.wrapping_sub g f)
  let i12 ← lift (swap &&& i11)
  let i13 ← lift (~~~ swap)
  let i14 ← lift (odd &&& f)
  let i15 ← lift (core.num.U64.wrapping_add g i14)
  let i16 ← lift (i13 &&& i15)
  let sum ← lift (i12 ||| i16)
  let i17 ← lift (UScalar.hcast .I64 sum)
  let i18 ← i17 >>> 1#i32
  let i19 ← lift (IScalar.hcast .U64 i18)
  ok (d2, f2, i19)

/-- [pasta_curves::inversion::portable::unpack]:
    Source: 'src/inversion/portable.rs', lines 57:0-62:1 -/
def inversion.portable.unpack
  (k : Std.U32) (w : Std.U64) : Result (Std.U64 × Std.U64) := do
  let i ← lift (core.num.U64.wrapping_sub 0#u64 w)
  let t ← lift (UScalar.hcast .I64 i)
  let i1 ← 40#u32 - k
  let i2 ← 1#i64 <<< i1
  let i3 ← lift (core.num.I64.wrapping_add t i2)
  let i4 ← 41#u32 - k
  let up ← i3 >>> i4
  let i5 ← 1#i64 <<< 20#i32
  let i6 ← i5 - 1#i64
  let i7 ← lift (core.num.I64.wrapping_add up i6)
  let v ← i7 >>> 21#i32
  let i8 ← v <<< 21#i32
  let i9 ← lift (core.num.I64.wrapping_sub up i8)
  let i10 ← lift (IScalar.hcast .U64 i9)
  let i11 ← lift (IScalar.hcast .U64 v)
  ok (i10, i11)

/-- [pasta_curves::inversion::portable::batch]: loop body 0:
    Source: 'src/inversion/portable.rs', lines 73:4-75:5 -/
@[rust_loop_body]
def inversion.portable.batch_loop.body
  (iter : core.ops.range.Range Std.U32) (d : Std.U64) (pf : Std.U64)
  (pg : Std.U64) :
  Result (ControlFlow ((core.ops.range.Range Std.U32) × Std.U64 × Std.U64 ×
    Std.U64) (Std.U64 × Std.U64 × Std.U64))
  := do
  let (o, iter1) ←
    core.iter.range.IteratorRange.next core.iter.range.StepU32 iter
  match o with
  | none => ok (done (d, pf, pg))
  | some _ =>
    let (d1, pf1, pg1) ← inversion.portable.divstep d pf pg
    ok (cont (iter1, d1, pf1, pg1))

/-- [pasta_curves::inversion::portable::batch]: loop 0:
    Source: 'src/inversion/portable.rs', lines 73:4-75:5 -/
@[rust_loop]
def inversion.portable.batch_loop
  (iter : core.ops.range.Range Std.U32) (d : Std.U64) (pf : Std.U64)
  (pg : Std.U64) :
  Result (Std.U64 × Std.U64 × Std.U64)
  := do
  loop
    (fun (iter1, d1, pf1, pg1) => inversion.portable.batch_loop.body iter1 d1
      pf1 pg1)
    (iter, d, pf, pg)

/-- [pasta_curves::inversion::portable::batch]:
    Source: 'src/inversion/portable.rs', lines 69:0-79:1 -/
def inversion.portable.batch
  (k : Std.U32) (d : Std.U64) (f : Std.U64) (g : Std.U64) :
  Result (Array Std.U64 5#usize)
  := do
  let i ← lift (f &&& 1048575#u64)
  let pf ← lift (i ||| 18446741874686296064#u64)
  let i1 ← lift (g &&& 1048575#u64)
  let pg ← lift (i1 ||| 13835058055282163712#u64)
  let (d1, pf1, pg1) ←
    inversion.portable.batch_loop { start := 0#u32, «end» := k } d pf pg
  let (m00, m01) ← inversion.portable.unpack k pf1
  let (m10, m11) ← inversion.portable.unpack k pg1
  ok (Array.make 5#usize [ d1, m00, m01, m10, m11 ])

/-- [pasta_curves::inversion::portable::next_low]:
    Source: 'src/inversion/portable.rs', lines 84:0-86:1 -/
def inversion.portable.next_low
  (k : Std.U32) (a : Std.U64) (b : Std.U64) (f : Std.U64) (g : Std.U64) :
  Result Std.U64
  := do
  let i ← lift (core.num.U64.wrapping_mul a f)
  let i1 ← lift (core.num.U64.wrapping_mul b g)
  let i2 ← lift (core.num.U64.wrapping_add i i1)
  i2 >>> k

/-- [pasta_curves::inversion::portable::mat_mul]:
    Source: 'src/inversion/portable.rs', lines 90:0-101:1 -/
def inversion.portable.mat_mul
  (m : Array Std.U64 4#usize) (n : Array Std.U64 4#usize) :
  Result (Array Std.U64 4#usize)
  := do
  let i ← Array.index_usize m 0#usize
  let i1 ← Array.index_usize n 0#usize
  let i2 ← lift (core.num.U64.wrapping_mul i i1)
  let i3 ← Array.index_usize m 1#usize
  let i4 ← Array.index_usize n 2#usize
  let i5 ← lift (core.num.U64.wrapping_mul i3 i4)
  let i6 ← lift (core.num.U64.wrapping_add i2 i5)
  let i7 ← Array.index_usize n 1#usize
  let i8 ← lift (core.num.U64.wrapping_mul i i7)
  let i9 ← Array.index_usize n 3#usize
  let i10 ← lift (core.num.U64.wrapping_mul i3 i9)
  let i11 ← lift (core.num.U64.wrapping_add i8 i10)
  let i12 ← Array.index_usize m 2#usize
  let i13 ← lift (core.num.U64.wrapping_mul i12 i1)
  let i14 ← Array.index_usize m 3#usize
  let i15 ← lift (core.num.U64.wrapping_mul i14 i4)
  let i16 ← lift (core.num.U64.wrapping_add i13 i15)
  let i17 ← lift (core.num.U64.wrapping_mul i12 i7)
  let i18 ← lift (core.num.U64.wrapping_mul i14 i9)
  let i19 ← lift (core.num.U64.wrapping_add i17 i18)
  ok (Array.make 4#usize [ i6, i11, i16, i19 ])

/-- [pasta_curves::inversion::portable::negate]:
    Source: 'src/inversion/portable.rs', lines 106:0-115:1 -/
def inversion.portable.negate
  (x : Array Std.U64 5#usize) (s : Std.U64) :
  Result (Array Std.U64 5#usize)
  := do
  let out := Array.repeat 5#usize 0#u64
  let carry ← lift (s &&& 1#u64)
  let i ← Array.index_usize x 0#usize
  let i1 ← lift (i ^^^ s)
  let (word, overflow) ← lift (core.num.U64.overflowing_add i1 carry)
  let out1 ← Array.update out 0#usize word
  let carry1 ← lift (core.convert.num.FromU64Bool.from overflow)
  let i2 ← Array.index_usize x 1#usize
  let i3 ← lift (i2 ^^^ s)
  let (word1, overflow1) ← lift (core.num.U64.overflowing_add i3 carry1)
  let out2 ← Array.update out1 1#usize word1
  let carry2 ← lift (core.convert.num.FromU64Bool.from overflow1)
  let i4 ← Array.index_usize x 2#usize
  let i5 ← lift (i4 ^^^ s)
  let (word2, overflow2) ← lift (core.num.U64.overflowing_add i5 carry2)
  let out3 ← Array.update out2 2#usize word2
  let carry3 ← lift (core.convert.num.FromU64Bool.from overflow2)
  let i6 ← Array.index_usize x 3#usize
  let i7 ← lift (i6 ^^^ s)
  let (word3, overflow3) ← lift (core.num.U64.overflowing_add i7 carry3)
  let out4 ← Array.update out3 3#usize word3
  let carry4 ← lift (core.convert.num.FromU64Bool.from overflow3)
  let i8 ← Array.index_usize x 4#usize
  let i9 ← lift (i8 ^^^ s)
  let (word4, _) ← lift (core.num.U64.overflowing_add i9 carry4)
  Array.update out4 4#usize word4

/-- [pasta_curves::inversion::portable::row]:
    Source: 'src/inversion/portable.rs', lines 122:0-133:1 -/
def inversion.portable.row
  (x : Array Std.U64 5#usize) (y : Array Std.U64 5#usize) (m0 : Std.U64)
  (m1 : Std.U64) (s0 : Std.U64) (s1 : Std.U64) :
  Result (Array Std.U64 5#usize)
  := do
  let x1 ← inversion.portable.negate x s0
  let y1 ← inversion.portable.negate y s1
  let out := Array.repeat 5#usize 0#u64
  let i ← Array.index_usize x1 0#usize
  let i1 ← lift (core.convert.num.FromU128U64.from i)
  let i2 ← lift (core.convert.num.FromU128U64.from m0)
  let i3 ← i1 * i2
  let i4 ← 0#u128 + i3
  let i5 ← Array.index_usize y1 0#usize
  let i6 ← lift (core.convert.num.FromU128U64.from i5)
  let i7 ← lift (core.convert.num.FromU128U64.from m1)
  let i8 ← i6 * i7
  let column ← i4 + i8
  let i9 ← lift (UScalar.cast .U64 column)
  let out1 ← Array.update out 0#usize i9
  let carry ← column >>> 64#i32
  let i10 ← Array.index_usize x1 1#usize
  let i11 ← lift (core.convert.num.FromU128U64.from i10)
  let i12 ← lift (core.convert.num.FromU128U64.from m0)
  let i13 ← i11 * i12
  let i14 ← carry + i13
  let i15 ← Array.index_usize y1 1#usize
  let i16 ← lift (core.convert.num.FromU128U64.from i15)
  let i17 ← lift (core.convert.num.FromU128U64.from m1)
  let i18 ← i16 * i17
  let column1 ← i14 + i18
  let i19 ← lift (UScalar.cast .U64 column1)
  let out2 ← Array.update out1 1#usize i19
  let carry1 ← column1 >>> 64#i32
  let i20 ← Array.index_usize x1 2#usize
  let i21 ← lift (core.convert.num.FromU128U64.from i20)
  let i22 ← lift (core.convert.num.FromU128U64.from m0)
  let i23 ← i21 * i22
  let i24 ← carry1 + i23
  let i25 ← Array.index_usize y1 2#usize
  let i26 ← lift (core.convert.num.FromU128U64.from i25)
  let i27 ← lift (core.convert.num.FromU128U64.from m1)
  let i28 ← i26 * i27
  let column2 ← i24 + i28
  let i29 ← lift (UScalar.cast .U64 column2)
  let out3 ← Array.update out2 2#usize i29
  let carry2 ← column2 >>> 64#i32
  let i30 ← Array.index_usize x1 3#usize
  let i31 ← lift (core.convert.num.FromU128U64.from i30)
  let i32 ← lift (core.convert.num.FromU128U64.from m0)
  let i33 ← i31 * i32
  let i34 ← carry2 + i33
  let i35 ← Array.index_usize y1 3#usize
  let i36 ← lift (core.convert.num.FromU128U64.from i35)
  let i37 ← lift (core.convert.num.FromU128U64.from m1)
  let i38 ← i36 * i37
  let column3 ← i34 + i38
  let i39 ← lift (UScalar.cast .U64 column3)
  let out4 ← Array.update out3 3#usize i39
  let carry3 ← column3 >>> 64#i32
  let i40 ← Array.index_usize x1 4#usize
  let i41 ← lift (core.convert.num.FromU128U64.from i40)
  let i42 ← lift (core.convert.num.FromU128U64.from m0)
  let i43 ← i41 * i42
  let i44 ← carry3 + i43
  let i45 ← Array.index_usize y1 4#usize
  let i46 ← lift (core.convert.num.FromU128U64.from i45)
  let i47 ← lift (core.convert.num.FromU128U64.from m1)
  let i48 ← i46 * i47
  let column4 ← i44 + i48
  let i49 ← lift (UScalar.cast .U64 column4)
  let _ ← column4 >>> 64#i32
  Array.update out4 4#usize i49

/-- [pasta_curves::inversion::portable::add5]:
    Source: 'src/inversion/portable.rs', lines 138:0-148:1 -/
def inversion.portable.add5
  (x : Array Std.U64 5#usize) (y : Array Std.U64 5#usize) :
  Result (Array Std.U64 5#usize)
  := do
  let out := Array.repeat 5#usize 0#u64
  let i ← Array.index_usize x 0#usize
  let i1 ← Array.index_usize y 0#usize
  let (sum, overflow1) ← lift (core.num.U64.overflowing_add i i1)
  let (sum1, overflow2) ← lift (core.num.U64.overflowing_add sum 0#u64)
  let out1 ← Array.update out 0#usize sum1
  let carry ←
    lift (core.convert.num.FromU64Bool.from (overflow1 || overflow2))
  let i2 ← Array.index_usize x 1#usize
  let i3 ← Array.index_usize y 1#usize
  let (sum2, overflow11) ← lift (core.num.U64.overflowing_add i2 i3)
  let (sum3, overflow21) ← lift (core.num.U64.overflowing_add sum2 carry)
  let out2 ← Array.update out1 1#usize sum3
  let carry1 ←
    lift (core.convert.num.FromU64Bool.from (overflow11 || overflow21))
  let i4 ← Array.index_usize x 2#usize
  let i5 ← Array.index_usize y 2#usize
  let (sum4, overflow12) ← lift (core.num.U64.overflowing_add i4 i5)
  let (sum5, overflow22) ← lift (core.num.U64.overflowing_add sum4 carry1)
  let out3 ← Array.update out2 2#usize sum5
  let carry2 ←
    lift (core.convert.num.FromU64Bool.from (overflow12 || overflow22))
  let i6 ← Array.index_usize x 3#usize
  let i7 ← Array.index_usize y 3#usize
  let (sum6, overflow13) ← lift (core.num.U64.overflowing_add i6 i7)
  let (sum7, overflow23) ← lift (core.num.U64.overflowing_add sum6 carry2)
  let out4 ← Array.update out3 3#usize sum7
  let carry3 ←
    lift (core.convert.num.FromU64Bool.from (overflow13 || overflow23))
  let i8 ← Array.index_usize x 4#usize
  let i9 ← Array.index_usize y 4#usize
  let (sum8, _) ← lift (core.num.U64.overflowing_add i8 i9)
  let (sum9, _) ← lift (core.num.U64.overflowing_add sum8 carry3)
  Array.update out4 4#usize sum9

/-- [pasta_curves::inversion::portable::{impl pasta_curves::inversion::InvertBlocks for pasta_curves::inversion::portable::Backend}::cond_sub]:
    Source: 'src/inversion/portable.rs', lines 246:4-261:5 -/
def inversion.portable.Backend.Insts.Pasta_curvesInversionInvertBlocks.cond_sub
  (value : Array Std.U64 4#usize) (modulus : Array Std.U64 4#usize) :
  Result (Array Std.U64 4#usize)
  := do
  let difference := Array.repeat 4#usize 0#u64
  let i ← Array.index_usize value 0#usize
  let i1 ← Array.index_usize modulus 0#usize
  let (word, underflow1) ← lift (core.num.U64.overflowing_sub i i1)
  let (word1, underflow2) ← lift (core.num.U64.overflowing_sub word 0#u64)
  let difference1 ← Array.update difference 0#usize word1
  let borrow ←
    lift (core.convert.num.FromU64Bool.from (underflow1 || underflow2))
  let i2 ← Array.index_usize value 1#usize
  let i3 ← Array.index_usize modulus 1#usize
  let (word2, underflow11) ← lift (core.num.U64.overflowing_sub i2 i3)
  let (word3, underflow21) ← lift (core.num.U64.overflowing_sub word2 borrow)
  let difference2 ← Array.update difference1 1#usize word3
  let borrow1 ←
    lift (core.convert.num.FromU64Bool.from (underflow11 || underflow21))
  let i4 ← Array.index_usize value 2#usize
  let i5 ← Array.index_usize modulus 2#usize
  let (word4, underflow12) ← lift (core.num.U64.overflowing_sub i4 i5)
  let (word5, underflow22) ←
    lift (core.num.U64.overflowing_sub word4 borrow1)
  let difference3 ← Array.update difference2 2#usize word5
  let borrow2 ←
    lift (core.convert.num.FromU64Bool.from (underflow12 || underflow22))
  let i6 ← Array.index_usize value 3#usize
  let i7 ← Array.index_usize modulus 3#usize
  let (word6, underflow13) ← lift (core.num.U64.overflowing_sub i6 i7)
  let (word7, underflow23) ←
    lift (core.num.U64.overflowing_sub word6 borrow2)
  let difference4 ← Array.update difference3 3#usize word7
  let borrow3 ←
    lift (core.convert.num.FromU64Bool.from (underflow13 || underflow23))
  let keep ← lift (core.num.U64.wrapping_sub 0#u64 borrow3)
  let out := Array.repeat 4#usize 0#u64
  let i8 ← lift (keep &&& i)
  let i9 ← lift (~~~ keep)
  let i10 ← Array.index_usize difference4 0#usize
  let i11 ← lift (i9 &&& i10)
  let i12 ← lift (i8 ||| i11)
  let out1 ← Array.update out 0#usize i12
  let i13 ← lift (keep &&& i2)
  let i14 ← lift (~~~ keep)
  let i15 ← Array.index_usize difference4 1#usize
  let i16 ← lift (i14 &&& i15)
  let i17 ← lift (i13 ||| i16)
  let out2 ← Array.update out1 1#usize i17
  let i18 ← lift (keep &&& i4)
  let i19 ← lift (~~~ keep)
  let i20 ← Array.index_usize difference4 2#usize
  let i21 ← lift (i19 &&& i20)
  let i22 ← lift (i18 ||| i21)
  let out3 ← Array.update out2 2#usize i22
  let i23 ← lift (keep &&& i6)
  let i24 ← lift (~~~ keep)
  let i25 ← Array.index_usize difference4 3#usize
  let i26 ← lift (i24 &&& i25)
  let i27 ← lift (i23 ||| i26)
  Array.update out3 3#usize i27

/-- [pasta_curves::inversion::portable::{impl pasta_curves::inversion::InvertBlocks for pasta_curves::inversion::portable::Backend}::amontred]:
    Source: 'src/inversion/portable.rs', lines 219:4-242:5 -/
def inversion.portable.Backend.Insts.Pasta_curvesInversionInvertBlocks.amontred
  (t : Array Std.U64 5#usize) (modulus : Array Std.U64 4#usize) (inv : Std.U64)
  :
  Result (Array Std.U64 4#usize)
  := do
  let i ← Array.index_usize modulus 0#usize
  let i1 ← i <<< 61#i32
  let i2 ← i >>> 3#i32
  let i3 ← Array.index_usize modulus 1#usize
  let i4 ← i3 <<< 61#i32
  let i5 ← lift (i2 ||| i4)
  let i6 ← i3 >>> 3#i32
  let i7 ← Array.index_usize modulus 2#usize
  let i8 ← i7 <<< 61#i32
  let i9 ← lift (i6 ||| i8)
  let i10 ← i7 >>> 3#i32
  let i11 ← Array.index_usize modulus 3#usize
  let i12 ← i11 <<< 61#i32
  let i13 ← lift (i10 ||| i12)
  let i14 ← i11 >>> 3#i32
  let s ←
    inversion.portable.add5 t (Array.make 5#usize [ i1, i5, i9, i13, i14 ])
  let i15 ← Array.index_usize s 0#usize
  let w ← lift (core.num.U64.wrapping_mul i15 inv)
  let i16 ← lift (core.convert.num.FromU128U64.from i15)
  let i17 ← lift (core.convert.num.FromU128U64.from w)
  let i18 ← lift (core.convert.num.FromU128U64.from i)
  let i19 ← i17 * i18
  let i20 ← i16 + i19
  let carry ← i20 >>> 64#i32
  let i21 ← Array.index_usize s 1#usize
  let i22 ← lift (core.convert.num.FromU128U64.from i21)
  let i23 ← carry + i22
  let i24 ← lift (core.convert.num.FromU128U64.from w)
  let i25 ← lift (core.convert.num.FromU128U64.from i3)
  let i26 ← i24 * i25
  let column1 ← i23 + i26
  let i27 ← column1 >>> 64#i32
  let i28 ← Array.index_usize s 2#usize
  let i29 ← lift (core.convert.num.FromU128U64.from i28)
  let i30 ← i27 + i29
  let i31 ← lift (core.convert.num.FromU128U64.from w)
  let i32 ← lift (core.convert.num.FromU128U64.from i7)
  let i33 ← i31 * i32
  let column2 ← i30 + i33
  let i34 ← column2 >>> 64#i32
  let i35 ← Array.index_usize s 3#usize
  let i36 ← lift (core.convert.num.FromU128U64.from i35)
  let i37 ← i34 + i36
  let i38 ← lift (core.convert.num.FromU128U64.from w)
  let i39 ← lift (core.convert.num.FromU128U64.from i11)
  let i40 ← i38 * i39
  let column3 ← i37 + i40
  let i41 ← column3 >>> 64#i32
  let i42 ← Array.index_usize s 4#usize
  let i43 ← lift (core.convert.num.FromU128U64.from i42)
  let column4 ← i41 + i43
  let i44 ← lift (UScalar.cast .U64 column1)
  let i45 ← lift (UScalar.cast .U64 column2)
  let i46 ← lift (UScalar.cast .U64 column3)
  let i47 ← lift (UScalar.cast .U64 column4)
  ok (Array.make 4#usize [ i44, i45, i46, i47 ])

/-- [pasta_curves::inversion::portable::{impl pasta_curves::inversion::InvertBlocks for pasta_curves::inversion::portable::Backend}::uv_row]:
    Source: 'src/inversion/portable.rs', lines 209:4-213:5 -/
def inversion.portable.Backend.Insts.Pasta_curvesInversionInvertBlocks.uv_row
  (u : Array Std.U64 4#usize) (v : Array Std.U64 4#usize) (m0 : Std.U64)
  (m1 : Std.U64) (s0 : Std.U64) (s1 : Std.U64) :
  Result (Array Std.U64 5#usize)
  := do
  let i ← Array.index_usize u 0#usize
  let i1 ← Array.index_usize u 1#usize
  let i2 ← Array.index_usize u 2#usize
  let i3 ← Array.index_usize u 3#usize
  let i4 ← Array.index_usize v 0#usize
  let i5 ← Array.index_usize v 1#usize
  let i6 ← Array.index_usize v 2#usize
  let i7 ← Array.index_usize v 3#usize
  inversion.portable.row (Array.make 5#usize [ i, i1, i2, i3, 0#u64 ])
    (Array.make 5#usize [ i4, i5, i6, i7, 0#u64 ]) m0 m1 s0 s1

/-- [pasta_curves::inversion::portable::{impl pasta_curves::inversion::InvertBlocks for pasta_curves::inversion::portable::Backend}::fg_row]:
    Source: 'src/inversion/portable.rs', lines 196:4-205:5 -/
def inversion.portable.Backend.Insts.Pasta_curvesInversionInvertBlocks.fg_row
  (f : Array Std.U64 5#usize) (g : Array Std.U64 5#usize) (m0 : Std.U64)
  (m1 : Std.U64) (s0 : Std.U64) (s1 : Std.U64) :
  Result (Array Std.U64 5#usize)
  := do
  let t ← inversion.portable.row f g m0 m1 s0 s1
  let i ← Array.index_usize t 0#usize
  let i1 ← i >>> 59#i32
  let i2 ← Array.index_usize t 1#usize
  let i3 ← i2 <<< 5#i32
  let i4 ← lift (i1 ||| i3)
  let i5 ← i2 >>> 59#i32
  let i6 ← Array.index_usize t 2#usize
  let i7 ← i6 <<< 5#i32
  let i8 ← lift (i5 ||| i7)
  let i9 ← i6 >>> 59#i32
  let i10 ← Array.index_usize t 3#usize
  let i11 ← i10 <<< 5#i32
  let i12 ← lift (i9 ||| i11)
  let i13 ← i10 >>> 59#i32
  let i14 ← Array.index_usize t 4#usize
  let i15 ← i14 <<< 5#i32
  let i16 ← lift (i13 ||| i15)
  let i17 ← lift (UScalar.hcast .I64 i14)
  let i18 ← i17 >>> 59#i32
  let i19 ← lift (IScalar.hcast .U64 i18)
  ok (Array.make 5#usize [ i4, i8, i12, i16, i19 ])

/-- [pasta_curves::inversion::portable::{impl pasta_curves::inversion::InvertBlocks for pasta_curves::inversion::portable::Backend}::sign_mag]:
    Source: 'src/inversion/portable.rs', lines 174:4-191:5 -/
def inversion.portable.Backend.Insts.Pasta_curvesInversionInvertBlocks.sign_mag
  (m00 : Std.U64) (m01 : Std.U64) (m10 : Std.U64) (m11 : Std.U64) :
  Result (Array Std.U64 8#usize)
  := do
  let i ← inversion.portable.sign_mask m00
  let i1 ← inversion.portable.sign_mask m01
  let i2 ← inversion.portable.sign_mask m10
  let i3 ← inversion.portable.sign_mask m11
  let s00 ← Array.index_usize (Array.make 4#usize [ i, i1, i2, i3 ]) 0#usize
  let s01 ← Array.index_usize (Array.make 4#usize [ i, i1, i2, i3 ]) 1#usize
  let s10 ← Array.index_usize (Array.make 4#usize [ i, i1, i2, i3 ]) 2#usize
  let s11 ← Array.index_usize (Array.make 4#usize [ i, i1, i2, i3 ]) 3#usize
  let i4 ← lift (m00 ^^^ s00)
  let i5 ← lift (core.num.U64.wrapping_sub i4 s00)
  let i6 ← lift (m01 ^^^ s01)
  let i7 ← lift (core.num.U64.wrapping_sub i6 s01)
  let i8 ← lift (m10 ^^^ s10)
  let i9 ← lift (core.num.U64.wrapping_sub i8 s10)
  let i10 ← lift (m11 ^^^ s11)
  let i11 ← lift (core.num.U64.wrapping_sub i10 s11)
  ok (Array.make 8#usize [ i5, i7, i9, i11, s00, s01, s10, s11 ])

/-- [pasta_curves::inversion::portable::{impl pasta_curves::inversion::InvertBlocks for pasta_curves::inversion::portable::Backend}::divstep59]:
    Source: 'src/inversion/portable.rs', lines 157:4-170:5 -/
def
  inversion.portable.Backend.Insts.Pasta_curvesInversionInvertBlocks.divstep59
  (d : Std.U64) (f0 : Std.U64) (g0 : Std.U64) :
  Result (Array Std.U64 5#usize)
  := do
  let a ← inversion.portable.batch 20#u32 d f0 g0
  let d1 ← Array.index_usize a 0#usize
  let a1 ← Array.index_usize a 1#usize
  let b1 ← Array.index_usize a 2#usize
  let c1 ← Array.index_usize a 3#usize
  let e1 ← Array.index_usize a 4#usize
  let f1 ← inversion.portable.next_low 20#u32 a1 b1 f0 g0
  let g1 ← inversion.portable.next_low 20#u32 c1 e1 f0 g0
  let a2 ← inversion.portable.batch 20#u32 d1 f1 g1
  let d2 ← Array.index_usize a2 0#usize
  let a21 ← Array.index_usize a2 1#usize
  let b2 ← Array.index_usize a2 2#usize
  let c2 ← Array.index_usize a2 3#usize
  let e2 ← Array.index_usize a2 4#usize
  let f2 ← inversion.portable.next_low 20#u32 a21 b2 f1 g1
  let g2 ← inversion.portable.next_low 20#u32 c2 e2 f1 g1
  let a3 ← inversion.portable.batch 19#u32 d2 f2 g2
  let d3 ← Array.index_usize a3 0#usize
  let a31 ← Array.index_usize a3 1#usize
  let b3 ← Array.index_usize a3 2#usize
  let c3 ← Array.index_usize a3 3#usize
  let e3 ← Array.index_usize a3 4#usize
  let a4 ←
    inversion.portable.mat_mul (Array.make 4#usize [ a21, b2, c2, e2 ])
      (Array.make 4#usize [ a1, b1, c1, e1 ])
  let a5 ←
    inversion.portable.mat_mul (Array.make 4#usize [ a31, b3, c3, e3 ]) a4
  let m00 ← Array.index_usize a5 0#usize
  let m01 ← Array.index_usize a5 1#usize
  let m10 ← Array.index_usize a5 2#usize
  let m11 ← Array.index_usize a5 3#usize
  ok (Array.make 5#usize [ d3, m00, m01, m10, m11 ])

/-- Trait implementation: [pasta_curves::inversion::portable::{impl pasta_curves::inversion::InvertBlocks for pasta_curves::inversion::portable::Backend}]
    Source: 'src/inversion/portable.rs', lines 153:0-262:1 -/
@[reducible]
def inversion.portable.Backend.Insts.Pasta_curvesInversionInvertBlocks :
  inversion.InvertBlocks inversion.portable.Backend := {
  divstep59 :=
    inversion.portable.Backend.Insts.Pasta_curvesInversionInvertBlocks.divstep59
  sign_mag :=
    inversion.portable.Backend.Insts.Pasta_curvesInversionInvertBlocks.sign_mag
  fg_row :=
    inversion.portable.Backend.Insts.Pasta_curvesInversionInvertBlocks.fg_row
  uv_row :=
    inversion.portable.Backend.Insts.Pasta_curvesInversionInvertBlocks.uv_row
  amontred :=
    inversion.portable.Backend.Insts.Pasta_curvesInversionInvertBlocks.amontred
  cond_sub :=
    inversion.portable.Backend.Insts.Pasta_curvesInversionInvertBlocks.cond_sub
}

/-- [pasta_curves::inversion::invert_with]: loop body 0:
    Source: 'src/inversion.rs', lines 82:4-93:5 -/
@[rust_loop_body]
def inversion.invert_with_loop.body
  {B : Type} (InvertBlocksInst : inversion.InvertBlocks B)
  (modulus : Array Std.U64 4#usize) (inv : Std.U64)
  (iter : core.ops.range.Range Std.I32) (d : Std.U64)
  (f : Array Std.U64 5#usize) (g : Array Std.U64 5#usize)
  (u : Array Std.U64 4#usize) (v : Array Std.U64 4#usize) :
  Result (ControlFlow ((core.ops.range.Range Std.I32) × Std.U64 × (Array
    Std.U64 5#usize) × (Array Std.U64 5#usize) × (Array Std.U64 4#usize) ×
    (Array Std.U64 4#usize)) (Std.U64 × (Array Std.U64 5#usize) × (Array
    Std.U64 5#usize) × (Array Std.U64 4#usize) × (Array Std.U64 4#usize)))
  := do
  let (o, iter1) ←
    core.iter.range.IteratorRange.next core.iter.range.StepI32 iter
  match o with
  | none => ok (done (d, f, g, u, v))
  | some _ =>
    let i ← Array.index_usize f 0#usize
    let i1 ← Array.index_usize g 0#usize
    let a ← InvertBlocksInst.divstep59 d i i1
    let d2 ← Array.index_usize a 0#usize
    let m00 ← Array.index_usize a 1#usize
    let m01 ← Array.index_usize a 2#usize
    let m10 ← Array.index_usize a 3#usize
    let m11 ← Array.index_usize a 4#usize
    let a1 ← InvertBlocksInst.sign_mag m00 m01 m10 m11
    let m001 ← Array.index_usize a1 0#usize
    let m011 ← Array.index_usize a1 1#usize
    let m101 ← Array.index_usize a1 2#usize
    let m111 ← Array.index_usize a1 3#usize
    let s00 ← Array.index_usize a1 4#usize
    let s01 ← Array.index_usize a1 5#usize
    let s10 ← Array.index_usize a1 6#usize
    let s11 ← Array.index_usize a1 7#usize
    let f2 ← InvertBlocksInst.fg_row f g m001 m011 s00 s01
    let g1 ← InvertBlocksInst.fg_row f g m101 m111 s10 s11
    let tu ← InvertBlocksInst.uv_row u v m001 m011 s00 s01
    let tv ← InvertBlocksInst.uv_row u v m101 m111 s10 s11
    let u1 ← InvertBlocksInst.amontred tu modulus inv
    let v1 ← InvertBlocksInst.amontred tv modulus inv
    ok (cont (iter1, d2, f2, g1, u1, v1))

/-- [pasta_curves::inversion::invert_with]: loop 0:
    Source: 'src/inversion.rs', lines 82:4-93:5 -/
@[rust_loop]
def inversion.invert_with_loop
  {B : Type} (InvertBlocksInst : inversion.InvertBlocks B)
  (iter : core.ops.range.Range Std.I32) (modulus : Array Std.U64 4#usize)
  (inv : Std.U64) (d : Std.U64) (f : Array Std.U64 5#usize)
  (g : Array Std.U64 5#usize) (u : Array Std.U64 4#usize)
  (v : Array Std.U64 4#usize) :
  Result (Std.U64 × (Array Std.U64 5#usize) × (Array Std.U64 5#usize) ×
    (Array Std.U64 4#usize) × (Array Std.U64 4#usize))
  := do
  loop
    (fun (iter1, d1, f1, g1, u1, v1) => inversion.invert_with_loop.body
      InvertBlocksInst modulus inv iter1 d1 f1 g1 u1 v1)
    (iter, d, f, g, u, v)

/-- [pasta_curves::inversion::invert_with]:
    Source: 'src/inversion.rs', lines 71:0-99:1 -/
def inversion.invert_with
  {B : Type} (InvertBlocksInst : inversion.InvertBlocks B)
  (x : Array Std.U64 4#usize) (modulus : Array Std.U64 4#usize) (inv : Std.U64)
  (v0 : Array Std.U64 4#usize) :
  Result (Array Std.U64 4#usize)
  := do
  let i ← Array.index_usize modulus 0#usize
  let i1 ← Array.index_usize modulus 1#usize
  let i2 ← Array.index_usize modulus 2#usize
  let i3 ← Array.index_usize modulus 3#usize
  let i4 ← Array.index_usize x 0#usize
  let i5 ← Array.index_usize x 1#usize
  let i6 ← Array.index_usize x 2#usize
  let i7 ← Array.index_usize x 3#usize
  let u := Array.repeat 4#usize 0#u64
  let (d, f, g, u1, v) ←
    inversion.invert_with_loop InvertBlocksInst
      { start := 0#i32, «end» := 9#i32 } modulus inv 1#u64
      (Array.make 5#usize [ i, i1, i2, i3, 0#u64 ])
      (Array.make 5#usize [ i4, i5, i6, i7, 0#u64 ]) u v0
  let i8 ← Array.index_usize f 0#usize
  let i9 ← Array.index_usize g 0#usize
  let a ← InvertBlocksInst.divstep59 d i8 i9
  let m00 ← Array.index_usize a 1#usize
  let m01 ← Array.index_usize a 2#usize
  let m10 ← Array.index_usize a 3#usize
  let m11 ← Array.index_usize a 4#usize
  let i10 ← lift (core.num.U64.wrapping_mul i8 m00)
  let i11 ← lift (core.num.U64.wrapping_mul i9 m01)
  let i12 ← lift (core.num.U64.wrapping_add i10 i11)
  let i13 ← lift (UScalar.hcast .I64 i12)
  let i14 ← i13 >>> 63#i32
  let sign ← lift (IScalar.hcast .U64 i14)
  let a1 ← InvertBlocksInst.sign_mag m00 m01 m10 m11
  let m001 ← Array.index_usize a1 0#usize
  let m011 ← Array.index_usize a1 1#usize
  let s00 ← Array.index_usize a1 4#usize
  let s01 ← Array.index_usize a1 5#usize
  let i15 ← lift (s00 ^^^ sign)
  let i16 ← lift (s01 ^^^ sign)
  let t ← InvertBlocksInst.uv_row u1 v m001 m011 i15 i16
  let a2 ← InvertBlocksInst.amontred t modulus inv
  InvertBlocksInst.cond_sub a2 modulus

end pasta_curves
