-- THIS FILE WAS AUTOMATICALLY GENERATED BY AENEAS
-- [pasta_curves]: function definitions
module
public import Aeneas
public import PastaCurves.Portable.Types
@[expose] public section
open Aeneas Aeneas.Std Result ControlFlow Error
set_option linter.dupNamespace false
set_option linter.hashCommand false
set_option linter.unusedVariables false
set_option linter.style.whitespace false
set_option linter.style.setOption false
set_option linter.style.longLine false

/- You can set the `maxHeartbeats` value with the `-max-heartbeats` CLI option -/
set_option maxHeartbeats 1000000

/- You can set the `maxRecDepth` value with the `-max-recdepth` CLI option -/
set_option maxRecDepth 2048

namespace pasta_curves

/-- [pasta_curves::inversion::portable::sign_mask]:
    Source: 'src/inversion/portable.rs', lines 23:0-25:1 -/
def inversion.portable.sign_mask (x : Std.U64) : Result Std.U64 := do
  let i ← lift (UScalar.hcast .I64 x)
  let i1 ← i >>> 63#i32
  ok (IScalar.hcast .U64 i1)

/-- [pasta_curves::inversion::portable::divstep]:
    Source: 'src/inversion/portable.rs', lines 32:0-39:1 -/
def inversion.portable.divstep
  (two_delta : Std.U64) (f : Std.U64) (g : Std.U64) :
  Result (Std.U64 × Std.U64 × Std.U64)
  := do
  let i ← lift (g &&& 1#u64)
  let odd ← lift (core.num.U64.wrapping_sub 0#u64 i)
  let i1 ← lift (core.num.U64.wrapping_sub 0#u64 two_delta)
  let i2 ← inversion.portable.sign_mask i1
  let swap ← lift (odd &&& i2)
  let i3 ← lift (core.num.U64.wrapping_sub 2#u64 two_delta)
  let i4 ← lift (swap &&& i3)
  let i5 ← lift (~~~ swap)
  let i6 ← lift (core.num.U64.wrapping_add two_delta 2#u64)
  let i7 ← lift (i5 &&& i6)
  let two_delta_new ← lift (i4 ||| i7)
  let i8 ← lift (swap &&& g)
  let i9 ← lift (~~~ swap)
  let i10 ← lift (i9 &&& f)
  let f_new ← lift (i8 ||| i10)
  let i11 ← lift (core.num.U64.wrapping_sub g f)
  let i12 ← lift (swap &&& i11)
  let i13 ← lift (~~~ swap)
  let i14 ← lift (odd &&& f)
  let i15 ← lift (core.num.U64.wrapping_add g i14)
  let i16 ← lift (i13 &&& i15)
  let sum ← lift (i12 ||| i16)
  let i17 ← lift (UScalar.hcast .I64 sum)
  let i18 ← i17 >>> 1#i32
  let i19 ← lift (IScalar.hcast .U64 i18)
  ok (two_delta_new, f_new, i19)

/-- [pasta_curves::inversion::portable::unpack]:
    Source: 'src/inversion/portable.rs', lines 45:0-50:1 -/
def inversion.portable.unpack
  (k : Std.U32) (w : Std.U64) : Result (Std.U64 × Std.U64) := do
  let i ← lift (core.num.U64.wrapping_sub 0#u64 w)
  let t ← lift (UScalar.hcast .I64 i)
  let i1 ← 40#u32 - k
  let i2 ← 1#i64 <<< i1
  let i3 ← lift (core.num.I64.wrapping_add t i2)
  let i4 ← 41#u32 - k
  let up ← i3 >>> i4
  let i5 ← 1#i64 <<< 20#i32
  let i6 ← i5 - 1#i64
  let i7 ← lift (core.num.I64.wrapping_add up i6)
  let v ← i7 >>> 21#i32
  let i8 ← v <<< 21#i32
  let i9 ← lift (core.num.I64.wrapping_sub up i8)
  let i10 ← lift (IScalar.hcast .U64 i9)
  let i11 ← lift (IScalar.hcast .U64 v)
  ok (i10, i11)

/-- [pasta_curves::inversion::portable::batch]: loop body 0:
    Source: 'src/inversion/portable.rs', lines 61:4-63:5 -/
@[rust_loop_body]
def inversion.portable.batch_loop.body
  (iter : core.ops.range.Range Std.U32) (two_delta : Std.U64) (pf : Std.U64)
  (pg : Std.U64) :
  Result (ControlFlow ((core.ops.range.Range Std.U32) × Std.U64 × Std.U64 ×
    Std.U64) (Std.U64 × Std.U64 × Std.U64))
  := do
  let (o, iter1) ←
    core.iter.range.IteratorRange.next core.iter.range.StepU32 iter
  match o with
  | none => ok (done (two_delta, pf, pg))
  | some _ =>
    let (two_delta1, pf1, pg1) ← inversion.portable.divstep two_delta pf pg
    ok (cont (iter1, two_delta1, pf1, pg1))

/-- [pasta_curves::inversion::portable::batch]: loop 0:
    Source: 'src/inversion/portable.rs', lines 61:4-63:5 -/
@[rust_loop]
def inversion.portable.batch_loop
  (iter : core.ops.range.Range Std.U32) (two_delta : Std.U64) (pf : Std.U64)
  (pg : Std.U64) :
  Result (Std.U64 × Std.U64 × Std.U64)
  := do
  loop
    (fun (iter1, two_delta1, pf1, pg1) => inversion.portable.batch_loop.body
      iter1 two_delta1 pf1 pg1)
    (iter, two_delta, pf, pg)

/-- [pasta_curves::inversion::portable::batch]:
    Source: 'src/inversion/portable.rs', lines 57:0-67:1 -/
def inversion.portable.batch
  (k : Std.U32) (two_delta : Std.U64) (f : Std.U64) (g : Std.U64) :
  Result (Array Std.U64 5#usize)
  := do
  let i ← lift (f &&& 1048575#u64)
  let pf ← lift (i ||| 18446741874686296064#u64)
  let i1 ← lift (g &&& 1048575#u64)
  let pg ← lift (i1 ||| 13835058055282163712#u64)
  let (two_delta1, pf1, pg1) ←
    inversion.portable.batch_loop { start := 0#u32, «end» := k } two_delta pf
      pg
  let (u, v) ← inversion.portable.unpack k pf1
  let (q, r) ← inversion.portable.unpack k pg1
  ok (Array.make 5#usize [ two_delta1, u, v, q, r ])

/-- [pasta_curves::inversion::portable::next_low]:
    Source: 'src/inversion/portable.rs', lines 72:0-74:1 -/
def inversion.portable.next_low
  (k : Std.U32) (a : Std.U64) (b : Std.U64) (f : Std.U64) (g : Std.U64) :
  Result Std.U64
  := do
  let i ← lift (core.num.U64.wrapping_mul a f)
  let i1 ← lift (core.num.U64.wrapping_mul b g)
  let i2 ← lift (core.num.U64.wrapping_add i i1)
  i2 >>> k

/-- [pasta_curves::inversion::portable::mat_mul]:
    Source: 'src/inversion/portable.rs', lines 78:0-89:1 -/
def inversion.portable.mat_mul
  (m : Array Std.U64 4#usize) (n : Array Std.U64 4#usize) :
  Result (Array Std.U64 4#usize)
  := do
  let i ← Array.index_usize m 0#usize
  let i1 ← Array.index_usize n 0#usize
  let i2 ← lift (core.num.U64.wrapping_mul i i1)
  let i3 ← Array.index_usize m 1#usize
  let i4 ← Array.index_usize n 2#usize
  let i5 ← lift (core.num.U64.wrapping_mul i3 i4)
  let i6 ← lift (core.num.U64.wrapping_add i2 i5)
  let i7 ← Array.index_usize n 1#usize
  let i8 ← lift (core.num.U64.wrapping_mul i i7)
  let i9 ← Array.index_usize n 3#usize
  let i10 ← lift (core.num.U64.wrapping_mul i3 i9)
  let i11 ← lift (core.num.U64.wrapping_add i8 i10)
  let i12 ← Array.index_usize m 2#usize
  let i13 ← lift (core.num.U64.wrapping_mul i12 i1)
  let i14 ← Array.index_usize m 3#usize
  let i15 ← lift (core.num.U64.wrapping_mul i14 i4)
  let i16 ← lift (core.num.U64.wrapping_add i13 i15)
  let i17 ← lift (core.num.U64.wrapping_mul i12 i7)
  let i18 ← lift (core.num.U64.wrapping_mul i14 i9)
  let i19 ← lift (core.num.U64.wrapping_add i17 i18)
  ok (Array.make 4#usize [ i6, i11, i16, i19 ])

/-- [pasta_curves::inversion::portable::negate]: loop body 0:
    Source: 'src/inversion/portable.rs', lines 96:4-100:5 -/
@[rust_loop_body]
def inversion.portable.negate_loop.body
  (x : Array Std.U64 5#usize) (s : Std.U64)
  (iter : core.ops.range.Range Std.Usize) (out : Array Std.U64 5#usize)
  (carry : Std.U64) :
  Result (ControlFlow ((core.ops.range.Range Std.Usize) × (Array Std.U64
    5#usize) × Std.U64) (Array Std.U64 5#usize))
  := do
  let (o, iter1) ←
    core.iter.range.IteratorRange.next core.iter.range.StepUsize iter
  match o with
  | none => ok (done out)
  | some i =>
    let i1 ← Array.index_usize x i
    let i2 ← lift (i1 ^^^ s)
    let (word, overflow) ← lift (core.num.U64.overflowing_add i2 carry)
    let a ← Array.update out i word
    let carry1 ← lift (core.convert.num.FromU64Bool.from overflow)
    ok (cont (iter1, a, carry1))

/-- [pasta_curves::inversion::portable::negate]: loop 0:
    Source: 'src/inversion/portable.rs', lines 96:4-100:5 -/
@[rust_loop]
def inversion.portable.negate_loop
  (iter : core.ops.range.Range Std.Usize) (x : Array Std.U64 5#usize)
  (s : Std.U64) (out : Array Std.U64 5#usize) (carry : Std.U64) :
  Result (Array Std.U64 5#usize)
  := do
  loop
    (fun (iter1, out1, carry1) => inversion.portable.negate_loop.body x s iter1
      out1 carry1)
    (iter, out, carry)

/-- [pasta_curves::inversion::portable::negate]:
    Source: 'src/inversion/portable.rs', lines 93:0-102:1 -/
def inversion.portable.negate
  (x : Array Std.U64 5#usize) (s : Std.U64) :
  Result (Array Std.U64 5#usize)
  := do
  let out := Array.repeat 5#usize 0#u64
  let carry ← lift (s &&& 1#u64)
  inversion.portable.negate_loop { start := 0#usize, «end» := 5#usize } x s
    out carry

/-- [pasta_curves::inversion::portable::row]: loop body 0:
    Source: 'src/inversion/portable.rs', lines 113:4-117:5 -/
@[rust_loop_body]
def inversion.portable.row_loop.body
  (m0 : Std.U64) (m1 : Std.U64) (x : Array Std.U64 5#usize)
  (y : Array Std.U64 5#usize) (iter : core.ops.range.Range Std.Usize)
  (out : Array Std.U64 5#usize) (carry : Std.U128) :
  Result (ControlFlow ((core.ops.range.Range Std.Usize) × (Array Std.U64
    5#usize) × Std.U128) (Array Std.U64 5#usize))
  := do
  let (o, iter1) ←
    core.iter.range.IteratorRange.next core.iter.range.StepUsize iter
  match o with
  | none => ok (done out)
  | some i =>
    let i1 ← Array.index_usize x i
    let i2 ← lift (core.convert.num.FromU128U64.from i1)
    let i3 ← lift (core.convert.num.FromU128U64.from m0)
    let i4 ← i2 * i3
    let i5 ← carry + i4
    let i6 ← Array.index_usize y i
    let i7 ← lift (core.convert.num.FromU128U64.from i6)
    let i8 ← lift (core.convert.num.FromU128U64.from m1)
    let i9 ← i7 * i8
    let column ← i5 + i9
    let i10 ← lift (UScalar.cast .U64 column)
    let a ← Array.update out i i10
    let carry1 ← column >>> 64#i32
    ok (cont (iter1, a, carry1))

/-- [pasta_curves::inversion::portable::row]: loop 0:
    Source: 'src/inversion/portable.rs', lines 113:4-117:5 -/
@[rust_loop]
def inversion.portable.row_loop
  (iter : core.ops.range.Range Std.Usize) (m0 : Std.U64) (m1 : Std.U64)
  (x : Array Std.U64 5#usize) (y : Array Std.U64 5#usize)
  (out : Array Std.U64 5#usize) (carry : Std.U128) :
  Result (Array Std.U64 5#usize)
  := do
  loop
    (fun (iter1, out1, carry1) => inversion.portable.row_loop.body m0 m1 x y
      iter1 out1 carry1)
    (iter, out, carry)

/-- [pasta_curves::inversion::portable::row]:
    Source: 'src/inversion/portable.rs', lines 108:0-119:1 -/
def inversion.portable.row
  (x : Array Std.U64 5#usize) (y : Array Std.U64 5#usize) (m0 : Std.U64)
  (m1 : Std.U64) (s0 : Std.U64) (s1 : Std.U64) :
  Result (Array Std.U64 5#usize)
  := do
  let x1 ← inversion.portable.negate x s0
  let y1 ← inversion.portable.negate y s1
  let out := Array.repeat 5#usize 0#u64
  inversion.portable.row_loop { start := 0#usize, «end» := 5#usize } m0 m1 x1
    y1 out 0#u128

/-- [pasta_curves::inversion::portable::add5]: loop body 0:
    Source: 'src/inversion/portable.rs', lines 126:4-131:5 -/
@[rust_loop_body]
def inversion.portable.add5_loop.body
  (x : Array Std.U64 5#usize) (y : Array Std.U64 5#usize)
  (iter : core.ops.range.Range Std.Usize) (out : Array Std.U64 5#usize)
  (carry : Std.U64) :
  Result (ControlFlow ((core.ops.range.Range Std.Usize) × (Array Std.U64
    5#usize) × Std.U64) (Array Std.U64 5#usize))
  := do
  let (o, iter1) ←
    core.iter.range.IteratorRange.next core.iter.range.StepUsize iter
  match o with
  | none => ok (done out)
  | some i =>
    let i1 ← Array.index_usize x i
    let i2 ← Array.index_usize y i
    let (sum, overflow1) ← lift (core.num.U64.overflowing_add i1 i2)
    let (sum1, overflow2) ← lift (core.num.U64.overflowing_add sum carry)
    let a ← Array.update out i sum1
    let carry1 ←
      lift (core.convert.num.FromU64Bool.from (overflow1 || overflow2))
    ok (cont (iter1, a, carry1))

/-- [pasta_curves::inversion::portable::add5]: loop 0:
    Source: 'src/inversion/portable.rs', lines 126:4-131:5 -/
@[rust_loop]
def inversion.portable.add5_loop
  (iter : core.ops.range.Range Std.Usize) (x : Array Std.U64 5#usize)
  (y : Array Std.U64 5#usize) (out : Array Std.U64 5#usize) (carry : Std.U64) :
  Result (Array Std.U64 5#usize)
  := do
  loop
    (fun (iter1, out1, carry1) => inversion.portable.add5_loop.body x y iter1
      out1 carry1)
    (iter, out, carry)

/-- [pasta_curves::inversion::portable::add5]:
    Source: 'src/inversion/portable.rs', lines 123:0-133:1 -/
def inversion.portable.add5
  (x : Array Std.U64 5#usize) (y : Array Std.U64 5#usize) :
  Result (Array Std.U64 5#usize)
  := do
  let out := Array.repeat 5#usize 0#u64
  inversion.portable.add5_loop { start := 0#usize, «end» := 5#usize } x y out
    0#u64

/-- [pasta_curves::inversion::portable::{impl pasta_curves::inversion::InvertBlocks for pasta_curves::inversion::portable::Backend}::cond_sub]: loop body 0:
    Source: 'src/inversion/portable.rs', lines 234:8-239:9 -/
@[rust_loop_body]
def
  inversion.portable.Backend.Insts.Pasta_curvesInversionInvertBlocks.cond_sub_loop0.body
  (value : Array Std.U64 4#usize) (modulus : Array Std.U64 4#usize)
  (iter : core.ops.range.Range Std.Usize) (difference : Array Std.U64 4#usize)
  (borrow : Std.U64) :
  Result (ControlFlow ((core.ops.range.Range Std.Usize) × (Array Std.U64
    4#usize) × Std.U64) ((Array Std.U64 4#usize) × Std.U64))
  := do
  let (o, iter1) ←
    core.iter.range.IteratorRange.next core.iter.range.StepUsize iter
  match o with
  | none => ok (done (difference, borrow))
  | some i =>
    let i1 ← Array.index_usize value i
    let i2 ← Array.index_usize modulus i
    let (word, underflow1) ← lift (core.num.U64.overflowing_sub i1 i2)
    let (word1, underflow2) ← lift (core.num.U64.overflowing_sub word borrow)
    let a ← Array.update difference i word1
    let borrow1 ←
      lift (core.convert.num.FromU64Bool.from (underflow1 || underflow2))
    ok (cont (iter1, a, borrow1))

/-- [pasta_curves::inversion::portable::{impl pasta_curves::inversion::InvertBlocks for pasta_curves::inversion::portable::Backend}::cond_sub]: loop 0:
    Source: 'src/inversion/portable.rs', lines 234:8-239:9 -/
@[rust_loop]
def
  inversion.portable.Backend.Insts.Pasta_curvesInversionInvertBlocks.cond_sub_loop0
  (iter : core.ops.range.Range Std.Usize) (value : Array Std.U64 4#usize)
  (modulus : Array Std.U64 4#usize) (difference : Array Std.U64 4#usize)
  (borrow : Std.U64) :
  Result ((Array Std.U64 4#usize) × Std.U64)
  := do
  loop
    (fun (iter1, difference1, borrow1) =>
      inversion.portable.Backend.Insts.Pasta_curvesInversionInvertBlocks.cond_sub_loop0.body
      value modulus iter1 difference1 borrow1)
    (iter, difference, borrow)

/-- [pasta_curves::inversion::portable::{impl pasta_curves::inversion::InvertBlocks for pasta_curves::inversion::portable::Backend}::cond_sub]: loop body 1:
    Source: 'src/inversion/portable.rs', lines 242:8-244:9 -/
@[rust_loop_body]
def
  inversion.portable.Backend.Insts.Pasta_curvesInversionInvertBlocks.cond_sub_loop1.body
  (value : Array Std.U64 4#usize) (difference : Array Std.U64 4#usize)
  (keep : Std.U64) (iter : core.ops.range.Range Std.Usize)
  (out : Array Std.U64 4#usize) :
  Result (ControlFlow ((core.ops.range.Range Std.Usize) × (Array Std.U64
    4#usize)) (Array Std.U64 4#usize))
  := do
  let (o, iter1) ←
    core.iter.range.IteratorRange.next core.iter.range.StepUsize iter
  match o with
  | none => ok (done out)
  | some i =>
    let i1 ← Array.index_usize value i
    let i2 ← lift (keep &&& i1)
    let i3 ← lift (~~~ keep)
    let i4 ← Array.index_usize difference i
    let i5 ← lift (i3 &&& i4)
    let i6 ← lift (i2 ||| i5)
    let a ← Array.update out i i6
    ok (cont (iter1, a))

/-- [pasta_curves::inversion::portable::{impl pasta_curves::inversion::InvertBlocks for pasta_curves::inversion::portable::Backend}::cond_sub]: loop 1:
    Source: 'src/inversion/portable.rs', lines 242:8-244:9 -/
@[rust_loop]
def
  inversion.portable.Backend.Insts.Pasta_curvesInversionInvertBlocks.cond_sub_loop1
  (iter : core.ops.range.Range Std.Usize) (value : Array Std.U64 4#usize)
  (difference : Array Std.U64 4#usize) (keep : Std.U64)
  (out : Array Std.U64 4#usize) :
  Result (Array Std.U64 4#usize)
  := do
  loop
    (fun (iter1, out1) =>
      inversion.portable.Backend.Insts.Pasta_curvesInversionInvertBlocks.cond_sub_loop1.body
      value difference keep iter1 out1)
    (iter, out)

/-- [pasta_curves::inversion::portable::{impl pasta_curves::inversion::InvertBlocks for pasta_curves::inversion::portable::Backend}::cond_sub]:
    Source: 'src/inversion/portable.rs', lines 231:4-246:5 -/
def inversion.portable.Backend.Insts.Pasta_curvesInversionInvertBlocks.cond_sub
  (value : Array Std.U64 4#usize) (modulus : Array Std.U64 4#usize) :
  Result (Array Std.U64 4#usize)
  := do
  let difference := Array.repeat 4#usize 0#u64
  let (difference1, borrow) ←
    inversion.portable.Backend.Insts.Pasta_curvesInversionInvertBlocks.cond_sub_loop0
      { start := 0#usize, «end» := 4#usize } value modulus difference 0#u64
  let keep ← lift (core.num.U64.wrapping_sub 0#u64 borrow)
  let out := Array.repeat 4#usize 0#u64
  inversion.portable.Backend.Insts.Pasta_curvesInversionInvertBlocks.cond_sub_loop1
    { start := 0#usize, «end» := 4#usize } value difference1 keep out

/-- [pasta_curves::inversion::portable::{impl pasta_curves::inversion::InvertBlocks for pasta_curves::inversion::portable::Backend}::amontred]:
    Source: 'src/inversion/portable.rs', lines 204:4-227:5 -/
def inversion.portable.Backend.Insts.Pasta_curvesInversionInvertBlocks.amontred
  (t : Array Std.U64 5#usize) (modulus : Array Std.U64 4#usize) (inv : Std.U64)
  :
  Result (Array Std.U64 4#usize)
  := do
  let i ← Array.index_usize modulus 0#usize
  let i1 ← i <<< 61#i32
  let i2 ← i >>> 3#i32
  let i3 ← Array.index_usize modulus 1#usize
  let i4 ← i3 <<< 61#i32
  let i5 ← lift (i2 ||| i4)
  let i6 ← i3 >>> 3#i32
  let i7 ← Array.index_usize modulus 2#usize
  let i8 ← i7 <<< 61#i32
  let i9 ← lift (i6 ||| i8)
  let i10 ← i7 >>> 3#i32
  let i11 ← Array.index_usize modulus 3#usize
  let i12 ← i11 <<< 61#i32
  let i13 ← lift (i10 ||| i12)
  let i14 ← i11 >>> 3#i32
  let s ←
    inversion.portable.add5 t (Array.make 5#usize [ i1, i5, i9, i13, i14 ])
  let i15 ← Array.index_usize s 0#usize
  let w ← lift (core.num.U64.wrapping_mul i15 inv)
  let i16 ← lift (core.convert.num.FromU128U64.from i15)
  let i17 ← lift (core.convert.num.FromU128U64.from w)
  let i18 ← lift (core.convert.num.FromU128U64.from i)
  let i19 ← i17 * i18
  let i20 ← i16 + i19
  let carry ← i20 >>> 64#i32
  let i21 ← Array.index_usize s 1#usize
  let i22 ← lift (core.convert.num.FromU128U64.from i21)
  let i23 ← carry + i22
  let i24 ← lift (core.convert.num.FromU128U64.from w)
  let i25 ← lift (core.convert.num.FromU128U64.from i3)
  let i26 ← i24 * i25
  let column1 ← i23 + i26
  let i27 ← column1 >>> 64#i32
  let i28 ← Array.index_usize s 2#usize
  let i29 ← lift (core.convert.num.FromU128U64.from i28)
  let i30 ← i27 + i29
  let i31 ← lift (core.convert.num.FromU128U64.from w)
  let i32 ← lift (core.convert.num.FromU128U64.from i7)
  let i33 ← i31 * i32
  let column2 ← i30 + i33
  let i34 ← column2 >>> 64#i32
  let i35 ← Array.index_usize s 3#usize
  let i36 ← lift (core.convert.num.FromU128U64.from i35)
  let i37 ← i34 + i36
  let i38 ← lift (core.convert.num.FromU128U64.from w)
  let i39 ← lift (core.convert.num.FromU128U64.from i11)
  let i40 ← i38 * i39
  let column3 ← i37 + i40
  let i41 ← column3 >>> 64#i32
  let i42 ← Array.index_usize s 4#usize
  let i43 ← lift (core.convert.num.FromU128U64.from i42)
  let column4 ← i41 + i43
  let i44 ← lift (UScalar.cast .U64 column1)
  let i45 ← lift (UScalar.cast .U64 column2)
  let i46 ← lift (UScalar.cast .U64 column3)
  let i47 ← lift (UScalar.cast .U64 column4)
  ok (Array.make 4#usize [ i44, i45, i46, i47 ])

/-- [pasta_curves::inversion::portable::{impl pasta_curves::inversion::InvertBlocks for pasta_curves::inversion::portable::Backend}::de_row]:
    Source: 'src/inversion/portable.rs', lines 194:4-198:5 -/
def inversion.portable.Backend.Insts.Pasta_curvesInversionInvertBlocks.de_row
  (d : Array Std.U64 4#usize) (e : Array Std.U64 4#usize) (m0 : Std.U64)
  (m1 : Std.U64) (s0 : Std.U64) (s1 : Std.U64) :
  Result (Array Std.U64 5#usize)
  := do
  let i ← Array.index_usize d 0#usize
  let i1 ← Array.index_usize d 1#usize
  let i2 ← Array.index_usize d 2#usize
  let i3 ← Array.index_usize d 3#usize
  let i4 ← Array.index_usize e 0#usize
  let i5 ← Array.index_usize e 1#usize
  let i6 ← Array.index_usize e 2#usize
  let i7 ← Array.index_usize e 3#usize
  inversion.portable.row (Array.make 5#usize [ i, i1, i2, i3, 0#u64 ])
    (Array.make 5#usize [ i4, i5, i6, i7, 0#u64 ]) m0 m1 s0 s1

/-- [pasta_curves::inversion::portable::{impl pasta_curves::inversion::InvertBlocks for pasta_curves::inversion::portable::Backend}::fg_row]:
    Source: 'src/inversion/portable.rs', lines 181:4-190:5 -/
def inversion.portable.Backend.Insts.Pasta_curvesInversionInvertBlocks.fg_row
  (f : Array Std.U64 5#usize) (g : Array Std.U64 5#usize) (m0 : Std.U64)
  (m1 : Std.U64) (s0 : Std.U64) (s1 : Std.U64) :
  Result (Array Std.U64 5#usize)
  := do
  let t ← inversion.portable.row f g m0 m1 s0 s1
  let i ← Array.index_usize t 0#usize
  let i1 ← i >>> 59#i32
  let i2 ← Array.index_usize t 1#usize
  let i3 ← i2 <<< 5#i32
  let i4 ← lift (i1 ||| i3)
  let i5 ← i2 >>> 59#i32
  let i6 ← Array.index_usize t 2#usize
  let i7 ← i6 <<< 5#i32
  let i8 ← lift (i5 ||| i7)
  let i9 ← i6 >>> 59#i32
  let i10 ← Array.index_usize t 3#usize
  let i11 ← i10 <<< 5#i32
  let i12 ← lift (i9 ||| i11)
  let i13 ← i10 >>> 59#i32
  let i14 ← Array.index_usize t 4#usize
  let i15 ← i14 <<< 5#i32
  let i16 ← lift (i13 ||| i15)
  let i17 ← lift (UScalar.hcast .I64 i14)
  let i18 ← i17 >>> 59#i32
  let i19 ← lift (IScalar.hcast .U64 i18)
  ok (Array.make 5#usize [ i4, i8, i12, i16, i19 ])

/-- [pasta_curves::inversion::portable::{impl pasta_curves::inversion::InvertBlocks for pasta_curves::inversion::portable::Backend}::sign_mag]:
    Source: 'src/inversion/portable.rs', lines 159:4-176:5 -/
def inversion.portable.Backend.Insts.Pasta_curvesInversionInvertBlocks.sign_mag
  (u : Std.U64) (v : Std.U64) (q : Std.U64) (r : Std.U64) :
  Result (Array Std.U64 8#usize)
  := do
  let i ← inversion.portable.sign_mask u
  let i1 ← inversion.portable.sign_mask v
  let i2 ← inversion.portable.sign_mask q
  let i3 ← inversion.portable.sign_mask r
  let su ← Array.index_usize (Array.make 4#usize [ i, i1, i2, i3 ]) 0#usize
  let sv ← Array.index_usize (Array.make 4#usize [ i, i1, i2, i3 ]) 1#usize
  let sq ← Array.index_usize (Array.make 4#usize [ i, i1, i2, i3 ]) 2#usize
  let sr ← Array.index_usize (Array.make 4#usize [ i, i1, i2, i3 ]) 3#usize
  let i4 ← lift (u ^^^ su)
  let i5 ← lift (core.num.U64.wrapping_sub i4 su)
  let i6 ← lift (v ^^^ sv)
  let i7 ← lift (core.num.U64.wrapping_sub i6 sv)
  let i8 ← lift (q ^^^ sq)
  let i9 ← lift (core.num.U64.wrapping_sub i8 sq)
  let i10 ← lift (r ^^^ sr)
  let i11 ← lift (core.num.U64.wrapping_sub i10 sr)
  ok (Array.make 8#usize [ i5, i7, i9, i11, su, sv, sq, sr ])

/-- [pasta_curves::inversion::portable::{impl pasta_curves::inversion::InvertBlocks for pasta_curves::inversion::portable::Backend}::divstep59]:
    Source: 'src/inversion/portable.rs', lines 142:4-155:5 -/
def
  inversion.portable.Backend.Insts.Pasta_curvesInversionInvertBlocks.divstep59
  (two_delta : Std.U64) (f0 : Std.U64) (g0 : Std.U64) :
  Result (Array Std.U64 5#usize)
  := do
  let a ← inversion.portable.batch 20#u32 two_delta f0 g0
  let two_delta1 ← Array.index_usize a 0#usize
  let u1 ← Array.index_usize a 1#usize
  let v1 ← Array.index_usize a 2#usize
  let q1 ← Array.index_usize a 3#usize
  let r1 ← Array.index_usize a 4#usize
  let f1 ← inversion.portable.next_low 20#u32 u1 v1 f0 g0
  let g1 ← inversion.portable.next_low 20#u32 q1 r1 f0 g0
  let a1 ← inversion.portable.batch 20#u32 two_delta1 f1 g1
  let two_delta2 ← Array.index_usize a1 0#usize
  let u2 ← Array.index_usize a1 1#usize
  let v2 ← Array.index_usize a1 2#usize
  let q2 ← Array.index_usize a1 3#usize
  let r2 ← Array.index_usize a1 4#usize
  let f2 ← inversion.portable.next_low 20#u32 u2 v2 f1 g1
  let g2 ← inversion.portable.next_low 20#u32 q2 r2 f1 g1
  let a2 ← inversion.portable.batch 19#u32 two_delta2 f2 g2
  let two_delta3 ← Array.index_usize a2 0#usize
  let u3 ← Array.index_usize a2 1#usize
  let v3 ← Array.index_usize a2 2#usize
  let q3 ← Array.index_usize a2 3#usize
  let r3 ← Array.index_usize a2 4#usize
  let a3 ←
    inversion.portable.mat_mul (Array.make 4#usize [ u2, v2, q2, r2 ])
      (Array.make 4#usize [ u1, v1, q1, r1 ])
  let a4 ←
    inversion.portable.mat_mul (Array.make 4#usize [ u3, v3, q3, r3 ]) a3
  let u ← Array.index_usize a4 0#usize
  let v ← Array.index_usize a4 1#usize
  let q ← Array.index_usize a4 2#usize
  let r ← Array.index_usize a4 3#usize
  ok (Array.make 5#usize [ two_delta3, u, v, q, r ])

/-- Trait implementation: [pasta_curves::inversion::portable::{impl pasta_curves::inversion::InvertBlocks for pasta_curves::inversion::portable::Backend}]
    Source: 'src/inversion/portable.rs', lines 138:0-247:1 -/
@[reducible]
def inversion.portable.Backend.Insts.Pasta_curvesInversionInvertBlocks :
  inversion.InvertBlocks inversion.portable.Backend := {
  divstep59 :=
    inversion.portable.Backend.Insts.Pasta_curvesInversionInvertBlocks.divstep59
  sign_mag :=
    inversion.portable.Backend.Insts.Pasta_curvesInversionInvertBlocks.sign_mag
  fg_row :=
    inversion.portable.Backend.Insts.Pasta_curvesInversionInvertBlocks.fg_row
  de_row :=
    inversion.portable.Backend.Insts.Pasta_curvesInversionInvertBlocks.de_row
  amontred :=
    inversion.portable.Backend.Insts.Pasta_curvesInversionInvertBlocks.amontred
  cond_sub :=
    inversion.portable.Backend.Insts.Pasta_curvesInversionInvertBlocks.cond_sub
}

/-- [pasta_curves::inversion::invert_with]: loop body 0:
    Source: 'src/inversion.rs', lines 82:4-93:5 -/
@[rust_loop_body]
def inversion.invert_with_loop.body
  {B : Type} (InvertBlocksInst : inversion.InvertBlocks B)
  (modulus : Array Std.U64 4#usize) (inv : Std.U64)
  (iter : core.ops.range.Range Std.I32) (two_delta : Std.U64)
  (f : Array Std.U64 5#usize) (g : Array Std.U64 5#usize)
  (d : Array Std.U64 4#usize) (e : Array Std.U64 4#usize) :
  Result (ControlFlow ((core.ops.range.Range Std.I32) × Std.U64 × (Array
    Std.U64 5#usize) × (Array Std.U64 5#usize) × (Array Std.U64 4#usize) ×
    (Array Std.U64 4#usize)) (Std.U64 × (Array Std.U64 5#usize) × (Array
    Std.U64 5#usize) × (Array Std.U64 4#usize) × (Array Std.U64 4#usize)))
  := do
  let (o, iter1) ←
    core.iter.range.IteratorRange.next core.iter.range.StepI32 iter
  match o with
  | none => ok (done (two_delta, f, g, d, e))
  | some _ =>
    let i ← Array.index_usize f 0#usize
    let i1 ← Array.index_usize g 0#usize
    let a ← InvertBlocksInst.divstep59 two_delta i i1
    let two_delta_new ← Array.index_usize a 0#usize
    let u ← Array.index_usize a 1#usize
    let v ← Array.index_usize a 2#usize
    let q ← Array.index_usize a 3#usize
    let r ← Array.index_usize a 4#usize
    let a1 ← InvertBlocksInst.sign_mag u v q r
    let u1 ← Array.index_usize a1 0#usize
    let v1 ← Array.index_usize a1 1#usize
    let q1 ← Array.index_usize a1 2#usize
    let r1 ← Array.index_usize a1 3#usize
    let su ← Array.index_usize a1 4#usize
    let sv ← Array.index_usize a1 5#usize
    let sq ← Array.index_usize a1 6#usize
    let sr ← Array.index_usize a1 7#usize
    let f_new ← InvertBlocksInst.fg_row f g u1 v1 su sv
    let g1 ← InvertBlocksInst.fg_row f g q1 r1 sq sr
    let td ← InvertBlocksInst.de_row d e u1 v1 su sv
    let te ← InvertBlocksInst.de_row d e q1 r1 sq sr
    let d1 ← InvertBlocksInst.amontred td modulus inv
    let e1 ← InvertBlocksInst.amontred te modulus inv
    ok (cont (iter1, two_delta_new, f_new, g1, d1, e1))

/-- [pasta_curves::inversion::invert_with]: loop 0:
    Source: 'src/inversion.rs', lines 82:4-93:5 -/
@[rust_loop]
def inversion.invert_with_loop
  {B : Type} (InvertBlocksInst : inversion.InvertBlocks B)
  (iter : core.ops.range.Range Std.I32) (modulus : Array Std.U64 4#usize)
  (inv : Std.U64) (two_delta : Std.U64) (f : Array Std.U64 5#usize)
  (g : Array Std.U64 5#usize) (d : Array Std.U64 4#usize)
  (e : Array Std.U64 4#usize) :
  Result (Std.U64 × (Array Std.U64 5#usize) × (Array Std.U64 5#usize) ×
    (Array Std.U64 4#usize) × (Array Std.U64 4#usize))
  := do
  loop
    (fun (iter1, two_delta1, f1, g1, d1, e1) => inversion.invert_with_loop.body
      InvertBlocksInst modulus inv iter1 two_delta1 f1 g1 d1 e1)
    (iter, two_delta, f, g, d, e)

/-- [pasta_curves::inversion::invert_with]:
    Source: 'src/inversion.rs', lines 71:0-99:1 -/
def inversion.invert_with
  {B : Type} (InvertBlocksInst : inversion.InvertBlocks B)
  (x : Array Std.U64 4#usize) (modulus : Array Std.U64 4#usize) (inv : Std.U64)
  (e0 : Array Std.U64 4#usize) :
  Result (Array Std.U64 4#usize)
  := do
  let i ← Array.index_usize modulus 0#usize
  let i1 ← Array.index_usize modulus 1#usize
  let i2 ← Array.index_usize modulus 2#usize
  let i3 ← Array.index_usize modulus 3#usize
  let i4 ← Array.index_usize x 0#usize
  let i5 ← Array.index_usize x 1#usize
  let i6 ← Array.index_usize x 2#usize
  let i7 ← Array.index_usize x 3#usize
  let d := Array.repeat 4#usize 0#u64
  let (two_delta, f, g, d1, e) ←
    inversion.invert_with_loop InvertBlocksInst
      { start := 0#i32, «end» := 9#i32 } modulus inv 1#u64
      (Array.make 5#usize [ i, i1, i2, i3, 0#u64 ])
      (Array.make 5#usize [ i4, i5, i6, i7, 0#u64 ]) d e0
  let i8 ← Array.index_usize f 0#usize
  let i9 ← Array.index_usize g 0#usize
  let a ← InvertBlocksInst.divstep59 two_delta i8 i9
  let u ← Array.index_usize a 1#usize
  let v ← Array.index_usize a 2#usize
  let q ← Array.index_usize a 3#usize
  let r ← Array.index_usize a 4#usize
  let i10 ← lift (core.num.U64.wrapping_mul i8 u)
  let i11 ← lift (core.num.U64.wrapping_mul i9 v)
  let i12 ← lift (core.num.U64.wrapping_add i10 i11)
  let i13 ← lift (UScalar.hcast .I64 i12)
  let i14 ← i13 >>> 63#i32
  let sign ← lift (IScalar.hcast .U64 i14)
  let a1 ← InvertBlocksInst.sign_mag u v q r
  let u1 ← Array.index_usize a1 0#usize
  let v1 ← Array.index_usize a1 1#usize
  let su ← Array.index_usize a1 4#usize
  let sv ← Array.index_usize a1 5#usize
  let i15 ← lift (su ^^^ sign)
  let i16 ← lift (sv ^^^ sign)
  let t ← InvertBlocksInst.de_row d1 e u1 v1 i15 i16
  let a2 ← InvertBlocksInst.amontred t modulus inv
  InvertBlocksInst.cond_sub a2 modulus

end pasta_curves
