#!/usr/bin/env python3
"""Generate `lean/PastaCurves/Inversion/HullData.lean` from `hull_certificate.json`.

The JSON is the termination certificate for the half-delta divstep (Bernstein's "hull light"
data of 2023, public domain, as checked in HOL Light by Harrison): the half-planes of the two
stable hulls `H0` and `H1`, of the outer box and the initial triangle, and one Farkas record per
target half-plane for each of the ten inclusions. `verify_hull_certificate.py` checks the JSON
independently in exact arithmetic; `PastaCurves/Inversion/HullCert.lean` proves the same facts from
the generated definitions by `decide`.

    gen_hull.py            write the Lean file
    gen_hull.py --check    exit 1 if the Lean file is not what the JSON generates
"""

import json
import sys
from fractions import Fraction
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
JSON = ROOT / "scripts" / "hull_certificate.json"
OUT = ROOT / "PastaCurves" / "Inversion" / "HullData.lean"

HEADER = """\
import PastaCurves.Inversion.HullBound

/-!
# The hull certificate's data

GENERATED by `lean/scripts/gen_hull.py` from `lean/scripts/hull_certificate.json`; do not edit.

The data is Bernstein's "hull light" certificate of 2023: `hull-light-20230416.sage` at
`cr.yp.to`, public domain, SHA-256 `{sha}`. Harrison checked it in HOL Light, in
`jrh13/hol-light` under `Divstep/hull_light.ml`. It consists of half-planes `a x + b y ≤ c` for
four regions: the stable hulls `H0` and `H1`, the outer box `houter`, and the initial triangle
`hinit`. For each of the ten inclusions it gives one Farkas record per target half-plane, in the
target's order. `HullCert.lean` turns these into `Certified H0 H1`.
-/

namespace PastaCurves.Inversion.Hull

"""


def rat(text):
    """A JSON rational, as a Lean `ℚ` literal."""
    q = Fraction(text)
    if q.denominator == 1:
        n = q.numerator
        return f"({n} : ℚ)" if n < 0 else str(n)
    return f"({q.numerator} / {q.denominator} : ℚ)"


def region(name, doc, planes):
    lines = [f"/-- {doc} -/", f"def {name} : Region := ["]
    for a, b, c in planes:
        lines.append(f"  ⟨{rat(a)}, {rat(b)}, {rat(c)}⟩,")
    lines[-1] = lines[-1].rstrip(",")
    lines.append("]")
    return "\n".join(lines) + "\n\n"


def farkas(inc):
    lines = [
        (
            f"/-- Farkas records for `{inc['name']}`: `{inc['source']}` into `{inc['target']}` under "
            f"the map `{inc['matrix']}` divided by `s^{inc['k']}`. -/"
        ),
        f"def farkas_{inc['name']} : List Farkas := [",
    ]
    for r in inc["farkas"]:
        lines.append(
            f"  ⟨{r['i']}, {r['j']}, {rat(r['m'])}, {rat(r['n'])}, {rat(r['p'])}, {rat(r['q'])}⟩,"
        )
    lines[-1] = lines[-1].rstrip(",")
    lines.append("]")
    return "\n".join(lines) + "\n\n"


def generate(cert):
    out = HEADER.format(sha=cert["source"]["sha256"])
    polys = cert["polygons"]
    out += region("H0", "The stable hull `S_{-1/2}`, 80 half-planes.", polys["H0"])
    out += region("H1", "The stable hull `S_{1/2}`, 80 half-planes.", polys["H1"])
    out += region("houter", "The outer box `|x| ≤ 8193/8192`, `|y| ≤ 379/512`.", polys["houter"])
    out += region("hinit", "The initial triangle `0 ≤ y ≤ x ≤ 1`.", polys["hinit"])
    for inc in cert["inclusions"]:
        out += farkas(inc)
    out += "end PastaCurves.Inversion.Hull\n"
    return out


def main(argv):
    cert = json.loads(JSON.read_text())
    text = generate(cert)
    if "--check" in argv:
        current = OUT.read_text() if OUT.exists() else ""
        if current != text:
            print(
                f"{OUT.relative_to(ROOT)} is not current; run lean/scripts/gen_hull.py",
                file=sys.stderr,
            )
            return 1
        print(f"{OUT.relative_to(ROOT)}: current.")
        return 0
    OUT.write_text(text)
    print(f"wrote {OUT.relative_to(ROOT)} ({text.count(chr(10))} lines)")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
