#!/usr/bin/env python3
# Copyright (c) 2026 the pasta-asm contributors.
# SPDX-License-Identifier: Apache-2.0
"""Architecture-specific x86-64 emitter for the unified Lean generator.

The shared :mod:`asm_source` parser extracts and validates the Rust function, asm
templates, declarations, options, locals, and source result order. This module
validates x86-64 instruction semantics, register initialization, memory reads, and
CF/OF use, then emits the mechanical SSA-style Lean transcription. The two full
internal multiplication rounds are factored only after their flattened binding IRs
match under the source's accumulator-register rotation and RHS-limb substitution.
Invoke it via ``python3 lean/scripts/gen.py`` or use ``--check`` for a non-writing
comparison.
"""

import dataclasses
import re
from pathlib import Path
from typing import Dict, List, Optional, Sequence, Set, Tuple

import asm_source
import gen
from asm_source import Declaration, GenerationError, ParsedFunction


ROOT = Path(__file__).resolve().parents[2]
SOURCE = ROOT / "src/asm/x86_64.rs"
OUTPUT = ROOT / "lean/PastaAsm/X86_64/Transcription.lean"
PASTA_HIGH_LIMB = 1 << 62

HEADER = """/-
Copyright Supranational LLC (the routines, transcribed from Semolina v0.1.4).
Copyright (c) 2026 the pasta-asm contributors (the transcription).
Released under the Apache License, Version 2.0, as described in the file LICENSE.
-/
import PastaAsm.X86_64.Semantics

/-!
# The crate's inline x86-64 Pasta field blocks, transcribed

GENERATED by `lean/scripts/gen.py` from the six `asm!` blocks in
`src/asm/x86_64.rs`; do not edit by hand. Each source instruction occurs in a trailing
comment on the let binding that models it. Registers are lexically rebound after
each write. The two identical full internal multiplication rounds are represented by
a generated helper after their flattened IRs have been compared modulo the source's
register rotation. `cf` and `ofl` model x86 CF and OF independently; the generator
rejects a read after an instruction that invalidates the corresponding flag.

Pointer operands are represented only by reads of their four input limbs. The
generator accepts no stores, no address other than a declared read-only pointer
plus 0, 8, 16, or 24 bytes, and no register read before an input or instruction has
written it. The fixed RDX operand, 32-bit `:e` XOR-zero idiom, operand outputs, and
Rust return-tuple order are parsed from the source rather than inferred here.
-/

namespace PastaAsm.X86_64

-- A mechanical transcription intentionally retains dead architectural results.
set_option linter.unusedVariables false

"""

FOOTER = "\nend PastaAsm.X86_64\n"


@dataclasses.dataclass(frozen=True)
class RoutineConfig:
    rust_name: str
    lean_name: str
    args: Tuple[Tuple[str, str], ...]
    result_type: str
    result_count: int
    doc: str


RESERVED_OPERAND_NAMES = {"rdx", "cf", "ofl", "s", "d", "m", "n"}


def validate_high_limb(source: str) -> None:
    matches = re.findall(
        r"^\s*const\s+PASTA_HIGH_LIMB\s*:\s*u64\s*=\s*([^;]+);",
        source,
        re.MULTILINE,
    )
    if len(matches) != 1:
        raise GenerationError("expected exactly one PASTA_HIGH_LIMB declaration")
    expression = re.sub(r"\s+", "", matches[0])
    if expression != "1<<62" or PASTA_HIGH_LIMB != 0x4000000000000000:
        raise GenerationError(
            "PASTA_HIGH_LIMB must be `1 << 62` (0x4000000000000000)"
        )


def parse_declaration(text: str) -> Declaration:
    return asm_source.parse_declaration(
        text,
        reserved_names=RESERVED_OPERAND_NAMES,
        fixed_registers={"rdx"},
        const_operands={"PASTA_HIGH_LIMB"},
    )


MUL_ROUND_RANGES = ((28, 63), (64, 99))
MUL_ROUND_ROTATIONS = (
    {"be": "r0", "ce": "r1", "de": "r2", "ee": "r3", "ae": "r4"},
    {"ce": "r0", "de": "r1", "ee": "r2", "ae": "r3", "be": "r4"},
)
MUL_ACC_FIELDS = ("r0", "r1", "r2", "r3", "r4", "q")


ROUTINES = (
    RoutineConfig(
        "add", "addMod",
        (("lhs", "Limbs"), ("rhs", "Limbs"), ("modulus", "Limbs")),
        "Limbs", 4,
        "The inline `asm!` block of `add`: modular addition followed by its conditional reduction.",
    ),
    RoutineConfig(
        "sub", "subMod",
        (("lhs", "Limbs"), ("rhs", "Limbs"), ("modulus", "Limbs")),
        "Limbs", 4,
        "The inline `asm!` block of `sub`: modular subtraction and conditional modulus addition.",
    ),
    RoutineConfig(
        "mul", "mulMont",
        (("lhs", "Limbs"), ("rhs", "Limbs"), ("modulus", "Limbs"), ("inv", "Nat")),
        "Limbs", 4,
        "The inline `asm!` block of `mul`: Montgomery multiplication and conditional reduction.",
    ),
    RoutineConfig(
        "square_lo", "squareLo", (("value", "Limbs"),), "WideLimbs", 8,
        "The inline `asm!` block of `square_lo`: the unreduced 512-bit square.",
    ),
    RoutineConfig(
        "square_hi", "squareHi",
        (("product", "WideLimbs"), ("modulus", "Limbs"), ("inv", "Nat")),
        "Limbs", 4,
        "The inline `asm!` block of `square_hi`: Montgomery reduction of `squareLo`'s product.",
    ),
    RoutineConfig(
        "from_mont", "fromMont",
        (("value", "Limbs"), ("modulus", "Limbs"), ("inv", "Nat")),
        "Limbs", 4,
        "The inline `asm!` block of `from_mont`: Montgomery reduction of a four-limb value.",
    ),
)


def parse_function(source: str, config: RoutineConfig) -> ParsedFunction:
    return asm_source.parse_function(
        source,
        config.rust_name,
        [name for name, _ in config.args],
        config.result_count,
        reserved_names=RESERVED_OPERAND_NAMES,
        fixed_registers={"rdx"},
        const_operands={"PASTA_HIGH_LIMB"},
    )


@dataclasses.dataclass(frozen=True)
class RegisterToken:
    name: str
    modifier: Optional[str] = None


class Emitter(gen.Emitter):
    """Validate x86-64 instructions and record them in the shared binding IR."""

    def __init__(self, directions: Dict[str, str], pointers: Dict[str, str],
                 clear_values: bool = True):
        super().__init__()
        self.directions = dict(directions)
        self.pointers = dict(pointers)
        self.cf_valid = False
        self.of_valid = False
        self.used_memory = False
        # Whether the skeleton clears each extracted value's definition (see `prepare`).
        self.clear_values = clear_values

    @staticmethod
    def _fact_for_input(register: str, expression: str):
        field = re.fullmatch(r"([A-Za-z_]\w*)\.(l[0-7])", expression)
        if field:
            return ("load", field.group(1), field.group(2))
        if expression == "inv":
            return ("inv",)
        return ("mov", expression)

    @staticmethod
    def _reads(*operands: str) -> Set[str]:
        return {
            operand for operand in operands
            if re.fullmatch(r"[A-Za-z_]\w*", operand) and not operand.isdigit()
        }

    def bind_argument(self, register: str, expression: str, description: str) -> None:
        self._check_declared(register)
        if register in self.known or register in self.pointers:
            raise GenerationError(f"duplicate initial binding for {register}")
        self.bind(
            register, expression, description, reads=(), load="." in expression,
            fact=self._fact_for_input(register, expression),
        )

    def bind_pointer(self, register: str, argument: str) -> None:
        self._check_declared(register)
        if register in self.known or register in self.pointers:
            raise GenerationError(f"duplicate initial binding for {register}")
        self.pointers[register] = argument

    def _check_declared(self, register: str) -> None:
        if register not in self.directions:
            raise GenerationError(f"undeclared register {register}")

    def _check_readable(self, register: str) -> None:
        self._check_declared(register)
        if self.directions[register] not in ("in", "inout"):
            raise GenerationError(f"output-only register {register} read before being written")

    def _check_writable(self, register: str) -> None:
        self._check_declared(register)
        if self.directions[register] not in ("out", "inout"):
            raise GenerationError(f"input-only register {register} cannot be written")

    @staticmethod
    def parse_register(token: str) -> RegisterToken:
        token = token.strip()
        if token.startswith("qword ptr") or token.startswith("["):
            raise GenerationError(f"memory write is unsupported: {token}")
        if token == "rdx":
            return RegisterToken("rdx")
        match = re.fullmatch(r"\{([A-Za-z_]\w*)(?::([A-Za-z_]\w*))?\}", token)
        if not match:
            raise GenerationError(f"unsupported register operand {token}")
        return RegisterToken(match.group(1), match.group(2))

    def read_register(self, token: str, allow_modifier: bool = False) -> str:
        parsed = self.parse_register(token)
        self._check_declared(parsed.name)
        if parsed.modifier and not allow_modifier:
            raise GenerationError(f"unsupported register modifier :{parsed.modifier} in {token}")
        if parsed.name in self.pointers:
            raise GenerationError(f"pointer register {parsed.name} used outside an address")
        if parsed.name not in self.known:
            self._check_readable(parsed.name)
            raise GenerationError(f"register {parsed.name} read before being written")
        return parsed.name

    def write_register(self, token: str, allow_modifier: bool = False) -> RegisterToken:
        parsed = self.parse_register(token)
        self._check_writable(parsed.name)
        if parsed.modifier and not allow_modifier:
            raise GenerationError(f"unsupported register modifier :{parsed.modifier} in {token}")
        if parsed.name in self.pointers:
            raise GenerationError(f"cannot overwrite pointer operand {parsed.name}")
        self.known.add(parsed.name)
        return parsed

    def read_value(self, token: str) -> str:
        token = token.strip()
        if re.fullmatch(r"(?:0|[1-9][0-9]*|0x[0-9A-Fa-f]+)", token):
            return str(int(token, 0))
        memory = re.fullmatch(
            r"qword\s+ptr\s*\[\s*\{([A-Za-z_]\w*)\}\s*(?:\+\s*([0-9]+))?\s*\]",
            token,
        )
        if memory:
            base, displacement_text = memory.groups()
            self._check_declared(base)
            if base not in self.pointers:
                raise GenerationError(f"address base {base} is not a read-only pointer operand")
            displacement = int(displacement_text or "0")
            if displacement not in (0, 8, 16, 24):
                raise GenerationError(f"unsupported memory offset {displacement}")
            self.used_memory = True
            return f"{self.pointers[base]}.l{displacement // 8}"
        return self.read_register(token)

    @staticmethod
    def split_instruction(text: str) -> Tuple[str, List[str]]:
        found = re.fullmatch(r"\s*([A-Za-z][A-Za-z0-9]*)\s*(.*?)\s*", text)
        if not found:
            raise GenerationError(f"cannot parse instruction {text!r}")
        op, rest = found.groups()
        operands = [part.strip() for part in rest.split(",")] if rest else []
        if any(not operand for operand in operands):
            raise GenerationError(f"empty operand in instruction {text!r}")
        return op.lower(), operands

    @staticmethod
    def require_count(op: str, operands: Sequence[str], count: int) -> None:
        if len(operands) != count:
            raise GenerationError(f"{op} expects {count} operands, got {len(operands)}")

    @staticmethod
    def immediate(token: str) -> int:
        if not re.fullmatch(r"(?:0|[1-9][0-9]*)", token.strip()):
            raise GenerationError(f"unsupported immediate {token}")
        return int(token)

    def require_cf(self, text: str) -> None:
        if not self.cf_valid:
            raise GenerationError(f"CF read while invalid: {text}")

    def require_of(self, text: str) -> None:
        if not self.of_valid:
            raise GenerationError(f"OF read while invalid: {text}")

    def emit(self, name: str, expr: str, comment: Optional[str] = None,
             *, reads=(), fact=None, note=None) -> None:
        self.bind(name, expr, comment, reads=reads, fact=fact, note=note)

    def render(self, result_names):
        """Retain every architectural result in the mechanical x86 transcription."""
        return [(f"  let {e['name']} := {e['expr']}", e.get("note") or e["comment"]) for e in self.entries]

    def binary_add(self, op: str, operands: Sequence[str], text: str) -> None:
        self.require_count(op, operands, 2)
        dst_old = self.read_register(operands[0])
        src = self.read_value(operands[1])
        carry = "0"
        if op in ("adc", "adcx"):
            self.require_cf(text)
            carry = "cf"
        elif op == "adox":
            self.require_of(text)
            carry = "ofl"
        dst = self.write_register(operands[0]).name
        flag = "ofl" if op == "adox" else "cf"
        self.emit("s", f"addc {dst_old} {src} {carry}", text,
                  reads=self._reads(dst_old, src, carry), fact=("x86_adds", dst_old, src, carry))
        self.emit(dst, "s.1", reads=("s",), fact=("fst",), note=f"  `-> {dst}")
        self.emit(flag, "s.2", reads=("s",), fact=("snd",), note=f"  `-> {flag}")
        if op == "adox":
            self.of_valid = True
        else:
            self.cf_valid = True
            if op in ("add", "adc"):
                self.of_valid = False

    def binary_sub(self, op: str, operands: Sequence[str], text: str) -> None:
        self.require_count(op, operands, 2)
        dst_old = self.read_register(operands[0])
        src = self.read_value(operands[1])
        borrow = "0"
        if op == "sbb":
            self.require_cf(text)
            borrow = "cf"
        dst = self.write_register(operands[0]).name
        self.emit("d", f"sbb {dst_old} {src} {borrow}", text,
                  reads=self._reads(dst_old, src, borrow), fact=("x86_subs", dst_old, src, borrow))
        self.emit(dst, "d.1", reads=("d",), fact=("fst",), note=f"  `-> {dst}")
        self.emit("cf", "d.2", reads=("d",), fact=("snd",), note="  `-> cf")
        self.cf_valid = True
        self.of_valid = False

    def emit_instruction(self, text: str) -> None:
        op, operands = self.split_instruction(text)
        try:
            if op in ("mov", "movabs"):
                self.require_count(op, operands, 2)
                src = self.read_value(operands[1])
                dst = self.write_register(operands[0]).name
                self.emit(dst, src, text, reads=self._reads(src), fact=("mov", src))
            elif op == "mulx":
                self.require_count(op, operands, 3)
                rdx = self.read_register("rdx")
                src = self.read_value(operands[2])
                high = self.write_register(operands[0]).name
                low = self.write_register(operands[1]).name
                if high == low:
                    raise GenerationError("mulx destinations must be distinct")
                self.emit("m", f"mulx {rdx} {src}", text,
                          reads=self._reads(rdx, src), fact=("x86_mulx", rdx, src))
                self.emit(high, "m.1", reads=("m",), fact=("fst",), note=f"  `-> {high}")
                self.emit(low, "m.2", reads=("m",), fact=("snd",), note=f"  `-> {low}")
            elif op == "imul":
                self.require_count(op, operands, 2)
                old = self.read_register(operands[0])
                src = self.read_value(operands[1])
                dst = self.write_register(operands[0]).name
                self.emit(dst, f"mulLo {old} {src}", text,
                          reads=self._reads(old, src), fact=("mul", old, src))
                self.cf_valid = False
                self.of_valid = False
            elif op in ("shl", "shr"):
                self.require_count(op, operands, 2)
                old = self.read_register(operands[0])
                amount = self.immediate(operands[1])
                if not 1 <= amount < 64:
                    raise GenerationError("only unmasked nonzero 64-bit shift counts are supported")
                dst = self.write_register(operands[0]).name
                operation = "lsl" if op == "shl" else "lsr"
                self.emit(dst, f"{operation} {old} {amount}", text,
                          reads=(old,), fact=(operation, old, amount))
                self.cf_valid = False
                self.of_valid = False
            elif op in ("add", "adc", "adcx", "adox"):
                self.binary_add(op, operands, text)
            elif op in ("sub", "sbb"):
                self.binary_sub(op, operands, text)
            elif op == "neg":
                self.require_count(op, operands, 1)
                old = self.read_register(operands[0])
                dst = self.write_register(operands[0]).name
                self.emit("n", f"neg {old}", text, reads=(old,), fact=("x86_neg", old))
                self.emit(dst, "n.1", reads=("n",), fact=("fst",), note=f"  `-> {dst}")
                self.emit("cf", "n.2", reads=("n",), fact=("snd",), note="  `-> cf")
                self.cf_valid = True
                self.of_valid = False
            elif op == "cmovnc":
                self.require_count(op, operands, 2)
                self.require_cf(text)
                old = self.read_register(operands[0])
                src = self.read_value(operands[1])
                dst = self.write_register(operands[0]).name
                self.emit(dst, f"cmovnc cf {old} {src}", text,
                          reads=self._reads("cf", old, src), fact=("select", "cf", src, old))
            elif op == "xor":
                self.require_count(op, operands, 2)
                left = self.parse_register(operands[0])
                right = self.parse_register(operands[1])
                self._check_declared(left.name)
                self._check_declared(right.name)
                if left.name != right.name or left.modifier != right.modifier:
                    raise GenerationError("only XOR-self zeroing is supported")
                self._check_writable(left.name)
                if left.modifier not in (None, "e"):
                    raise GenerationError(f"unsupported XOR register modifier :{left.modifier}")
                if left.name in self.pointers:
                    raise GenerationError(f"cannot XOR pointer operand {left.name}")
                self.known.add(left.name)
                self.emit(left.name, "0", text, reads=(), fact=("x86_xor",))
                self.emit("cf", "0", reads=(), fact=("zero_cf",), note="  `-> cf")
                self.emit("ofl", "0", reads=(), fact=("zero_of",), note="  `-> ofl")
                self.cf_valid = True
                self.of_valid = True
            else:
                raise GenerationError(f"unsupported instruction {op}: {text}")
        except GenerationError as error:
            if str(error).endswith(f": {text}"):
                raise
            raise GenerationError(f"{error}: {text}") from error


def input_expression(
    value: str,
    locals_map: Dict[str, Tuple[str, int]],
    argument_types: Dict[str, str],
) -> Tuple[str, str]:
    direct = re.fullmatch(r"([A-Za-z_]\w*)\[([0-9]+)\]", value)
    if direct:
        argument, index_text = direct.groups()
        index = int(index_text)
    elif value in locals_map:
        argument, index = locals_map[value]
    elif value in argument_types and argument_types[value] == "Nat":
        return value, "scalar input"
    else:
        raise GenerationError(f"unsupported input operand expression {value}")
    if argument not in argument_types:
        raise GenerationError(f"operand reads non-argument {argument}")
    kind = argument_types[argument]
    limit = 8 if kind == "WideLimbs" else 4 if kind == "Limbs" else 0
    if index < 0 or index >= limit:
        raise GenerationError(f"limb {index} is out of range for {argument} : {kind}")
    return f"{argument}.l{index}", f"input {value}"


TRIPLE_FACTS = {"x86_adds", "x86_subs", "x86_mulx", "x86_neg", "x86_xor"}


class SkeletonBackend(gen.SkeletonBackend):
    """x86-64 instruction grouping and ISA proof facts for the shared traversal."""

    def prepare(self, emitter, live_entries):
        # x86 renders every instruction binding, and the skeleton extracts every one of them:
        # `lift_lets` and `extract_lets` run with merging off, so equal values stay separate.
        entries = [dict(entry) for entry in emitter.entries]
        names = gen.ssa_names(entries)
        for index, entry in enumerate(entries):
            if entry["fact"][0] in TRIPLE_FACTS:
                # An instruction's three result bindings are consecutive.
                entry["group"] = [(entries[j], names[j]) for j in range(index, index + 3)]
                entry["group_fact"] = entry["fact"]
                if entry["fact"][0] in ("x86_adds", "x86_subs"):
                    entry["group_label"] = names[index + 1]
        # For the factored round and the block that calls it, clearing each extracted value
        # would recheck the remaining dependent `hr` tail every time; their local definitions
        # stay transparent, and the generated facts still record every step.
        return gen.SkeletonPreparation(entries, names, clear_values=emitter.clear_values)

    def fact(self, kind, ops, context):
        group = context.group_entries
        group_names = context.group_names
        if kind == "x86_mulx":
            a, b = ops
            high, low = group_names[1:3]
            context.eq(high, f"(mulx {a} {b}).1")
            context.lines.append(
                f"  have b_{high} : {high} < 2^64 := by rw [e_{high}]; "
                "exact Nat.div_lt_of_lt_mul (Nat.mul_lt_mul'' "
                f"{context.lt64(a)} {context.lt64(b)})"
            )
            context.bnd[high] = f"b_{high}"
            context.ren[group[1][0]["name"]] = high
            context.eq(low, f"(mulx {a} {b}).2")
            context.lines.append(
                f"  have b_{low} : {low} < 2^64 := by rw [e_{low}]; "
                "exact Nat.mod_lt _ (Nat.two_pow_pos _)"
            )
            context.bnd[low] = f"b_{low}"
            context.ren[group[2][0]["name"]] = low
            context.lines.append(f"  have d_{high} : {low} + 2^64 * {high} = {a} * {b} := by")
            context.lines.append(f"    rw [e_{low}, e_{high}]; exact Nat.mod_add_div _ _")
            return True
        if kind in ("x86_adds", "x86_subs"):
            a, b, carry = ops
            value_name, flag_name = group_names[1:3]
            semantic = "addc" if kind == "x86_adds" else "sbb"
            context.eq(value_name, f"({semantic} {a} {b} {carry}).1")
            context.eq(flag_name, f"({semantic} {a} {b} {carry}).2")
            if kind == "x86_adds":
                linear = f"{value_name} + 2^64 * {flag_name} = {a} + {b} + {carry}"
                linear_proof = f"addc_lin {a} {b} {carry}"
                value_proof = f"addc_value_lt {a} {b} {carry}"
                flag_proof = (
                    f"addc_carry_le_one {a} {b} {carry} {context.lt64(a)} {context.lt64(b)} {context.le1(carry)}"
                )
            else:
                linear = f"{value_name} + {b} + {carry} = {a} + 2^64 * {flag_name}"
                linear_proof = f"sbb_lin {a} {b} {carry} {context.lt64(a)} {context.lt64(b)} {context.le1(carry)}"
                value_proof = f"sbb_value_lt {a} {b} {carry}"
                flag_proof = f"sbb_borrow_le_one {a} {b} {carry}"
            context.lines.append(f"  have l_{value_name} : {linear} := by")
            context.lines.append(f"    rw [e_{value_name}, e_{flag_name}]; exact {linear_proof}")
            context.lines.append(
                f"  have b_{value_name} : {value_name} < 2^64 := by rw [e_{value_name}]; "
                f"exact {value_proof}"
            )
            context.lines.append(
                f"  have b_{flag_name} : {flag_name} ≤ 1 := by rw [e_{flag_name}]; "
                f"exact {flag_proof}"
            )
            context.lines.append(f"  clear e_{value_name} e_{flag_name}")
            context.ren[group[2][0]["name"]] = flag_name
            context.ren[group[1][0]["name"]] = value_name
            context.bnd[value_name], context.bnd[flag_name] = f"b_{value_name}", f"b_{flag_name}"
            context.unit_bound.add(flag_name)
            return True
        if kind == "x86_neg":
            (operand,) = ops
            value_name, flag_name = group_names[1:3]
            context.eq(value_name, f"(neg {operand}).1")
            context.lines.append(
                f"  have b_{value_name} : {value_name} < 2^64 := by rw [e_{value_name}]; "
                f"exact sbb_value_lt 0 {operand} 0"
            )
            context.ren[group[1][0]["name"]] = value_name
            context.bnd[value_name] = f"b_{value_name}"
            context.eq(flag_name, f"(neg {operand}).2")
            context.lines.append(f"  have b_{flag_name} : {flag_name} ≤ 1 := by")
            context.lines.append(f"    rw [e_{flag_name}]; simp only [neg]; split <;> omega")
            context.ren[group[2][0]["name"]] = flag_name
            context.bnd[flag_name] = f"b_{flag_name}"
            context.unit_bound.add(flag_name)
            return True
        if kind == "x86_xor":
            data_name, cf_name, of_name = group_names
            context.eq(data_name, "0")
            context.lines.append(
                f"  have b_{data_name} : {data_name} < 2^64 := by rw [e_{data_name}]; decide"
            )
            context.ren[group[0][0]["name"]] = data_name
            context.bnd[data_name] = f"b_{data_name}"
            for flag, member in ((cf_name, group[1][0]), (of_name, group[2][0])):
                context.eq(flag, "0")
                context.lines.append(f"  have b_{flag} : {flag} ≤ 1 := by rw [e_{flag}]; decide")
                context.ren[member["name"]] = flag
                context.bnd[flag] = f"b_{flag}"
                context.unit_bound.add(flag)
            return True
        return False


SKELETON_BACKEND = SkeletonBackend()


class Routine(gen.Routine):
    """An x86 routine, whose source docstrings and internal lets are already line-sized."""

    architecture = "X86_64"
    skeleton_backend = SKELETON_BACKEND

    def text(self, column):
        body = []
        for code, comment in self.lines:
            if comment is None:
                body.append(code)
            else:
                body.append(
                    f"{code.ljust(column) if len(code) + 2 <= column else code + '  '}-- {comment}"
                )
        head = f"{self.struct}\n" if self.struct else ""
        return head + f"/-- {self.doc} -/\n{self.signature}\n" + "\n".join(body) + f"\n{self.result}\n"


def comment_column(routines):
    """Two spaces past the widest instruction binding in these routines."""
    return 2 + max(
        len(code) for routine in routines for code, comment in routine.lines
        if code is not None and comment is not None
    )


def emit_routine(source: str, config: RoutineConfig) -> Routine:
    """Validate and transcribe one source block into the shared routine IR."""
    parsed = parse_function(source, config)
    argument_types = dict(config.args)
    directions = asm_source.declaration_directions(parsed, config.rust_name)
    emitter = Emitter(directions, {})
    pointer_count = 0

    fixed_rdx = [decl for decl in parsed.declarations if decl.fixed]
    uses_architectural_rdx = any(
        re.search(r"(?<![A-Za-z0-9_{])rdx(?![A-Za-z0-9_}])", instruction)
        for instruction in parsed.instructions
    )
    if uses_architectural_rdx and len(fixed_rdx) != 1:
        raise GenerationError(
            f"{config.rust_name}: literal rdx requires exactly one fixed out(\"rdx\") _ operand"
        )
    if not uses_architectural_rdx and fixed_rdx:
        raise GenerationError(f"{config.rust_name}: unused fixed rdx operand")

    for declaration in parsed.declarations:
        if declaration.fixed:
            continue
        if declaration.kind == "const":
            emitter.bind_argument(
                declaration.name, str(PASTA_HIGH_LIMB),
                f"operand {declaration.name} = const PASTA_HIGH_LIMB",
            )
        elif declaration.kind in ("in", "inout"):
            pointer = re.fullmatch(r"([A-Za-z_]\w*)\.as_ptr\(\)", declaration.value)
            if pointer:
                argument = pointer.group(1)
                if argument_types.get(argument) != "Limbs":
                    raise GenerationError(
                        f"{config.rust_name}: pointer {declaration.name} is not a Limbs argument"
                    )
                emitter.bind_pointer(declaration.name, argument)
                pointer_count += 1
            else:
                expression, description = input_expression(
                    declaration.value, parsed.locals, argument_types
                )
                emitter.bind_argument(declaration.name, expression, description)
        elif declaration.kind != "out":
            raise GenerationError(
                f"{config.rust_name}: unsupported direction {declaration.kind}"
            )

    if pointer_count:
        if "readonly" not in parsed.options or "nomem" in parsed.options:
            raise GenerationError(
                f"{config.rust_name}: pointer operands require readonly and forbid nomem"
            )
    elif "nomem" not in parsed.options or "readonly" in parsed.options:
        raise GenerationError(
            f"{config.rust_name}: register-only block requires nomem and forbids readonly"
        )

    for pc, instruction in enumerate(parsed.instructions):
        emitter.pc = pc
        emitter.emit_instruction(instruction)
    if emitter.used_memory != bool(pointer_count):
        raise GenerationError(
            f"{config.rust_name}: declared pointer operands and memory reads disagree"
        )

    result_registers = list(asm_source.returned_registers(parsed, config.rust_name))
    for register in result_registers:
        if register not in emitter.known:
            raise GenerationError(
                f"{config.rust_name}: output register {register} was never written"
            )

    grouped: List[str] = []
    index = 0
    while index < len(config.args):
        name, kind = config.args[index]
        same = [name]
        index += 1
        while index < len(config.args) and config.args[index][1] == kind:
            same.append(config.args[index][0])
            index += 1
        grouped.append(f"({' '.join(same)} : {kind})")
    signature = f"def {config.lean_name} {' '.join(grouped)} : {config.result_type} :="

    result = f"  ⟨{', '.join(result_registers)}⟩"
    return Routine(
        config.doc, signature, emitter.render(result_registers), result,
        config.lean_name, emitter, result_registers,
    )


def _rename_round_value(value, rotation, rhs_limb):
    """Canonicalize one flattened multiplication round's register-valued IR."""
    if isinstance(value, str):
        if value == rhs_limb:
            return "b"
        for register, canonical in rotation.items():
            value = re.sub(
                rf"(?<![A-Za-z0-9_']){re.escape(register)}(?![A-Za-z0-9_'])",
                canonical,
                value,
            )
        return value
    if isinstance(value, tuple):
        return tuple(_rename_round_value(item, rotation, rhs_limb) for item in value)
    if isinstance(value, list):
        return [_rename_round_value(item, rotation, rhs_limb) for item in value]
    return value


def _normalized_mul_round_entries(emitter, pc_range, rotation, rhs_limb):
    """Return one full round under canonical accumulator names and a scalar RHS limb."""
    first, last = pc_range
    entries = []
    for entry in emitter.entries:
        if entry["pc"] is None or not first <= entry["pc"] <= last:
            continue
        normalized = dict(entry)
        normalized["name"] = _rename_round_value(entry["name"], rotation, rhs_limb)
        normalized["expr"] = _rename_round_value(entry["expr"], rotation, rhs_limb)
        normalized["reads"] = {
            _rename_round_value(read, rotation, rhs_limb) for read in entry["reads"]
        }
        normalized["fact"] = _rename_round_value(entry["fact"], rotation, rhs_limb)
        normalized["pc"] = entry["pc"] - first
        entries.append(normalized)
    return entries


def _round_fingerprint(entries):
    """The semantic IR fields whose equality justifies replacing a flattened round by a call."""
    return [
        (entry["name"], entry["expr"], tuple(sorted(entry["reads"])),
         entry["load"], entry["fact"], entry["pc"])
        for entry in entries
    ]


def _mul_acc_struct():
    return """/-- The rotating five-limb accumulator of `mulMont`, together with the most recent
Montgomery quotient. The next round does not read `q`; retaining it exposes the round invariant
needed by the block proof. -/
structure MulMontAcc where
  /-- accumulator limb 0 -/
  r0 : Nat
  /-- accumulator limb 1 -/
  r1 : Nat
  /-- accumulator limb 2 -/
  r2 : Nat
  /-- accumulator limb 3 -/
  r3 : Nat
  /-- accumulator limb 4 -/
  r4 : Nat
  /-- the most recent Montgomery quotient -/
  q : Nat
  deriving DecidableEq, Repr

namespace MulMontAcc

/-- Every field is below `2^64`. -/
def Bounded (s : MulMontAcc) : Prop :=
  s.r0 < 2^64 ∧ s.r1 < 2^64 ∧ s.r2 < 2^64 ∧ s.r3 < 2^64 ∧ s.r4 < 2^64 ∧ s.q < 2^64

/-- The value of the five accumulator limbs. -/
def toNat (s : MulMontAcc) : Nat :=
  s.r0 + 2^64 * s.r1 + 2^128 * s.r2 + 2^192 * s.r3 + 2^256 * s.r4

end MulMontAcc
"""


def factor_mul_rounds(routine: Routine):
    """Mechanically validate and factor the two full flattened rounds of ``mulMont``."""
    rounds = [
        _normalized_mul_round_entries(routine.emitter, pc_range, rotation, f"rhs.l{index}")
        for index, (pc_range, rotation) in enumerate(
            zip(MUL_ROUND_RANGES, MUL_ROUND_ROTATIONS), start=1
        )
    ]
    if not rounds[0] or _round_fingerprint(rounds[0]) != _round_fingerprint(rounds[1]):
        raise GenerationError(
            "mul: flattened full rounds 1 and 2 differ after accumulator rotation"
        )

    first_pc = min(entry["pc"] for entry in rounds[0])
    source_load = next(
        (entry for entry in rounds[0] if entry["name"] == "rdx" and entry["pc"] == first_pc),
        None,
    )
    if source_load is None or source_load["expr"] != "b":
        raise GenerationError("mul: factored round does not begin by loading its RHS limb into RDX")

    round_emitter = Emitter({}, {}, clear_values=False)
    round_emitter.bind("inv", "inv", "scalar argument", reads=(), fact=("inv",))
    round_emitter.bind("b", "b", source_load["comment"], reads=(), fact=("param", "b"))
    for field in MUL_ACC_FIELDS:
        if field == "q":
            continue
        round_emitter.bind(
            field, f"acc.{field}", "accumulator argument", reads=(), load=True,
            fact=("load", "acc", field),
        )
    # The first source instruction loads the round's scalar RHS limb into RDX. The helper
    # receives that scalar as its parameter ``b``, so the load is not part of the round's body:
    # substitute ``b`` into the remaining validated IR.
    helper_entries = []
    aliases = {"rdx": "b"}
    for entry in rounds[0]:
        if entry["pc"] == first_pc:
            continue
        normalized = dict(entry)
        normalized["expr"] = _rename_round_value(entry["expr"], aliases, "")
        normalized["reads"] = {
            _rename_round_value(read, aliases, "") for read in entry["reads"]
        }
        normalized["fact"] = _rename_round_value(entry["fact"], aliases, "")
        helper_entries.append(normalized)
        # The omitted entry load creates the initial alias only. Once the source writes RDX,
        # subsequent reads must see that new quotient/register value rather than the helper's b.
        aliases.pop(entry["name"], None)
    round_emitter.entries.extend(dict(entry) for entry in helper_entries)
    round_result = ["r1", "r2", "r3", "r4", "r0", "rdx"]
    round_lines = round_emitter.render(round_result)
    round_routine = Routine(
        "One full internal round of `mulMont`: add `lhs * b` to the rotating five-limb "
        "accumulator, cancel its low limb with the Montgomery quotient, and shift by one limb. "
        "The source's flattened rounds 1 and 2 are checked to have this same binding IR modulo "
        "their accumulator-register rotation and RHS limb.",
        "def mulMontRound (lhs modulus : Limbs) (inv b : Nat) "
        "(acc : MulMontAcc) : MulMontAcc :=",
        round_lines,
        f"  ⟨{', '.join(round_result)}⟩",
        "mulMontRound", round_emitter, round_result,
        struct=_mul_acc_struct(), arg_fields={"acc": MUL_ACC_FIELDS},
    )

    # The multiplication proof clears values itself, at its arithmetic phase boundaries, rather
    # than after each extraction, which would recheck its large dependent tail every time.
    main_emitter = Emitter(routine.emitter.directions, {}, clear_values=False)
    main_emitter.entries = [
        dict(entry) for entry in routine.emitter.entries
        if entry["pc"] is None or entry["pc"] < MUL_ROUND_RANGES[0][0]
    ]
    current = ["be", "ce", "de", "ee", "ae"]
    inv_register = "inv"
    for round_number, rhs_index in ((1, 1), (2, 2)):
        call_args = [inv_register, f"rhs.l{rhs_index}"] + current + ["rdx"]
        fmt = "mulMontRound lhs modulus {0} {1} ⟨" + ", ".join(
            "{%d}" % index for index in range(2, 8)
        ) + "⟩"
        round_name = f"round{round_number}"
        main_emitter.entries.append(dict(
            name=round_name, expr=fmt.format(*call_args), comment=f"factored round {round_number}",
            note=None, reads=set([inv_register, f"rhs.l{rhs_index}"] + current + ["rdx"]), load=False,
            fact=("call", fmt, call_args), pc=None,
        ))
        next_current = current[1:] + current[:1]
        for register, field in zip(next_current + ["rdx"], MUL_ACC_FIELDS):
            main_emitter.entries.append(dict(
                name=register, expr=f"{round_name}.{field}",
                comment=f"round {round_number} output", note=None, reads={round_name}, load=False,
                fact=("callout", round_name, field), pc=None,
            ))
        current = next_current
    main_emitter.entries.extend(
        dict(entry) for entry in routine.emitter.entries
        if entry["pc"] is not None and entry["pc"] > MUL_ROUND_RANGES[-1][1]
    )
    main = Routine(
        routine.doc, routine.signature, main_emitter.render(routine.result_names), routine.result,
        routine.name, main_emitter, routine.result_names,
    )
    return [round_routine, main]


def emit_routines(source: str, config: RoutineConfig):
    """Emit a source routine, plus its helper when repeated rounds are factored."""
    routine = emit_routine(source, config)
    return factor_mul_rounds(routine) if config.lean_name == "mulMont" else [routine]


def transcribe(source: str, config: RoutineConfig) -> str:
    """Render one x86-64 source routine and any validated factored helpers."""
    routines = emit_routines(source, config)
    return "\n".join(routine.text(comment_column([routine])) for routine in routines)


def gen_program(source: Optional[str] = None) -> str:
    routines = all_routines(source)
    return HEADER + "\n".join(
        routine.text(comment_column([routine])) for routine in routines
    ) + FOOTER


def all_routines(source: Optional[str] = None):
    """Return the validated x86-64 assembly routines and factored round helper."""
    if source is None:
        source = SOURCE.read_text()
    validate_high_limb(source)
    routines = []
    for config in ROUTINES:
        routines.extend(emit_routines(source, config))
    return routines


def generated_outputs():
    """Return the x86-64 generated paths and contents without writing files."""
    return [(OUTPUT, gen_program())]

