#!/usr/bin/env python3
# Copyright (c) 2026 the pasta-asm contributors.
# SPDX-License-Identifier: Apache-2.0
"""Unit tests for shared reference-vector parsing, filtering, and emission."""

import sys
import unittest
from collections import Counter

# Running this source-tree test should not leave lean/scripts/__pycache__ behind.
sys.dont_write_bytecode = True

import gen


def contract_counts(vectors, in_contract):
    counts = Counter()
    omitted = Counter()
    for op, key, vals in vectors:
        operands = [int(value, 16) for value in vals[:-1]]
        (counts if in_contract(op, key, operands) else omitted)[op] += 1
    return counts, omitted


class SharedVectorTests(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.lines = gen.VECTORS.read_text().splitlines()
        cls.vectors = gen.parse_vectors(cls.lines)
        cls.generated = gen.render_vector_data(cls.lines)

    def test_corpus_shape_covers_both_fields_and_all_operations(self):
        self.assertEqual(
            Counter((key, op) for op, key, _ in self.vectors),
            Counter(
                {
                    ("Fp", "MUL"): 493,
                    ("Fq", "MUL"): 493,
                    ("Fp", "SQR"): 17,
                    ("Fq", "SQR"): 17,
                    ("Fp", "FROM"): 17,
                    ("Fq", "FROM"): 17,
                }
            ),
        )

    def test_public_contract_counts(self):
        included, omitted = contract_counts(self.vectors, gen.in_public_contract)
        self.assertEqual(included, Counter({"MUL": 806, "FROM": 34, "SQR": 34}))
        self.assertEqual(omitted, Counter({"MUL": 180}))

    def test_generated_file_is_registered_and_current(self):
        outputs = dict(gen.generated_outputs())
        self.assertIn(gen.OUT_VECTORS, outputs)
        self.assertEqual(outputs[gen.OUT_VECTORS], self.generated)
        self.assertEqual(gen.OUT_VECTORS.read_text(), self.generated)

    def test_generated_file_holds_every_in_contract_vector_once(self):
        # Each entry opens with its index and its field.
        lists = self.generated.split("\ndef ")[1:]
        entries = {}
        for block in lists:
            indices = [
                int(line[3:].split(",", 1)[0])
                for line in block.splitlines()
                if line.startswith("  (") and line.endswith("Base,")
            ]
            self.assertEqual(indices, list(range(len(indices))))
            entries[block.split(" ", 1)[0]] = len(indices)
        self.assertEqual(entries, {"mulVectors": 806, "sqrVectors": 34, "fromVectors": 34})
        self.assertIn(
            "-- 874 vectors; omitted as outside the public contracts: 180 MUL.",
            self.generated,
        )

    def test_generated_file_records_provenance(self):
        self.assertIn("GENERATED by `lean/scripts/gen.py`", self.generated)
        self.assertIn("8ad85e9fab7929f6236960e472f432a4bd9ccd74", self.generated)
        self.assertIn("run on an Apple M-series machine", self.generated)
        self.assertIn("import PastaAsm.Fields", self.generated)


if __name__ == "__main__":
    unittest.main()
