/-
Copyright Supranational LLC (the routines, transcribed from Semolina v0.1.4).
Copyright (c) 2026 the pasta_curves contributors (the transcription).
-/
import PastaCurves.AArch64.Leakage

/-!
# The crate's inline Pasta field blocks, as instruction streams

GENERATED by `lean/scripts/gen.py` from the `asm!` blocks of `mul`, `square`, `add`, `sub`,
`divstep59`, `sign_mag`, `fg_row`, `uv_row`, `amontred`, and `cond_sub` in `src/asm/aarch64.rs`; do
not edit by hand. Each definition is a block's instruction stream as syntax, one
`PastaCurves.AArch64.Instr` per instruction in the block's order, with the instruction as the
trailing comment: the input of the constant-time proofs, which classify each instruction by the
leakage policy of `PastaCurves.AArch64.Leakage`. The front end that reads the blocks is the
transcription's, and every stream is of a block that lifts.
-/

namespace PastaCurves.AArch64

/-- The instruction stream of the inline `asm!` block of `mul`, as written, its macro invocations
expanded. -/
def mulMontProgram : List Instr := [
  ⟨.mul, [.reg "r0", .reg "a0", .reg "b0"]⟩,                    -- mul r0,a0,b0
  ⟨.mul, [.reg "r1", .reg "a1", .reg "b0"]⟩,                    -- mul r1,a1,b0
  ⟨.mul, [.reg "r2", .reg "a2", .reg "b0"]⟩,                    -- mul r2,a2,b0
  ⟨.mul, [.reg "r3", .reg "a3", .reg "b0"]⟩,                    -- mul r3,a3,b0
  ⟨.umulh, [.reg "t0", .reg "a0", .reg "b0"]⟩,                  -- umulh t0,a0,b0
  ⟨.umulh, [.reg "t1", .reg "a1", .reg "b0"]⟩,                  -- umulh t1,a1,b0
  ⟨.mul, [.reg "q", .reg "inv", .reg "r0"]⟩,                    -- mul q,inv,r0
  ⟨.umulh, [.reg "t2", .reg "a2", .reg "b0"]⟩,                  -- umulh t2,a2,b0
  ⟨.umulh, [.reg "t3", .reg "a3", .reg "b0"]⟩,                  -- umulh t3,a3,b0
  ⟨.adds, [.reg "r1", .reg "r1", .reg "t0"]⟩,                   -- adds r1,r1,t0
  ⟨.adcs, [.reg "r2", .reg "r2", .reg "t1"]⟩,                   -- adcs r2,r2,t1
  ⟨.mul, [.reg "t1", .reg "p1", .reg "q"]⟩,                     -- mul t1,p1,q
  ⟨.adcs, [.reg "r3", .reg "r3", .reg "t2"]⟩,                   -- adcs r3,r3,t2
  ⟨.adc, [.reg "r4", .zero, .reg "t3"]⟩,                        -- adc r4,xzr,t3
  ⟨.lsl, [.reg "t3", .reg "q", .imm 62]⟩,                       -- lsl t3,q,#62
  ⟨.subs, [.zero, .reg "r0", .imm 1]⟩,                          -- subs xzr,r0,#1
  ⟨.umulh, [.reg "t0", .reg "p0", .reg "q"]⟩,                   -- umulh t0,p0,q
  ⟨.adcs, [.reg "r1", .reg "r1", .reg "t1"]⟩,                   -- adcs r1,r1,t1
  ⟨.umulh, [.reg "t1", .reg "p1", .reg "q"]⟩,                   -- umulh t1,p1,q
  ⟨.adcs, [.reg "r2", .reg "r2", .zero]⟩,                       -- adcs r2,r2,xzr
  ⟨.adcs, [.reg "r3", .reg "r3", .reg "t3"]⟩,                   -- adcs r3,r3,t3
  ⟨.lsr, [.reg "t3", .reg "q", .imm 2]⟩,                        -- lsr t3,q,#2
  ⟨.adc, [.reg "r4", .reg "r4", .zero]⟩,                        -- adc r4,r4,xzr
  ⟨.adds, [.reg "r0", .reg "r1", .reg "t0"]⟩,                   -- adds r0,r1,t0
  ⟨.mul, [.reg "t0", .reg "a0", .reg "b1"]⟩,                    -- mul t0,a0,b1
  ⟨.adcs, [.reg "r1", .reg "r2", .reg "t1"]⟩,                   -- adcs r1,r2,t1
  ⟨.mul, [.reg "t1", .reg "a1", .reg "b1"]⟩,                    -- mul t1,a1,b1
  ⟨.adcs, [.reg "r2", .reg "r3", .zero]⟩,                       -- adcs r2,r3,xzr
  ⟨.mul, [.reg "t2", .reg "a2", .reg "b1"]⟩,                    -- mul t2,a2,b1
  ⟨.adcs, [.reg "r3", .reg "r4", .reg "t3"]⟩,                   -- adcs r3,r4,t3
  ⟨.mul, [.reg "t3", .reg "a3", .reg "b1"]⟩,                    -- mul t3,a3,b1
  ⟨.adc, [.reg "r4", .zero, .zero]⟩,                            -- adc r4,xzr,xzr
  ⟨.adds, [.reg "r0", .reg "r0", .reg "t0"]⟩,                   -- adds r0,r0,t0
  ⟨.umulh, [.reg "t0", .reg "a0", .reg "b1"]⟩,                  -- umulh t0,a0,b1
  ⟨.adcs, [.reg "r1", .reg "r1", .reg "t1"]⟩,                   -- adcs r1,r1,t1
  ⟨.umulh, [.reg "t1", .reg "a1", .reg "b1"]⟩,                  -- umulh t1,a1,b1
  ⟨.adcs, [.reg "r2", .reg "r2", .reg "t2"]⟩,                   -- adcs r2,r2,t2
  ⟨.mul, [.reg "q", .reg "inv", .reg "r0"]⟩,                    -- mul q,inv,r0
  ⟨.umulh, [.reg "t2", .reg "a2", .reg "b1"]⟩,                  -- umulh t2,a2,b1
  ⟨.adcs, [.reg "r3", .reg "r3", .reg "t3"]⟩,                   -- adcs r3,r3,t3
  ⟨.umulh, [.reg "t3", .reg "a3", .reg "b1"]⟩,                  -- umulh t3,a3,b1
  ⟨.adc, [.reg "r4", .reg "r4", .zero]⟩,                        -- adc r4,r4,xzr
  ⟨.adds, [.reg "r1", .reg "r1", .reg "t0"]⟩,                   -- adds r1,r1,t0
  ⟨.adcs, [.reg "r2", .reg "r2", .reg "t1"]⟩,                   -- adcs r2,r2,t1
  ⟨.mul, [.reg "t1", .reg "p1", .reg "q"]⟩,                     -- mul t1,p1,q
  ⟨.adcs, [.reg "r3", .reg "r3", .reg "t2"]⟩,                   -- adcs r3,r3,t2
  ⟨.adc, [.reg "r4", .reg "r4", .reg "t3"]⟩,                    -- adc r4,r4,t3
  ⟨.lsl, [.reg "t3", .reg "q", .imm 62]⟩,                       -- lsl t3,q,#62
  ⟨.subs, [.zero, .reg "r0", .imm 1]⟩,                          -- subs xzr,r0,#1
  ⟨.umulh, [.reg "t0", .reg "p0", .reg "q"]⟩,                   -- umulh t0,p0,q
  ⟨.adcs, [.reg "r1", .reg "r1", .reg "t1"]⟩,                   -- adcs r1,r1,t1
  ⟨.umulh, [.reg "t1", .reg "p1", .reg "q"]⟩,                   -- umulh t1,p1,q
  ⟨.adcs, [.reg "r2", .reg "r2", .zero]⟩,                       -- adcs r2,r2,xzr
  ⟨.adcs, [.reg "r3", .reg "r3", .reg "t3"]⟩,                   -- adcs r3,r3,t3
  ⟨.lsr, [.reg "t3", .reg "q", .imm 2]⟩,                        -- lsr t3,q,#2
  ⟨.adc, [.reg "r4", .reg "r4", .zero]⟩,                        -- adc r4,r4,xzr
  ⟨.adds, [.reg "r0", .reg "r1", .reg "t0"]⟩,                   -- adds r0,r1,t0
  ⟨.mul, [.reg "t0", .reg "a0", .reg "b2"]⟩,                    -- mul t0,a0,b2
  ⟨.adcs, [.reg "r1", .reg "r2", .reg "t1"]⟩,                   -- adcs r1,r2,t1
  ⟨.mul, [.reg "t1", .reg "a1", .reg "b2"]⟩,                    -- mul t1,a1,b2
  ⟨.adcs, [.reg "r2", .reg "r3", .zero]⟩,                       -- adcs r2,r3,xzr
  ⟨.mul, [.reg "t2", .reg "a2", .reg "b2"]⟩,                    -- mul t2,a2,b2
  ⟨.adcs, [.reg "r3", .reg "r4", .reg "t3"]⟩,                   -- adcs r3,r4,t3
  ⟨.mul, [.reg "t3", .reg "a3", .reg "b2"]⟩,                    -- mul t3,a3,b2
  ⟨.adc, [.reg "r4", .zero, .zero]⟩,                            -- adc r4,xzr,xzr
  ⟨.adds, [.reg "r0", .reg "r0", .reg "t0"]⟩,                   -- adds r0,r0,t0
  ⟨.umulh, [.reg "t0", .reg "a0", .reg "b2"]⟩,                  -- umulh t0,a0,b2
  ⟨.adcs, [.reg "r1", .reg "r1", .reg "t1"]⟩,                   -- adcs r1,r1,t1
  ⟨.umulh, [.reg "t1", .reg "a1", .reg "b2"]⟩,                  -- umulh t1,a1,b2
  ⟨.adcs, [.reg "r2", .reg "r2", .reg "t2"]⟩,                   -- adcs r2,r2,t2
  ⟨.mul, [.reg "q", .reg "inv", .reg "r0"]⟩,                    -- mul q,inv,r0
  ⟨.umulh, [.reg "t2", .reg "a2", .reg "b2"]⟩,                  -- umulh t2,a2,b2
  ⟨.adcs, [.reg "r3", .reg "r3", .reg "t3"]⟩,                   -- adcs r3,r3,t3
  ⟨.umulh, [.reg "t3", .reg "a3", .reg "b2"]⟩,                  -- umulh t3,a3,b2
  ⟨.adc, [.reg "r4", .reg "r4", .zero]⟩,                        -- adc r4,r4,xzr
  ⟨.adds, [.reg "r1", .reg "r1", .reg "t0"]⟩,                   -- adds r1,r1,t0
  ⟨.adcs, [.reg "r2", .reg "r2", .reg "t1"]⟩,                   -- adcs r2,r2,t1
  ⟨.mul, [.reg "t1", .reg "p1", .reg "q"]⟩,                     -- mul t1,p1,q
  ⟨.adcs, [.reg "r3", .reg "r3", .reg "t2"]⟩,                   -- adcs r3,r3,t2
  ⟨.adc, [.reg "r4", .reg "r4", .reg "t3"]⟩,                    -- adc r4,r4,t3
  ⟨.lsl, [.reg "t3", .reg "q", .imm 62]⟩,                       -- lsl t3,q,#62
  ⟨.subs, [.zero, .reg "r0", .imm 1]⟩,                          -- subs xzr,r0,#1
  ⟨.umulh, [.reg "t0", .reg "p0", .reg "q"]⟩,                   -- umulh t0,p0,q
  ⟨.adcs, [.reg "r1", .reg "r1", .reg "t1"]⟩,                   -- adcs r1,r1,t1
  ⟨.umulh, [.reg "t1", .reg "p1", .reg "q"]⟩,                   -- umulh t1,p1,q
  ⟨.adcs, [.reg "r2", .reg "r2", .zero]⟩,                       -- adcs r2,r2,xzr
  ⟨.adcs, [.reg "r3", .reg "r3", .reg "t3"]⟩,                   -- adcs r3,r3,t3
  ⟨.lsr, [.reg "t3", .reg "q", .imm 2]⟩,                        -- lsr t3,q,#2
  ⟨.adc, [.reg "r4", .reg "r4", .zero]⟩,                        -- adc r4,r4,xzr
  ⟨.adds, [.reg "r0", .reg "r1", .reg "t0"]⟩,                   -- adds r0,r1,t0
  ⟨.mul, [.reg "t0", .reg "a0", .reg "b3"]⟩,                    -- mul t0,a0,b3
  ⟨.adcs, [.reg "r1", .reg "r2", .reg "t1"]⟩,                   -- adcs r1,r2,t1
  ⟨.mul, [.reg "t1", .reg "a1", .reg "b3"]⟩,                    -- mul t1,a1,b3
  ⟨.adcs, [.reg "r2", .reg "r3", .zero]⟩,                       -- adcs r2,r3,xzr
  ⟨.mul, [.reg "t2", .reg "a2", .reg "b3"]⟩,                    -- mul t2,a2,b3
  ⟨.adcs, [.reg "r3", .reg "r4", .reg "t3"]⟩,                   -- adcs r3,r4,t3
  ⟨.mul, [.reg "t3", .reg "a3", .reg "b3"]⟩,                    -- mul t3,a3,b3
  ⟨.adc, [.reg "r4", .zero, .zero]⟩,                            -- adc r4,xzr,xzr
  ⟨.adds, [.reg "r0", .reg "r0", .reg "t0"]⟩,                   -- adds r0,r0,t0
  ⟨.umulh, [.reg "t0", .reg "a0", .reg "b3"]⟩,                  -- umulh t0,a0,b3
  ⟨.adcs, [.reg "r1", .reg "r1", .reg "t1"]⟩,                   -- adcs r1,r1,t1
  ⟨.umulh, [.reg "t1", .reg "a1", .reg "b3"]⟩,                  -- umulh t1,a1,b3
  ⟨.adcs, [.reg "r2", .reg "r2", .reg "t2"]⟩,                   -- adcs r2,r2,t2
  ⟨.mul, [.reg "q", .reg "inv", .reg "r0"]⟩,                    -- mul q,inv,r0
  ⟨.umulh, [.reg "t2", .reg "a2", .reg "b3"]⟩,                  -- umulh t2,a2,b3
  ⟨.adcs, [.reg "r3", .reg "r3", .reg "t3"]⟩,                   -- adcs r3,r3,t3
  ⟨.umulh, [.reg "t3", .reg "a3", .reg "b3"]⟩,                  -- umulh t3,a3,b3
  ⟨.adc, [.reg "r4", .reg "r4", .zero]⟩,                        -- adc r4,r4,xzr
  ⟨.adds, [.reg "r1", .reg "r1", .reg "t0"]⟩,                   -- adds r1,r1,t0
  ⟨.adcs, [.reg "r2", .reg "r2", .reg "t1"]⟩,                   -- adcs r2,r2,t1
  ⟨.mul, [.reg "t1", .reg "p1", .reg "q"]⟩,                     -- mul t1,p1,q
  ⟨.adcs, [.reg "r3", .reg "r3", .reg "t2"]⟩,                   -- adcs r3,r3,t2
  ⟨.adc, [.reg "r4", .reg "r4", .reg "t3"]⟩,                    -- adc r4,r4,t3
  ⟨.lsl, [.reg "t3", .reg "q", .imm 62]⟩,                       -- lsl t3,q,#62
  ⟨.subs, [.zero, .reg "r0", .imm 1]⟩,                          -- subs xzr,r0,#1
  ⟨.umulh, [.reg "t0", .reg "p0", .reg "q"]⟩,                   -- umulh t0,p0,q
  ⟨.adcs, [.reg "r1", .reg "r1", .reg "t1"]⟩,                   -- adcs r1,r1,t1
  ⟨.umulh, [.reg "t1", .reg "p1", .reg "q"]⟩,                   -- umulh t1,p1,q
  ⟨.adcs, [.reg "r2", .reg "r2", .zero]⟩,                       -- adcs r2,r2,xzr
  ⟨.adcs, [.reg "r3", .reg "r3", .reg "t3"]⟩,                   -- adcs r3,r3,t3
  ⟨.lsr, [.reg "t3", .reg "q", .imm 2]⟩,                        -- lsr t3,q,#2
  ⟨.adc, [.reg "r4", .reg "r4", .zero]⟩,                        -- adc r4,r4,xzr
  ⟨.adds, [.reg "r0", .reg "r1", .reg "t0"]⟩,                   -- adds r0,r1,t0
  ⟨.adcs, [.reg "r1", .reg "r2", .reg "t1"]⟩,                   -- adcs r1,r2,t1
  ⟨.adcs, [.reg "r2", .reg "r3", .zero]⟩,                       -- adcs r2,r3,xzr
  ⟨.adcs, [.reg "r3", .reg "r4", .reg "t3"]⟩,                   -- adcs r3,r4,t3
  ⟨.mov, [.reg "q", .imm 0x4000000000000000]⟩,                  -- mov q,#0x4000000000000000
  ⟨.subs, [.reg "t0", .reg "r0", .reg "p0"]⟩,                   -- subs t0,r0,p0
  ⟨.sbcs, [.reg "t1", .reg "r1", .reg "p1"]⟩,                   -- sbcs t1,r1,p1
  ⟨.sbcs, [.reg "t2", .reg "r2", .zero]⟩,                       -- sbcs t2,r2,xzr
  ⟨.sbcs, [.reg "t3", .reg "r3", .reg "q"]⟩,                    -- sbcs t3,r3,q
  ⟨.csel, [.reg "r0", .reg "r0", .reg "t0", .cond .lo]⟩,        -- csel r0,r0,t0,lo
  ⟨.csel, [.reg "r1", .reg "r1", .reg "t1", .cond .lo]⟩,        -- csel r1,r1,t1,lo
  ⟨.csel, [.reg "r2", .reg "r2", .reg "t2", .cond .lo]⟩,        -- csel r2,r2,t2,lo
  ⟨.csel, [.reg "r3", .reg "r3", .reg "t3", .cond .lo]⟩         -- csel r3,r3,t3,lo
]

/-- The instruction stream of the inline `asm!` block of `square`, as written, its macro invocations
expanded. -/
def sqrMontProgram : List Instr := [
  ⟨.mul, [.reg "z1", .reg "a1", .reg "a0"]⟩,                    -- mul z1,a1,a0
  ⟨.umulh, [.reg "w1", .reg "a1", .reg "a0"]⟩,                  -- umulh w1,a1,a0
  ⟨.mul, [.reg "z2", .reg "a2", .reg "a0"]⟩,                    -- mul z2,a2,a0
  ⟨.umulh, [.reg "w2", .reg "a2", .reg "a0"]⟩,                  -- umulh w2,a2,a0
  ⟨.mul, [.reg "z3", .reg "a3", .reg "a0"]⟩,                    -- mul z3,a3,a0
  ⟨.umulh, [.reg "z4", .reg "a3", .reg "a0"]⟩,                  -- umulh z4,a3,a0
  ⟨.adds, [.reg "z2", .reg "z2", .reg "w1"]⟩,                   -- adds z2,z2,w1
  ⟨.mul, [.reg "w0", .reg "a2", .reg "a1"]⟩,                    -- mul w0,a2,a1
  ⟨.umulh, [.reg "w1", .reg "a2", .reg "a1"]⟩,                  -- umulh w1,a2,a1
  ⟨.adcs, [.reg "z3", .reg "z3", .reg "w2"]⟩,                   -- adcs z3,z3,w2
  ⟨.mul, [.reg "w2", .reg "a3", .reg "a1"]⟩,                    -- mul w2,a3,a1
  ⟨.umulh, [.reg "w3", .reg "a3", .reg "a1"]⟩,                  -- umulh w3,a3,a1
  ⟨.adc, [.reg "z4", .reg "z4", .zero]⟩,                        -- adc z4,z4,xzr
  ⟨.mul, [.reg "z5", .reg "a3", .reg "a2"]⟩,                    -- mul z5,a3,a2
  ⟨.umulh, [.reg "z6", .reg "a3", .reg "a2"]⟩,                  -- umulh z6,a3,a2
  ⟨.adds, [.reg "w1", .reg "w1", .reg "w2"]⟩,                   -- adds w1,w1,w2
  ⟨.mul, [.reg "z0", .reg "a0", .reg "a0"]⟩,                    -- mul z0,a0,a0
  ⟨.adc, [.reg "w2", .reg "w3", .zero]⟩,                        -- adc w2,w3,xzr
  ⟨.adds, [.reg "z3", .reg "z3", .reg "w0"]⟩,                   -- adds z3,z3,w0
  ⟨.umulh, [.reg "a0", .reg "a0", .reg "a0"]⟩,                  -- umulh a0,a0,a0
  ⟨.adcs, [.reg "z4", .reg "z4", .reg "w1"]⟩,                   -- adcs z4,z4,w1
  ⟨.mul, [.reg "w1", .reg "a1", .reg "a1"]⟩,                    -- mul w1,a1,a1
  ⟨.adcs, [.reg "z5", .reg "z5", .reg "w2"]⟩,                   -- adcs z5,z5,w2
  ⟨.umulh, [.reg "a1", .reg "a1", .reg "a1"]⟩,                  -- umulh a1,a1,a1
  ⟨.adc, [.reg "z6", .reg "z6", .zero]⟩,                        -- adc z6,z6,xzr
  ⟨.adds, [.reg "z1", .reg "z1", .reg "z1"]⟩,                   -- adds z1,z1,z1
  ⟨.mul, [.reg "w2", .reg "a2", .reg "a2"]⟩,                    -- mul w2,a2,a2
  ⟨.adcs, [.reg "z2", .reg "z2", .reg "z2"]⟩,                   -- adcs z2,z2,z2
  ⟨.umulh, [.reg "a2", .reg "a2", .reg "a2"]⟩,                  -- umulh a2,a2,a2
  ⟨.adcs, [.reg "z3", .reg "z3", .reg "z3"]⟩,                   -- adcs z3,z3,z3
  ⟨.mul, [.reg "w3", .reg "a3", .reg "a3"]⟩,                    -- mul w3,a3,a3
  ⟨.adcs, [.reg "z4", .reg "z4", .reg "z4"]⟩,                   -- adcs z4,z4,z4
  ⟨.umulh, [.reg "a3", .reg "a3", .reg "a3"]⟩,                  -- umulh a3,a3,a3
  ⟨.adcs, [.reg "z5", .reg "z5", .reg "z5"]⟩,                   -- adcs z5,z5,z5
  ⟨.adcs, [.reg "z6", .reg "z6", .reg "z6"]⟩,                   -- adcs z6,z6,z6
  ⟨.adc, [.reg "z7", .zero, .zero]⟩,                            -- adc z7,xzr,xzr
  ⟨.mul, [.reg "q", .reg "inv", .reg "z0"]⟩,                    -- mul q,inv,z0
  ⟨.adds, [.reg "z1", .reg "z1", .reg "a0"]⟩,                   -- adds z1,z1,a0
  ⟨.adcs, [.reg "z2", .reg "z2", .reg "w1"]⟩,                   -- adcs z2,z2,w1
  ⟨.adcs, [.reg "z3", .reg "z3", .reg "a1"]⟩,                   -- adcs z3,z3,a1
  ⟨.adcs, [.reg "z4", .reg "z4", .reg "w2"]⟩,                   -- adcs z4,z4,w2
  ⟨.adcs, [.reg "z5", .reg "z5", .reg "a2"]⟩,                   -- adcs z5,z5,a2
  ⟨.adcs, [.reg "z6", .reg "z6", .reg "w3"]⟩,                   -- adcs z6,z6,w3
  ⟨.adc, [.reg "z7", .reg "z7", .reg "a3"]⟩,                    -- adc z7,z7,a3
  ⟨.mul, [.reg "w1", .reg "p1", .reg "q"]⟩,                     -- mul w1,p1,q
  ⟨.lsl, [.reg "w3", .reg "q", .imm 62]⟩,                       -- lsl w3,q,#62
  ⟨.subs, [.zero, .reg "z0", .imm 1]⟩,                          -- subs xzr,z0,#1
  ⟨.umulh, [.reg "w0", .reg "p0", .reg "q"]⟩,                   -- umulh w0,p0,q
  ⟨.adcs, [.reg "z1", .reg "z1", .reg "w1"]⟩,                   -- adcs z1,z1,w1
  ⟨.umulh, [.reg "w1", .reg "p1", .reg "q"]⟩,                   -- umulh w1,p1,q
  ⟨.adcs, [.reg "z2", .reg "z2", .zero]⟩,                       -- adcs z2,z2,xzr
  ⟨.adcs, [.reg "z3", .reg "z3", .reg "w3"]⟩,                   -- adcs z3,z3,w3
  ⟨.lsr, [.reg "w3", .reg "q", .imm 2]⟩,                        -- lsr w3,q,#2
  ⟨.adc, [.reg "cy", .zero, .zero]⟩,                            -- adc cy,xzr,xzr
  ⟨.adds, [.reg "z0", .reg "z1", .reg "w0"]⟩,                   -- adds z0,z1,w0
  ⟨.adcs, [.reg "z1", .reg "z2", .reg "w1"]⟩,                   -- adcs z1,z2,w1
  ⟨.adcs, [.reg "z2", .reg "z3", .zero]⟩,                       -- adcs z2,z3,xzr
  ⟨.mul, [.reg "q", .reg "inv", .reg "z0"]⟩,                    -- mul q,inv,z0
  ⟨.adc, [.reg "z3", .reg "cy", .reg "w3"]⟩,                    -- adc z3,cy,w3
  ⟨.mul, [.reg "w1", .reg "p1", .reg "q"]⟩,                     -- mul w1,p1,q
  ⟨.lsl, [.reg "w3", .reg "q", .imm 62]⟩,                       -- lsl w3,q,#62
  ⟨.subs, [.zero, .reg "z0", .imm 1]⟩,                          -- subs xzr,z0,#1
  ⟨.umulh, [.reg "w0", .reg "p0", .reg "q"]⟩,                   -- umulh w0,p0,q
  ⟨.adcs, [.reg "z1", .reg "z1", .reg "w1"]⟩,                   -- adcs z1,z1,w1
  ⟨.umulh, [.reg "w1", .reg "p1", .reg "q"]⟩,                   -- umulh w1,p1,q
  ⟨.adcs, [.reg "z2", .reg "z2", .zero]⟩,                       -- adcs z2,z2,xzr
  ⟨.adcs, [.reg "z3", .reg "z3", .reg "w3"]⟩,                   -- adcs z3,z3,w3
  ⟨.lsr, [.reg "w3", .reg "q", .imm 2]⟩,                        -- lsr w3,q,#2
  ⟨.adc, [.reg "cy", .zero, .zero]⟩,                            -- adc cy,xzr,xzr
  ⟨.adds, [.reg "z0", .reg "z1", .reg "w0"]⟩,                   -- adds z0,z1,w0
  ⟨.adcs, [.reg "z1", .reg "z2", .reg "w1"]⟩,                   -- adcs z1,z2,w1
  ⟨.adcs, [.reg "z2", .reg "z3", .zero]⟩,                       -- adcs z2,z3,xzr
  ⟨.mul, [.reg "q", .reg "inv", .reg "z0"]⟩,                    -- mul q,inv,z0
  ⟨.adc, [.reg "z3", .reg "cy", .reg "w3"]⟩,                    -- adc z3,cy,w3
  ⟨.mul, [.reg "w1", .reg "p1", .reg "q"]⟩,                     -- mul w1,p1,q
  ⟨.lsl, [.reg "w3", .reg "q", .imm 62]⟩,                       -- lsl w3,q,#62
  ⟨.subs, [.zero, .reg "z0", .imm 1]⟩,                          -- subs xzr,z0,#1
  ⟨.umulh, [.reg "w0", .reg "p0", .reg "q"]⟩,                   -- umulh w0,p0,q
  ⟨.adcs, [.reg "z1", .reg "z1", .reg "w1"]⟩,                   -- adcs z1,z1,w1
  ⟨.umulh, [.reg "w1", .reg "p1", .reg "q"]⟩,                   -- umulh w1,p1,q
  ⟨.adcs, [.reg "z2", .reg "z2", .zero]⟩,                       -- adcs z2,z2,xzr
  ⟨.adcs, [.reg "z3", .reg "z3", .reg "w3"]⟩,                   -- adcs z3,z3,w3
  ⟨.lsr, [.reg "w3", .reg "q", .imm 2]⟩,                        -- lsr w3,q,#2
  ⟨.adc, [.reg "cy", .zero, .zero]⟩,                            -- adc cy,xzr,xzr
  ⟨.adds, [.reg "z0", .reg "z1", .reg "w0"]⟩,                   -- adds z0,z1,w0
  ⟨.adcs, [.reg "z1", .reg "z2", .reg "w1"]⟩,                   -- adcs z1,z2,w1
  ⟨.adcs, [.reg "z2", .reg "z3", .zero]⟩,                       -- adcs z2,z3,xzr
  ⟨.mul, [.reg "q", .reg "inv", .reg "z0"]⟩,                    -- mul q,inv,z0
  ⟨.adc, [.reg "z3", .reg "cy", .reg "w3"]⟩,                    -- adc z3,cy,w3
  ⟨.mul, [.reg "w1", .reg "p1", .reg "q"]⟩,                     -- mul w1,p1,q
  ⟨.lsl, [.reg "w3", .reg "q", .imm 62]⟩,                       -- lsl w3,q,#62
  ⟨.subs, [.zero, .reg "z0", .imm 1]⟩,                          -- subs xzr,z0,#1
  ⟨.umulh, [.reg "w0", .reg "p0", .reg "q"]⟩,                   -- umulh w0,p0,q
  ⟨.adcs, [.reg "z1", .reg "z1", .reg "w1"]⟩,                   -- adcs z1,z1,w1
  ⟨.umulh, [.reg "w1", .reg "p1", .reg "q"]⟩,                   -- umulh w1,p1,q
  ⟨.adcs, [.reg "z2", .reg "z2", .zero]⟩,                       -- adcs z2,z2,xzr
  ⟨.adcs, [.reg "z3", .reg "z3", .reg "w3"]⟩,                   -- adcs z3,z3,w3
  ⟨.lsr, [.reg "w3", .reg "q", .imm 2]⟩,                        -- lsr w3,q,#2
  ⟨.adc, [.reg "cy", .zero, .zero]⟩,                            -- adc cy,xzr,xzr
  ⟨.adds, [.reg "z0", .reg "z1", .reg "w0"]⟩,                   -- adds z0,z1,w0
  ⟨.adcs, [.reg "z1", .reg "z2", .reg "w1"]⟩,                   -- adcs z1,z2,w1
  ⟨.adcs, [.reg "z2", .reg "z3", .zero]⟩,                       -- adcs z2,z3,xzr
  ⟨.adc, [.reg "z3", .reg "cy", .reg "w3"]⟩,                    -- adc z3,cy,w3
  ⟨.adds, [.reg "a0", .reg "z0", .reg "z4"]⟩,                   -- adds a0,z0,z4
  ⟨.adcs, [.reg "a1", .reg "z1", .reg "z5"]⟩,                   -- adcs a1,z1,z5
  ⟨.adcs, [.reg "a2", .reg "z2", .reg "z6"]⟩,                   -- adcs a2,z2,z6
  ⟨.adc, [.reg "a3", .reg "z3", .reg "z7"]⟩,                    -- adc a3,z3,z7
  ⟨.mov, [.reg "q", .imm 0x4000000000000000]⟩,                  -- mov q,#0x4000000000000000
  ⟨.subs, [.reg "z0", .reg "a0", .reg "p0"]⟩,                   -- subs z0,a0,p0
  ⟨.sbcs, [.reg "z1", .reg "a1", .reg "p1"]⟩,                   -- sbcs z1,a1,p1
  ⟨.sbcs, [.reg "z2", .reg "a2", .zero]⟩,                       -- sbcs z2,a2,xzr
  ⟨.sbcs, [.reg "z3", .reg "a3", .reg "q"]⟩,                    -- sbcs z3,a3,q
  ⟨.csel, [.reg "a0", .reg "a0", .reg "z0", .cond .lo]⟩,        -- csel a0,a0,z0,lo
  ⟨.csel, [.reg "a1", .reg "a1", .reg "z1", .cond .lo]⟩,        -- csel a1,a1,z1,lo
  ⟨.csel, [.reg "a2", .reg "a2", .reg "z2", .cond .lo]⟩,        -- csel a2,a2,z2,lo
  ⟨.csel, [.reg "a3", .reg "a3", .reg "z3", .cond .lo]⟩         -- csel a3,a3,z3,lo
]

/-- The instruction stream of the inline `asm!` block of `add`, as written, its macro invocations
expanded. -/
def addModProgram : List Instr := [
  ⟨.adds, [.reg "r0", .reg "r0", .reg "b0"]⟩,                   -- adds r0,r0,b0
  ⟨.adcs, [.reg "r1", .reg "r1", .reg "b1"]⟩,                   -- adcs r1,r1,b1
  ⟨.adcs, [.reg "r2", .reg "r2", .reg "b2"]⟩,                   -- adcs r2,r2,b2
  ⟨.adc, [.reg "r3", .reg "r3", .reg "b3"]⟩,                    -- adc r3,r3,b3
  ⟨.subs, [.reg "t0", .reg "r0", .reg "p0"]⟩,                   -- subs t0,r0,p0
  ⟨.sbcs, [.reg "t1", .reg "r1", .reg "p1"]⟩,                   -- sbcs t1,r1,p1
  ⟨.sbcs, [.reg "t2", .reg "r2", .zero]⟩,                       -- sbcs t2,r2,xzr
  ⟨.sbcs, [.reg "t3", .reg "r3", .reg "p3"]⟩,                   -- sbcs t3,r3,p3
  ⟨.csel, [.reg "r0", .reg "t0", .reg "r0", .cond .cs]⟩,        -- csel r0,t0,r0,cs
  ⟨.csel, [.reg "r1", .reg "t1", .reg "r1", .cond .cs]⟩,        -- csel r1,t1,r1,cs
  ⟨.csel, [.reg "r2", .reg "t2", .reg "r2", .cond .cs]⟩,        -- csel r2,t2,r2,cs
  ⟨.csel, [.reg "r3", .reg "t3", .reg "r3", .cond .cs]⟩         -- csel r3,t3,r3,cs
]

/-- The instruction stream of the inline `asm!` block of `sub`, as written, its macro invocations
expanded. -/
def subModProgram : List Instr := [
  ⟨.subs, [.reg "r0", .reg "r0", .reg "b0"]⟩,                   -- subs r0,r0,b0
  ⟨.sbcs, [.reg "r1", .reg "r1", .reg "b1"]⟩,                   -- sbcs r1,r1,b1
  ⟨.sbcs, [.reg "r2", .reg "r2", .reg "b2"]⟩,                   -- sbcs r2,r2,b2
  ⟨.sbcs, [.reg "r3", .reg "r3", .reg "b3"]⟩,                   -- sbcs r3,r3,b3
  ⟨.csel, [.reg "t0", .reg "p0", .zero, .cond .cc]⟩,            -- csel t0,p0,xzr,cc
  ⟨.csel, [.reg "t1", .reg "p1", .zero, .cond .cc]⟩,            -- csel t1,p1,xzr,cc
  ⟨.csel, [.reg "t3", .reg "p3", .zero, .cond .cc]⟩,            -- csel t3,p3,xzr,cc
  ⟨.adds, [.reg "r0", .reg "r0", .reg "t0"]⟩,                   -- adds r0,r0,t0
  ⟨.adcs, [.reg "r1", .reg "r1", .reg "t1"]⟩,                   -- adcs r1,r1,t1
  ⟨.adcs, [.reg "r2", .reg "r2", .zero]⟩,                       -- adcs r2,r2,xzr
  ⟨.adc, [.reg "r3", .reg "r3", .reg "t3"]⟩                     -- adc r3,r3,t3
]

/-- The instruction stream of the inline `asm!` block of `divstep59`, as written, its macro
invocations expanded. -/
def divstep59BlockProgram : List Instr := [
  ⟨.and, [.reg "pf", .reg "f", .imm 0xfffff]⟩,                  -- and pf,f,#0xfffff
  ⟨.orr, [.reg "pf", .reg "pf", .imm 0xfffffe0000000000]⟩,      -- orr pf,pf,#0xfffffe0000000000
  ⟨.and, [.reg "pg", .reg "g", .imm 0xfffff]⟩,                  -- and pg,g,#0xfffff
  ⟨.orr, [.reg "pg", .reg "pg", .imm 0xc000000000000000]⟩,      -- orr pg,pg,#0xc000000000000000
  ⟨.tst, [.reg "pg", .imm 1]⟩,                                  -- tst pg,#1
  ⟨.csel, [.reg "t", .reg "pf", .zero, .cond .ne]⟩,             -- csel t,pf,xzr,ne
  ⟨.ccmp, [.reg "d", .zero, .imm 8, .cond .ne]⟩,                -- ccmp d,xzr,#8,ne
  ⟨.cneg, [.reg "d", .reg "d", .cond .ge]⟩,                     -- cneg d,d,ge
  ⟨.cneg, [.reg "t", .reg "t", .cond .ge]⟩,                     -- cneg t,t,ge
  ⟨.csel, [.reg "pf", .reg "pg", .reg "pf", .cond .ge]⟩,        -- csel pf,pg,pf,ge
  ⟨.add, [.reg "pg", .reg "pg", .reg "t"]⟩,                     -- add pg,pg,t
  ⟨.add, [.reg "d", .reg "d", .imm 2]⟩,                         -- add d,d,#2
  ⟨.tst, [.reg "pg", .imm 2]⟩,                                  -- tst pg,#2
  ⟨.asr, [.reg "pg", .reg "pg", .imm 1]⟩,                       -- asr pg,pg,#1
  ⟨.csel, [.reg "t", .reg "pf", .zero, .cond .ne]⟩,             -- csel t,pf,xzr,ne
  ⟨.ccmp, [.reg "d", .zero, .imm 8, .cond .ne]⟩,                -- ccmp d,xzr,#8,ne
  ⟨.cneg, [.reg "d", .reg "d", .cond .ge]⟩,                     -- cneg d,d,ge
  ⟨.cneg, [.reg "t", .reg "t", .cond .ge]⟩,                     -- cneg t,t,ge
  ⟨.csel, [.reg "pf", .reg "pg", .reg "pf", .cond .ge]⟩,        -- csel pf,pg,pf,ge
  ⟨.add, [.reg "pg", .reg "pg", .reg "t"]⟩,                     -- add pg,pg,t
  ⟨.add, [.reg "d", .reg "d", .imm 2]⟩,                         -- add d,d,#2
  ⟨.tst, [.reg "pg", .imm 2]⟩,                                  -- tst pg,#2
  ⟨.asr, [.reg "pg", .reg "pg", .imm 1]⟩,                       -- asr pg,pg,#1
  ⟨.csel, [.reg "t", .reg "pf", .zero, .cond .ne]⟩,             -- csel t,pf,xzr,ne
  ⟨.ccmp, [.reg "d", .zero, .imm 8, .cond .ne]⟩,                -- ccmp d,xzr,#8,ne
  ⟨.cneg, [.reg "d", .reg "d", .cond .ge]⟩,                     -- cneg d,d,ge
  ⟨.cneg, [.reg "t", .reg "t", .cond .ge]⟩,                     -- cneg t,t,ge
  ⟨.csel, [.reg "pf", .reg "pg", .reg "pf", .cond .ge]⟩,        -- csel pf,pg,pf,ge
  ⟨.add, [.reg "pg", .reg "pg", .reg "t"]⟩,                     -- add pg,pg,t
  ⟨.add, [.reg "d", .reg "d", .imm 2]⟩,                         -- add d,d,#2
  ⟨.tst, [.reg "pg", .imm 2]⟩,                                  -- tst pg,#2
  ⟨.asr, [.reg "pg", .reg "pg", .imm 1]⟩,                       -- asr pg,pg,#1
  ⟨.csel, [.reg "t", .reg "pf", .zero, .cond .ne]⟩,             -- csel t,pf,xzr,ne
  ⟨.ccmp, [.reg "d", .zero, .imm 8, .cond .ne]⟩,                -- ccmp d,xzr,#8,ne
  ⟨.cneg, [.reg "d", .reg "d", .cond .ge]⟩,                     -- cneg d,d,ge
  ⟨.cneg, [.reg "t", .reg "t", .cond .ge]⟩,                     -- cneg t,t,ge
  ⟨.csel, [.reg "pf", .reg "pg", .reg "pf", .cond .ge]⟩,        -- csel pf,pg,pf,ge
  ⟨.add, [.reg "pg", .reg "pg", .reg "t"]⟩,                     -- add pg,pg,t
  ⟨.add, [.reg "d", .reg "d", .imm 2]⟩,                         -- add d,d,#2
  ⟨.tst, [.reg "pg", .imm 2]⟩,                                  -- tst pg,#2
  ⟨.asr, [.reg "pg", .reg "pg", .imm 1]⟩,                       -- asr pg,pg,#1
  ⟨.csel, [.reg "t", .reg "pf", .zero, .cond .ne]⟩,             -- csel t,pf,xzr,ne
  ⟨.ccmp, [.reg "d", .zero, .imm 8, .cond .ne]⟩,                -- ccmp d,xzr,#8,ne
  ⟨.cneg, [.reg "d", .reg "d", .cond .ge]⟩,                     -- cneg d,d,ge
  ⟨.cneg, [.reg "t", .reg "t", .cond .ge]⟩,                     -- cneg t,t,ge
  ⟨.csel, [.reg "pf", .reg "pg", .reg "pf", .cond .ge]⟩,        -- csel pf,pg,pf,ge
  ⟨.add, [.reg "pg", .reg "pg", .reg "t"]⟩,                     -- add pg,pg,t
  ⟨.add, [.reg "d", .reg "d", .imm 2]⟩,                         -- add d,d,#2
  ⟨.tst, [.reg "pg", .imm 2]⟩,                                  -- tst pg,#2
  ⟨.asr, [.reg "pg", .reg "pg", .imm 1]⟩,                       -- asr pg,pg,#1
  ⟨.csel, [.reg "t", .reg "pf", .zero, .cond .ne]⟩,             -- csel t,pf,xzr,ne
  ⟨.ccmp, [.reg "d", .zero, .imm 8, .cond .ne]⟩,                -- ccmp d,xzr,#8,ne
  ⟨.cneg, [.reg "d", .reg "d", .cond .ge]⟩,                     -- cneg d,d,ge
  ⟨.cneg, [.reg "t", .reg "t", .cond .ge]⟩,                     -- cneg t,t,ge
  ⟨.csel, [.reg "pf", .reg "pg", .reg "pf", .cond .ge]⟩,        -- csel pf,pg,pf,ge
  ⟨.add, [.reg "pg", .reg "pg", .reg "t"]⟩,                     -- add pg,pg,t
  ⟨.add, [.reg "d", .reg "d", .imm 2]⟩,                         -- add d,d,#2
  ⟨.tst, [.reg "pg", .imm 2]⟩,                                  -- tst pg,#2
  ⟨.asr, [.reg "pg", .reg "pg", .imm 1]⟩,                       -- asr pg,pg,#1
  ⟨.csel, [.reg "t", .reg "pf", .zero, .cond .ne]⟩,             -- csel t,pf,xzr,ne
  ⟨.ccmp, [.reg "d", .zero, .imm 8, .cond .ne]⟩,                -- ccmp d,xzr,#8,ne
  ⟨.cneg, [.reg "d", .reg "d", .cond .ge]⟩,                     -- cneg d,d,ge
  ⟨.cneg, [.reg "t", .reg "t", .cond .ge]⟩,                     -- cneg t,t,ge
  ⟨.csel, [.reg "pf", .reg "pg", .reg "pf", .cond .ge]⟩,        -- csel pf,pg,pf,ge
  ⟨.add, [.reg "pg", .reg "pg", .reg "t"]⟩,                     -- add pg,pg,t
  ⟨.add, [.reg "d", .reg "d", .imm 2]⟩,                         -- add d,d,#2
  ⟨.tst, [.reg "pg", .imm 2]⟩,                                  -- tst pg,#2
  ⟨.asr, [.reg "pg", .reg "pg", .imm 1]⟩,                       -- asr pg,pg,#1
  ⟨.csel, [.reg "t", .reg "pf", .zero, .cond .ne]⟩,             -- csel t,pf,xzr,ne
  ⟨.ccmp, [.reg "d", .zero, .imm 8, .cond .ne]⟩,                -- ccmp d,xzr,#8,ne
  ⟨.cneg, [.reg "d", .reg "d", .cond .ge]⟩,                     -- cneg d,d,ge
  ⟨.cneg, [.reg "t", .reg "t", .cond .ge]⟩,                     -- cneg t,t,ge
  ⟨.csel, [.reg "pf", .reg "pg", .reg "pf", .cond .ge]⟩,        -- csel pf,pg,pf,ge
  ⟨.add, [.reg "pg", .reg "pg", .reg "t"]⟩,                     -- add pg,pg,t
  ⟨.add, [.reg "d", .reg "d", .imm 2]⟩,                         -- add d,d,#2
  ⟨.tst, [.reg "pg", .imm 2]⟩,                                  -- tst pg,#2
  ⟨.asr, [.reg "pg", .reg "pg", .imm 1]⟩,                       -- asr pg,pg,#1
  ⟨.csel, [.reg "t", .reg "pf", .zero, .cond .ne]⟩,             -- csel t,pf,xzr,ne
  ⟨.ccmp, [.reg "d", .zero, .imm 8, .cond .ne]⟩,                -- ccmp d,xzr,#8,ne
  ⟨.cneg, [.reg "d", .reg "d", .cond .ge]⟩,                     -- cneg d,d,ge
  ⟨.cneg, [.reg "t", .reg "t", .cond .ge]⟩,                     -- cneg t,t,ge
  ⟨.csel, [.reg "pf", .reg "pg", .reg "pf", .cond .ge]⟩,        -- csel pf,pg,pf,ge
  ⟨.add, [.reg "pg", .reg "pg", .reg "t"]⟩,                     -- add pg,pg,t
  ⟨.add, [.reg "d", .reg "d", .imm 2]⟩,                         -- add d,d,#2
  ⟨.tst, [.reg "pg", .imm 2]⟩,                                  -- tst pg,#2
  ⟨.asr, [.reg "pg", .reg "pg", .imm 1]⟩,                       -- asr pg,pg,#1
  ⟨.csel, [.reg "t", .reg "pf", .zero, .cond .ne]⟩,             -- csel t,pf,xzr,ne
  ⟨.ccmp, [.reg "d", .zero, .imm 8, .cond .ne]⟩,                -- ccmp d,xzr,#8,ne
  ⟨.cneg, [.reg "d", .reg "d", .cond .ge]⟩,                     -- cneg d,d,ge
  ⟨.cneg, [.reg "t", .reg "t", .cond .ge]⟩,                     -- cneg t,t,ge
  ⟨.csel, [.reg "pf", .reg "pg", .reg "pf", .cond .ge]⟩,        -- csel pf,pg,pf,ge
  ⟨.add, [.reg "pg", .reg "pg", .reg "t"]⟩,                     -- add pg,pg,t
  ⟨.add, [.reg "d", .reg "d", .imm 2]⟩,                         -- add d,d,#2
  ⟨.tst, [.reg "pg", .imm 2]⟩,                                  -- tst pg,#2
  ⟨.asr, [.reg "pg", .reg "pg", .imm 1]⟩,                       -- asr pg,pg,#1
  ⟨.csel, [.reg "t", .reg "pf", .zero, .cond .ne]⟩,             -- csel t,pf,xzr,ne
  ⟨.ccmp, [.reg "d", .zero, .imm 8, .cond .ne]⟩,                -- ccmp d,xzr,#8,ne
  ⟨.cneg, [.reg "d", .reg "d", .cond .ge]⟩,                     -- cneg d,d,ge
  ⟨.cneg, [.reg "t", .reg "t", .cond .ge]⟩,                     -- cneg t,t,ge
  ⟨.csel, [.reg "pf", .reg "pg", .reg "pf", .cond .ge]⟩,        -- csel pf,pg,pf,ge
  ⟨.add, [.reg "pg", .reg "pg", .reg "t"]⟩,                     -- add pg,pg,t
  ⟨.add, [.reg "d", .reg "d", .imm 2]⟩,                         -- add d,d,#2
  ⟨.tst, [.reg "pg", .imm 2]⟩,                                  -- tst pg,#2
  ⟨.asr, [.reg "pg", .reg "pg", .imm 1]⟩,                       -- asr pg,pg,#1
  ⟨.csel, [.reg "t", .reg "pf", .zero, .cond .ne]⟩,             -- csel t,pf,xzr,ne
  ⟨.ccmp, [.reg "d", .zero, .imm 8, .cond .ne]⟩,                -- ccmp d,xzr,#8,ne
  ⟨.cneg, [.reg "d", .reg "d", .cond .ge]⟩,                     -- cneg d,d,ge
  ⟨.cneg, [.reg "t", .reg "t", .cond .ge]⟩,                     -- cneg t,t,ge
  ⟨.csel, [.reg "pf", .reg "pg", .reg "pf", .cond .ge]⟩,        -- csel pf,pg,pf,ge
  ⟨.add, [.reg "pg", .reg "pg", .reg "t"]⟩,                     -- add pg,pg,t
  ⟨.add, [.reg "d", .reg "d", .imm 2]⟩,                         -- add d,d,#2
  ⟨.tst, [.reg "pg", .imm 2]⟩,                                  -- tst pg,#2
  ⟨.asr, [.reg "pg", .reg "pg", .imm 1]⟩,                       -- asr pg,pg,#1
  ⟨.csel, [.reg "t", .reg "pf", .zero, .cond .ne]⟩,             -- csel t,pf,xzr,ne
  ⟨.ccmp, [.reg "d", .zero, .imm 8, .cond .ne]⟩,                -- ccmp d,xzr,#8,ne
  ⟨.cneg, [.reg "d", .reg "d", .cond .ge]⟩,                     -- cneg d,d,ge
  ⟨.cneg, [.reg "t", .reg "t", .cond .ge]⟩,                     -- cneg t,t,ge
  ⟨.csel, [.reg "pf", .reg "pg", .reg "pf", .cond .ge]⟩,        -- csel pf,pg,pf,ge
  ⟨.add, [.reg "pg", .reg "pg", .reg "t"]⟩,                     -- add pg,pg,t
  ⟨.add, [.reg "d", .reg "d", .imm 2]⟩,                         -- add d,d,#2
  ⟨.tst, [.reg "pg", .imm 2]⟩,                                  -- tst pg,#2
  ⟨.asr, [.reg "pg", .reg "pg", .imm 1]⟩,                       -- asr pg,pg,#1
  ⟨.csel, [.reg "t", .reg "pf", .zero, .cond .ne]⟩,             -- csel t,pf,xzr,ne
  ⟨.ccmp, [.reg "d", .zero, .imm 8, .cond .ne]⟩,                -- ccmp d,xzr,#8,ne
  ⟨.cneg, [.reg "d", .reg "d", .cond .ge]⟩,                     -- cneg d,d,ge
  ⟨.cneg, [.reg "t", .reg "t", .cond .ge]⟩,                     -- cneg t,t,ge
  ⟨.csel, [.reg "pf", .reg "pg", .reg "pf", .cond .ge]⟩,        -- csel pf,pg,pf,ge
  ⟨.add, [.reg "pg", .reg "pg", .reg "t"]⟩,                     -- add pg,pg,t
  ⟨.add, [.reg "d", .reg "d", .imm 2]⟩,                         -- add d,d,#2
  ⟨.tst, [.reg "pg", .imm 2]⟩,                                  -- tst pg,#2
  ⟨.asr, [.reg "pg", .reg "pg", .imm 1]⟩,                       -- asr pg,pg,#1
  ⟨.csel, [.reg "t", .reg "pf", .zero, .cond .ne]⟩,             -- csel t,pf,xzr,ne
  ⟨.ccmp, [.reg "d", .zero, .imm 8, .cond .ne]⟩,                -- ccmp d,xzr,#8,ne
  ⟨.cneg, [.reg "d", .reg "d", .cond .ge]⟩,                     -- cneg d,d,ge
  ⟨.cneg, [.reg "t", .reg "t", .cond .ge]⟩,                     -- cneg t,t,ge
  ⟨.csel, [.reg "pf", .reg "pg", .reg "pf", .cond .ge]⟩,        -- csel pf,pg,pf,ge
  ⟨.add, [.reg "pg", .reg "pg", .reg "t"]⟩,                     -- add pg,pg,t
  ⟨.add, [.reg "d", .reg "d", .imm 2]⟩,                         -- add d,d,#2
  ⟨.tst, [.reg "pg", .imm 2]⟩,                                  -- tst pg,#2
  ⟨.asr, [.reg "pg", .reg "pg", .imm 1]⟩,                       -- asr pg,pg,#1
  ⟨.csel, [.reg "t", .reg "pf", .zero, .cond .ne]⟩,             -- csel t,pf,xzr,ne
  ⟨.ccmp, [.reg "d", .zero, .imm 8, .cond .ne]⟩,                -- ccmp d,xzr,#8,ne
  ⟨.cneg, [.reg "d", .reg "d", .cond .ge]⟩,                     -- cneg d,d,ge
  ⟨.cneg, [.reg "t", .reg "t", .cond .ge]⟩,                     -- cneg t,t,ge
  ⟨.csel, [.reg "pf", .reg "pg", .reg "pf", .cond .ge]⟩,        -- csel pf,pg,pf,ge
  ⟨.add, [.reg "pg", .reg "pg", .reg "t"]⟩,                     -- add pg,pg,t
  ⟨.add, [.reg "d", .reg "d", .imm 2]⟩,                         -- add d,d,#2
  ⟨.tst, [.reg "pg", .imm 2]⟩,                                  -- tst pg,#2
  ⟨.asr, [.reg "pg", .reg "pg", .imm 1]⟩,                       -- asr pg,pg,#1
  ⟨.csel, [.reg "t", .reg "pf", .zero, .cond .ne]⟩,             -- csel t,pf,xzr,ne
  ⟨.ccmp, [.reg "d", .zero, .imm 8, .cond .ne]⟩,                -- ccmp d,xzr,#8,ne
  ⟨.cneg, [.reg "d", .reg "d", .cond .ge]⟩,                     -- cneg d,d,ge
  ⟨.cneg, [.reg "t", .reg "t", .cond .ge]⟩,                     -- cneg t,t,ge
  ⟨.csel, [.reg "pf", .reg "pg", .reg "pf", .cond .ge]⟩,        -- csel pf,pg,pf,ge
  ⟨.add, [.reg "pg", .reg "pg", .reg "t"]⟩,                     -- add pg,pg,t
  ⟨.add, [.reg "d", .reg "d", .imm 2]⟩,                         -- add d,d,#2
  ⟨.tst, [.reg "pg", .imm 2]⟩,                                  -- tst pg,#2
  ⟨.asr, [.reg "pg", .reg "pg", .imm 1]⟩,                       -- asr pg,pg,#1
  ⟨.csel, [.reg "t", .reg "pf", .zero, .cond .ne]⟩,             -- csel t,pf,xzr,ne
  ⟨.ccmp, [.reg "d", .zero, .imm 8, .cond .ne]⟩,                -- ccmp d,xzr,#8,ne
  ⟨.cneg, [.reg "d", .reg "d", .cond .ge]⟩,                     -- cneg d,d,ge
  ⟨.cneg, [.reg "t", .reg "t", .cond .ge]⟩,                     -- cneg t,t,ge
  ⟨.csel, [.reg "pf", .reg "pg", .reg "pf", .cond .ge]⟩,        -- csel pf,pg,pf,ge
  ⟨.add, [.reg "pg", .reg "pg", .reg "t"]⟩,                     -- add pg,pg,t
  ⟨.add, [.reg "d", .reg "d", .imm 2]⟩,                         -- add d,d,#2
  ⟨.tst, [.reg "pg", .imm 2]⟩,                                  -- tst pg,#2
  ⟨.asr, [.reg "pg", .reg "pg", .imm 1]⟩,                       -- asr pg,pg,#1
  ⟨.csel, [.reg "t", .reg "pf", .zero, .cond .ne]⟩,             -- csel t,pf,xzr,ne
  ⟨.ccmp, [.reg "d", .zero, .imm 8, .cond .ne]⟩,                -- ccmp d,xzr,#8,ne
  ⟨.cneg, [.reg "d", .reg "d", .cond .ge]⟩,                     -- cneg d,d,ge
  ⟨.cneg, [.reg "t", .reg "t", .cond .ge]⟩,                     -- cneg t,t,ge
  ⟨.csel, [.reg "pf", .reg "pg", .reg "pf", .cond .ge]⟩,        -- csel pf,pg,pf,ge
  ⟨.add, [.reg "pg", .reg "pg", .reg "t"]⟩,                     -- add pg,pg,t
  ⟨.add, [.reg "d", .reg "d", .imm 2]⟩,                         -- add d,d,#2
  ⟨.tst, [.reg "pg", .imm 2]⟩,                                  -- tst pg,#2
  ⟨.asr, [.reg "pg", .reg "pg", .imm 1]⟩,                       -- asr pg,pg,#1
  ⟨.csel, [.reg "t", .reg "pf", .zero, .cond .ne]⟩,             -- csel t,pf,xzr,ne
  ⟨.ccmp, [.reg "d", .zero, .imm 8, .cond .ne]⟩,                -- ccmp d,xzr,#8,ne
  ⟨.cneg, [.reg "d", .reg "d", .cond .ge]⟩,                     -- cneg d,d,ge
  ⟨.cneg, [.reg "t", .reg "t", .cond .ge]⟩,                     -- cneg t,t,ge
  ⟨.csel, [.reg "pf", .reg "pg", .reg "pf", .cond .ge]⟩,        -- csel pf,pg,pf,ge
  ⟨.add, [.reg "pg", .reg "pg", .reg "t"]⟩,                     -- add pg,pg,t
  ⟨.add, [.reg "d", .reg "d", .imm 2]⟩,                         -- add d,d,#2
  ⟨.asr, [.reg "pg", .reg "pg", .imm 1]⟩,                       -- asr pg,pg,#1
  ⟨.add, [.reg "a00", .reg "pf", .imm 0x100, .lsl 12]⟩,         -- add a00,pf,#0x100,lsl #12
  ⟨.sbfx, [.reg "a00", .reg "a00", .imm 21, .imm 21]⟩,          -- sbfx a00,a00,#21,#21
  ⟨.mov, [.reg "a11", .imm 0x100000]⟩,                          -- mov a11,#0x100000
  ⟨.add, [.reg "a11", .reg "a11", .reg "a11", .lsl 21]⟩,        -- add a11,a11,a11,lsl #21
  ⟨.add, [.reg "a01", .reg "pf", .reg "a11"]⟩,                  -- add a01,pf,a11
  ⟨.asr, [.reg "a01", .reg "a01", .imm 42]⟩,                    -- asr a01,a01,#42
  ⟨.add, [.reg "a10", .reg "pg", .imm 0x100, .lsl 12]⟩,         -- add a10,pg,#0x100,lsl #12
  ⟨.sbfx, [.reg "a10", .reg "a10", .imm 21, .imm 21]⟩,          -- sbfx a10,a10,#21,#21
  ⟨.add, [.reg "a11", .reg "pg", .reg "a11"]⟩,                  -- add a11,pg,a11
  ⟨.asr, [.reg "a11", .reg "a11", .imm 42]⟩,                    -- asr a11,a11,#42
  ⟨.mul, [.reg "t", .reg "a00", .reg "f"]⟩,                     -- mul t,a00,f
  ⟨.mul, [.reg "t2", .reg "a01", .reg "g"]⟩,                    -- mul t2,a01,g
  ⟨.mul, [.reg "f", .reg "a10", .reg "f"]⟩,                     -- mul f,a10,f
  ⟨.mul, [.reg "g", .reg "a11", .reg "g"]⟩,                     -- mul g,a11,g
  ⟨.add, [.reg "pf", .reg "t", .reg "t2"]⟩,                     -- add pf,t,t2
  ⟨.add, [.reg "pg", .reg "f", .reg "g"]⟩,                      -- add pg,f,g
  ⟨.asr, [.reg "f", .reg "pf", .imm 20]⟩,                       -- asr f,pf,#20
  ⟨.asr, [.reg "g", .reg "pg", .imm 20]⟩,                       -- asr g,pg,#20
  ⟨.and, [.reg "pf", .reg "f", .imm 0xfffff]⟩,                  -- and pf,f,#0xfffff
  ⟨.orr, [.reg "pf", .reg "pf", .imm 0xfffffe0000000000]⟩,      -- orr pf,pf,#0xfffffe0000000000
  ⟨.and, [.reg "pg", .reg "g", .imm 0xfffff]⟩,                  -- and pg,g,#0xfffff
  ⟨.orr, [.reg "pg", .reg "pg", .imm 0xc000000000000000]⟩,      -- orr pg,pg,#0xc000000000000000
  ⟨.tst, [.reg "pg", .imm 1]⟩,                                  -- tst pg,#1
  ⟨.csel, [.reg "t", .reg "pf", .zero, .cond .ne]⟩,             -- csel t,pf,xzr,ne
  ⟨.ccmp, [.reg "d", .zero, .imm 8, .cond .ne]⟩,                -- ccmp d,xzr,#8,ne
  ⟨.cneg, [.reg "d", .reg "d", .cond .ge]⟩,                     -- cneg d,d,ge
  ⟨.cneg, [.reg "t", .reg "t", .cond .ge]⟩,                     -- cneg t,t,ge
  ⟨.csel, [.reg "pf", .reg "pg", .reg "pf", .cond .ge]⟩,        -- csel pf,pg,pf,ge
  ⟨.add, [.reg "pg", .reg "pg", .reg "t"]⟩,                     -- add pg,pg,t
  ⟨.add, [.reg "d", .reg "d", .imm 2]⟩,                         -- add d,d,#2
  ⟨.tst, [.reg "pg", .imm 2]⟩,                                  -- tst pg,#2
  ⟨.asr, [.reg "pg", .reg "pg", .imm 1]⟩,                       -- asr pg,pg,#1
  ⟨.csel, [.reg "t", .reg "pf", .zero, .cond .ne]⟩,             -- csel t,pf,xzr,ne
  ⟨.ccmp, [.reg "d", .zero, .imm 8, .cond .ne]⟩,                -- ccmp d,xzr,#8,ne
  ⟨.cneg, [.reg "d", .reg "d", .cond .ge]⟩,                     -- cneg d,d,ge
  ⟨.cneg, [.reg "t", .reg "t", .cond .ge]⟩,                     -- cneg t,t,ge
  ⟨.csel, [.reg "pf", .reg "pg", .reg "pf", .cond .ge]⟩,        -- csel pf,pg,pf,ge
  ⟨.add, [.reg "pg", .reg "pg", .reg "t"]⟩,                     -- add pg,pg,t
  ⟨.add, [.reg "d", .reg "d", .imm 2]⟩,                         -- add d,d,#2
  ⟨.tst, [.reg "pg", .imm 2]⟩,                                  -- tst pg,#2
  ⟨.asr, [.reg "pg", .reg "pg", .imm 1]⟩,                       -- asr pg,pg,#1
  ⟨.csel, [.reg "t", .reg "pf", .zero, .cond .ne]⟩,             -- csel t,pf,xzr,ne
  ⟨.ccmp, [.reg "d", .zero, .imm 8, .cond .ne]⟩,                -- ccmp d,xzr,#8,ne
  ⟨.cneg, [.reg "d", .reg "d", .cond .ge]⟩,                     -- cneg d,d,ge
  ⟨.cneg, [.reg "t", .reg "t", .cond .ge]⟩,                     -- cneg t,t,ge
  ⟨.csel, [.reg "pf", .reg "pg", .reg "pf", .cond .ge]⟩,        -- csel pf,pg,pf,ge
  ⟨.add, [.reg "pg", .reg "pg", .reg "t"]⟩,                     -- add pg,pg,t
  ⟨.add, [.reg "d", .reg "d", .imm 2]⟩,                         -- add d,d,#2
  ⟨.tst, [.reg "pg", .imm 2]⟩,                                  -- tst pg,#2
  ⟨.asr, [.reg "pg", .reg "pg", .imm 1]⟩,                       -- asr pg,pg,#1
  ⟨.csel, [.reg "t", .reg "pf", .zero, .cond .ne]⟩,             -- csel t,pf,xzr,ne
  ⟨.ccmp, [.reg "d", .zero, .imm 8, .cond .ne]⟩,                -- ccmp d,xzr,#8,ne
  ⟨.cneg, [.reg "d", .reg "d", .cond .ge]⟩,                     -- cneg d,d,ge
  ⟨.cneg, [.reg "t", .reg "t", .cond .ge]⟩,                     -- cneg t,t,ge
  ⟨.csel, [.reg "pf", .reg "pg", .reg "pf", .cond .ge]⟩,        -- csel pf,pg,pf,ge
  ⟨.add, [.reg "pg", .reg "pg", .reg "t"]⟩,                     -- add pg,pg,t
  ⟨.add, [.reg "d", .reg "d", .imm 2]⟩,                         -- add d,d,#2
  ⟨.tst, [.reg "pg", .imm 2]⟩,                                  -- tst pg,#2
  ⟨.asr, [.reg "pg", .reg "pg", .imm 1]⟩,                       -- asr pg,pg,#1
  ⟨.csel, [.reg "t", .reg "pf", .zero, .cond .ne]⟩,             -- csel t,pf,xzr,ne
  ⟨.ccmp, [.reg "d", .zero, .imm 8, .cond .ne]⟩,                -- ccmp d,xzr,#8,ne
  ⟨.cneg, [.reg "d", .reg "d", .cond .ge]⟩,                     -- cneg d,d,ge
  ⟨.cneg, [.reg "t", .reg "t", .cond .ge]⟩,                     -- cneg t,t,ge
  ⟨.csel, [.reg "pf", .reg "pg", .reg "pf", .cond .ge]⟩,        -- csel pf,pg,pf,ge
  ⟨.add, [.reg "pg", .reg "pg", .reg "t"]⟩,                     -- add pg,pg,t
  ⟨.add, [.reg "d", .reg "d", .imm 2]⟩,                         -- add d,d,#2
  ⟨.tst, [.reg "pg", .imm 2]⟩,                                  -- tst pg,#2
  ⟨.asr, [.reg "pg", .reg "pg", .imm 1]⟩,                       -- asr pg,pg,#1
  ⟨.csel, [.reg "t", .reg "pf", .zero, .cond .ne]⟩,             -- csel t,pf,xzr,ne
  ⟨.ccmp, [.reg "d", .zero, .imm 8, .cond .ne]⟩,                -- ccmp d,xzr,#8,ne
  ⟨.cneg, [.reg "d", .reg "d", .cond .ge]⟩,                     -- cneg d,d,ge
  ⟨.cneg, [.reg "t", .reg "t", .cond .ge]⟩,                     -- cneg t,t,ge
  ⟨.csel, [.reg "pf", .reg "pg", .reg "pf", .cond .ge]⟩,        -- csel pf,pg,pf,ge
  ⟨.add, [.reg "pg", .reg "pg", .reg "t"]⟩,                     -- add pg,pg,t
  ⟨.add, [.reg "d", .reg "d", .imm 2]⟩,                         -- add d,d,#2
  ⟨.tst, [.reg "pg", .imm 2]⟩,                                  -- tst pg,#2
  ⟨.asr, [.reg "pg", .reg "pg", .imm 1]⟩,                       -- asr pg,pg,#1
  ⟨.csel, [.reg "t", .reg "pf", .zero, .cond .ne]⟩,             -- csel t,pf,xzr,ne
  ⟨.ccmp, [.reg "d", .zero, .imm 8, .cond .ne]⟩,                -- ccmp d,xzr,#8,ne
  ⟨.cneg, [.reg "d", .reg "d", .cond .ge]⟩,                     -- cneg d,d,ge
  ⟨.cneg, [.reg "t", .reg "t", .cond .ge]⟩,                     -- cneg t,t,ge
  ⟨.csel, [.reg "pf", .reg "pg", .reg "pf", .cond .ge]⟩,        -- csel pf,pg,pf,ge
  ⟨.add, [.reg "pg", .reg "pg", .reg "t"]⟩,                     -- add pg,pg,t
  ⟨.add, [.reg "d", .reg "d", .imm 2]⟩,                         -- add d,d,#2
  ⟨.tst, [.reg "pg", .imm 2]⟩,                                  -- tst pg,#2
  ⟨.asr, [.reg "pg", .reg "pg", .imm 1]⟩,                       -- asr pg,pg,#1
  ⟨.csel, [.reg "t", .reg "pf", .zero, .cond .ne]⟩,             -- csel t,pf,xzr,ne
  ⟨.ccmp, [.reg "d", .zero, .imm 8, .cond .ne]⟩,                -- ccmp d,xzr,#8,ne
  ⟨.cneg, [.reg "d", .reg "d", .cond .ge]⟩,                     -- cneg d,d,ge
  ⟨.cneg, [.reg "t", .reg "t", .cond .ge]⟩,                     -- cneg t,t,ge
  ⟨.csel, [.reg "pf", .reg "pg", .reg "pf", .cond .ge]⟩,        -- csel pf,pg,pf,ge
  ⟨.add, [.reg "pg", .reg "pg", .reg "t"]⟩,                     -- add pg,pg,t
  ⟨.add, [.reg "d", .reg "d", .imm 2]⟩,                         -- add d,d,#2
  ⟨.tst, [.reg "pg", .imm 2]⟩,                                  -- tst pg,#2
  ⟨.asr, [.reg "pg", .reg "pg", .imm 1]⟩,                       -- asr pg,pg,#1
  ⟨.csel, [.reg "t", .reg "pf", .zero, .cond .ne]⟩,             -- csel t,pf,xzr,ne
  ⟨.ccmp, [.reg "d", .zero, .imm 8, .cond .ne]⟩,                -- ccmp d,xzr,#8,ne
  ⟨.cneg, [.reg "d", .reg "d", .cond .ge]⟩,                     -- cneg d,d,ge
  ⟨.cneg, [.reg "t", .reg "t", .cond .ge]⟩,                     -- cneg t,t,ge
  ⟨.csel, [.reg "pf", .reg "pg", .reg "pf", .cond .ge]⟩,        -- csel pf,pg,pf,ge
  ⟨.add, [.reg "pg", .reg "pg", .reg "t"]⟩,                     -- add pg,pg,t
  ⟨.add, [.reg "d", .reg "d", .imm 2]⟩,                         -- add d,d,#2
  ⟨.tst, [.reg "pg", .imm 2]⟩,                                  -- tst pg,#2
  ⟨.asr, [.reg "pg", .reg "pg", .imm 1]⟩,                       -- asr pg,pg,#1
  ⟨.csel, [.reg "t", .reg "pf", .zero, .cond .ne]⟩,             -- csel t,pf,xzr,ne
  ⟨.ccmp, [.reg "d", .zero, .imm 8, .cond .ne]⟩,                -- ccmp d,xzr,#8,ne
  ⟨.cneg, [.reg "d", .reg "d", .cond .ge]⟩,                     -- cneg d,d,ge
  ⟨.cneg, [.reg "t", .reg "t", .cond .ge]⟩,                     -- cneg t,t,ge
  ⟨.csel, [.reg "pf", .reg "pg", .reg "pf", .cond .ge]⟩,        -- csel pf,pg,pf,ge
  ⟨.add, [.reg "pg", .reg "pg", .reg "t"]⟩,                     -- add pg,pg,t
  ⟨.add, [.reg "d", .reg "d", .imm 2]⟩,                         -- add d,d,#2
  ⟨.tst, [.reg "pg", .imm 2]⟩,                                  -- tst pg,#2
  ⟨.asr, [.reg "pg", .reg "pg", .imm 1]⟩,                       -- asr pg,pg,#1
  ⟨.csel, [.reg "t", .reg "pf", .zero, .cond .ne]⟩,             -- csel t,pf,xzr,ne
  ⟨.ccmp, [.reg "d", .zero, .imm 8, .cond .ne]⟩,                -- ccmp d,xzr,#8,ne
  ⟨.cneg, [.reg "d", .reg "d", .cond .ge]⟩,                     -- cneg d,d,ge
  ⟨.cneg, [.reg "t", .reg "t", .cond .ge]⟩,                     -- cneg t,t,ge
  ⟨.csel, [.reg "pf", .reg "pg", .reg "pf", .cond .ge]⟩,        -- csel pf,pg,pf,ge
  ⟨.add, [.reg "pg", .reg "pg", .reg "t"]⟩,                     -- add pg,pg,t
  ⟨.add, [.reg "d", .reg "d", .imm 2]⟩,                         -- add d,d,#2
  ⟨.tst, [.reg "pg", .imm 2]⟩,                                  -- tst pg,#2
  ⟨.asr, [.reg "pg", .reg "pg", .imm 1]⟩,                       -- asr pg,pg,#1
  ⟨.csel, [.reg "t", .reg "pf", .zero, .cond .ne]⟩,             -- csel t,pf,xzr,ne
  ⟨.ccmp, [.reg "d", .zero, .imm 8, .cond .ne]⟩,                -- ccmp d,xzr,#8,ne
  ⟨.cneg, [.reg "d", .reg "d", .cond .ge]⟩,                     -- cneg d,d,ge
  ⟨.cneg, [.reg "t", .reg "t", .cond .ge]⟩,                     -- cneg t,t,ge
  ⟨.csel, [.reg "pf", .reg "pg", .reg "pf", .cond .ge]⟩,        -- csel pf,pg,pf,ge
  ⟨.add, [.reg "pg", .reg "pg", .reg "t"]⟩,                     -- add pg,pg,t
  ⟨.add, [.reg "d", .reg "d", .imm 2]⟩,                         -- add d,d,#2
  ⟨.tst, [.reg "pg", .imm 2]⟩,                                  -- tst pg,#2
  ⟨.asr, [.reg "pg", .reg "pg", .imm 1]⟩,                       -- asr pg,pg,#1
  ⟨.csel, [.reg "t", .reg "pf", .zero, .cond .ne]⟩,             -- csel t,pf,xzr,ne
  ⟨.ccmp, [.reg "d", .zero, .imm 8, .cond .ne]⟩,                -- ccmp d,xzr,#8,ne
  ⟨.cneg, [.reg "d", .reg "d", .cond .ge]⟩,                     -- cneg d,d,ge
  ⟨.cneg, [.reg "t", .reg "t", .cond .ge]⟩,                     -- cneg t,t,ge
  ⟨.csel, [.reg "pf", .reg "pg", .reg "pf", .cond .ge]⟩,        -- csel pf,pg,pf,ge
  ⟨.add, [.reg "pg", .reg "pg", .reg "t"]⟩,                     -- add pg,pg,t
  ⟨.add, [.reg "d", .reg "d", .imm 2]⟩,                         -- add d,d,#2
  ⟨.tst, [.reg "pg", .imm 2]⟩,                                  -- tst pg,#2
  ⟨.asr, [.reg "pg", .reg "pg", .imm 1]⟩,                       -- asr pg,pg,#1
  ⟨.csel, [.reg "t", .reg "pf", .zero, .cond .ne]⟩,             -- csel t,pf,xzr,ne
  ⟨.ccmp, [.reg "d", .zero, .imm 8, .cond .ne]⟩,                -- ccmp d,xzr,#8,ne
  ⟨.cneg, [.reg "d", .reg "d", .cond .ge]⟩,                     -- cneg d,d,ge
  ⟨.cneg, [.reg "t", .reg "t", .cond .ge]⟩,                     -- cneg t,t,ge
  ⟨.csel, [.reg "pf", .reg "pg", .reg "pf", .cond .ge]⟩,        -- csel pf,pg,pf,ge
  ⟨.add, [.reg "pg", .reg "pg", .reg "t"]⟩,                     -- add pg,pg,t
  ⟨.add, [.reg "d", .reg "d", .imm 2]⟩,                         -- add d,d,#2
  ⟨.tst, [.reg "pg", .imm 2]⟩,                                  -- tst pg,#2
  ⟨.asr, [.reg "pg", .reg "pg", .imm 1]⟩,                       -- asr pg,pg,#1
  ⟨.csel, [.reg "t", .reg "pf", .zero, .cond .ne]⟩,             -- csel t,pf,xzr,ne
  ⟨.ccmp, [.reg "d", .zero, .imm 8, .cond .ne]⟩,                -- ccmp d,xzr,#8,ne
  ⟨.cneg, [.reg "d", .reg "d", .cond .ge]⟩,                     -- cneg d,d,ge
  ⟨.cneg, [.reg "t", .reg "t", .cond .ge]⟩,                     -- cneg t,t,ge
  ⟨.csel, [.reg "pf", .reg "pg", .reg "pf", .cond .ge]⟩,        -- csel pf,pg,pf,ge
  ⟨.add, [.reg "pg", .reg "pg", .reg "t"]⟩,                     -- add pg,pg,t
  ⟨.add, [.reg "d", .reg "d", .imm 2]⟩,                         -- add d,d,#2
  ⟨.tst, [.reg "pg", .imm 2]⟩,                                  -- tst pg,#2
  ⟨.asr, [.reg "pg", .reg "pg", .imm 1]⟩,                       -- asr pg,pg,#1
  ⟨.csel, [.reg "t", .reg "pf", .zero, .cond .ne]⟩,             -- csel t,pf,xzr,ne
  ⟨.ccmp, [.reg "d", .zero, .imm 8, .cond .ne]⟩,                -- ccmp d,xzr,#8,ne
  ⟨.cneg, [.reg "d", .reg "d", .cond .ge]⟩,                     -- cneg d,d,ge
  ⟨.cneg, [.reg "t", .reg "t", .cond .ge]⟩,                     -- cneg t,t,ge
  ⟨.csel, [.reg "pf", .reg "pg", .reg "pf", .cond .ge]⟩,        -- csel pf,pg,pf,ge
  ⟨.add, [.reg "pg", .reg "pg", .reg "t"]⟩,                     -- add pg,pg,t
  ⟨.add, [.reg "d", .reg "d", .imm 2]⟩,                         -- add d,d,#2
  ⟨.tst, [.reg "pg", .imm 2]⟩,                                  -- tst pg,#2
  ⟨.asr, [.reg "pg", .reg "pg", .imm 1]⟩,                       -- asr pg,pg,#1
  ⟨.csel, [.reg "t", .reg "pf", .zero, .cond .ne]⟩,             -- csel t,pf,xzr,ne
  ⟨.ccmp, [.reg "d", .zero, .imm 8, .cond .ne]⟩,                -- ccmp d,xzr,#8,ne
  ⟨.cneg, [.reg "d", .reg "d", .cond .ge]⟩,                     -- cneg d,d,ge
  ⟨.cneg, [.reg "t", .reg "t", .cond .ge]⟩,                     -- cneg t,t,ge
  ⟨.csel, [.reg "pf", .reg "pg", .reg "pf", .cond .ge]⟩,        -- csel pf,pg,pf,ge
  ⟨.add, [.reg "pg", .reg "pg", .reg "t"]⟩,                     -- add pg,pg,t
  ⟨.add, [.reg "d", .reg "d", .imm 2]⟩,                         -- add d,d,#2
  ⟨.tst, [.reg "pg", .imm 2]⟩,                                  -- tst pg,#2
  ⟨.asr, [.reg "pg", .reg "pg", .imm 1]⟩,                       -- asr pg,pg,#1
  ⟨.csel, [.reg "t", .reg "pf", .zero, .cond .ne]⟩,             -- csel t,pf,xzr,ne
  ⟨.ccmp, [.reg "d", .zero, .imm 8, .cond .ne]⟩,                -- ccmp d,xzr,#8,ne
  ⟨.cneg, [.reg "d", .reg "d", .cond .ge]⟩,                     -- cneg d,d,ge
  ⟨.cneg, [.reg "t", .reg "t", .cond .ge]⟩,                     -- cneg t,t,ge
  ⟨.csel, [.reg "pf", .reg "pg", .reg "pf", .cond .ge]⟩,        -- csel pf,pg,pf,ge
  ⟨.add, [.reg "pg", .reg "pg", .reg "t"]⟩,                     -- add pg,pg,t
  ⟨.add, [.reg "d", .reg "d", .imm 2]⟩,                         -- add d,d,#2
  ⟨.tst, [.reg "pg", .imm 2]⟩,                                  -- tst pg,#2
  ⟨.asr, [.reg "pg", .reg "pg", .imm 1]⟩,                       -- asr pg,pg,#1
  ⟨.csel, [.reg "t", .reg "pf", .zero, .cond .ne]⟩,             -- csel t,pf,xzr,ne
  ⟨.ccmp, [.reg "d", .zero, .imm 8, .cond .ne]⟩,                -- ccmp d,xzr,#8,ne
  ⟨.cneg, [.reg "d", .reg "d", .cond .ge]⟩,                     -- cneg d,d,ge
  ⟨.cneg, [.reg "t", .reg "t", .cond .ge]⟩,                     -- cneg t,t,ge
  ⟨.csel, [.reg "pf", .reg "pg", .reg "pf", .cond .ge]⟩,        -- csel pf,pg,pf,ge
  ⟨.add, [.reg "pg", .reg "pg", .reg "t"]⟩,                     -- add pg,pg,t
  ⟨.add, [.reg "d", .reg "d", .imm 2]⟩,                         -- add d,d,#2
  ⟨.tst, [.reg "pg", .imm 2]⟩,                                  -- tst pg,#2
  ⟨.asr, [.reg "pg", .reg "pg", .imm 1]⟩,                       -- asr pg,pg,#1
  ⟨.csel, [.reg "t", .reg "pf", .zero, .cond .ne]⟩,             -- csel t,pf,xzr,ne
  ⟨.ccmp, [.reg "d", .zero, .imm 8, .cond .ne]⟩,                -- ccmp d,xzr,#8,ne
  ⟨.cneg, [.reg "d", .reg "d", .cond .ge]⟩,                     -- cneg d,d,ge
  ⟨.cneg, [.reg "t", .reg "t", .cond .ge]⟩,                     -- cneg t,t,ge
  ⟨.csel, [.reg "pf", .reg "pg", .reg "pf", .cond .ge]⟩,        -- csel pf,pg,pf,ge
  ⟨.add, [.reg "pg", .reg "pg", .reg "t"]⟩,                     -- add pg,pg,t
  ⟨.add, [.reg "d", .reg "d", .imm 2]⟩,                         -- add d,d,#2
  ⟨.asr, [.reg "pg", .reg "pg", .imm 1]⟩,                       -- asr pg,pg,#1
  ⟨.add, [.reg "b00", .reg "pf", .imm 0x100, .lsl 12]⟩,         -- add b00,pf,#0x100,lsl #12
  ⟨.sbfx, [.reg "b00", .reg "b00", .imm 21, .imm 21]⟩,          -- sbfx b00,b00,#21,#21
  ⟨.mov, [.reg "b11", .imm 0x100000]⟩,                          -- mov b11,#0x100000
  ⟨.add, [.reg "b11", .reg "b11", .reg "b11", .lsl 21]⟩,        -- add b11,b11,b11,lsl #21
  ⟨.add, [.reg "b01", .reg "pf", .reg "b11"]⟩,                  -- add b01,pf,b11
  ⟨.asr, [.reg "b01", .reg "b01", .imm 42]⟩,                    -- asr b01,b01,#42
  ⟨.add, [.reg "b10", .reg "pg", .imm 0x100, .lsl 12]⟩,         -- add b10,pg,#0x100,lsl #12
  ⟨.sbfx, [.reg "b10", .reg "b10", .imm 21, .imm 21]⟩,          -- sbfx b10,b10,#21,#21
  ⟨.add, [.reg "b11", .reg "pg", .reg "b11"]⟩,                  -- add b11,pg,b11
  ⟨.asr, [.reg "b11", .reg "b11", .imm 42]⟩,                    -- asr b11,b11,#42
  ⟨.mul, [.reg "t", .reg "b00", .reg "f"]⟩,                     -- mul t,b00,f
  ⟨.mul, [.reg "t2", .reg "b01", .reg "g"]⟩,                    -- mul t2,b01,g
  ⟨.mul, [.reg "f", .reg "b10", .reg "f"]⟩,                     -- mul f,b10,f
  ⟨.mul, [.reg "g", .reg "b11", .reg "g"]⟩,                     -- mul g,b11,g
  ⟨.add, [.reg "pf", .reg "t", .reg "t2"]⟩,                     -- add pf,t,t2
  ⟨.add, [.reg "pg", .reg "f", .reg "g"]⟩,                      -- add pg,f,g
  ⟨.asr, [.reg "f", .reg "pf", .imm 20]⟩,                       -- asr f,pf,#20
  ⟨.asr, [.reg "g", .reg "pg", .imm 20]⟩,                       -- asr g,pg,#20
  ⟨.and, [.reg "pf", .reg "f", .imm 0xfffff]⟩,                  -- and pf,f,#0xfffff
  ⟨.orr, [.reg "pf", .reg "pf", .imm 0xfffffe0000000000]⟩,      -- orr pf,pf,#0xfffffe0000000000
  ⟨.and, [.reg "pg", .reg "g", .imm 0xfffff]⟩,                  -- and pg,g,#0xfffff
  ⟨.orr, [.reg "pg", .reg "pg", .imm 0xc000000000000000]⟩,      -- orr pg,pg,#0xc000000000000000
  ⟨.tst, [.reg "pg", .imm 1]⟩,                                  -- tst pg,#1
  ⟨.csel, [.reg "t", .reg "pf", .zero, .cond .ne]⟩,             -- csel t,pf,xzr,ne
  ⟨.ccmp, [.reg "d", .zero, .imm 8, .cond .ne]⟩,                -- ccmp d,xzr,#8,ne
  ⟨.cneg, [.reg "d", .reg "d", .cond .ge]⟩,                     -- cneg d,d,ge
  ⟨.cneg, [.reg "t", .reg "t", .cond .ge]⟩,                     -- cneg t,t,ge
  ⟨.csel, [.reg "pf", .reg "pg", .reg "pf", .cond .ge]⟩,        -- csel pf,pg,pf,ge
  ⟨.add, [.reg "pg", .reg "pg", .reg "t"]⟩,                     -- add pg,pg,t
  ⟨.add, [.reg "d", .reg "d", .imm 2]⟩,                         -- add d,d,#2
  ⟨.tst, [.reg "pg", .imm 2]⟩,                                  -- tst pg,#2
  ⟨.asr, [.reg "pg", .reg "pg", .imm 1]⟩,                       -- asr pg,pg,#1
  ⟨.csel, [.reg "t", .reg "pf", .zero, .cond .ne]⟩,             -- csel t,pf,xzr,ne
  ⟨.ccmp, [.reg "d", .zero, .imm 8, .cond .ne]⟩,                -- ccmp d,xzr,#8,ne
  ⟨.cneg, [.reg "d", .reg "d", .cond .ge]⟩,                     -- cneg d,d,ge
  ⟨.cneg, [.reg "t", .reg "t", .cond .ge]⟩,                     -- cneg t,t,ge
  ⟨.csel, [.reg "pf", .reg "pg", .reg "pf", .cond .ge]⟩,        -- csel pf,pg,pf,ge
  ⟨.add, [.reg "pg", .reg "pg", .reg "t"]⟩,                     -- add pg,pg,t
  ⟨.add, [.reg "d", .reg "d", .imm 2]⟩,                         -- add d,d,#2
  ⟨.tst, [.reg "pg", .imm 2]⟩,                                  -- tst pg,#2
  ⟨.asr, [.reg "pg", .reg "pg", .imm 1]⟩,                       -- asr pg,pg,#1
  ⟨.csel, [.reg "t", .reg "pf", .zero, .cond .ne]⟩,             -- csel t,pf,xzr,ne
  ⟨.ccmp, [.reg "d", .zero, .imm 8, .cond .ne]⟩,                -- ccmp d,xzr,#8,ne
  ⟨.cneg, [.reg "d", .reg "d", .cond .ge]⟩,                     -- cneg d,d,ge
  ⟨.cneg, [.reg "t", .reg "t", .cond .ge]⟩,                     -- cneg t,t,ge
  ⟨.csel, [.reg "pf", .reg "pg", .reg "pf", .cond .ge]⟩,        -- csel pf,pg,pf,ge
  ⟨.add, [.reg "pg", .reg "pg", .reg "t"]⟩,                     -- add pg,pg,t
  ⟨.add, [.reg "d", .reg "d", .imm 2]⟩,                         -- add d,d,#2
  ⟨.tst, [.reg "pg", .imm 2]⟩,                                  -- tst pg,#2
  ⟨.asr, [.reg "pg", .reg "pg", .imm 1]⟩,                       -- asr pg,pg,#1
  ⟨.csel, [.reg "t", .reg "pf", .zero, .cond .ne]⟩,             -- csel t,pf,xzr,ne
  ⟨.ccmp, [.reg "d", .zero, .imm 8, .cond .ne]⟩,                -- ccmp d,xzr,#8,ne
  ⟨.cneg, [.reg "d", .reg "d", .cond .ge]⟩,                     -- cneg d,d,ge
  ⟨.cneg, [.reg "t", .reg "t", .cond .ge]⟩,                     -- cneg t,t,ge
  ⟨.csel, [.reg "pf", .reg "pg", .reg "pf", .cond .ge]⟩,        -- csel pf,pg,pf,ge
  ⟨.add, [.reg "pg", .reg "pg", .reg "t"]⟩,                     -- add pg,pg,t
  ⟨.add, [.reg "d", .reg "d", .imm 2]⟩,                         -- add d,d,#2
  ⟨.tst, [.reg "pg", .imm 2]⟩,                                  -- tst pg,#2
  ⟨.asr, [.reg "pg", .reg "pg", .imm 1]⟩,                       -- asr pg,pg,#1
  ⟨.csel, [.reg "t", .reg "pf", .zero, .cond .ne]⟩,             -- csel t,pf,xzr,ne
  ⟨.ccmp, [.reg "d", .zero, .imm 8, .cond .ne]⟩,                -- ccmp d,xzr,#8,ne
  ⟨.cneg, [.reg "d", .reg "d", .cond .ge]⟩,                     -- cneg d,d,ge
  ⟨.cneg, [.reg "t", .reg "t", .cond .ge]⟩,                     -- cneg t,t,ge
  ⟨.csel, [.reg "pf", .reg "pg", .reg "pf", .cond .ge]⟩,        -- csel pf,pg,pf,ge
  ⟨.add, [.reg "pg", .reg "pg", .reg "t"]⟩,                     -- add pg,pg,t
  ⟨.add, [.reg "d", .reg "d", .imm 2]⟩,                         -- add d,d,#2
  ⟨.tst, [.reg "pg", .imm 2]⟩,                                  -- tst pg,#2
  ⟨.asr, [.reg "pg", .reg "pg", .imm 1]⟩,                       -- asr pg,pg,#1
  ⟨.csel, [.reg "t", .reg "pf", .zero, .cond .ne]⟩,             -- csel t,pf,xzr,ne
  ⟨.ccmp, [.reg "d", .zero, .imm 8, .cond .ne]⟩,                -- ccmp d,xzr,#8,ne
  ⟨.cneg, [.reg "d", .reg "d", .cond .ge]⟩,                     -- cneg d,d,ge
  ⟨.cneg, [.reg "t", .reg "t", .cond .ge]⟩,                     -- cneg t,t,ge
  ⟨.csel, [.reg "pf", .reg "pg", .reg "pf", .cond .ge]⟩,        -- csel pf,pg,pf,ge
  ⟨.add, [.reg "pg", .reg "pg", .reg "t"]⟩,                     -- add pg,pg,t
  ⟨.add, [.reg "d", .reg "d", .imm 2]⟩,                         -- add d,d,#2
  ⟨.tst, [.reg "pg", .imm 2]⟩,                                  -- tst pg,#2
  ⟨.asr, [.reg "pg", .reg "pg", .imm 1]⟩,                       -- asr pg,pg,#1
  ⟨.csel, [.reg "t", .reg "pf", .zero, .cond .ne]⟩,             -- csel t,pf,xzr,ne
  ⟨.ccmp, [.reg "d", .zero, .imm 8, .cond .ne]⟩,                -- ccmp d,xzr,#8,ne
  ⟨.cneg, [.reg "d", .reg "d", .cond .ge]⟩,                     -- cneg d,d,ge
  ⟨.cneg, [.reg "t", .reg "t", .cond .ge]⟩,                     -- cneg t,t,ge
  ⟨.csel, [.reg "pf", .reg "pg", .reg "pf", .cond .ge]⟩,        -- csel pf,pg,pf,ge
  ⟨.add, [.reg "pg", .reg "pg", .reg "t"]⟩,                     -- add pg,pg,t
  ⟨.add, [.reg "d", .reg "d", .imm 2]⟩,                         -- add d,d,#2
  ⟨.tst, [.reg "pg", .imm 2]⟩,                                  -- tst pg,#2
  ⟨.asr, [.reg "pg", .reg "pg", .imm 1]⟩,                       -- asr pg,pg,#1
  ⟨.csel, [.reg "t", .reg "pf", .zero, .cond .ne]⟩,             -- csel t,pf,xzr,ne
  ⟨.ccmp, [.reg "d", .zero, .imm 8, .cond .ne]⟩,                -- ccmp d,xzr,#8,ne
  ⟨.cneg, [.reg "d", .reg "d", .cond .ge]⟩,                     -- cneg d,d,ge
  ⟨.cneg, [.reg "t", .reg "t", .cond .ge]⟩,                     -- cneg t,t,ge
  ⟨.csel, [.reg "pf", .reg "pg", .reg "pf", .cond .ge]⟩,        -- csel pf,pg,pf,ge
  ⟨.add, [.reg "pg", .reg "pg", .reg "t"]⟩,                     -- add pg,pg,t
  ⟨.add, [.reg "d", .reg "d", .imm 2]⟩,                         -- add d,d,#2
  ⟨.tst, [.reg "pg", .imm 2]⟩,                                  -- tst pg,#2
  ⟨.asr, [.reg "pg", .reg "pg", .imm 1]⟩,                       -- asr pg,pg,#1
  ⟨.csel, [.reg "t", .reg "pf", .zero, .cond .ne]⟩,             -- csel t,pf,xzr,ne
  ⟨.ccmp, [.reg "d", .zero, .imm 8, .cond .ne]⟩,                -- ccmp d,xzr,#8,ne
  ⟨.cneg, [.reg "d", .reg "d", .cond .ge]⟩,                     -- cneg d,d,ge
  ⟨.cneg, [.reg "t", .reg "t", .cond .ge]⟩,                     -- cneg t,t,ge
  ⟨.csel, [.reg "pf", .reg "pg", .reg "pf", .cond .ge]⟩,        -- csel pf,pg,pf,ge
  ⟨.add, [.reg "pg", .reg "pg", .reg "t"]⟩,                     -- add pg,pg,t
  ⟨.add, [.reg "d", .reg "d", .imm 2]⟩,                         -- add d,d,#2
  ⟨.tst, [.reg "pg", .imm 2]⟩,                                  -- tst pg,#2
  ⟨.asr, [.reg "pg", .reg "pg", .imm 1]⟩,                       -- asr pg,pg,#1
  ⟨.csel, [.reg "t", .reg "pf", .zero, .cond .ne]⟩,             -- csel t,pf,xzr,ne
  ⟨.ccmp, [.reg "d", .zero, .imm 8, .cond .ne]⟩,                -- ccmp d,xzr,#8,ne
  ⟨.cneg, [.reg "d", .reg "d", .cond .ge]⟩,                     -- cneg d,d,ge
  ⟨.cneg, [.reg "t", .reg "t", .cond .ge]⟩,                     -- cneg t,t,ge
  ⟨.csel, [.reg "pf", .reg "pg", .reg "pf", .cond .ge]⟩,        -- csel pf,pg,pf,ge
  ⟨.add, [.reg "pg", .reg "pg", .reg "t"]⟩,                     -- add pg,pg,t
  ⟨.add, [.reg "d", .reg "d", .imm 2]⟩,                         -- add d,d,#2
  ⟨.tst, [.reg "pg", .imm 2]⟩,                                  -- tst pg,#2
  ⟨.asr, [.reg "pg", .reg "pg", .imm 1]⟩,                       -- asr pg,pg,#1
  ⟨.mul, [.reg "f", .reg "b00", .reg "a00"]⟩,                   -- mul f,b00,a00
  ⟨.mul, [.reg "g", .reg "b00", .reg "a01"]⟩,                   -- mul g,b00,a01
  ⟨.mul, [.reg "t", .reg "b10", .reg "a00"]⟩,                   -- mul t,b10,a00
  ⟨.mul, [.reg "t2", .reg "b10", .reg "a01"]⟩,                  -- mul t2,b10,a01
  ⟨.madd, [.reg "a00", .reg "b01", .reg "a10", .reg "f"]⟩,      -- madd a00,b01,a10,f
  ⟨.madd, [.reg "a01", .reg "b01", .reg "a11", .reg "g"]⟩,      -- madd a01,b01,a11,g
  ⟨.madd, [.reg "c10", .reg "b11", .reg "a10", .reg "t"]⟩,      -- madd c10,b11,a10,t
  ⟨.madd, [.reg "c11", .reg "b11", .reg "a11", .reg "t2"]⟩,     -- madd c11,b11,a11,t2
  ⟨.csel, [.reg "t", .reg "pf", .zero, .cond .ne]⟩,             -- csel t,pf,xzr,ne
  ⟨.ccmp, [.reg "d", .zero, .imm 8, .cond .ne]⟩,                -- ccmp d,xzr,#8,ne
  ⟨.cneg, [.reg "d", .reg "d", .cond .ge]⟩,                     -- cneg d,d,ge
  ⟨.cneg, [.reg "t", .reg "t", .cond .ge]⟩,                     -- cneg t,t,ge
  ⟨.csel, [.reg "pf", .reg "pg", .reg "pf", .cond .ge]⟩,        -- csel pf,pg,pf,ge
  ⟨.add, [.reg "pg", .reg "pg", .reg "t"]⟩,                     -- add pg,pg,t
  ⟨.add, [.reg "d", .reg "d", .imm 2]⟩,                         -- add d,d,#2
  ⟨.tst, [.reg "pg", .imm 2]⟩,                                  -- tst pg,#2
  ⟨.asr, [.reg "pg", .reg "pg", .imm 1]⟩,                       -- asr pg,pg,#1
  ⟨.csel, [.reg "t", .reg "pf", .zero, .cond .ne]⟩,             -- csel t,pf,xzr,ne
  ⟨.ccmp, [.reg "d", .zero, .imm 8, .cond .ne]⟩,                -- ccmp d,xzr,#8,ne
  ⟨.cneg, [.reg "d", .reg "d", .cond .ge]⟩,                     -- cneg d,d,ge
  ⟨.cneg, [.reg "t", .reg "t", .cond .ge]⟩,                     -- cneg t,t,ge
  ⟨.csel, [.reg "pf", .reg "pg", .reg "pf", .cond .ge]⟩,        -- csel pf,pg,pf,ge
  ⟨.add, [.reg "pg", .reg "pg", .reg "t"]⟩,                     -- add pg,pg,t
  ⟨.add, [.reg "d", .reg "d", .imm 2]⟩,                         -- add d,d,#2
  ⟨.tst, [.reg "pg", .imm 2]⟩,                                  -- tst pg,#2
  ⟨.asr, [.reg "pg", .reg "pg", .imm 1]⟩,                       -- asr pg,pg,#1
  ⟨.csel, [.reg "t", .reg "pf", .zero, .cond .ne]⟩,             -- csel t,pf,xzr,ne
  ⟨.ccmp, [.reg "d", .zero, .imm 8, .cond .ne]⟩,                -- ccmp d,xzr,#8,ne
  ⟨.cneg, [.reg "d", .reg "d", .cond .ge]⟩,                     -- cneg d,d,ge
  ⟨.cneg, [.reg "t", .reg "t", .cond .ge]⟩,                     -- cneg t,t,ge
  ⟨.csel, [.reg "pf", .reg "pg", .reg "pf", .cond .ge]⟩,        -- csel pf,pg,pf,ge
  ⟨.add, [.reg "pg", .reg "pg", .reg "t"]⟩,                     -- add pg,pg,t
  ⟨.add, [.reg "d", .reg "d", .imm 2]⟩,                         -- add d,d,#2
  ⟨.tst, [.reg "pg", .imm 2]⟩,                                  -- tst pg,#2
  ⟨.asr, [.reg "pg", .reg "pg", .imm 1]⟩,                       -- asr pg,pg,#1
  ⟨.csel, [.reg "t", .reg "pf", .zero, .cond .ne]⟩,             -- csel t,pf,xzr,ne
  ⟨.ccmp, [.reg "d", .zero, .imm 8, .cond .ne]⟩,                -- ccmp d,xzr,#8,ne
  ⟨.cneg, [.reg "d", .reg "d", .cond .ge]⟩,                     -- cneg d,d,ge
  ⟨.cneg, [.reg "t", .reg "t", .cond .ge]⟩,                     -- cneg t,t,ge
  ⟨.csel, [.reg "pf", .reg "pg", .reg "pf", .cond .ge]⟩,        -- csel pf,pg,pf,ge
  ⟨.add, [.reg "pg", .reg "pg", .reg "t"]⟩,                     -- add pg,pg,t
  ⟨.add, [.reg "d", .reg "d", .imm 2]⟩,                         -- add d,d,#2
  ⟨.tst, [.reg "pg", .imm 2]⟩,                                  -- tst pg,#2
  ⟨.asr, [.reg "pg", .reg "pg", .imm 1]⟩,                       -- asr pg,pg,#1
  ⟨.csel, [.reg "t", .reg "pf", .zero, .cond .ne]⟩,             -- csel t,pf,xzr,ne
  ⟨.ccmp, [.reg "d", .zero, .imm 8, .cond .ne]⟩,                -- ccmp d,xzr,#8,ne
  ⟨.cneg, [.reg "d", .reg "d", .cond .ge]⟩,                     -- cneg d,d,ge
  ⟨.cneg, [.reg "t", .reg "t", .cond .ge]⟩,                     -- cneg t,t,ge
  ⟨.csel, [.reg "pf", .reg "pg", .reg "pf", .cond .ge]⟩,        -- csel pf,pg,pf,ge
  ⟨.add, [.reg "pg", .reg "pg", .reg "t"]⟩,                     -- add pg,pg,t
  ⟨.add, [.reg "d", .reg "d", .imm 2]⟩,                         -- add d,d,#2
  ⟨.tst, [.reg "pg", .imm 2]⟩,                                  -- tst pg,#2
  ⟨.asr, [.reg "pg", .reg "pg", .imm 1]⟩,                       -- asr pg,pg,#1
  ⟨.csel, [.reg "t", .reg "pf", .zero, .cond .ne]⟩,             -- csel t,pf,xzr,ne
  ⟨.ccmp, [.reg "d", .zero, .imm 8, .cond .ne]⟩,                -- ccmp d,xzr,#8,ne
  ⟨.cneg, [.reg "d", .reg "d", .cond .ge]⟩,                     -- cneg d,d,ge
  ⟨.cneg, [.reg "t", .reg "t", .cond .ge]⟩,                     -- cneg t,t,ge
  ⟨.csel, [.reg "pf", .reg "pg", .reg "pf", .cond .ge]⟩,        -- csel pf,pg,pf,ge
  ⟨.add, [.reg "pg", .reg "pg", .reg "t"]⟩,                     -- add pg,pg,t
  ⟨.add, [.reg "d", .reg "d", .imm 2]⟩,                         -- add d,d,#2
  ⟨.tst, [.reg "pg", .imm 2]⟩,                                  -- tst pg,#2
  ⟨.asr, [.reg "pg", .reg "pg", .imm 1]⟩,                       -- asr pg,pg,#1
  ⟨.csel, [.reg "t", .reg "pf", .zero, .cond .ne]⟩,             -- csel t,pf,xzr,ne
  ⟨.ccmp, [.reg "d", .zero, .imm 8, .cond .ne]⟩,                -- ccmp d,xzr,#8,ne
  ⟨.cneg, [.reg "d", .reg "d", .cond .ge]⟩,                     -- cneg d,d,ge
  ⟨.cneg, [.reg "t", .reg "t", .cond .ge]⟩,                     -- cneg t,t,ge
  ⟨.csel, [.reg "pf", .reg "pg", .reg "pf", .cond .ge]⟩,        -- csel pf,pg,pf,ge
  ⟨.add, [.reg "pg", .reg "pg", .reg "t"]⟩,                     -- add pg,pg,t
  ⟨.add, [.reg "d", .reg "d", .imm 2]⟩,                         -- add d,d,#2
  ⟨.tst, [.reg "pg", .imm 2]⟩,                                  -- tst pg,#2
  ⟨.asr, [.reg "pg", .reg "pg", .imm 1]⟩,                       -- asr pg,pg,#1
  ⟨.csel, [.reg "t", .reg "pf", .zero, .cond .ne]⟩,             -- csel t,pf,xzr,ne
  ⟨.ccmp, [.reg "d", .zero, .imm 8, .cond .ne]⟩,                -- ccmp d,xzr,#8,ne
  ⟨.cneg, [.reg "d", .reg "d", .cond .ge]⟩,                     -- cneg d,d,ge
  ⟨.cneg, [.reg "t", .reg "t", .cond .ge]⟩,                     -- cneg t,t,ge
  ⟨.csel, [.reg "pf", .reg "pg", .reg "pf", .cond .ge]⟩,        -- csel pf,pg,pf,ge
  ⟨.add, [.reg "pg", .reg "pg", .reg "t"]⟩,                     -- add pg,pg,t
  ⟨.add, [.reg "d", .reg "d", .imm 2]⟩,                         -- add d,d,#2
  ⟨.tst, [.reg "pg", .imm 2]⟩,                                  -- tst pg,#2
  ⟨.asr, [.reg "pg", .reg "pg", .imm 1]⟩,                       -- asr pg,pg,#1
  ⟨.csel, [.reg "t", .reg "pf", .zero, .cond .ne]⟩,             -- csel t,pf,xzr,ne
  ⟨.ccmp, [.reg "d", .zero, .imm 8, .cond .ne]⟩,                -- ccmp d,xzr,#8,ne
  ⟨.cneg, [.reg "d", .reg "d", .cond .ge]⟩,                     -- cneg d,d,ge
  ⟨.cneg, [.reg "t", .reg "t", .cond .ge]⟩,                     -- cneg t,t,ge
  ⟨.csel, [.reg "pf", .reg "pg", .reg "pf", .cond .ge]⟩,        -- csel pf,pg,pf,ge
  ⟨.add, [.reg "pg", .reg "pg", .reg "t"]⟩,                     -- add pg,pg,t
  ⟨.add, [.reg "d", .reg "d", .imm 2]⟩,                         -- add d,d,#2
  ⟨.asr, [.reg "pg", .reg "pg", .imm 1]⟩,                       -- asr pg,pg,#1
  ⟨.add, [.reg "b00", .reg "pf", .imm 0x100, .lsl 12]⟩,         -- add b00,pf,#0x100,lsl #12
  ⟨.sbfx, [.reg "b00", .reg "b00", .imm 22, .imm 21]⟩,          -- sbfx b00,b00,#22,#21
  ⟨.mov, [.reg "b11", .imm 0x100000]⟩,                          -- mov b11,#0x100000
  ⟨.add, [.reg "b11", .reg "b11", .reg "b11", .lsl 21]⟩,        -- add b11,b11,b11,lsl #21
  ⟨.add, [.reg "b01", .reg "pf", .reg "b11"]⟩,                  -- add b01,pf,b11
  ⟨.asr, [.reg "b01", .reg "b01", .imm 43]⟩,                    -- asr b01,b01,#43
  ⟨.add, [.reg "b10", .reg "pg", .imm 0x100, .lsl 12]⟩,         -- add b10,pg,#0x100,lsl #12
  ⟨.sbfx, [.reg "b10", .reg "b10", .imm 22, .imm 21]⟩,          -- sbfx b10,b10,#22,#21
  ⟨.add, [.reg "b11", .reg "pg", .reg "b11"]⟩,                  -- add b11,pg,b11
  ⟨.asr, [.reg "b11", .reg "b11", .imm 43]⟩,                    -- asr b11,b11,#43
  ⟨.mneg, [.reg "f", .reg "b00", .reg "a00"]⟩,                  -- mneg f,b00,a00
  ⟨.mneg, [.reg "g", .reg "b00", .reg "a01"]⟩,                  -- mneg g,b00,a01
  ⟨.mneg, [.reg "pf", .reg "b10", .reg "a00"]⟩,                 -- mneg pf,b10,a00
  ⟨.mneg, [.reg "pg", .reg "b10", .reg "a01"]⟩,                 -- mneg pg,b10,a01
  ⟨.msub, [.reg "m00", .reg "b01", .reg "c10", .reg "f"]⟩,      -- msub m00,b01,c10,f
  ⟨.msub, [.reg "m01", .reg "b01", .reg "c11", .reg "g"]⟩,      -- msub m01,b01,c11,g
  ⟨.msub, [.reg "m10", .reg "b11", .reg "c10", .reg "pf"]⟩,     -- msub m10,b11,c10,pf
  ⟨.msub, [.reg "m11", .reg "b11", .reg "c11", .reg "pg"]⟩      -- msub m11,b11,c11,pg
]

/-- The instruction stream of the inline `asm!` block of `sign_mag`, as written, its macro
invocations expanded. -/
def signMagBlockProgram : List Instr := [
  ⟨.cmp, [.reg "m00", .zero]⟩,                                  -- cmp m00,xzr
  ⟨.csetm, [.reg "s00", .cond .mi]⟩,                            -- csetm s00,mi
  ⟨.cneg, [.reg "m00", .reg "m00", .cond .mi]⟩,                 -- cneg m00,m00,mi
  ⟨.cmp, [.reg "m01", .zero]⟩,                                  -- cmp m01,xzr
  ⟨.csetm, [.reg "s01", .cond .mi]⟩,                            -- csetm s01,mi
  ⟨.cneg, [.reg "m01", .reg "m01", .cond .mi]⟩,                 -- cneg m01,m01,mi
  ⟨.cmp, [.reg "m10", .zero]⟩,                                  -- cmp m10,xzr
  ⟨.csetm, [.reg "s10", .cond .mi]⟩,                            -- csetm s10,mi
  ⟨.cneg, [.reg "m10", .reg "m10", .cond .mi]⟩,                 -- cneg m10,m10,mi
  ⟨.cmp, [.reg "m11", .zero]⟩,                                  -- cmp m11,xzr
  ⟨.csetm, [.reg "s11", .cond .mi]⟩,                            -- csetm s11,mi
  ⟨.cneg, [.reg "m11", .reg "m11", .cond .mi]⟩                  -- cneg m11,m11,mi
]

/-- The instruction stream of the inline `asm!` block of `fg_row`, as written, its macro invocations
expanded. -/
def fgRowBlockProgram : List Instr := [
  ⟨.and, [.reg "lo", .reg "m0", .reg "s0"]⟩,                    -- and lo,m0,s0
  ⟨.and, [.reg "w", .reg "m1", .reg "s1"]⟩,                     -- and w,m1,s1
  ⟨.add, [.reg "d0", .reg "lo", .reg "w"]⟩,                     -- add d0,lo,w
  ⟨.eor, [.reg "w", .reg "f0", .reg "s0"]⟩,                     -- eor w,f0,s0
  ⟨.mul, [.reg "lo", .reg "w", .reg "m0"]⟩,                     -- mul lo,w,m0
  ⟨.umulh, [.reg "w", .reg "w", .reg "m0"]⟩,                    -- umulh w,w,m0
  ⟨.adds, [.reg "d0", .reg "d0", .reg "lo"]⟩,                   -- adds d0,d0,lo
  ⟨.adc, [.reg "d1", .zero, .reg "w"]⟩,                         -- adc d1,xzr,w
  ⟨.eor, [.reg "w", .reg "g0", .reg "s1"]⟩,                     -- eor w,g0,s1
  ⟨.mul, [.reg "lo", .reg "w", .reg "m1"]⟩,                     -- mul lo,w,m1
  ⟨.umulh, [.reg "w", .reg "w", .reg "m1"]⟩,                    -- umulh w,w,m1
  ⟨.adds, [.reg "d0", .reg "d0", .reg "lo"]⟩,                   -- adds d0,d0,lo
  ⟨.adc, [.reg "d1", .reg "d1", .reg "w"]⟩,                     -- adc d1,d1,w
  ⟨.eor, [.reg "w", .reg "f1", .reg "s0"]⟩,                     -- eor w,f1,s0
  ⟨.mul, [.reg "lo", .reg "w", .reg "m0"]⟩,                     -- mul lo,w,m0
  ⟨.umulh, [.reg "w", .reg "w", .reg "m0"]⟩,                    -- umulh w,w,m0
  ⟨.adds, [.reg "d1", .reg "d1", .reg "lo"]⟩,                   -- adds d1,d1,lo
  ⟨.adc, [.reg "d2", .zero, .reg "w"]⟩,                         -- adc d2,xzr,w
  ⟨.eor, [.reg "w", .reg "g1", .reg "s1"]⟩,                     -- eor w,g1,s1
  ⟨.mul, [.reg "lo", .reg "w", .reg "m1"]⟩,                     -- mul lo,w,m1
  ⟨.umulh, [.reg "w", .reg "w", .reg "m1"]⟩,                    -- umulh w,w,m1
  ⟨.adds, [.reg "d1", .reg "d1", .reg "lo"]⟩,                   -- adds d1,d1,lo
  ⟨.adc, [.reg "d2", .reg "d2", .reg "w"]⟩,                     -- adc d2,d2,w
  ⟨.extr, [.reg "d0", .reg "d1", .reg "d0", .imm 59]⟩,          -- extr d0,d1,d0,#59
  ⟨.eor, [.reg "w", .reg "f2", .reg "s0"]⟩,                     -- eor w,f2,s0
  ⟨.mul, [.reg "lo", .reg "w", .reg "m0"]⟩,                     -- mul lo,w,m0
  ⟨.umulh, [.reg "w", .reg "w", .reg "m0"]⟩,                    -- umulh w,w,m0
  ⟨.adds, [.reg "d2", .reg "d2", .reg "lo"]⟩,                   -- adds d2,d2,lo
  ⟨.adc, [.reg "d3", .zero, .reg "w"]⟩,                         -- adc d3,xzr,w
  ⟨.eor, [.reg "w", .reg "g2", .reg "s1"]⟩,                     -- eor w,g2,s1
  ⟨.mul, [.reg "lo", .reg "w", .reg "m1"]⟩,                     -- mul lo,w,m1
  ⟨.umulh, [.reg "w", .reg "w", .reg "m1"]⟩,                    -- umulh w,w,m1
  ⟨.adds, [.reg "d2", .reg "d2", .reg "lo"]⟩,                   -- adds d2,d2,lo
  ⟨.adc, [.reg "d3", .reg "d3", .reg "w"]⟩,                     -- adc d3,d3,w
  ⟨.extr, [.reg "d1", .reg "d2", .reg "d1", .imm 59]⟩,          -- extr d1,d2,d1,#59
  ⟨.eor, [.reg "w", .reg "f3", .reg "s0"]⟩,                     -- eor w,f3,s0
  ⟨.eor, [.reg "d4", .reg "f4", .reg "s0"]⟩,                    -- eor d4,f4,s0
  ⟨.and, [.reg "d4", .reg "d4", .reg "m0"]⟩,                    -- and d4,d4,m0
  ⟨.neg, [.reg "d4", .reg "d4"]⟩,                               -- neg d4,d4
  ⟨.mul, [.reg "lo", .reg "w", .reg "m0"]⟩,                     -- mul lo,w,m0
  ⟨.umulh, [.reg "w", .reg "w", .reg "m0"]⟩,                    -- umulh w,w,m0
  ⟨.adds, [.reg "d3", .reg "d3", .reg "lo"]⟩,                   -- adds d3,d3,lo
  ⟨.adc, [.reg "d4", .reg "d4", .reg "w"]⟩,                     -- adc d4,d4,w
  ⟨.eor, [.reg "w", .reg "g3", .reg "s1"]⟩,                     -- eor w,g3,s1
  ⟨.eor, [.reg "lo", .reg "g4", .reg "s1"]⟩,                    -- eor lo,g4,s1
  ⟨.and, [.reg "lo", .reg "lo", .reg "m1"]⟩,                    -- and lo,lo,m1
  ⟨.sub, [.reg "d4", .reg "d4", .reg "lo"]⟩,                    -- sub d4,d4,lo
  ⟨.mul, [.reg "lo", .reg "w", .reg "m1"]⟩,                     -- mul lo,w,m1
  ⟨.umulh, [.reg "w", .reg "w", .reg "m1"]⟩,                    -- umulh w,w,m1
  ⟨.adds, [.reg "d3", .reg "d3", .reg "lo"]⟩,                   -- adds d3,d3,lo
  ⟨.adc, [.reg "d4", .reg "d4", .reg "w"]⟩,                     -- adc d4,d4,w
  ⟨.extr, [.reg "d2", .reg "d3", .reg "d2", .imm 59]⟩,          -- extr d2,d3,d2,#59
  ⟨.extr, [.reg "d3", .reg "d4", .reg "d3", .imm 59]⟩,          -- extr d3,d4,d3,#59
  ⟨.asr, [.reg "d4", .reg "d4", .imm 59]⟩                       -- asr d4,d4,#59
]

/-- The instruction stream of the inline `asm!` block of `uv_row`, as written, its macro invocations
expanded. -/
def uvRowBlockProgram : List Instr := [
  ⟨.and, [.reg "lo", .reg "m0", .reg "s0"]⟩,                    -- and lo,m0,s0
  ⟨.and, [.reg "w", .reg "m1", .reg "s1"]⟩,                     -- and w,m1,s1
  ⟨.add, [.reg "t0", .reg "lo", .reg "w"]⟩,                     -- add t0,lo,w
  ⟨.eor, [.reg "w", .reg "u0", .reg "s0"]⟩,                     -- eor w,u0,s0
  ⟨.mul, [.reg "lo", .reg "w", .reg "m0"]⟩,                     -- mul lo,w,m0
  ⟨.umulh, [.reg "w", .reg "w", .reg "m0"]⟩,                    -- umulh w,w,m0
  ⟨.adds, [.reg "t0", .reg "t0", .reg "lo"]⟩,                   -- adds t0,t0,lo
  ⟨.adc, [.reg "t1", .zero, .reg "w"]⟩,                         -- adc t1,xzr,w
  ⟨.eor, [.reg "w", .reg "v0", .reg "s1"]⟩,                     -- eor w,v0,s1
  ⟨.mul, [.reg "lo", .reg "w", .reg "m1"]⟩,                     -- mul lo,w,m1
  ⟨.umulh, [.reg "w", .reg "w", .reg "m1"]⟩,                    -- umulh w,w,m1
  ⟨.adds, [.reg "t0", .reg "t0", .reg "lo"]⟩,                   -- adds t0,t0,lo
  ⟨.adc, [.reg "t1", .reg "t1", .reg "w"]⟩,                     -- adc t1,t1,w
  ⟨.eor, [.reg "w", .reg "u1", .reg "s0"]⟩,                     -- eor w,u1,s0
  ⟨.mul, [.reg "lo", .reg "w", .reg "m0"]⟩,                     -- mul lo,w,m0
  ⟨.umulh, [.reg "w", .reg "w", .reg "m0"]⟩,                    -- umulh w,w,m0
  ⟨.adds, [.reg "t1", .reg "t1", .reg "lo"]⟩,                   -- adds t1,t1,lo
  ⟨.adc, [.reg "t2", .zero, .reg "w"]⟩,                         -- adc t2,xzr,w
  ⟨.eor, [.reg "w", .reg "v1", .reg "s1"]⟩,                     -- eor w,v1,s1
  ⟨.mul, [.reg "lo", .reg "w", .reg "m1"]⟩,                     -- mul lo,w,m1
  ⟨.umulh, [.reg "w", .reg "w", .reg "m1"]⟩,                    -- umulh w,w,m1
  ⟨.adds, [.reg "t1", .reg "t1", .reg "lo"]⟩,                   -- adds t1,t1,lo
  ⟨.adc, [.reg "t2", .reg "t2", .reg "w"]⟩,                     -- adc t2,t2,w
  ⟨.eor, [.reg "w", .reg "u2", .reg "s0"]⟩,                     -- eor w,u2,s0
  ⟨.mul, [.reg "lo", .reg "w", .reg "m0"]⟩,                     -- mul lo,w,m0
  ⟨.umulh, [.reg "w", .reg "w", .reg "m0"]⟩,                    -- umulh w,w,m0
  ⟨.adds, [.reg "t2", .reg "t2", .reg "lo"]⟩,                   -- adds t2,t2,lo
  ⟨.adc, [.reg "t3", .zero, .reg "w"]⟩,                         -- adc t3,xzr,w
  ⟨.eor, [.reg "w", .reg "v2", .reg "s1"]⟩,                     -- eor w,v2,s1
  ⟨.mul, [.reg "lo", .reg "w", .reg "m1"]⟩,                     -- mul lo,w,m1
  ⟨.umulh, [.reg "w", .reg "w", .reg "m1"]⟩,                    -- umulh w,w,m1
  ⟨.adds, [.reg "t2", .reg "t2", .reg "lo"]⟩,                   -- adds t2,t2,lo
  ⟨.adc, [.reg "t3", .reg "t3", .reg "w"]⟩,                     -- adc t3,t3,w
  ⟨.eor, [.reg "w", .reg "u3", .reg "s0"]⟩,                     -- eor w,u3,s0
  ⟨.and, [.reg "t4", .reg "s0", .reg "m0"]⟩,                    -- and t4,s0,m0
  ⟨.neg, [.reg "t4", .reg "t4"]⟩,                               -- neg t4,t4
  ⟨.mul, [.reg "lo", .reg "w", .reg "m0"]⟩,                     -- mul lo,w,m0
  ⟨.umulh, [.reg "w", .reg "w", .reg "m0"]⟩,                    -- umulh w,w,m0
  ⟨.adds, [.reg "t3", .reg "t3", .reg "lo"]⟩,                   -- adds t3,t3,lo
  ⟨.adc, [.reg "t4", .reg "t4", .reg "w"]⟩,                     -- adc t4,t4,w
  ⟨.eor, [.reg "w", .reg "v3", .reg "s1"]⟩,                     -- eor w,v3,s1
  ⟨.and, [.reg "lo", .reg "s1", .reg "m1"]⟩,                    -- and lo,s1,m1
  ⟨.sub, [.reg "t4", .reg "t4", .reg "lo"]⟩,                    -- sub t4,t4,lo
  ⟨.mul, [.reg "lo", .reg "w", .reg "m1"]⟩,                     -- mul lo,w,m1
  ⟨.umulh, [.reg "w", .reg "w", .reg "m1"]⟩,                    -- umulh w,w,m1
  ⟨.adds, [.reg "t3", .reg "t3", .reg "lo"]⟩,                   -- adds t3,t3,lo
  ⟨.adc, [.reg "t4", .reg "t4", .reg "w"]⟩                      -- adc t4,t4,w
]

/-- The instruction stream of the inline `asm!` block of `amontred`, as written, its macro
invocations expanded. -/
def amontredBlockProgram : List Instr := [
  ⟨.lsl, [.reg "w", .reg "p0", .imm 61]⟩,                       -- lsl w,p0,#61
  ⟨.adds, [.reg "t0", .reg "t0", .reg "w"]⟩,                    -- adds t0,t0,w
  ⟨.extr, [.reg "w", .reg "p1", .reg "p0", .imm 3]⟩,            -- extr w,p1,p0,#3
  ⟨.adcs, [.reg "t1", .reg "t1", .reg "w"]⟩,                    -- adcs t1,t1,w
  ⟨.lsr, [.reg "w", .reg "p1", .imm 3]⟩,                        -- lsr w,p1,#3
  ⟨.adcs, [.reg "t2", .reg "t2", .reg "w"]⟩,                    -- adcs t2,t2,w
  ⟨.adcs, [.reg "t3", .reg "t3", .zero]⟩,                       -- adcs t3,t3,xzr
  ⟨.mov, [.reg "w", .imm 0x800000000000000]⟩,                   -- mov w,#0x800000000000000
  ⟨.adc, [.reg "t4", .reg "t4", .reg "w"]⟩,                     -- adc t4,t4,w
  ⟨.mul, [.reg "q", .reg "t0", .reg "inv"]⟩,                    -- mul q,t0,inv
  ⟨.umulh, [.reg "hi", .reg "q", .reg "p0"]⟩,                   -- umulh hi,q,p0
  ⟨.mul, [.reg "lo", .reg "q", .reg "p1"]⟩,                     -- mul lo,q,p1
  ⟨.umulh, [.reg "w", .reg "q", .reg "p1"]⟩,                    -- umulh w,q,p1
  ⟨.lsl, [.reg "l3", .reg "q", .imm 62]⟩,                       -- lsl l3,q,#62
  ⟨.lsr, [.reg "h3", .reg "q", .imm 2]⟩,                        -- lsr h3,q,#2
  ⟨.subs, [.zero, .reg "t0", .imm 1]⟩,                          -- subs xzr,t0,#1
  ⟨.adcs, [.reg "t1", .reg "t1", .reg "hi"]⟩,                   -- adcs t1,t1,hi
  ⟨.adcs, [.reg "t2", .reg "t2", .reg "w"]⟩,                    -- adcs t2,t2,w
  ⟨.adcs, [.reg "t3", .reg "t3", .reg "l3"]⟩,                   -- adcs t3,t3,l3
  ⟨.adc, [.reg "t4", .reg "t4", .reg "h3"]⟩,                    -- adc t4,t4,h3
  ⟨.adds, [.reg "t1", .reg "t1", .reg "lo"]⟩,                   -- adds t1,t1,lo
  ⟨.adcs, [.reg "t2", .reg "t2", .zero]⟩,                       -- adcs t2,t2,xzr
  ⟨.adcs, [.reg "t3", .reg "t3", .zero]⟩,                       -- adcs t3,t3,xzr
  ⟨.adc, [.reg "t4", .reg "t4", .zero]⟩                         -- adc t4,t4,xzr
]

/-- The instruction stream of the inline `asm!` block of `cond_sub`, as written, its macro
invocations expanded. -/
def condSubBlockProgram : List Instr := [
  ⟨.mov, [.reg "q", .imm 0x4000000000000000]⟩,                  -- mov q,#0x4000000000000000
  ⟨.subs, [.reg "t0", .reg "r0", .reg "p0"]⟩,                   -- subs t0,r0,p0
  ⟨.sbcs, [.reg "t1", .reg "r1", .reg "p1"]⟩,                   -- sbcs t1,r1,p1
  ⟨.sbcs, [.reg "t2", .reg "r2", .zero]⟩,                       -- sbcs t2,r2,xzr
  ⟨.sbcs, [.reg "t3", .reg "r3", .reg "q"]⟩,                    -- sbcs t3,r3,q
  ⟨.csel, [.reg "r0", .reg "r0", .reg "t0", .cond .lo]⟩,        -- csel r0,r0,t0,lo
  ⟨.csel, [.reg "r1", .reg "r1", .reg "t1", .cond .lo]⟩,        -- csel r1,r1,t1,lo
  ⟨.csel, [.reg "r2", .reg "r2", .reg "t2", .cond .lo]⟩,        -- csel r2,r2,t2,lo
  ⟨.csel, [.reg "r3", .reg "r3", .reg "t3", .cond .lo]⟩         -- csel r3,r3,t3,lo
]

end PastaCurves.AArch64
