/-
Copyright Supranational LLC (the routines, transcribed from Semolina v0.1.4).
Copyright (c) 2026 the pasta_curves contributors (the transcription).
-/
import PastaCurves.AArch64.Semantics

/-!
# The crate's inline Pasta field blocks, transcribed

GENERATED by `lean/scripts/gen.py` from the `asm!` blocks of `mul`, `square`, `add`, `sub`,
`divstep59`, `sign_mag`, `fg_row`, `uv_row`, `amontred`, and `cond_sub` in `src/asm/aarch64.rs`; do
not edit by hand. Each definition follows its block instruction by instruction (the instruction is
the trailing comment; the two lines that unpack an instruction's (result, carry) pair are marked as
its continuation), over the semantics of `PastaCurves.AArch64.Semantics`. Registers are rebound by
the instructions that write them, `c` is the carry flag, `fl` the four flags, `s` is the (result,
carry) pair of the instruction that last set both, argument limbs are read where the block's
operands bind them, and the output words are bound where the block's output operands hold them. A
block whose template invokes a macro for a repeated step calls that step's definition once per run
of consecutive invocations, iterated over the run. Bindings that nothing reads are left as comments.
See the generator's docstring for what it checks.
-/

namespace PastaCurves.AArch64

/-- The registers that `mulMont` carries from one round to the next. -/
structure MulMontAcc where
  /-- accumulator limb 0 -/
  r0 : Nat
  /-- accumulator limb 1 -/
  r1 : Nat
  /-- accumulator limb 2 -/
  r2 : Nat
  /-- accumulator limb 3 -/
  r3 : Nat
  /-- accumulator limb 4 -/
  r4 : Nat
  /-- the round's Montgomery quotient `q` -/
  q : Nat
  /-- `low(p1 * q)`, the first term of the round's reduction -/
  t1 : Nat
  /-- `low(q * 2^62)`, the third term of the round's reduction -/
  t3 : Nat
  deriving DecidableEq, Repr

namespace MulMontAcc

/-- Every field is below `2^64`. -/
def Bounded (s : MulMontAcc) : Prop :=
   s.r0 < 2^64 ∧ s.r1 < 2^64 ∧ s.r2 < 2^64 ∧ s.r3 < 2^64 ∧ s.r4 < 2^64 ∧ s.q < 2^64 ∧ s.t1 < 2^64 ∧
      s.t3 < 2^64

/-- The accumulator's value: limbs `r0`, `r1`, `r2`, `r3`, `r4` with weights `2^0` to `2^256`. -/
def toNat (s : MulMontAcc) : Nat :=
   s.r0 + 2^64 * s.r1 + 2^128 * s.r2 + 2^192 * s.r3 + 2^256 * s.r4

end MulMontAcc

/-- One round of `mulMont`: the instructions between one `lsl t3,q,#62` and the next in each of its
3 rounds, on the round's `rhs` limb `b` and the registers `acc` carried from the previous round. -/
def mulMontRound (lhs modulus : Limbs) (inv b : Nat) (acc : MulMontAcc) : MulMontAcc :=
  let a0 := lhs.l0              -- argument
  let a1 := lhs.l1              -- argument
  let a2 := lhs.l2              -- argument
  let a3 := lhs.l3              -- argument
  let p0 := modulus.l0          -- argument
  let p1 := modulus.l1          -- argument
  let inv := inv                -- argument
  let b1 := b                   -- argument
  let r0 := acc.r0              -- argument
  let r1 := acc.r1              -- argument
  let r2 := acc.r2              -- argument
  let r3 := acc.r3              -- argument
  let r4 := acc.r4              -- argument
  let q := acc.q                -- argument
  let t1 := acc.t1              -- argument
  let t3 := acc.t3              -- argument
  let c := (subc r0 1 1).2      -- subs xzr,r0,#1
  let t0 := umulh p0 q          -- umulh t0,p0,q
  let s := addc r1 t1 c         -- adcs r1,r1,t1
  let r1 := s.1                 --   `-> r1
  let c := s.2                  --   `-> carry
  let t1 := umulh p1 q          -- umulh t1,p1,q
  let s := addc r2 0 c          -- adcs r2,r2,xzr
  let r2 := s.1                 --   `-> r2
  let c := s.2                  --   `-> carry
  let s := addc r3 t3 c         -- adcs r3,r3,t3
  let r3 := s.1                 --   `-> r3
  let c := s.2                  --   `-> carry
  let t3 := lsr q 2             -- lsr t3,q,#2
  let r4 := (addc r4 0 c).1     -- adc r4,r4,xzr
  let s := addc r1 t0 0         -- adds r0,r1,t0
  let r0 := s.1                 --   `-> r0
  let c := s.2                  --   `-> carry
  let t0 := mulLo a0 b1         -- mul t0,a0,b1
  let s := addc r2 t1 c         -- adcs r1,r2,t1
  let r1 := s.1                 --   `-> r1
  let c := s.2                  --   `-> carry
  let t1 := mulLo a1 b1         -- mul t1,a1,b1
  let s := addc r3 0 c          -- adcs r2,r3,xzr
  let r2 := s.1                 --   `-> r2
  let c := s.2                  --   `-> carry
  let t2 := mulLo a2 b1         -- mul t2,a2,b1
  let s := addc r4 t3 c         -- adcs r3,r4,t3
  let r3 := s.1                 --   `-> r3
  let c := s.2                  --   `-> carry
  let t3 := mulLo a3 b1         -- mul t3,a3,b1
  let r4 := (addc 0 0 c).1      -- adc r4,xzr,xzr
  let s := addc r0 t0 0         -- adds r0,r0,t0
  let r0 := s.1                 --   `-> r0
  let c := s.2                  --   `-> carry
  let t0 := umulh a0 b1         -- umulh t0,a0,b1
  let s := addc r1 t1 c         -- adcs r1,r1,t1
  let r1 := s.1                 --   `-> r1
  let c := s.2                  --   `-> carry
  let t1 := umulh a1 b1         -- umulh t1,a1,b1
  let s := addc r2 t2 c         -- adcs r2,r2,t2
  let r2 := s.1                 --   `-> r2
  let c := s.2                  --   `-> carry
  let q := mulLo inv r0         -- mul q,inv,r0
  let t2 := umulh a2 b1         -- umulh t2,a2,b1
  let s := addc r3 t3 c         -- adcs r3,r3,t3
  let r3 := s.1                 --   `-> r3
  let c := s.2                  --   `-> carry
  let t3 := umulh a3 b1         -- umulh t3,a3,b1
  let r4 := (addc r4 0 c).1     -- adc r4,r4,xzr
  let s := addc r1 t0 0         -- adds r1,r1,t0
  let r1 := s.1                 --   `-> r1
  let c := s.2                  --   `-> carry
  let s := addc r2 t1 c         -- adcs r2,r2,t1
  let r2 := s.1                 --   `-> r2
  let c := s.2                  --   `-> carry
  let t1 := mulLo p1 q          -- mul t1,p1,q
  let s := addc r3 t2 c         -- adcs r3,r3,t2
  let r3 := s.1                 --   `-> r3
  let c := s.2                  --   `-> carry
  let r4 := (addc r4 t3 c).1    -- adc r4,r4,t3
  let t3 := lsl q 62            -- lsl t3,q,#62
  ⟨r0, r1, r2, r3, r4, q, t1, t3⟩

/-- The inline `asm!` block of `mul`: Montgomery multiplication, `lhs * rhs * 2^-256 mod p`, with
the result in the block's output operands. Its rounds are those of Semolina's `mul_mont_pasta`; its
epilogue keeps four limbs of the final candidate. -/
def mulMont (lhs rhs modulus : Limbs) (inv : Nat) : Limbs :=
  let a0 := lhs.l0              -- argument
  let a1 := lhs.l1              -- argument
  let a2 := lhs.l2              -- argument
  let a3 := lhs.l3              -- argument
  let b0 := rhs.l0              -- argument
  let b1 := rhs.l1              -- argument
  let b2 := rhs.l2              -- argument
  let b3 := rhs.l3              -- argument
  let p0 := modulus.l0          -- argument
  let p1 := modulus.l1          -- argument
  let inv := inv                -- argument
  let r0 := mulLo a0 b0         -- mul r0,a0,b0
  let r1 := mulLo a1 b0         -- mul r1,a1,b0
  let r2 := mulLo a2 b0         -- mul r2,a2,b0
  let r3 := mulLo a3 b0         -- mul r3,a3,b0
  let t0 := umulh a0 b0         -- umulh t0,a0,b0
  let t1 := umulh a1 b0         -- umulh t1,a1,b0
  let q := mulLo inv r0         -- mul q,inv,r0
  let t2 := umulh a2 b0         -- umulh t2,a2,b0
  let t3 := umulh a3 b0         -- umulh t3,a3,b0
  let s := addc r1 t0 0         -- adds r1,r1,t0
  let r1 := s.1                 --   `-> r1
  let c := s.2                  --   `-> carry
  let s := addc r2 t1 c         -- adcs r2,r2,t1
  let r2 := s.1                 --   `-> r2
  let c := s.2                  --   `-> carry
  let t1 := mulLo p1 q          -- mul t1,p1,q
  let s := addc r3 t2 c         -- adcs r3,r3,t2
  let r3 := s.1                 --   `-> r3
  let c := s.2                  --   `-> carry
  let r4 := (addc 0 t3 c).1     -- adc r4,xzr,t3
  let t3 := lsl q 62            -- lsl t3,q,#62
  let round1 := mulMontRound lhs modulus inv b1 ⟨r0, r1, r2, r3, r4, q, t1, t3⟩  -- round 1
  let r0 := round1.r0           -- round 1 output
  let r1 := round1.r1           -- round 1 output
  let r2 := round1.r2           -- round 1 output
  let r3 := round1.r3           -- round 1 output
  let r4 := round1.r4           -- round 1 output
  let q := round1.q             -- round 1 output
  let t1 := round1.t1           -- round 1 output
  let t3 := round1.t3           -- round 1 output
  let round2 := mulMontRound lhs modulus inv b2 ⟨r0, r1, r2, r3, r4, q, t1, t3⟩  -- round 2
  let r0 := round2.r0           -- round 2 output
  let r1 := round2.r1           -- round 2 output
  let r2 := round2.r2           -- round 2 output
  let r3 := round2.r3           -- round 2 output
  let r4 := round2.r4           -- round 2 output
  let q := round2.q             -- round 2 output
  let t1 := round2.t1           -- round 2 output
  let t3 := round2.t3           -- round 2 output
  let round3 := mulMontRound lhs modulus inv b3 ⟨r0, r1, r2, r3, r4, q, t1, t3⟩  -- round 3
  let r0 := round3.r0           -- round 3 output
  let r1 := round3.r1           -- round 3 output
  let r2 := round3.r2           -- round 3 output
  let r3 := round3.r3           -- round 3 output
  let r4 := round3.r4           -- round 3 output
  let q := round3.q             -- round 3 output
  let t1 := round3.t1           -- round 3 output
  let t3 := round3.t3           -- round 3 output
  let c := (subc r0 1 1).2      -- subs xzr,r0,#1
  let t0 := umulh p0 q          -- umulh t0,p0,q
  let s := addc r1 t1 c         -- adcs r1,r1,t1
  let r1 := s.1                 --   `-> r1
  let c := s.2                  --   `-> carry
  let t1 := umulh p1 q          -- umulh t1,p1,q
  let s := addc r2 0 c          -- adcs r2,r2,xzr
  let r2 := s.1                 --   `-> r2
  let c := s.2                  --   `-> carry
  let s := addc r3 t3 c         -- adcs r3,r3,t3
  let r3 := s.1                 --   `-> r3
  let c := s.2                  --   `-> carry
  let t3 := lsr q 2             -- lsr t3,q,#2
  let r4 := (addc r4 0 c).1     -- adc r4,r4,xzr
  let s := addc r1 t0 0         -- adds r0,r1,t0
  let r0 := s.1                 --   `-> r0
  let c := s.2                  --   `-> carry
  let s := addc r2 t1 c         -- adcs r1,r2,t1
  let r1 := s.1                 --   `-> r1
  let c := s.2                  --   `-> carry
  let s := addc r3 0 c          -- adcs r2,r3,xzr
  let r2 := s.1                 --   `-> r2
  let c := s.2                  --   `-> carry
  let s := addc r4 t3 c         -- adcs r3,r4,t3
  let r3 := s.1                 --   `-> r3
  let q := 0x4000000000000000   -- mov q,#0x4000000000000000
  let s := subc r0 p0 1         -- subs t0,r0,p0
  let t0 := s.1                 --   `-> t0
  let c := s.2                  --   `-> carry
  let s := subc r1 p1 c         -- sbcs t1,r1,p1
  let t1 := s.1                 --   `-> t1
  let c := s.2                  --   `-> carry
  let s := subc r2 0 c          -- sbcs t2,r2,xzr
  let t2 := s.1                 --   `-> t2
  let c := s.2                  --   `-> carry
  let s := subc r3 q c          -- sbcs t3,r3,q
  let t3 := s.1                 --   `-> t3
  let c := s.2                  --   `-> carry
  let r0 := cselLo c r0 t0      -- csel r0,r0,t0,lo
  let r1 := cselLo c r1 t1      -- csel r1,r1,t1,lo
  let r2 := cselLo c r2 t2      -- csel r2,r2,t2,lo
  let r3 := cselLo c r3 t3      -- csel r3,r3,t3,lo
  ⟨r0, r1, r2, r3⟩

/-- The inline `asm!` block of `square`: Montgomery squaring, `value^2 * 2^-256 mod p`, the squaring
loop body of Semolina's `sqr_n_mul_mont_pasta` followed by a conditional subtraction, with the
result in the block's `inout` operands. -/
def sqrMont (value modulus : Limbs) (inv : Nat) : Limbs :=
  let a0 := value.l0            -- argument
  let a1 := value.l1            -- argument
  let a2 := value.l2            -- argument
  let a3 := value.l3            -- argument
  let p0 := modulus.l0          -- argument
  let p1 := modulus.l1          -- argument
  let inv := inv                -- argument
  let z1 := mulLo a1 a0         -- mul z1,a1,a0
  let w1 := umulh a1 a0         -- umulh w1,a1,a0
  let z2 := mulLo a2 a0         -- mul z2,a2,a0
  let w2 := umulh a2 a0         -- umulh w2,a2,a0
  let z3 := mulLo a3 a0         -- mul z3,a3,a0
  let z4 := umulh a3 a0         -- umulh z4,a3,a0
  let s := addc z2 w1 0         -- adds z2,z2,w1
  let z2 := s.1                 --   `-> z2
  let c := s.2                  --   `-> carry
  let w0 := mulLo a2 a1         -- mul w0,a2,a1
  let w1 := umulh a2 a1         -- umulh w1,a2,a1
  let s := addc z3 w2 c         -- adcs z3,z3,w2
  let z3 := s.1                 --   `-> z3
  let c := s.2                  --   `-> carry
  let w2 := mulLo a3 a1         -- mul w2,a3,a1
  let w3 := umulh a3 a1         -- umulh w3,a3,a1
  let z4 := (addc z4 0 c).1     -- adc z4,z4,xzr
  let z5 := mulLo a3 a2         -- mul z5,a3,a2
  let z6 := umulh a3 a2         -- umulh z6,a3,a2
  let s := addc w1 w2 0         -- adds w1,w1,w2
  let w1 := s.1                 --   `-> w1
  let c := s.2                  --   `-> carry
  let z0 := mulLo a0 a0         -- mul z0,a0,a0
  let w2 := (addc w3 0 c).1     -- adc w2,w3,xzr
  let s := addc z3 w0 0         -- adds z3,z3,w0
  let z3 := s.1                 --   `-> z3
  let c := s.2                  --   `-> carry
  let a0 := umulh a0 a0         -- umulh a0,a0,a0
  let s := addc z4 w1 c         -- adcs z4,z4,w1
  let z4 := s.1                 --   `-> z4
  let c := s.2                  --   `-> carry
  let w1 := mulLo a1 a1         -- mul w1,a1,a1
  let s := addc z5 w2 c         -- adcs z5,z5,w2
  let z5 := s.1                 --   `-> z5
  let c := s.2                  --   `-> carry
  let a1 := umulh a1 a1         -- umulh a1,a1,a1
  let z6 := (addc z6 0 c).1     -- adc z6,z6,xzr
  let s := addc z1 z1 0         -- adds z1,z1,z1
  let z1 := s.1                 --   `-> z1
  let c := s.2                  --   `-> carry
  let w2 := mulLo a2 a2         -- mul w2,a2,a2
  let s := addc z2 z2 c         -- adcs z2,z2,z2
  let z2 := s.1                 --   `-> z2
  let c := s.2                  --   `-> carry
  let a2 := umulh a2 a2         -- umulh a2,a2,a2
  let s := addc z3 z3 c         -- adcs z3,z3,z3
  let z3 := s.1                 --   `-> z3
  let c := s.2                  --   `-> carry
  let w3 := mulLo a3 a3         -- mul w3,a3,a3
  let s := addc z4 z4 c         -- adcs z4,z4,z4
  let z4 := s.1                 --   `-> z4
  let c := s.2                  --   `-> carry
  let a3 := umulh a3 a3         -- umulh a3,a3,a3
  let s := addc z5 z5 c         -- adcs z5,z5,z5
  let z5 := s.1                 --   `-> z5
  let c := s.2                  --   `-> carry
  let s := addc z6 z6 c         -- adcs z6,z6,z6
  let z6 := s.1                 --   `-> z6
  let c := s.2                  --   `-> carry
  let z7 := (addc 0 0 c).1      -- adc z7,xzr,xzr
  let q := mulLo inv z0         -- mul q,inv,z0
  let s := addc z1 a0 0         -- adds z1,z1,a0
  let z1 := s.1                 --   `-> z1
  let c := s.2                  --   `-> carry
  let s := addc z2 w1 c         -- adcs z2,z2,w1
  let z2 := s.1                 --   `-> z2
  let c := s.2                  --   `-> carry
  let s := addc z3 a1 c         -- adcs z3,z3,a1
  let z3 := s.1                 --   `-> z3
  let c := s.2                  --   `-> carry
  let s := addc z4 w2 c         -- adcs z4,z4,w2
  let z4 := s.1                 --   `-> z4
  let c := s.2                  --   `-> carry
  let s := addc z5 a2 c         -- adcs z5,z5,a2
  let z5 := s.1                 --   `-> z5
  let c := s.2                  --   `-> carry
  let s := addc z6 w3 c         -- adcs z6,z6,w3
  let z6 := s.1                 --   `-> z6
  let c := s.2                  --   `-> carry
  let z7 := (addc z7 a3 c).1    -- adc z7,z7,a3
  let w1 := mulLo p1 q          -- mul w1,p1,q
  let w3 := lsl q 62            -- lsl w3,q,#62
  let c := (subc z0 1 1).2      -- subs xzr,z0,#1
  let w0 := umulh p0 q          -- umulh w0,p0,q
  let s := addc z1 w1 c         -- adcs z1,z1,w1
  let z1 := s.1                 --   `-> z1
  let c := s.2                  --   `-> carry
  let w1 := umulh p1 q          -- umulh w1,p1,q
  let s := addc z2 0 c          -- adcs z2,z2,xzr
  let z2 := s.1                 --   `-> z2
  let c := s.2                  --   `-> carry
  let s := addc z3 w3 c         -- adcs z3,z3,w3
  let z3 := s.1                 --   `-> z3
  let c := s.2                  --   `-> carry
  let w3 := lsr q 2             -- lsr w3,q,#2
  let cy := (addc 0 0 c).1      -- adc cy,xzr,xzr
  let s := addc z1 w0 0         -- adds z0,z1,w0
  let z0 := s.1                 --   `-> z0
  let c := s.2                  --   `-> carry
  let s := addc z2 w1 c         -- adcs z1,z2,w1
  let z1 := s.1                 --   `-> z1
  let c := s.2                  --   `-> carry
  let s := addc z3 0 c          -- adcs z2,z3,xzr
  let z2 := s.1                 --   `-> z2
  let c := s.2                  --   `-> carry
  let q := mulLo inv z0         -- mul q,inv,z0
  let z3 := (addc cy w3 c).1    -- adc z3,cy,w3
  let w1 := mulLo p1 q          -- mul w1,p1,q
  let w3 := lsl q 62            -- lsl w3,q,#62
  let c := (subc z0 1 1).2      -- subs xzr,z0,#1
  let w0 := umulh p0 q          -- umulh w0,p0,q
  let s := addc z1 w1 c         -- adcs z1,z1,w1
  let z1 := s.1                 --   `-> z1
  let c := s.2                  --   `-> carry
  let w1 := umulh p1 q          -- umulh w1,p1,q
  let s := addc z2 0 c          -- adcs z2,z2,xzr
  let z2 := s.1                 --   `-> z2
  let c := s.2                  --   `-> carry
  let s := addc z3 w3 c         -- adcs z3,z3,w3
  let z3 := s.1                 --   `-> z3
  let c := s.2                  --   `-> carry
  let w3 := lsr q 2             -- lsr w3,q,#2
  let cy := (addc 0 0 c).1      -- adc cy,xzr,xzr
  let s := addc z1 w0 0         -- adds z0,z1,w0
  let z0 := s.1                 --   `-> z0
  let c := s.2                  --   `-> carry
  let s := addc z2 w1 c         -- adcs z1,z2,w1
  let z1 := s.1                 --   `-> z1
  let c := s.2                  --   `-> carry
  let s := addc z3 0 c          -- adcs z2,z3,xzr
  let z2 := s.1                 --   `-> z2
  let c := s.2                  --   `-> carry
  let q := mulLo inv z0         -- mul q,inv,z0
  let z3 := (addc cy w3 c).1    -- adc z3,cy,w3
  let w1 := mulLo p1 q          -- mul w1,p1,q
  let w3 := lsl q 62            -- lsl w3,q,#62
  let c := (subc z0 1 1).2      -- subs xzr,z0,#1
  let w0 := umulh p0 q          -- umulh w0,p0,q
  let s := addc z1 w1 c         -- adcs z1,z1,w1
  let z1 := s.1                 --   `-> z1
  let c := s.2                  --   `-> carry
  let w1 := umulh p1 q          -- umulh w1,p1,q
  let s := addc z2 0 c          -- adcs z2,z2,xzr
  let z2 := s.1                 --   `-> z2
  let c := s.2                  --   `-> carry
  let s := addc z3 w3 c         -- adcs z3,z3,w3
  let z3 := s.1                 --   `-> z3
  let c := s.2                  --   `-> carry
  let w3 := lsr q 2             -- lsr w3,q,#2
  let cy := (addc 0 0 c).1      -- adc cy,xzr,xzr
  let s := addc z1 w0 0         -- adds z0,z1,w0
  let z0 := s.1                 --   `-> z0
  let c := s.2                  --   `-> carry
  let s := addc z2 w1 c         -- adcs z1,z2,w1
  let z1 := s.1                 --   `-> z1
  let c := s.2                  --   `-> carry
  let s := addc z3 0 c          -- adcs z2,z3,xzr
  let z2 := s.1                 --   `-> z2
  let c := s.2                  --   `-> carry
  let q := mulLo inv z0         -- mul q,inv,z0
  let z3 := (addc cy w3 c).1    -- adc z3,cy,w3
  let w1 := mulLo p1 q          -- mul w1,p1,q
  let w3 := lsl q 62            -- lsl w3,q,#62
  let c := (subc z0 1 1).2      -- subs xzr,z0,#1
  let w0 := umulh p0 q          -- umulh w0,p0,q
  let s := addc z1 w1 c         -- adcs z1,z1,w1
  let z1 := s.1                 --   `-> z1
  let c := s.2                  --   `-> carry
  let w1 := umulh p1 q          -- umulh w1,p1,q
  let s := addc z2 0 c          -- adcs z2,z2,xzr
  let z2 := s.1                 --   `-> z2
  let c := s.2                  --   `-> carry
  let s := addc z3 w3 c         -- adcs z3,z3,w3
  let z3 := s.1                 --   `-> z3
  let c := s.2                  --   `-> carry
  let w3 := lsr q 2             -- lsr w3,q,#2
  let cy := (addc 0 0 c).1      -- adc cy,xzr,xzr
  let s := addc z1 w0 0         -- adds z0,z1,w0
  let z0 := s.1                 --   `-> z0
  let c := s.2                  --   `-> carry
  let s := addc z2 w1 c         -- adcs z1,z2,w1
  let z1 := s.1                 --   `-> z1
  let c := s.2                  --   `-> carry
  let s := addc z3 0 c          -- adcs z2,z3,xzr
  let z2 := s.1                 --   `-> z2
  let c := s.2                  --   `-> carry
  let z3 := (addc cy w3 c).1    -- adc z3,cy,w3
  let s := addc z0 z4 0         -- adds a0,z0,z4
  let a0 := s.1                 --   `-> a0
  let c := s.2                  --   `-> carry
  let s := addc z1 z5 c         -- adcs a1,z1,z5
  let a1 := s.1                 --   `-> a1
  let c := s.2                  --   `-> carry
  let s := addc z2 z6 c         -- adcs a2,z2,z6
  let a2 := s.1                 --   `-> a2
  let c := s.2                  --   `-> carry
  let a3 := (addc z3 z7 c).1    -- adc a3,z3,z7
  let q := 0x4000000000000000   -- mov q,#0x4000000000000000
  let s := subc a0 p0 1         -- subs z0,a0,p0
  let z0 := s.1                 --   `-> z0
  let c := s.2                  --   `-> carry
  let s := subc a1 p1 c         -- sbcs z1,a1,p1
  let z1 := s.1                 --   `-> z1
  let c := s.2                  --   `-> carry
  let s := subc a2 0 c          -- sbcs z2,a2,xzr
  let z2 := s.1                 --   `-> z2
  let c := s.2                  --   `-> carry
  let s := subc a3 q c          -- sbcs z3,a3,q
  let z3 := s.1                 --   `-> z3
  let c := s.2                  --   `-> carry
  let a0 := cselLo c a0 z0      -- csel a0,a0,z0,lo
  let a1 := cselLo c a1 z1      -- csel a1,a1,z1,lo
  let a2 := cselLo c a2 z2      -- csel a2,a2,z2,lo
  let a3 := cselLo c a3 z3      -- csel a3,a3,z3,lo
  ⟨a0, a1, a2, a3⟩

/-- The inline `asm!` block of `add`: modular addition, `lhs + rhs mod p`, as a full-width addition,
a subtraction of the modulus, and the selection of the reduced sum when that subtraction did not
borrow, with the result in the block's `inout` operands. -/
def addMod (lhs rhs modulus : Limbs) : Limbs :=
  let r0 := lhs.l0              -- argument
  let r1 := lhs.l1              -- argument
  let r2 := lhs.l2              -- argument
  let r3 := lhs.l3              -- argument
  let b0 := rhs.l0              -- argument
  let b1 := rhs.l1              -- argument
  let b2 := rhs.l2              -- argument
  let b3 := rhs.l3              -- argument
  let p0 := modulus.l0          -- argument
  let p1 := modulus.l1          -- argument
  let p3 := modulus.l3          -- argument
  let s := addc r0 b0 0         -- adds r0,r0,b0
  let r0 := s.1                 --   `-> r0
  let c := s.2                  --   `-> carry
  let s := addc r1 b1 c         -- adcs r1,r1,b1
  let r1 := s.1                 --   `-> r1
  let c := s.2                  --   `-> carry
  let s := addc r2 b2 c         -- adcs r2,r2,b2
  let r2 := s.1                 --   `-> r2
  let c := s.2                  --   `-> carry
  let r3 := (addc r3 b3 c).1    -- adc r3,r3,b3
  let s := subc r0 p0 1         -- subs t0,r0,p0
  let t0 := s.1                 --   `-> t0
  let c := s.2                  --   `-> carry
  let s := subc r1 p1 c         -- sbcs t1,r1,p1
  let t1 := s.1                 --   `-> t1
  let c := s.2                  --   `-> carry
  let s := subc r2 0 c          -- sbcs t2,r2,xzr
  let t2 := s.1                 --   `-> t2
  let c := s.2                  --   `-> carry
  let s := subc r3 p3 c         -- sbcs t3,r3,p3
  let t3 := s.1                 --   `-> t3
  let c := s.2                  --   `-> carry
  let r0 := cselCs c t0 r0      -- csel r0,t0,r0,cs
  let r1 := cselCs c t1 r1      -- csel r1,t1,r1,cs
  let r2 := cselCs c t2 r2      -- csel r2,t2,r2,cs
  let r3 := cselCs c t3 r3      -- csel r3,t3,r3,cs
  ⟨r0, r1, r2, r3⟩

/-- The inline `asm!` block of `sub`: modular subtraction, `lhs - rhs mod p`, as a full-width
subtraction and the addition of the modulus when it borrowed, with the result in the block's `inout`
operands. -/
def subMod (lhs rhs modulus : Limbs) : Limbs :=
  let r0 := lhs.l0              -- argument
  let r1 := lhs.l1              -- argument
  let r2 := lhs.l2              -- argument
  let r3 := lhs.l3              -- argument
  let b0 := rhs.l0              -- argument
  let b1 := rhs.l1              -- argument
  let b2 := rhs.l2              -- argument
  let b3 := rhs.l3              -- argument
  let p0 := modulus.l0          -- argument
  let p1 := modulus.l1          -- argument
  let p3 := modulus.l3          -- argument
  let s := subc r0 b0 1         -- subs r0,r0,b0
  let r0 := s.1                 --   `-> r0
  let c := s.2                  --   `-> carry
  let s := subc r1 b1 c         -- sbcs r1,r1,b1
  let r1 := s.1                 --   `-> r1
  let c := s.2                  --   `-> carry
  let s := subc r2 b2 c         -- sbcs r2,r2,b2
  let r2 := s.1                 --   `-> r2
  let c := s.2                  --   `-> carry
  let s := subc r3 b3 c         -- sbcs r3,r3,b3
  let r3 := s.1                 --   `-> r3
  let c := s.2                  --   `-> carry
  let t0 := cselLo c p0 0       -- csel t0,p0,xzr,cc
  let t1 := cselLo c p1 0       -- csel t1,p1,xzr,cc
  let t3 := cselLo c p3 0       -- csel t3,p3,xzr,cc
  let s := addc r0 t0 0         -- adds r0,r0,t0
  let r0 := s.1                 --   `-> r0
  let c := s.2                  --   `-> carry
  let s := addc r1 t1 c         -- adcs r1,r1,t1
  let r1 := s.1                 --   `-> r1
  let c := s.2                  --   `-> carry
  let s := addc r2 0 c          -- adcs r2,r2,xzr
  let r2 := s.1                 --   `-> r2
  let c := s.2                  --   `-> carry
  let r3 := (addc r3 t3 c).1    -- adc r3,r3,t3
  ⟨r0, r1, r2, r3⟩

/-- The registers that `divstepRound` carries in and out. -/
structure DivstepState where
  /-- the doubled half-delta `d`, as a two's-complement word -/
  d : Nat
  /-- the packed `f` word -/
  f : Nat
  /-- the packed `g` word -/
  g : Nat
  /-- the flags, set by the parity test of the packed `g` word -/
  fl : Flags
  deriving DecidableEq, Repr

namespace DivstepState

/-- Every word is below `2^64`. -/
def Bounded (s : DivstepState) : Prop :=
   s.d < 2^64 ∧ s.f < 2^64 ∧ s.g < 2^64

end DivstepState

/-- `divstep!()`, one packed half-delta divstep on the words `f` and `g` at `d`, from the flags of
the parity test of `g`, ending with the parity test of the new `g` for the next step -/
def divstepRound (st : DivstepState) : DivstepState :=
  let d := st.d                 -- argument
  let pf := st.f                -- argument
  let pg := st.g                -- argument
  let fl := st.fl               -- argument
  let t := cselNe fl pf 0       -- csel t,pf,xzr,ne
  let fl := ccmpNe fl d 0 8     -- ccmp d,xzr,#8,ne
  let d := cnegGe fl d          -- cneg d,d,ge
  let t := cnegGe fl t          -- cneg t,t,ge
  let pf := cselGe fl pg pf     -- csel pf,pg,pf,ge
  let pg := addw pg t           -- add pg,pg,t
  let d := addw d 2             -- add d,d,#2
  let fl := tstFlags (andw pg 2)  -- tst pg,#2
  let pg := asr pg 1            -- asr pg,pg,#1
  ⟨d, pf, pg, fl⟩

/-- `divstep!(last)`, the last divstep of a batch: `divstepRound` without the parity test at its end
-/
def divstepLast (st : DivstepState) : DivstepState :=
  let d := st.d                 -- argument
  let pf := st.f                -- argument
  let pg := st.g                -- argument
  let fl := st.fl               -- argument
  let t := cselNe fl pf 0       -- csel t,pf,xzr,ne
  let fl := ccmpNe fl d 0 8     -- ccmp d,xzr,#8,ne
  let d := cnegGe fl d          -- cneg d,d,ge
  let t := cnegGe fl t          -- cneg t,t,ge
  let pf := cselGe fl pg pf     -- csel pf,pg,pf,ge
  let pg := addw pg t           -- add pg,pg,t
  let d := addw d 2             -- add d,d,#2
  let pg := asr pg 1            -- asr pg,pg,#1
  ⟨d, pf, pg, fl⟩

/-- The inline `asm!` block of `divstep59`: 59 half-delta divsteps on the low words `f0` and `g0` of
`f` and `g` at `d`, as three packed batches of 20, 20, and 19 steps in which the matrix coefficients
ride in the upper bits of the two words, with the two matrix products between and after the batches.
It is s2n-bignum's `divstep59` macro on named registers. The result is the new `d` and the 59-step
matrix, as two's-complement words. -/
def divstep59Block (d f0 g0 : Nat) : Divstep59Result :=
  let d := d                    -- argument
  let f := f0                   -- argument
  let g := g0                   -- argument
  let pf := andw f 0xfffff      -- and pf,f,#0xfffff
  let pf := orrw pf 0xfffffe0000000000  -- orr pf,pf,#0xfffffe0000000000
  let pg := andw g 0xfffff      -- and pg,g,#0xfffff
  let pg := orrw pg 0xc000000000000000  -- orr pg,pg,#0xc000000000000000
  let fl := tstFlags (andw pg 1)  -- tst pg,#1
  let step19 := divstepRound^[19] ⟨d, pf, pg, fl⟩  -- divstep!(), invocations 1 to 19
  let d := step19.d             -- divstep!(), invocations 1 to 19 output
  let pf := step19.f            -- divstep!(), invocations 1 to 19 output
  let pg := step19.g            -- divstep!(), invocations 1 to 19 output
  let fl := step19.fl           -- divstep!(), invocations 1 to 19 output
  let step20 := divstepLast ⟨d, pf, pg, fl⟩  -- divstep!(last), invocation 20
  let d := step20.d             -- divstep!(last), invocation 20 output
  let pf := step20.f            -- divstep!(last), invocation 20 output
  let pg := step20.g            -- divstep!(last), invocation 20 output
  -- divstep!(last), invocation 20 output: fl = step20.fl is never read
  let a00 := addw pf 0x100000   -- add a00,pf,#0x100,lsl #12
  let a00 := sbfx a00 21 21     -- sbfx a00,a00,#21,#21
  let a11 := 0x100000           -- mov a11,#0x100000
  let a11 := addw a11 (lsl a11 21)  -- add a11,a11,a11,lsl #21
  let a01 := addw pf a11        -- add a01,pf,a11
  let a01 := asr a01 42         -- asr a01,a01,#42
  let a10 := addw pg 0x100000   -- add a10,pg,#0x100,lsl #12
  let a10 := sbfx a10 21 21     -- sbfx a10,a10,#21,#21
  let a11 := addw pg a11        -- add a11,pg,a11
  let a11 := asr a11 42         -- asr a11,a11,#42
  let t := mulLo a00 f          -- mul t,a00,f
  let t2 := mulLo a01 g         -- mul t2,a01,g
  let f := mulLo a10 f          -- mul f,a10,f
  let g := mulLo a11 g          -- mul g,a11,g
  let pf := addw t t2           -- add pf,t,t2
  let pg := addw f g            -- add pg,f,g
  let f := asr pf 20            -- asr f,pf,#20
  let g := asr pg 20            -- asr g,pg,#20
  let pf := andw f 0xfffff      -- and pf,f,#0xfffff
  let pf := orrw pf 0xfffffe0000000000  -- orr pf,pf,#0xfffffe0000000000
  let pg := andw g 0xfffff      -- and pg,g,#0xfffff
  let pg := orrw pg 0xc000000000000000  -- orr pg,pg,#0xc000000000000000
  let fl := tstFlags (andw pg 1)  -- tst pg,#1
  let step39 := divstepRound^[19] ⟨d, pf, pg, fl⟩  -- divstep!(), invocations 21 to 39
  let d := step39.d             -- divstep!(), invocations 21 to 39 output
  let pf := step39.f            -- divstep!(), invocations 21 to 39 output
  let pg := step39.g            -- divstep!(), invocations 21 to 39 output
  let fl := step39.fl           -- divstep!(), invocations 21 to 39 output
  let step40 := divstepLast ⟨d, pf, pg, fl⟩  -- divstep!(last), invocation 40
  let d := step40.d             -- divstep!(last), invocation 40 output
  let pf := step40.f            -- divstep!(last), invocation 40 output
  let pg := step40.g            -- divstep!(last), invocation 40 output
  -- divstep!(last), invocation 40 output: fl = step40.fl is never read
  let b00 := addw pf 0x100000   -- add b00,pf,#0x100,lsl #12
  let b00 := sbfx b00 21 21     -- sbfx b00,b00,#21,#21
  let b11 := 0x100000           -- mov b11,#0x100000
  let b11 := addw b11 (lsl b11 21)  -- add b11,b11,b11,lsl #21
  let b01 := addw pf b11        -- add b01,pf,b11
  let b01 := asr b01 42         -- asr b01,b01,#42
  let b10 := addw pg 0x100000   -- add b10,pg,#0x100,lsl #12
  let b10 := sbfx b10 21 21     -- sbfx b10,b10,#21,#21
  let b11 := addw pg b11        -- add b11,pg,b11
  let b11 := asr b11 42         -- asr b11,b11,#42
  let t := mulLo b00 f          -- mul t,b00,f
  let t2 := mulLo b01 g         -- mul t2,b01,g
  let f := mulLo b10 f          -- mul f,b10,f
  let g := mulLo b11 g          -- mul g,b11,g
  let pf := addw t t2           -- add pf,t,t2
  let pg := addw f g            -- add pg,f,g
  let f := asr pf 20            -- asr f,pf,#20
  let g := asr pg 20            -- asr g,pg,#20
  let pf := andw f 0xfffff      -- and pf,f,#0xfffff
  let pf := orrw pf 0xfffffe0000000000  -- orr pf,pf,#0xfffffe0000000000
  let pg := andw g 0xfffff      -- and pg,g,#0xfffff
  let pg := orrw pg 0xc000000000000000  -- orr pg,pg,#0xc000000000000000
  let fl := tstFlags (andw pg 1)  -- tst pg,#1
  let step50 := divstepRound^[10] ⟨d, pf, pg, fl⟩  -- divstep!(), invocations 41 to 50
  let d := step50.d             -- divstep!(), invocations 41 to 50 output
  let pf := step50.f            -- divstep!(), invocations 41 to 50 output
  let pg := step50.g            -- divstep!(), invocations 41 to 50 output
  let fl := step50.fl           -- divstep!(), invocations 41 to 50 output
  let f := mulLo b00 a00        -- mul f,b00,a00
  let g := mulLo b00 a01        -- mul g,b00,a01
  let t := mulLo b10 a00        -- mul t,b10,a00
  let t2 := mulLo b10 a01       -- mul t2,b10,a01
  let a00 := madd b01 a10 f     -- madd a00,b01,a10,f
  let a01 := madd b01 a11 g     -- madd a01,b01,a11,g
  let c10 := madd b11 a10 t     -- madd c10,b11,a10,t
  let c11 := madd b11 a11 t2    -- madd c11,b11,a11,t2
  let step58 := divstepRound^[8] ⟨d, pf, pg, fl⟩  -- divstep!(), invocations 51 to 58
  let d := step58.d             -- divstep!(), invocations 51 to 58 output
  let pf := step58.f            -- divstep!(), invocations 51 to 58 output
  let pg := step58.g            -- divstep!(), invocations 51 to 58 output
  let fl := step58.fl           -- divstep!(), invocations 51 to 58 output
  let step59 := divstepLast ⟨d, pf, pg, fl⟩  -- divstep!(last), invocation 59
  let d := step59.d             -- divstep!(last), invocation 59 output
  let pf := step59.f            -- divstep!(last), invocation 59 output
  let pg := step59.g            -- divstep!(last), invocation 59 output
  -- divstep!(last), invocation 59 output: fl = step59.fl is never read
  let b00 := addw pf 0x100000   -- add b00,pf,#0x100,lsl #12
  let b00 := sbfx b00 22 21     -- sbfx b00,b00,#22,#21
  let b11 := 0x100000           -- mov b11,#0x100000
  let b11 := addw b11 (lsl b11 21)  -- add b11,b11,b11,lsl #21
  let b01 := addw pf b11        -- add b01,pf,b11
  let b01 := asr b01 43         -- asr b01,b01,#43
  let b10 := addw pg 0x100000   -- add b10,pg,#0x100,lsl #12
  let b10 := sbfx b10 22 21     -- sbfx b10,b10,#22,#21
  let b11 := addw pg b11        -- add b11,pg,b11
  let b11 := asr b11 43         -- asr b11,b11,#43
  let f := mneg b00 a00         -- mneg f,b00,a00
  let g := mneg b00 a01         -- mneg g,b00,a01
  let pf := mneg b10 a00        -- mneg pf,b10,a00
  let pg := mneg b10 a01        -- mneg pg,b10,a01
  let m00 := msub b01 c10 f     -- msub m00,b01,c10,f
  let m01 := msub b01 c11 g     -- msub m01,b01,c11,g
  let m10 := msub b11 c10 pf    -- msub m10,b11,c10,pf
  let m11 := msub b11 c11 pg    -- msub m11,b11,c11,pg
  ⟨d, m00, m01, m10, m11⟩

/-- The inline `asm!` block of `sign_mag`: the sign-magnitude form of the four entries of a
transition matrix, each entry's magnitude and its sign as a mask (all ones when negative, else
zero), which the row blocks take. -/
def signMagBlock (m00 m01 m10 m11 : Nat) : SignMag :=
  let m00 := m00                -- argument
  let m01 := m01                -- argument
  let m10 := m10                -- argument
  let m11 := m11                -- argument
  let fl := cmpFlags m00 0      -- cmp m00,xzr
  let s00 := csetmMi fl         -- csetm s00,mi
  let m00 := cnegMi fl m00      -- cneg m00,m00,mi
  let fl := cmpFlags m01 0      -- cmp m01,xzr
  let s01 := csetmMi fl         -- csetm s01,mi
  let m01 := cnegMi fl m01      -- cneg m01,m01,mi
  let fl := cmpFlags m10 0      -- cmp m10,xzr
  let s10 := csetmMi fl         -- csetm s10,mi
  let m10 := cnegMi fl m10      -- cneg m10,m10,mi
  let fl := cmpFlags m11 0      -- cmp m11,xzr
  let s11 := csetmMi fl         -- csetm s11,mi
  let m11 := cnegMi fl m11      -- cneg m11,m11,mi
  ⟨m00, m01, m10, m11, s00, s01, s10, s11⟩

/-- The inline `asm!` block of `fg_row`: one row of the update of `f` and `g`, `(m0 f + m1 g) /
2^59` on five-word signed values, from the row's magnitudes `m0`, `m1` and sign masks `s0`, `s1`, as
a 320-bit accumulation shifted right by 59. -/
def fgRowBlock (f g : Signed5) (m0 m1 s0 s1 : Nat) : Signed5 :=
  let f0 := f.l0                -- argument
  let f1 := f.l1                -- argument
  let f2 := f.l2                -- argument
  let f3 := f.l3                -- argument
  let f4 := f.l4                -- argument
  let g0 := g.l0                -- argument
  let g1 := g.l1                -- argument
  let g2 := g.l2                -- argument
  let g3 := g.l3                -- argument
  let g4 := g.l4                -- argument
  let m0 := m0                  -- argument
  let m1 := m1                  -- argument
  let s0 := s0                  -- argument
  let s1 := s1                  -- argument
  let lo := andw m0 s0          -- and lo,m0,s0
  let w := andw m1 s1           -- and w,m1,s1
  let d0 := addw lo w           -- add d0,lo,w
  let w := eorw f0 s0           -- eor w,f0,s0
  let lo := mulLo w m0          -- mul lo,w,m0
  let w := umulh w m0           -- umulh w,w,m0
  let s := addc d0 lo 0         -- adds d0,d0,lo
  let d0 := s.1                 --   `-> d0
  let c := s.2                  --   `-> carry
  let d1 := (addc 0 w c).1      -- adc d1,xzr,w
  let w := eorw g0 s1           -- eor w,g0,s1
  let lo := mulLo w m1          -- mul lo,w,m1
  let w := umulh w m1           -- umulh w,w,m1
  let s := addc d0 lo 0         -- adds d0,d0,lo
  let d0 := s.1                 --   `-> d0
  let c := s.2                  --   `-> carry
  let d1 := (addc d1 w c).1     -- adc d1,d1,w
  let w := eorw f1 s0           -- eor w,f1,s0
  let lo := mulLo w m0          -- mul lo,w,m0
  let w := umulh w m0           -- umulh w,w,m0
  let s := addc d1 lo 0         -- adds d1,d1,lo
  let d1 := s.1                 --   `-> d1
  let c := s.2                  --   `-> carry
  let d2 := (addc 0 w c).1      -- adc d2,xzr,w
  let w := eorw g1 s1           -- eor w,g1,s1
  let lo := mulLo w m1          -- mul lo,w,m1
  let w := umulh w m1           -- umulh w,w,m1
  let s := addc d1 lo 0         -- adds d1,d1,lo
  let d1 := s.1                 --   `-> d1
  let c := s.2                  --   `-> carry
  let d2 := (addc d2 w c).1     -- adc d2,d2,w
  let d0 := extr d1 d0 59       -- extr d0,d1,d0,#59
  let w := eorw f2 s0           -- eor w,f2,s0
  let lo := mulLo w m0          -- mul lo,w,m0
  let w := umulh w m0           -- umulh w,w,m0
  let s := addc d2 lo 0         -- adds d2,d2,lo
  let d2 := s.1                 --   `-> d2
  let c := s.2                  --   `-> carry
  let d3 := (addc 0 w c).1      -- adc d3,xzr,w
  let w := eorw g2 s1           -- eor w,g2,s1
  let lo := mulLo w m1          -- mul lo,w,m1
  let w := umulh w m1           -- umulh w,w,m1
  let s := addc d2 lo 0         -- adds d2,d2,lo
  let d2 := s.1                 --   `-> d2
  let c := s.2                  --   `-> carry
  let d3 := (addc d3 w c).1     -- adc d3,d3,w
  let d1 := extr d2 d1 59       -- extr d1,d2,d1,#59
  let w := eorw f3 s0           -- eor w,f3,s0
  let d4 := eorw f4 s0          -- eor d4,f4,s0
  let d4 := andw d4 m0          -- and d4,d4,m0
  let d4 := negw d4             -- neg d4,d4
  let lo := mulLo w m0          -- mul lo,w,m0
  let w := umulh w m0           -- umulh w,w,m0
  let s := addc d3 lo 0         -- adds d3,d3,lo
  let d3 := s.1                 --   `-> d3
  let c := s.2                  --   `-> carry
  let d4 := (addc d4 w c).1     -- adc d4,d4,w
  let w := eorw g3 s1           -- eor w,g3,s1
  let lo := eorw g4 s1          -- eor lo,g4,s1
  let lo := andw lo m1          -- and lo,lo,m1
  let d4 := subw d4 lo          -- sub d4,d4,lo
  let lo := mulLo w m1          -- mul lo,w,m1
  let w := umulh w m1           -- umulh w,w,m1
  let s := addc d3 lo 0         -- adds d3,d3,lo
  let d3 := s.1                 --   `-> d3
  let c := s.2                  --   `-> carry
  let d4 := (addc d4 w c).1     -- adc d4,d4,w
  let d2 := extr d3 d2 59       -- extr d2,d3,d2,#59
  let d3 := extr d4 d3 59       -- extr d3,d4,d3,#59
  let d4 := asr d4 59           -- asr d4,d4,#59
  ⟨d0, d1, d2, d3, d4⟩

/-- The inline `asm!` block of `uv_row`: one row of the combination of `u` and `v`, `m0 u + m1 v` as
a five-word signed value, from the row's magnitudes `m0`, `m1` and sign masks `s0`, `s1`. It is the
accumulation of `fgRowBlock` without the shift. -/
def uvRowBlock (u v : Limbs) (m0 m1 s0 s1 : Nat) : Signed5 :=
  let u0 := u.l0                -- argument
  let u1 := u.l1                -- argument
  let u2 := u.l2                -- argument
  let u3 := u.l3                -- argument
  let v0 := v.l0                -- argument
  let v1 := v.l1                -- argument
  let v2 := v.l2                -- argument
  let v3 := v.l3                -- argument
  let m0 := m0                  -- argument
  let m1 := m1                  -- argument
  let s0 := s0                  -- argument
  let s1 := s1                  -- argument
  let lo := andw m0 s0          -- and lo,m0,s0
  let w := andw m1 s1           -- and w,m1,s1
  let t0 := addw lo w           -- add t0,lo,w
  let w := eorw u0 s0           -- eor w,u0,s0
  let lo := mulLo w m0          -- mul lo,w,m0
  let w := umulh w m0           -- umulh w,w,m0
  let s := addc t0 lo 0         -- adds t0,t0,lo
  let t0 := s.1                 --   `-> t0
  let c := s.2                  --   `-> carry
  let t1 := (addc 0 w c).1      -- adc t1,xzr,w
  let w := eorw v0 s1           -- eor w,v0,s1
  let lo := mulLo w m1          -- mul lo,w,m1
  let w := umulh w m1           -- umulh w,w,m1
  let s := addc t0 lo 0         -- adds t0,t0,lo
  let t0 := s.1                 --   `-> t0
  let c := s.2                  --   `-> carry
  let t1 := (addc t1 w c).1     -- adc t1,t1,w
  let w := eorw u1 s0           -- eor w,u1,s0
  let lo := mulLo w m0          -- mul lo,w,m0
  let w := umulh w m0           -- umulh w,w,m0
  let s := addc t1 lo 0         -- adds t1,t1,lo
  let t1 := s.1                 --   `-> t1
  let c := s.2                  --   `-> carry
  let t2 := (addc 0 w c).1      -- adc t2,xzr,w
  let w := eorw v1 s1           -- eor w,v1,s1
  let lo := mulLo w m1          -- mul lo,w,m1
  let w := umulh w m1           -- umulh w,w,m1
  let s := addc t1 lo 0         -- adds t1,t1,lo
  let t1 := s.1                 --   `-> t1
  let c := s.2                  --   `-> carry
  let t2 := (addc t2 w c).1     -- adc t2,t2,w
  let w := eorw u2 s0           -- eor w,u2,s0
  let lo := mulLo w m0          -- mul lo,w,m0
  let w := umulh w m0           -- umulh w,w,m0
  let s := addc t2 lo 0         -- adds t2,t2,lo
  let t2 := s.1                 --   `-> t2
  let c := s.2                  --   `-> carry
  let t3 := (addc 0 w c).1      -- adc t3,xzr,w
  let w := eorw v2 s1           -- eor w,v2,s1
  let lo := mulLo w m1          -- mul lo,w,m1
  let w := umulh w m1           -- umulh w,w,m1
  let s := addc t2 lo 0         -- adds t2,t2,lo
  let t2 := s.1                 --   `-> t2
  let c := s.2                  --   `-> carry
  let t3 := (addc t3 w c).1     -- adc t3,t3,w
  let w := eorw u3 s0           -- eor w,u3,s0
  let t4 := andw s0 m0          -- and t4,s0,m0
  let t4 := negw t4             -- neg t4,t4
  let lo := mulLo w m0          -- mul lo,w,m0
  let w := umulh w m0           -- umulh w,w,m0
  let s := addc t3 lo 0         -- adds t3,t3,lo
  let t3 := s.1                 --   `-> t3
  let c := s.2                  --   `-> carry
  let t4 := (addc t4 w c).1     -- adc t4,t4,w
  let w := eorw v3 s1           -- eor w,v3,s1
  let lo := andw s1 m1          -- and lo,s1,m1
  let t4 := subw t4 lo          -- sub t4,t4,lo
  let lo := mulLo w m1          -- mul lo,w,m1
  let w := umulh w m1           -- umulh w,w,m1
  let s := addc t3 lo 0         -- adds t3,t3,lo
  let t3 := s.1                 --   `-> t3
  let c := s.2                  --   `-> carry
  let t4 := (addc t4 w c).1     -- adc t4,t4,w
  ⟨t0, t1, t2, t3, t4⟩

/-- The inline `asm!` block of `amontred`: the almost-Montgomery reduction of a five-word signed
value by one word, `(s + w p) / 2^64` for `s = t + 2^61 p` and `w = s inv mod 2^64`, as four words.
For the Pasta shape no top carry is captured and no conditional subtraction follows. -/
def amontredBlock (t : Signed5) (modulus : Limbs) (inv : Nat) : Limbs :=
  let t0 := t.l0                -- argument
  let t1 := t.l1                -- argument
  let t2 := t.l2                -- argument
  let t3 := t.l3                -- argument
  let t4 := t.l4                -- argument
  let p0 := modulus.l0          -- argument
  let p1 := modulus.l1          -- argument
  let inv := inv                -- argument
  let w := lsl p0 61            -- lsl w,p0,#61
  let s := addc t0 w 0          -- adds t0,t0,w
  let t0 := s.1                 --   `-> t0
  let c := s.2                  --   `-> carry
  let w := extr p1 p0 3         -- extr w,p1,p0,#3
  let s := addc t1 w c          -- adcs t1,t1,w
  let t1 := s.1                 --   `-> t1
  let c := s.2                  --   `-> carry
  let w := lsr p1 3             -- lsr w,p1,#3
  let s := addc t2 w c          -- adcs t2,t2,w
  let t2 := s.1                 --   `-> t2
  let c := s.2                  --   `-> carry
  let s := addc t3 0 c          -- adcs t3,t3,xzr
  let t3 := s.1                 --   `-> t3
  let c := s.2                  --   `-> carry
  let w := 0x800000000000000    -- mov w,#0x800000000000000
  let t4 := (addc t4 w c).1     -- adc t4,t4,w
  let q := mulLo t0 inv         -- mul q,t0,inv
  let hi := umulh q p0          -- umulh hi,q,p0
  let lo := mulLo q p1          -- mul lo,q,p1
  let w := umulh q p1           -- umulh w,q,p1
  let l3 := lsl q 62            -- lsl l3,q,#62
  let h3 := lsr q 2             -- lsr h3,q,#2
  let c := (subc t0 1 1).2      -- subs xzr,t0,#1
  let s := addc t1 hi c         -- adcs t1,t1,hi
  let t1 := s.1                 --   `-> t1
  let c := s.2                  --   `-> carry
  let s := addc t2 w c          -- adcs t2,t2,w
  let t2 := s.1                 --   `-> t2
  let c := s.2                  --   `-> carry
  let s := addc t3 l3 c         -- adcs t3,t3,l3
  let t3 := s.1                 --   `-> t3
  let c := s.2                  --   `-> carry
  let t4 := (addc t4 h3 c).1    -- adc t4,t4,h3
  let s := addc t1 lo 0         -- adds t1,t1,lo
  let t1 := s.1                 --   `-> t1
  let c := s.2                  --   `-> carry
  let s := addc t2 0 c          -- adcs t2,t2,xzr
  let t2 := s.1                 --   `-> t2
  let c := s.2                  --   `-> carry
  let s := addc t3 0 c          -- adcs t3,t3,xzr
  let t3 := s.1                 --   `-> t3
  let c := s.2                  --   `-> carry
  let t4 := (addc t4 0 c).1     -- adc t4,t4,xzr
  ⟨t1, t2, t3, t4⟩

/-- The inline `asm!` block of `cond_sub`: the subtraction of the modulus from `value`, kept unless
it borrows. For `value < 2p` the result is `value mod p`. -/
def condSubBlock (value modulus : Limbs) : Limbs :=
  let r0 := value.l0            -- argument
  let r1 := value.l1            -- argument
  let r2 := value.l2            -- argument
  let r3 := value.l3            -- argument
  let p0 := modulus.l0          -- argument
  let p1 := modulus.l1          -- argument
  let q := 0x4000000000000000   -- mov q,#0x4000000000000000
  let s := subc r0 p0 1         -- subs t0,r0,p0
  let t0 := s.1                 --   `-> t0
  let c := s.2                  --   `-> carry
  let s := subc r1 p1 c         -- sbcs t1,r1,p1
  let t1 := s.1                 --   `-> t1
  let c := s.2                  --   `-> carry
  let s := subc r2 0 c          -- sbcs t2,r2,xzr
  let t2 := s.1                 --   `-> t2
  let c := s.2                  --   `-> carry
  let s := subc r3 q c          -- sbcs t3,r3,q
  let t3 := s.1                 --   `-> t3
  let c := s.2                  --   `-> carry
  let r0 := cselLo c r0 t0      -- csel r0,r0,t0,lo
  let r1 := cselLo c r1 t1      -- csel r1,r1,t1,lo
  let r2 := cselLo c r2 t2      -- csel r2,r2,t2,lo
  let r3 := cselLo c r3 t3      -- csel r3,r3,t3,lo
  ⟨r0, r1, r2, r3⟩

end PastaCurves.AArch64
