/-
Copyright Supranational LLC (the routines, transcribed from Semolina v0.1.4).
Copyright (c) 2026 the pasta_curves contributors (the transcription).
-/
import PastaCurves.AArch64.Semantics

/-!
# The crate's inline Pasta field blocks, transcribed

GENERATED by `lean/scripts/gen.py` from the `asm!` blocks of `mul`, `square`, `add`, `sub`,
`divstep59`, and `sign_mag` in `src/asm/aarch64.rs`; do not edit by hand. Each definition follows
its block instruction by instruction (the instruction is the trailing comment; the two lines that
unpack an instruction's (result, carry) pair are marked as its continuation), over the semantics of
`PastaCurves.AArch64.Semantics`. Registers are rebound by the instructions that write them, `c` is
the carry flag, `fl` the four flags, `s` is the (result, carry) pair of the instruction that last
set both, argument limbs are read where the block's operands bind them, and the output words are
bound where the block's output operands hold them. A block whose template invokes a macro for a
repeated step calls that step's definition once per invocation. Bindings that nothing reads are left
as comments. See the generator's docstring for what it checks.
-/

namespace PastaCurves.AArch64

/-- The registers that `mulMont` carries from one round to the next. -/
structure MulMontAcc where
  /-- accumulator limb 0 -/
  r0 : Nat
  /-- accumulator limb 1 -/
  r1 : Nat
  /-- accumulator limb 2 -/
  r2 : Nat
  /-- accumulator limb 3 -/
  r3 : Nat
  /-- accumulator limb 4 -/
  r4 : Nat
  /-- the round's Montgomery quotient `q` -/
  q : Nat
  /-- `low(p1 * q)`, the first term of the round's reduction -/
  t1 : Nat
  /-- `low(q * 2^62)`, the third term of the round's reduction -/
  t3 : Nat
  deriving DecidableEq, Repr

namespace MulMontAcc

/-- Every field is below `2^64`. -/
def Bounded (s : MulMontAcc) : Prop :=
   s.r0 < 2^64 ∧ s.r1 < 2^64 ∧ s.r2 < 2^64 ∧ s.r3 < 2^64 ∧ s.r4 < 2^64 ∧ s.q < 2^64 ∧ s.t1 < 2^64 ∧
      s.t3 < 2^64

/-- The accumulator's value: limbs `r0`, `r1`, `r2`, `r3`, `r4` with weights `2^0` to `2^256`. -/
def toNat (s : MulMontAcc) : Nat :=
   s.r0 + 2^64 * s.r1 + 2^128 * s.r2 + 2^192 * s.r3 + 2^256 * s.r4

end MulMontAcc

/-- One round of `mulMont`: the instructions between one `lsl t3,q,#62` and the next in each of its
3 rounds, on the round's `rhs` limb `b` and the registers `acc` carried from the previous round. -/
def mulMontRound (lhs modulus : Limbs) (inv b : Nat) (acc : MulMontAcc) : MulMontAcc :=
  let a0 := lhs.l0              -- argument
  let a1 := lhs.l1              -- argument
  let a2 := lhs.l2              -- argument
  let a3 := lhs.l3              -- argument
  let p0 := modulus.l0          -- argument
  let p1 := modulus.l1          -- argument
  let inv := inv                -- argument
  let b1 := b                   -- argument
  let r0 := acc.r0              -- argument
  let r1 := acc.r1              -- argument
  let r2 := acc.r2              -- argument
  let r3 := acc.r3              -- argument
  let r4 := acc.r4              -- argument
  let q := acc.q                -- argument
  let t1 := acc.t1              -- argument
  let t3 := acc.t3              -- argument
  let c := (subc r0 1 1).2      -- subs xzr,r0,#1
  let t0 := umulh p0 q          -- umulh t0,p0,q
  let s := addc r1 t1 c         -- adcs r1,r1,t1
  let r1 := s.1                 --   `-> r1
  let c := s.2                  --   `-> carry
  let t1 := umulh p1 q          -- umulh t1,p1,q
  let s := addc r2 0 c          -- adcs r2,r2,xzr
  let r2 := s.1                 --   `-> r2
  let c := s.2                  --   `-> carry
  let s := addc r3 t3 c         -- adcs r3,r3,t3
  let r3 := s.1                 --   `-> r3
  let c := s.2                  --   `-> carry
  let t3 := lsr q 2             -- lsr t3,q,#2
  let r4 := (addc r4 0 c).1     -- adc r4,r4,xzr
  let s := addc r1 t0 0         -- adds r0,r1,t0
  let r0 := s.1                 --   `-> r0
  let c := s.2                  --   `-> carry
  let t0 := mulLo a0 b1         -- mul t0,a0,b1
  let s := addc r2 t1 c         -- adcs r1,r2,t1
  let r1 := s.1                 --   `-> r1
  let c := s.2                  --   `-> carry
  let t1 := mulLo a1 b1         -- mul t1,a1,b1
  let s := addc r3 0 c          -- adcs r2,r3,xzr
  let r2 := s.1                 --   `-> r2
  let c := s.2                  --   `-> carry
  let t2 := mulLo a2 b1         -- mul t2,a2,b1
  let s := addc r4 t3 c         -- adcs r3,r4,t3
  let r3 := s.1                 --   `-> r3
  let c := s.2                  --   `-> carry
  let t3 := mulLo a3 b1         -- mul t3,a3,b1
  let r4 := (addc 0 0 c).1      -- adc r4,xzr,xzr
  let s := addc r0 t0 0         -- adds r0,r0,t0
  let r0 := s.1                 --   `-> r0
  let c := s.2                  --   `-> carry
  let t0 := umulh a0 b1         -- umulh t0,a0,b1
  let s := addc r1 t1 c         -- adcs r1,r1,t1
  let r1 := s.1                 --   `-> r1
  let c := s.2                  --   `-> carry
  let t1 := umulh a1 b1         -- umulh t1,a1,b1
  let s := addc r2 t2 c         -- adcs r2,r2,t2
  let r2 := s.1                 --   `-> r2
  let c := s.2                  --   `-> carry
  let q := mulLo inv r0         -- mul q,inv,r0
  let t2 := umulh a2 b1         -- umulh t2,a2,b1
  let s := addc r3 t3 c         -- adcs r3,r3,t3
  let r3 := s.1                 --   `-> r3
  let c := s.2                  --   `-> carry
  let t3 := umulh a3 b1         -- umulh t3,a3,b1
  let r4 := (addc r4 0 c).1     -- adc r4,r4,xzr
  let s := addc r1 t0 0         -- adds r1,r1,t0
  let r1 := s.1                 --   `-> r1
  let c := s.2                  --   `-> carry
  let s := addc r2 t1 c         -- adcs r2,r2,t1
  let r2 := s.1                 --   `-> r2
  let c := s.2                  --   `-> carry
  let t1 := mulLo p1 q          -- mul t1,p1,q
  let s := addc r3 t2 c         -- adcs r3,r3,t2
  let r3 := s.1                 --   `-> r3
  let c := s.2                  --   `-> carry
  let r4 := (addc r4 t3 c).1    -- adc r4,r4,t3
  let t3 := lsl q 62            -- lsl t3,q,#62
  ⟨r0, r1, r2, r3, r4, q, t1, t3⟩

/-- The inline `asm!` block of `mul`: Montgomery multiplication, `lhs * rhs * 2^-256 mod p`, with
the result in the block's output operands. Its rounds are those of Semolina's `mul_mont_pasta`; its
epilogue keeps four limbs of the final candidate. -/
def mulMont (lhs rhs modulus : Limbs) (inv : Nat) : Limbs :=
  let a0 := lhs.l0              -- argument
  let a1 := lhs.l1              -- argument
  let a2 := lhs.l2              -- argument
  let a3 := lhs.l3              -- argument
  let b0 := rhs.l0              -- argument
  let b1 := rhs.l1              -- argument
  let b2 := rhs.l2              -- argument
  let b3 := rhs.l3              -- argument
  let p0 := modulus.l0          -- argument
  let p1 := modulus.l1          -- argument
  let inv := inv                -- argument
  let r0 := mulLo a0 b0         -- mul r0,a0,b0
  let r1 := mulLo a1 b0         -- mul r1,a1,b0
  let r2 := mulLo a2 b0         -- mul r2,a2,b0
  let r3 := mulLo a3 b0         -- mul r3,a3,b0
  let t0 := umulh a0 b0         -- umulh t0,a0,b0
  let t1 := umulh a1 b0         -- umulh t1,a1,b0
  let q := mulLo inv r0         -- mul q,inv,r0
  let t2 := umulh a2 b0         -- umulh t2,a2,b0
  let t3 := umulh a3 b0         -- umulh t3,a3,b0
  let s := addc r1 t0 0         -- adds r1,r1,t0
  let r1 := s.1                 --   `-> r1
  let c := s.2                  --   `-> carry
  let s := addc r2 t1 c         -- adcs r2,r2,t1
  let r2 := s.1                 --   `-> r2
  let c := s.2                  --   `-> carry
  let t1 := mulLo p1 q          -- mul t1,p1,q
  let s := addc r3 t2 c         -- adcs r3,r3,t2
  let r3 := s.1                 --   `-> r3
  let c := s.2                  --   `-> carry
  let r4 := (addc 0 t3 c).1     -- adc r4,xzr,t3
  let t3 := lsl q 62            -- lsl t3,q,#62
  let round1 := mulMontRound lhs modulus inv b1 ⟨r0, r1, r2, r3, r4, q, t1, t3⟩  -- round 1
  let r0 := round1.r0           -- round 1 output
  let r1 := round1.r1           -- round 1 output
  let r2 := round1.r2           -- round 1 output
  let r3 := round1.r3           -- round 1 output
  let r4 := round1.r4           -- round 1 output
  let q := round1.q             -- round 1 output
  let t1 := round1.t1           -- round 1 output
  let t3 := round1.t3           -- round 1 output
  let round2 := mulMontRound lhs modulus inv b2 ⟨r0, r1, r2, r3, r4, q, t1, t3⟩  -- round 2
  let r0 := round2.r0           -- round 2 output
  let r1 := round2.r1           -- round 2 output
  let r2 := round2.r2           -- round 2 output
  let r3 := round2.r3           -- round 2 output
  let r4 := round2.r4           -- round 2 output
  let q := round2.q             -- round 2 output
  let t1 := round2.t1           -- round 2 output
  let t3 := round2.t3           -- round 2 output
  let round3 := mulMontRound lhs modulus inv b3 ⟨r0, r1, r2, r3, r4, q, t1, t3⟩  -- round 3
  let r0 := round3.r0           -- round 3 output
  let r1 := round3.r1           -- round 3 output
  let r2 := round3.r2           -- round 3 output
  let r3 := round3.r3           -- round 3 output
  let r4 := round3.r4           -- round 3 output
  let q := round3.q             -- round 3 output
  let t1 := round3.t1           -- round 3 output
  let t3 := round3.t3           -- round 3 output
  let c := (subc r0 1 1).2      -- subs xzr,r0,#1
  let t0 := umulh p0 q          -- umulh t0,p0,q
  let s := addc r1 t1 c         -- adcs r1,r1,t1
  let r1 := s.1                 --   `-> r1
  let c := s.2                  --   `-> carry
  let t1 := umulh p1 q          -- umulh t1,p1,q
  let s := addc r2 0 c          -- adcs r2,r2,xzr
  let r2 := s.1                 --   `-> r2
  let c := s.2                  --   `-> carry
  let s := addc r3 t3 c         -- adcs r3,r3,t3
  let r3 := s.1                 --   `-> r3
  let c := s.2                  --   `-> carry
  let t3 := lsr q 2             -- lsr t3,q,#2
  let r4 := (addc r4 0 c).1     -- adc r4,r4,xzr
  let s := addc r1 t0 0         -- adds r0,r1,t0
  let r0 := s.1                 --   `-> r0
  let c := s.2                  --   `-> carry
  let s := addc r2 t1 c         -- adcs r1,r2,t1
  let r1 := s.1                 --   `-> r1
  let c := s.2                  --   `-> carry
  let s := addc r3 0 c          -- adcs r2,r3,xzr
  let r2 := s.1                 --   `-> r2
  let c := s.2                  --   `-> carry
  let s := addc r4 t3 c         -- adcs r3,r4,t3
  let r3 := s.1                 --   `-> r3
  let q := 4611686018427387904  -- mov q,#0x4000000000000000
  let s := subc r0 p0 1         -- subs t0,r0,p0
  let t0 := s.1                 --   `-> t0
  let c := s.2                  --   `-> carry
  let s := subc r1 p1 c         -- sbcs t1,r1,p1
  let t1 := s.1                 --   `-> t1
  let c := s.2                  --   `-> carry
  let s := subc r2 0 c          -- sbcs t2,r2,xzr
  let t2 := s.1                 --   `-> t2
  let c := s.2                  --   `-> carry
  let s := subc r3 q c          -- sbcs t3,r3,q
  let t3 := s.1                 --   `-> t3
  let c := s.2                  --   `-> carry
  let r0 := cselLo c r0 t0      -- csel r0,r0,t0,lo
  let r1 := cselLo c r1 t1      -- csel r1,r1,t1,lo
  let r2 := cselLo c r2 t2      -- csel r2,r2,t2,lo
  let r3 := cselLo c r3 t3      -- csel r3,r3,t3,lo
  ⟨r0, r1, r2, r3⟩

/-- The inline `asm!` block of `square`: Montgomery squaring, `value^2 * 2^-256 mod p`, the squaring
loop body of Semolina's `sqr_n_mul_mont_pasta` followed by a conditional subtraction, with the
result in the block's `inout` operands. -/
def sqrMont (value modulus : Limbs) (inv : Nat) : Limbs :=
  let a0 := value.l0            -- argument
  let a1 := value.l1            -- argument
  let a2 := value.l2            -- argument
  let a3 := value.l3            -- argument
  let p0 := modulus.l0          -- argument
  let p1 := modulus.l1          -- argument
  let inv := inv                -- argument
  let z1 := mulLo a1 a0         -- mul z1,a1,a0
  let w1 := umulh a1 a0         -- umulh w1,a1,a0
  let z2 := mulLo a2 a0         -- mul z2,a2,a0
  let w2 := umulh a2 a0         -- umulh w2,a2,a0
  let z3 := mulLo a3 a0         -- mul z3,a3,a0
  let z4 := umulh a3 a0         -- umulh z4,a3,a0
  let s := addc z2 w1 0         -- adds z2,z2,w1
  let z2 := s.1                 --   `-> z2
  let c := s.2                  --   `-> carry
  let w0 := mulLo a2 a1         -- mul w0,a2,a1
  let w1 := umulh a2 a1         -- umulh w1,a2,a1
  let s := addc z3 w2 c         -- adcs z3,z3,w2
  let z3 := s.1                 --   `-> z3
  let c := s.2                  --   `-> carry
  let w2 := mulLo a3 a1         -- mul w2,a3,a1
  let w3 := umulh a3 a1         -- umulh w3,a3,a1
  let z4 := (addc z4 0 c).1     -- adc z4,z4,xzr
  let z5 := mulLo a3 a2         -- mul z5,a3,a2
  let z6 := umulh a3 a2         -- umulh z6,a3,a2
  let s := addc w1 w2 0         -- adds w1,w1,w2
  let w1 := s.1                 --   `-> w1
  let c := s.2                  --   `-> carry
  let z0 := mulLo a0 a0         -- mul z0,a0,a0
  let w2 := (addc w3 0 c).1     -- adc w2,w3,xzr
  let s := addc z3 w0 0         -- adds z3,z3,w0
  let z3 := s.1                 --   `-> z3
  let c := s.2                  --   `-> carry
  let a0 := umulh a0 a0         -- umulh a0,a0,a0
  let s := addc z4 w1 c         -- adcs z4,z4,w1
  let z4 := s.1                 --   `-> z4
  let c := s.2                  --   `-> carry
  let w1 := mulLo a1 a1         -- mul w1,a1,a1
  let s := addc z5 w2 c         -- adcs z5,z5,w2
  let z5 := s.1                 --   `-> z5
  let c := s.2                  --   `-> carry
  let a1 := umulh a1 a1         -- umulh a1,a1,a1
  let z6 := (addc z6 0 c).1     -- adc z6,z6,xzr
  let s := addc z1 z1 0         -- adds z1,z1,z1
  let z1 := s.1                 --   `-> z1
  let c := s.2                  --   `-> carry
  let w2 := mulLo a2 a2         -- mul w2,a2,a2
  let s := addc z2 z2 c         -- adcs z2,z2,z2
  let z2 := s.1                 --   `-> z2
  let c := s.2                  --   `-> carry
  let a2 := umulh a2 a2         -- umulh a2,a2,a2
  let s := addc z3 z3 c         -- adcs z3,z3,z3
  let z3 := s.1                 --   `-> z3
  let c := s.2                  --   `-> carry
  let w3 := mulLo a3 a3         -- mul w3,a3,a3
  let s := addc z4 z4 c         -- adcs z4,z4,z4
  let z4 := s.1                 --   `-> z4
  let c := s.2                  --   `-> carry
  let a3 := umulh a3 a3         -- umulh a3,a3,a3
  let s := addc z5 z5 c         -- adcs z5,z5,z5
  let z5 := s.1                 --   `-> z5
  let c := s.2                  --   `-> carry
  let s := addc z6 z6 c         -- adcs z6,z6,z6
  let z6 := s.1                 --   `-> z6
  let c := s.2                  --   `-> carry
  let z7 := (addc 0 0 c).1      -- adc z7,xzr,xzr
  let q := mulLo inv z0         -- mul q,inv,z0
  let s := addc z1 a0 0         -- adds z1,z1,a0
  let z1 := s.1                 --   `-> z1
  let c := s.2                  --   `-> carry
  let s := addc z2 w1 c         -- adcs z2,z2,w1
  let z2 := s.1                 --   `-> z2
  let c := s.2                  --   `-> carry
  let s := addc z3 a1 c         -- adcs z3,z3,a1
  let z3 := s.1                 --   `-> z3
  let c := s.2                  --   `-> carry
  let s := addc z4 w2 c         -- adcs z4,z4,w2
  let z4 := s.1                 --   `-> z4
  let c := s.2                  --   `-> carry
  let s := addc z5 a2 c         -- adcs z5,z5,a2
  let z5 := s.1                 --   `-> z5
  let c := s.2                  --   `-> carry
  let s := addc z6 w3 c         -- adcs z6,z6,w3
  let z6 := s.1                 --   `-> z6
  let c := s.2                  --   `-> carry
  let z7 := (addc z7 a3 c).1    -- adc z7,z7,a3
  let w1 := mulLo p1 q          -- mul w1,p1,q
  let w3 := lsl q 62            -- lsl w3,q,#62
  let c := (subc z0 1 1).2      -- subs xzr,z0,#1
  let w0 := umulh p0 q          -- umulh w0,p0,q
  let s := addc z1 w1 c         -- adcs z1,z1,w1
  let z1 := s.1                 --   `-> z1
  let c := s.2                  --   `-> carry
  let w1 := umulh p1 q          -- umulh w1,p1,q
  let s := addc z2 0 c          -- adcs z2,z2,xzr
  let z2 := s.1                 --   `-> z2
  let c := s.2                  --   `-> carry
  let s := addc z3 w3 c         -- adcs z3,z3,w3
  let z3 := s.1                 --   `-> z3
  let c := s.2                  --   `-> carry
  let w3 := lsr q 2             -- lsr w3,q,#2
  let cy := (addc 0 0 c).1      -- adc cy,xzr,xzr
  let s := addc z1 w0 0         -- adds z0,z1,w0
  let z0 := s.1                 --   `-> z0
  let c := s.2                  --   `-> carry
  let s := addc z2 w1 c         -- adcs z1,z2,w1
  let z1 := s.1                 --   `-> z1
  let c := s.2                  --   `-> carry
  let s := addc z3 0 c          -- adcs z2,z3,xzr
  let z2 := s.1                 --   `-> z2
  let c := s.2                  --   `-> carry
  let q := mulLo inv z0         -- mul q,inv,z0
  let z3 := (addc cy w3 c).1    -- adc z3,cy,w3
  let w1 := mulLo p1 q          -- mul w1,p1,q
  let w3 := lsl q 62            -- lsl w3,q,#62
  let c := (subc z0 1 1).2      -- subs xzr,z0,#1
  let w0 := umulh p0 q          -- umulh w0,p0,q
  let s := addc z1 w1 c         -- adcs z1,z1,w1
  let z1 := s.1                 --   `-> z1
  let c := s.2                  --   `-> carry
  let w1 := umulh p1 q          -- umulh w1,p1,q
  let s := addc z2 0 c          -- adcs z2,z2,xzr
  let z2 := s.1                 --   `-> z2
  let c := s.2                  --   `-> carry
  let s := addc z3 w3 c         -- adcs z3,z3,w3
  let z3 := s.1                 --   `-> z3
  let c := s.2                  --   `-> carry
  let w3 := lsr q 2             -- lsr w3,q,#2
  let cy := (addc 0 0 c).1      -- adc cy,xzr,xzr
  let s := addc z1 w0 0         -- adds z0,z1,w0
  let z0 := s.1                 --   `-> z0
  let c := s.2                  --   `-> carry
  let s := addc z2 w1 c         -- adcs z1,z2,w1
  let z1 := s.1                 --   `-> z1
  let c := s.2                  --   `-> carry
  let s := addc z3 0 c          -- adcs z2,z3,xzr
  let z2 := s.1                 --   `-> z2
  let c := s.2                  --   `-> carry
  let q := mulLo inv z0         -- mul q,inv,z0
  let z3 := (addc cy w3 c).1    -- adc z3,cy,w3
  let w1 := mulLo p1 q          -- mul w1,p1,q
  let w3 := lsl q 62            -- lsl w3,q,#62
  let c := (subc z0 1 1).2      -- subs xzr,z0,#1
  let w0 := umulh p0 q          -- umulh w0,p0,q
  let s := addc z1 w1 c         -- adcs z1,z1,w1
  let z1 := s.1                 --   `-> z1
  let c := s.2                  --   `-> carry
  let w1 := umulh p1 q          -- umulh w1,p1,q
  let s := addc z2 0 c          -- adcs z2,z2,xzr
  let z2 := s.1                 --   `-> z2
  let c := s.2                  --   `-> carry
  let s := addc z3 w3 c         -- adcs z3,z3,w3
  let z3 := s.1                 --   `-> z3
  let c := s.2                  --   `-> carry
  let w3 := lsr q 2             -- lsr w3,q,#2
  let cy := (addc 0 0 c).1      -- adc cy,xzr,xzr
  let s := addc z1 w0 0         -- adds z0,z1,w0
  let z0 := s.1                 --   `-> z0
  let c := s.2                  --   `-> carry
  let s := addc z2 w1 c         -- adcs z1,z2,w1
  let z1 := s.1                 --   `-> z1
  let c := s.2                  --   `-> carry
  let s := addc z3 0 c          -- adcs z2,z3,xzr
  let z2 := s.1                 --   `-> z2
  let c := s.2                  --   `-> carry
  let q := mulLo inv z0         -- mul q,inv,z0
  let z3 := (addc cy w3 c).1    -- adc z3,cy,w3
  let w1 := mulLo p1 q          -- mul w1,p1,q
  let w3 := lsl q 62            -- lsl w3,q,#62
  let c := (subc z0 1 1).2      -- subs xzr,z0,#1
  let w0 := umulh p0 q          -- umulh w0,p0,q
  let s := addc z1 w1 c         -- adcs z1,z1,w1
  let z1 := s.1                 --   `-> z1
  let c := s.2                  --   `-> carry
  let w1 := umulh p1 q          -- umulh w1,p1,q
  let s := addc z2 0 c          -- adcs z2,z2,xzr
  let z2 := s.1                 --   `-> z2
  let c := s.2                  --   `-> carry
  let s := addc z3 w3 c         -- adcs z3,z3,w3
  let z3 := s.1                 --   `-> z3
  let c := s.2                  --   `-> carry
  let w3 := lsr q 2             -- lsr w3,q,#2
  let cy := (addc 0 0 c).1      -- adc cy,xzr,xzr
  let s := addc z1 w0 0         -- adds z0,z1,w0
  let z0 := s.1                 --   `-> z0
  let c := s.2                  --   `-> carry
  let s := addc z2 w1 c         -- adcs z1,z2,w1
  let z1 := s.1                 --   `-> z1
  let c := s.2                  --   `-> carry
  let s := addc z3 0 c          -- adcs z2,z3,xzr
  let z2 := s.1                 --   `-> z2
  let c := s.2                  --   `-> carry
  let z3 := (addc cy w3 c).1    -- adc z3,cy,w3
  let s := addc z0 z4 0         -- adds a0,z0,z4
  let a0 := s.1                 --   `-> a0
  let c := s.2                  --   `-> carry
  let s := addc z1 z5 c         -- adcs a1,z1,z5
  let a1 := s.1                 --   `-> a1
  let c := s.2                  --   `-> carry
  let s := addc z2 z6 c         -- adcs a2,z2,z6
  let a2 := s.1                 --   `-> a2
  let c := s.2                  --   `-> carry
  let a3 := (addc z3 z7 c).1    -- adc a3,z3,z7
  let q := 4611686018427387904  -- mov q,#0x4000000000000000
  let s := subc a0 p0 1         -- subs z0,a0,p0
  let z0 := s.1                 --   `-> z0
  let c := s.2                  --   `-> carry
  let s := subc a1 p1 c         -- sbcs z1,a1,p1
  let z1 := s.1                 --   `-> z1
  let c := s.2                  --   `-> carry
  let s := subc a2 0 c          -- sbcs z2,a2,xzr
  let z2 := s.1                 --   `-> z2
  let c := s.2                  --   `-> carry
  let s := subc a3 q c          -- sbcs z3,a3,q
  let z3 := s.1                 --   `-> z3
  let c := s.2                  --   `-> carry
  let a0 := cselLo c a0 z0      -- csel a0,a0,z0,lo
  let a1 := cselLo c a1 z1      -- csel a1,a1,z1,lo
  let a2 := cselLo c a2 z2      -- csel a2,a2,z2,lo
  let a3 := cselLo c a3 z3      -- csel a3,a3,z3,lo
  ⟨a0, a1, a2, a3⟩

/-- The inline `asm!` block of `add`: modular addition, `lhs + rhs mod p`, as a full-width addition,
a subtraction of the modulus, and the selection of the reduced sum when that subtraction did not
borrow, with the result in the block's `inout` operands. -/
def addMod (lhs rhs modulus : Limbs) : Limbs :=
  let r0 := lhs.l0              -- argument
  let r1 := lhs.l1              -- argument
  let r2 := lhs.l2              -- argument
  let r3 := lhs.l3              -- argument
  let b0 := rhs.l0              -- argument
  let b1 := rhs.l1              -- argument
  let b2 := rhs.l2              -- argument
  let b3 := rhs.l3              -- argument
  let p0 := modulus.l0          -- argument
  let p1 := modulus.l1          -- argument
  let p3 := modulus.l3          -- argument
  let s := addc r0 b0 0         -- adds r0,r0,b0
  let r0 := s.1                 --   `-> r0
  let c := s.2                  --   `-> carry
  let s := addc r1 b1 c         -- adcs r1,r1,b1
  let r1 := s.1                 --   `-> r1
  let c := s.2                  --   `-> carry
  let s := addc r2 b2 c         -- adcs r2,r2,b2
  let r2 := s.1                 --   `-> r2
  let c := s.2                  --   `-> carry
  let r3 := (addc r3 b3 c).1    -- adc r3,r3,b3
  let s := subc r0 p0 1         -- subs t0,r0,p0
  let t0 := s.1                 --   `-> t0
  let c := s.2                  --   `-> carry
  let s := subc r1 p1 c         -- sbcs t1,r1,p1
  let t1 := s.1                 --   `-> t1
  let c := s.2                  --   `-> carry
  let s := subc r2 0 c          -- sbcs t2,r2,xzr
  let t2 := s.1                 --   `-> t2
  let c := s.2                  --   `-> carry
  let s := subc r3 p3 c         -- sbcs t3,r3,p3
  let t3 := s.1                 --   `-> t3
  let c := s.2                  --   `-> carry
  let r0 := cselCs c t0 r0      -- csel r0,t0,r0,cs
  let r1 := cselCs c t1 r1      -- csel r1,t1,r1,cs
  let r2 := cselCs c t2 r2      -- csel r2,t2,r2,cs
  let r3 := cselCs c t3 r3      -- csel r3,t3,r3,cs
  ⟨r0, r1, r2, r3⟩

/-- The inline `asm!` block of `sub`: modular subtraction, `lhs - rhs mod p`, as a full-width
subtraction and the addition of the modulus when it borrowed, with the result in the block's `inout`
operands. -/
def subMod (lhs rhs modulus : Limbs) : Limbs :=
  let r0 := lhs.l0              -- argument
  let r1 := lhs.l1              -- argument
  let r2 := lhs.l2              -- argument
  let r3 := lhs.l3              -- argument
  let b0 := rhs.l0              -- argument
  let b1 := rhs.l1              -- argument
  let b2 := rhs.l2              -- argument
  let b3 := rhs.l3              -- argument
  let p0 := modulus.l0          -- argument
  let p1 := modulus.l1          -- argument
  let p3 := modulus.l3          -- argument
  let s := subc r0 b0 1         -- subs r0,r0,b0
  let r0 := s.1                 --   `-> r0
  let c := s.2                  --   `-> carry
  let s := subc r1 b1 c         -- sbcs r1,r1,b1
  let r1 := s.1                 --   `-> r1
  let c := s.2                  --   `-> carry
  let s := subc r2 b2 c         -- sbcs r2,r2,b2
  let r2 := s.1                 --   `-> r2
  let c := s.2                  --   `-> carry
  let s := subc r3 b3 c         -- sbcs r3,r3,b3
  let r3 := s.1                 --   `-> r3
  let c := s.2                  --   `-> carry
  let t0 := cselLo c p0 0       -- csel t0,p0,xzr,cc
  let t1 := cselLo c p1 0       -- csel t1,p1,xzr,cc
  let t3 := cselLo c p3 0       -- csel t3,p3,xzr,cc
  let s := addc r0 t0 0         -- adds r0,r0,t0
  let r0 := s.1                 --   `-> r0
  let c := s.2                  --   `-> carry
  let s := addc r1 t1 c         -- adcs r1,r1,t1
  let r1 := s.1                 --   `-> r1
  let c := s.2                  --   `-> carry
  let s := addc r2 0 c          -- adcs r2,r2,xzr
  let r2 := s.1                 --   `-> r2
  let c := s.2                  --   `-> carry
  let r3 := (addc r3 t3 c).1    -- adc r3,r3,t3
  ⟨r0, r1, r2, r3⟩

/-- The registers that `divstepRound` carries in and out. -/
structure DivstepState where
  /-- `two_delta = 2δ`, as a two's-complement word -/
  two_delta : Nat
  /-- the packed `f` word -/
  f : Nat
  /-- the packed `g` word -/
  g : Nat
  /-- the flags, set by the parity test of the packed `g` word -/
  fl : Flags
  deriving DecidableEq, Repr

namespace DivstepState

/-- Every word is below `2^64`. -/
def Bounded (s : DivstepState) : Prop :=
   s.two_delta < 2^64 ∧ s.f < 2^64 ∧ s.g < 2^64

end DivstepState

/-- `divstep!()`, one packed half-delta divstep on the words `f` and `g` at `two_delta`, from the
flags of the parity test of `g`, ending with the parity test of the new `g` for the next step -/
def divstepRound (st : DivstepState) : DivstepState :=
  let two_delta := st.two_delta  -- argument
  let pf := st.f                -- argument
  let pg := st.g                -- argument
  let fl := st.fl               -- argument
  let t := cselNe fl pf 0       -- csel t,pf,xzr,ne
  let fl := ccmpNe fl two_delta 0 8  -- ccmp two_delta,xzr,#8,ne
  let two_delta := cnegGe fl two_delta  -- cneg two_delta,two_delta,ge
  let t := cnegGe fl t          -- cneg t,t,ge
  let pf := cselGe fl pg pf     -- csel pf,pg,pf,ge
  let pg := addw pg t           -- add pg,pg,t
  let two_delta := addw two_delta 2  -- add two_delta,two_delta,#2
  let fl := tstFlags (andw pg 2)  -- tst pg,#2
  let pg := asr pg 1            -- asr pg,pg,#1
  ⟨two_delta, pf, pg, fl⟩

/-- `divstep!(last)`, the last divstep of a batch: `divstepRound` without the parity test at its end
-/
def divstepLast (st : DivstepState) : DivstepState :=
  let two_delta := st.two_delta  -- argument
  let pf := st.f                -- argument
  let pg := st.g                -- argument
  let fl := st.fl               -- argument
  let t := cselNe fl pf 0       -- csel t,pf,xzr,ne
  let fl := ccmpNe fl two_delta 0 8  -- ccmp two_delta,xzr,#8,ne
  let two_delta := cnegGe fl two_delta  -- cneg two_delta,two_delta,ge
  let t := cnegGe fl t          -- cneg t,t,ge
  let pf := cselGe fl pg pf     -- csel pf,pg,pf,ge
  let pg := addw pg t           -- add pg,pg,t
  let two_delta := addw two_delta 2  -- add two_delta,two_delta,#2
  let pg := asr pg 1            -- asr pg,pg,#1
  ⟨two_delta, pf, pg, fl⟩

/-- The result of `divstep59Block`: the new `two_delta` and the entries of the 59-step matrix, each
a two's-complement word. -/
structure Divstep59Result where
  two_delta : Nat
  u : Nat
  v : Nat
  q : Nat
  r : Nat
  deriving DecidableEq, Repr

/-- The inline `asm!` block of `divstep59`: 59 half-delta divsteps on the low words `f0` and `g0` of
`f` and `g` at `two_delta`, as three packed batches of 20, 20, and 19 steps in which the matrix
coefficients ride in the upper bits of the two words, with the two matrix products between and after
the batches. It is s2n-bignum's `divstep59` macro on named registers. The result is the new
`two_delta` and the 59-step matrix, as two's-complement words. -/
def divstep59Block (two_delta f0 g0 : Nat) : Divstep59Result :=
  let two_delta := two_delta    -- argument
  let f := f0                   -- argument
  let g := g0                   -- argument
  let pf := andw f 1048575      -- and pf,f,#0xfffff
  let pf := orrw pf 18446741874686296064  -- orr pf,pf,#0xfffffe0000000000
  let pg := andw g 1048575      -- and pg,g,#0xfffff
  let pg := orrw pg 13835058055282163712  -- orr pg,pg,#0xc000000000000000
  let fl := tstFlags (andw pg 1)  -- tst pg,#1
  let step1 := divstepRound ⟨two_delta, pf, pg, fl⟩  -- divstep!(), invocation 1
  let two_delta := step1.two_delta  -- divstep!(), invocation 1 output
  let pf := step1.f             -- divstep!(), invocation 1 output
  let pg := step1.g             -- divstep!(), invocation 1 output
  let fl := step1.fl            -- divstep!(), invocation 1 output
  let step2 := divstepRound ⟨two_delta, pf, pg, fl⟩  -- divstep!(), invocation 2
  let two_delta := step2.two_delta  -- divstep!(), invocation 2 output
  let pf := step2.f             -- divstep!(), invocation 2 output
  let pg := step2.g             -- divstep!(), invocation 2 output
  let fl := step2.fl            -- divstep!(), invocation 2 output
  let step3 := divstepRound ⟨two_delta, pf, pg, fl⟩  -- divstep!(), invocation 3
  let two_delta := step3.two_delta  -- divstep!(), invocation 3 output
  let pf := step3.f             -- divstep!(), invocation 3 output
  let pg := step3.g             -- divstep!(), invocation 3 output
  let fl := step3.fl            -- divstep!(), invocation 3 output
  let step4 := divstepRound ⟨two_delta, pf, pg, fl⟩  -- divstep!(), invocation 4
  let two_delta := step4.two_delta  -- divstep!(), invocation 4 output
  let pf := step4.f             -- divstep!(), invocation 4 output
  let pg := step4.g             -- divstep!(), invocation 4 output
  let fl := step4.fl            -- divstep!(), invocation 4 output
  let step5 := divstepRound ⟨two_delta, pf, pg, fl⟩  -- divstep!(), invocation 5
  let two_delta := step5.two_delta  -- divstep!(), invocation 5 output
  let pf := step5.f             -- divstep!(), invocation 5 output
  let pg := step5.g             -- divstep!(), invocation 5 output
  let fl := step5.fl            -- divstep!(), invocation 5 output
  let step6 := divstepRound ⟨two_delta, pf, pg, fl⟩  -- divstep!(), invocation 6
  let two_delta := step6.two_delta  -- divstep!(), invocation 6 output
  let pf := step6.f             -- divstep!(), invocation 6 output
  let pg := step6.g             -- divstep!(), invocation 6 output
  let fl := step6.fl            -- divstep!(), invocation 6 output
  let step7 := divstepRound ⟨two_delta, pf, pg, fl⟩  -- divstep!(), invocation 7
  let two_delta := step7.two_delta  -- divstep!(), invocation 7 output
  let pf := step7.f             -- divstep!(), invocation 7 output
  let pg := step7.g             -- divstep!(), invocation 7 output
  let fl := step7.fl            -- divstep!(), invocation 7 output
  let step8 := divstepRound ⟨two_delta, pf, pg, fl⟩  -- divstep!(), invocation 8
  let two_delta := step8.two_delta  -- divstep!(), invocation 8 output
  let pf := step8.f             -- divstep!(), invocation 8 output
  let pg := step8.g             -- divstep!(), invocation 8 output
  let fl := step8.fl            -- divstep!(), invocation 8 output
  let step9 := divstepRound ⟨two_delta, pf, pg, fl⟩  -- divstep!(), invocation 9
  let two_delta := step9.two_delta  -- divstep!(), invocation 9 output
  let pf := step9.f             -- divstep!(), invocation 9 output
  let pg := step9.g             -- divstep!(), invocation 9 output
  let fl := step9.fl            -- divstep!(), invocation 9 output
  let step10 := divstepRound ⟨two_delta, pf, pg, fl⟩  -- divstep!(), invocation 10
  let two_delta := step10.two_delta  -- divstep!(), invocation 10 output
  let pf := step10.f            -- divstep!(), invocation 10 output
  let pg := step10.g            -- divstep!(), invocation 10 output
  let fl := step10.fl           -- divstep!(), invocation 10 output
  let step11 := divstepRound ⟨two_delta, pf, pg, fl⟩  -- divstep!(), invocation 11
  let two_delta := step11.two_delta  -- divstep!(), invocation 11 output
  let pf := step11.f            -- divstep!(), invocation 11 output
  let pg := step11.g            -- divstep!(), invocation 11 output
  let fl := step11.fl           -- divstep!(), invocation 11 output
  let step12 := divstepRound ⟨two_delta, pf, pg, fl⟩  -- divstep!(), invocation 12
  let two_delta := step12.two_delta  -- divstep!(), invocation 12 output
  let pf := step12.f            -- divstep!(), invocation 12 output
  let pg := step12.g            -- divstep!(), invocation 12 output
  let fl := step12.fl           -- divstep!(), invocation 12 output
  let step13 := divstepRound ⟨two_delta, pf, pg, fl⟩  -- divstep!(), invocation 13
  let two_delta := step13.two_delta  -- divstep!(), invocation 13 output
  let pf := step13.f            -- divstep!(), invocation 13 output
  let pg := step13.g            -- divstep!(), invocation 13 output
  let fl := step13.fl           -- divstep!(), invocation 13 output
  let step14 := divstepRound ⟨two_delta, pf, pg, fl⟩  -- divstep!(), invocation 14
  let two_delta := step14.two_delta  -- divstep!(), invocation 14 output
  let pf := step14.f            -- divstep!(), invocation 14 output
  let pg := step14.g            -- divstep!(), invocation 14 output
  let fl := step14.fl           -- divstep!(), invocation 14 output
  let step15 := divstepRound ⟨two_delta, pf, pg, fl⟩  -- divstep!(), invocation 15
  let two_delta := step15.two_delta  -- divstep!(), invocation 15 output
  let pf := step15.f            -- divstep!(), invocation 15 output
  let pg := step15.g            -- divstep!(), invocation 15 output
  let fl := step15.fl           -- divstep!(), invocation 15 output
  let step16 := divstepRound ⟨two_delta, pf, pg, fl⟩  -- divstep!(), invocation 16
  let two_delta := step16.two_delta  -- divstep!(), invocation 16 output
  let pf := step16.f            -- divstep!(), invocation 16 output
  let pg := step16.g            -- divstep!(), invocation 16 output
  let fl := step16.fl           -- divstep!(), invocation 16 output
  let step17 := divstepRound ⟨two_delta, pf, pg, fl⟩  -- divstep!(), invocation 17
  let two_delta := step17.two_delta  -- divstep!(), invocation 17 output
  let pf := step17.f            -- divstep!(), invocation 17 output
  let pg := step17.g            -- divstep!(), invocation 17 output
  let fl := step17.fl           -- divstep!(), invocation 17 output
  let step18 := divstepRound ⟨two_delta, pf, pg, fl⟩  -- divstep!(), invocation 18
  let two_delta := step18.two_delta  -- divstep!(), invocation 18 output
  let pf := step18.f            -- divstep!(), invocation 18 output
  let pg := step18.g            -- divstep!(), invocation 18 output
  let fl := step18.fl           -- divstep!(), invocation 18 output
  let step19 := divstepRound ⟨two_delta, pf, pg, fl⟩  -- divstep!(), invocation 19
  let two_delta := step19.two_delta  -- divstep!(), invocation 19 output
  let pf := step19.f            -- divstep!(), invocation 19 output
  let pg := step19.g            -- divstep!(), invocation 19 output
  let fl := step19.fl           -- divstep!(), invocation 19 output
  let step20 := divstepLast ⟨two_delta, pf, pg, fl⟩  -- divstep!(last), invocation 20
  let two_delta := step20.two_delta  -- divstep!(last), invocation 20 output
  let pf := step20.f            -- divstep!(last), invocation 20 output
  let pg := step20.g            -- divstep!(last), invocation 20 output
  -- divstep!(last), invocation 20 output: fl = step20.fl is never read
  let a00 := addw pf 1048576    -- add a00,pf,#0x100,lsl #12
  let a00 := sbfx a00 21 21     -- sbfx a00,a00,#21,#21
  let a11 := 1048576            -- mov a11,#0x100000
  let a11 := addw a11 (lsl a11 21)  -- add a11,a11,a11,lsl #21
  let a01 := addw pf a11        -- add a01,pf,a11
  let a01 := asr a01 42         -- asr a01,a01,#42
  let a10 := addw pg 1048576    -- add a10,pg,#0x100,lsl #12
  let a10 := sbfx a10 21 21     -- sbfx a10,a10,#21,#21
  let a11 := addw pg a11        -- add a11,pg,a11
  let a11 := asr a11 42         -- asr a11,a11,#42
  let t := mulLo a00 f          -- mul t,a00,f
  let t2 := mulLo a01 g         -- mul t2,a01,g
  let f := mulLo a10 f          -- mul f,a10,f
  let g := mulLo a11 g          -- mul g,a11,g
  let pf := addw t t2           -- add pf,t,t2
  let pg := addw f g            -- add pg,f,g
  let f := asr pf 20            -- asr f,pf,#20
  let g := asr pg 20            -- asr g,pg,#20
  let pf := andw f 1048575      -- and pf,f,#0xfffff
  let pf := orrw pf 18446741874686296064  -- orr pf,pf,#0xfffffe0000000000
  let pg := andw g 1048575      -- and pg,g,#0xfffff
  let pg := orrw pg 13835058055282163712  -- orr pg,pg,#0xc000000000000000
  let fl := tstFlags (andw pg 1)  -- tst pg,#1
  let step21 := divstepRound ⟨two_delta, pf, pg, fl⟩  -- divstep!(), invocation 21
  let two_delta := step21.two_delta  -- divstep!(), invocation 21 output
  let pf := step21.f            -- divstep!(), invocation 21 output
  let pg := step21.g            -- divstep!(), invocation 21 output
  let fl := step21.fl           -- divstep!(), invocation 21 output
  let step22 := divstepRound ⟨two_delta, pf, pg, fl⟩  -- divstep!(), invocation 22
  let two_delta := step22.two_delta  -- divstep!(), invocation 22 output
  let pf := step22.f            -- divstep!(), invocation 22 output
  let pg := step22.g            -- divstep!(), invocation 22 output
  let fl := step22.fl           -- divstep!(), invocation 22 output
  let step23 := divstepRound ⟨two_delta, pf, pg, fl⟩  -- divstep!(), invocation 23
  let two_delta := step23.two_delta  -- divstep!(), invocation 23 output
  let pf := step23.f            -- divstep!(), invocation 23 output
  let pg := step23.g            -- divstep!(), invocation 23 output
  let fl := step23.fl           -- divstep!(), invocation 23 output
  let step24 := divstepRound ⟨two_delta, pf, pg, fl⟩  -- divstep!(), invocation 24
  let two_delta := step24.two_delta  -- divstep!(), invocation 24 output
  let pf := step24.f            -- divstep!(), invocation 24 output
  let pg := step24.g            -- divstep!(), invocation 24 output
  let fl := step24.fl           -- divstep!(), invocation 24 output
  let step25 := divstepRound ⟨two_delta, pf, pg, fl⟩  -- divstep!(), invocation 25
  let two_delta := step25.two_delta  -- divstep!(), invocation 25 output
  let pf := step25.f            -- divstep!(), invocation 25 output
  let pg := step25.g            -- divstep!(), invocation 25 output
  let fl := step25.fl           -- divstep!(), invocation 25 output
  let step26 := divstepRound ⟨two_delta, pf, pg, fl⟩  -- divstep!(), invocation 26
  let two_delta := step26.two_delta  -- divstep!(), invocation 26 output
  let pf := step26.f            -- divstep!(), invocation 26 output
  let pg := step26.g            -- divstep!(), invocation 26 output
  let fl := step26.fl           -- divstep!(), invocation 26 output
  let step27 := divstepRound ⟨two_delta, pf, pg, fl⟩  -- divstep!(), invocation 27
  let two_delta := step27.two_delta  -- divstep!(), invocation 27 output
  let pf := step27.f            -- divstep!(), invocation 27 output
  let pg := step27.g            -- divstep!(), invocation 27 output
  let fl := step27.fl           -- divstep!(), invocation 27 output
  let step28 := divstepRound ⟨two_delta, pf, pg, fl⟩  -- divstep!(), invocation 28
  let two_delta := step28.two_delta  -- divstep!(), invocation 28 output
  let pf := step28.f            -- divstep!(), invocation 28 output
  let pg := step28.g            -- divstep!(), invocation 28 output
  let fl := step28.fl           -- divstep!(), invocation 28 output
  let step29 := divstepRound ⟨two_delta, pf, pg, fl⟩  -- divstep!(), invocation 29
  let two_delta := step29.two_delta  -- divstep!(), invocation 29 output
  let pf := step29.f            -- divstep!(), invocation 29 output
  let pg := step29.g            -- divstep!(), invocation 29 output
  let fl := step29.fl           -- divstep!(), invocation 29 output
  let step30 := divstepRound ⟨two_delta, pf, pg, fl⟩  -- divstep!(), invocation 30
  let two_delta := step30.two_delta  -- divstep!(), invocation 30 output
  let pf := step30.f            -- divstep!(), invocation 30 output
  let pg := step30.g            -- divstep!(), invocation 30 output
  let fl := step30.fl           -- divstep!(), invocation 30 output
  let step31 := divstepRound ⟨two_delta, pf, pg, fl⟩  -- divstep!(), invocation 31
  let two_delta := step31.two_delta  -- divstep!(), invocation 31 output
  let pf := step31.f            -- divstep!(), invocation 31 output
  let pg := step31.g            -- divstep!(), invocation 31 output
  let fl := step31.fl           -- divstep!(), invocation 31 output
  let step32 := divstepRound ⟨two_delta, pf, pg, fl⟩  -- divstep!(), invocation 32
  let two_delta := step32.two_delta  -- divstep!(), invocation 32 output
  let pf := step32.f            -- divstep!(), invocation 32 output
  let pg := step32.g            -- divstep!(), invocation 32 output
  let fl := step32.fl           -- divstep!(), invocation 32 output
  let step33 := divstepRound ⟨two_delta, pf, pg, fl⟩  -- divstep!(), invocation 33
  let two_delta := step33.two_delta  -- divstep!(), invocation 33 output
  let pf := step33.f            -- divstep!(), invocation 33 output
  let pg := step33.g            -- divstep!(), invocation 33 output
  let fl := step33.fl           -- divstep!(), invocation 33 output
  let step34 := divstepRound ⟨two_delta, pf, pg, fl⟩  -- divstep!(), invocation 34
  let two_delta := step34.two_delta  -- divstep!(), invocation 34 output
  let pf := step34.f            -- divstep!(), invocation 34 output
  let pg := step34.g            -- divstep!(), invocation 34 output
  let fl := step34.fl           -- divstep!(), invocation 34 output
  let step35 := divstepRound ⟨two_delta, pf, pg, fl⟩  -- divstep!(), invocation 35
  let two_delta := step35.two_delta  -- divstep!(), invocation 35 output
  let pf := step35.f            -- divstep!(), invocation 35 output
  let pg := step35.g            -- divstep!(), invocation 35 output
  let fl := step35.fl           -- divstep!(), invocation 35 output
  let step36 := divstepRound ⟨two_delta, pf, pg, fl⟩  -- divstep!(), invocation 36
  let two_delta := step36.two_delta  -- divstep!(), invocation 36 output
  let pf := step36.f            -- divstep!(), invocation 36 output
  let pg := step36.g            -- divstep!(), invocation 36 output
  let fl := step36.fl           -- divstep!(), invocation 36 output
  let step37 := divstepRound ⟨two_delta, pf, pg, fl⟩  -- divstep!(), invocation 37
  let two_delta := step37.two_delta  -- divstep!(), invocation 37 output
  let pf := step37.f            -- divstep!(), invocation 37 output
  let pg := step37.g            -- divstep!(), invocation 37 output
  let fl := step37.fl           -- divstep!(), invocation 37 output
  let step38 := divstepRound ⟨two_delta, pf, pg, fl⟩  -- divstep!(), invocation 38
  let two_delta := step38.two_delta  -- divstep!(), invocation 38 output
  let pf := step38.f            -- divstep!(), invocation 38 output
  let pg := step38.g            -- divstep!(), invocation 38 output
  let fl := step38.fl           -- divstep!(), invocation 38 output
  let step39 := divstepRound ⟨two_delta, pf, pg, fl⟩  -- divstep!(), invocation 39
  let two_delta := step39.two_delta  -- divstep!(), invocation 39 output
  let pf := step39.f            -- divstep!(), invocation 39 output
  let pg := step39.g            -- divstep!(), invocation 39 output
  let fl := step39.fl           -- divstep!(), invocation 39 output
  let step40 := divstepLast ⟨two_delta, pf, pg, fl⟩  -- divstep!(last), invocation 40
  let two_delta := step40.two_delta  -- divstep!(last), invocation 40 output
  let pf := step40.f            -- divstep!(last), invocation 40 output
  let pg := step40.g            -- divstep!(last), invocation 40 output
  -- divstep!(last), invocation 40 output: fl = step40.fl is never read
  let b00 := addw pf 1048576    -- add b00,pf,#0x100,lsl #12
  let b00 := sbfx b00 21 21     -- sbfx b00,b00,#21,#21
  let b11 := 1048576            -- mov b11,#0x100000
  let b11 := addw b11 (lsl b11 21)  -- add b11,b11,b11,lsl #21
  let b01 := addw pf b11        -- add b01,pf,b11
  let b01 := asr b01 42         -- asr b01,b01,#42
  let b10 := addw pg 1048576    -- add b10,pg,#0x100,lsl #12
  let b10 := sbfx b10 21 21     -- sbfx b10,b10,#21,#21
  let b11 := addw pg b11        -- add b11,pg,b11
  let b11 := asr b11 42         -- asr b11,b11,#42
  let t := mulLo b00 f          -- mul t,b00,f
  let t2 := mulLo b01 g         -- mul t2,b01,g
  let f := mulLo b10 f          -- mul f,b10,f
  let g := mulLo b11 g          -- mul g,b11,g
  let pf := addw t t2           -- add pf,t,t2
  let pg := addw f g            -- add pg,f,g
  let f := asr pf 20            -- asr f,pf,#20
  let g := asr pg 20            -- asr g,pg,#20
  let pf := andw f 1048575      -- and pf,f,#0xfffff
  let pf := orrw pf 18446741874686296064  -- orr pf,pf,#0xfffffe0000000000
  let pg := andw g 1048575      -- and pg,g,#0xfffff
  let pg := orrw pg 13835058055282163712  -- orr pg,pg,#0xc000000000000000
  let fl := tstFlags (andw pg 1)  -- tst pg,#1
  let step41 := divstepRound ⟨two_delta, pf, pg, fl⟩  -- divstep!(), invocation 41
  let two_delta := step41.two_delta  -- divstep!(), invocation 41 output
  let pf := step41.f            -- divstep!(), invocation 41 output
  let pg := step41.g            -- divstep!(), invocation 41 output
  let fl := step41.fl           -- divstep!(), invocation 41 output
  let step42 := divstepRound ⟨two_delta, pf, pg, fl⟩  -- divstep!(), invocation 42
  let two_delta := step42.two_delta  -- divstep!(), invocation 42 output
  let pf := step42.f            -- divstep!(), invocation 42 output
  let pg := step42.g            -- divstep!(), invocation 42 output
  let fl := step42.fl           -- divstep!(), invocation 42 output
  let step43 := divstepRound ⟨two_delta, pf, pg, fl⟩  -- divstep!(), invocation 43
  let two_delta := step43.two_delta  -- divstep!(), invocation 43 output
  let pf := step43.f            -- divstep!(), invocation 43 output
  let pg := step43.g            -- divstep!(), invocation 43 output
  let fl := step43.fl           -- divstep!(), invocation 43 output
  let step44 := divstepRound ⟨two_delta, pf, pg, fl⟩  -- divstep!(), invocation 44
  let two_delta := step44.two_delta  -- divstep!(), invocation 44 output
  let pf := step44.f            -- divstep!(), invocation 44 output
  let pg := step44.g            -- divstep!(), invocation 44 output
  let fl := step44.fl           -- divstep!(), invocation 44 output
  let step45 := divstepRound ⟨two_delta, pf, pg, fl⟩  -- divstep!(), invocation 45
  let two_delta := step45.two_delta  -- divstep!(), invocation 45 output
  let pf := step45.f            -- divstep!(), invocation 45 output
  let pg := step45.g            -- divstep!(), invocation 45 output
  let fl := step45.fl           -- divstep!(), invocation 45 output
  let step46 := divstepRound ⟨two_delta, pf, pg, fl⟩  -- divstep!(), invocation 46
  let two_delta := step46.two_delta  -- divstep!(), invocation 46 output
  let pf := step46.f            -- divstep!(), invocation 46 output
  let pg := step46.g            -- divstep!(), invocation 46 output
  let fl := step46.fl           -- divstep!(), invocation 46 output
  let step47 := divstepRound ⟨two_delta, pf, pg, fl⟩  -- divstep!(), invocation 47
  let two_delta := step47.two_delta  -- divstep!(), invocation 47 output
  let pf := step47.f            -- divstep!(), invocation 47 output
  let pg := step47.g            -- divstep!(), invocation 47 output
  let fl := step47.fl           -- divstep!(), invocation 47 output
  let step48 := divstepRound ⟨two_delta, pf, pg, fl⟩  -- divstep!(), invocation 48
  let two_delta := step48.two_delta  -- divstep!(), invocation 48 output
  let pf := step48.f            -- divstep!(), invocation 48 output
  let pg := step48.g            -- divstep!(), invocation 48 output
  let fl := step48.fl           -- divstep!(), invocation 48 output
  let step49 := divstepRound ⟨two_delta, pf, pg, fl⟩  -- divstep!(), invocation 49
  let two_delta := step49.two_delta  -- divstep!(), invocation 49 output
  let pf := step49.f            -- divstep!(), invocation 49 output
  let pg := step49.g            -- divstep!(), invocation 49 output
  let fl := step49.fl           -- divstep!(), invocation 49 output
  let step50 := divstepRound ⟨two_delta, pf, pg, fl⟩  -- divstep!(), invocation 50
  let two_delta := step50.two_delta  -- divstep!(), invocation 50 output
  let pf := step50.f            -- divstep!(), invocation 50 output
  let pg := step50.g            -- divstep!(), invocation 50 output
  let fl := step50.fl           -- divstep!(), invocation 50 output
  let f := mulLo b00 a00        -- mul f,b00,a00
  let g := mulLo b00 a01        -- mul g,b00,a01
  let t := mulLo b10 a00        -- mul t,b10,a00
  let t2 := mulLo b10 a01       -- mul t2,b10,a01
  let a00 := madd b01 a10 f     -- madd a00,b01,a10,f
  let a01 := madd b01 a11 g     -- madd a01,b01,a11,g
  let c10 := madd b11 a10 t     -- madd c10,b11,a10,t
  let c11 := madd b11 a11 t2    -- madd c11,b11,a11,t2
  let step51 := divstepRound ⟨two_delta, pf, pg, fl⟩  -- divstep!(), invocation 51
  let two_delta := step51.two_delta  -- divstep!(), invocation 51 output
  let pf := step51.f            -- divstep!(), invocation 51 output
  let pg := step51.g            -- divstep!(), invocation 51 output
  let fl := step51.fl           -- divstep!(), invocation 51 output
  let step52 := divstepRound ⟨two_delta, pf, pg, fl⟩  -- divstep!(), invocation 52
  let two_delta := step52.two_delta  -- divstep!(), invocation 52 output
  let pf := step52.f            -- divstep!(), invocation 52 output
  let pg := step52.g            -- divstep!(), invocation 52 output
  let fl := step52.fl           -- divstep!(), invocation 52 output
  let step53 := divstepRound ⟨two_delta, pf, pg, fl⟩  -- divstep!(), invocation 53
  let two_delta := step53.two_delta  -- divstep!(), invocation 53 output
  let pf := step53.f            -- divstep!(), invocation 53 output
  let pg := step53.g            -- divstep!(), invocation 53 output
  let fl := step53.fl           -- divstep!(), invocation 53 output
  let step54 := divstepRound ⟨two_delta, pf, pg, fl⟩  -- divstep!(), invocation 54
  let two_delta := step54.two_delta  -- divstep!(), invocation 54 output
  let pf := step54.f            -- divstep!(), invocation 54 output
  let pg := step54.g            -- divstep!(), invocation 54 output
  let fl := step54.fl           -- divstep!(), invocation 54 output
  let step55 := divstepRound ⟨two_delta, pf, pg, fl⟩  -- divstep!(), invocation 55
  let two_delta := step55.two_delta  -- divstep!(), invocation 55 output
  let pf := step55.f            -- divstep!(), invocation 55 output
  let pg := step55.g            -- divstep!(), invocation 55 output
  let fl := step55.fl           -- divstep!(), invocation 55 output
  let step56 := divstepRound ⟨two_delta, pf, pg, fl⟩  -- divstep!(), invocation 56
  let two_delta := step56.two_delta  -- divstep!(), invocation 56 output
  let pf := step56.f            -- divstep!(), invocation 56 output
  let pg := step56.g            -- divstep!(), invocation 56 output
  let fl := step56.fl           -- divstep!(), invocation 56 output
  let step57 := divstepRound ⟨two_delta, pf, pg, fl⟩  -- divstep!(), invocation 57
  let two_delta := step57.two_delta  -- divstep!(), invocation 57 output
  let pf := step57.f            -- divstep!(), invocation 57 output
  let pg := step57.g            -- divstep!(), invocation 57 output
  let fl := step57.fl           -- divstep!(), invocation 57 output
  let step58 := divstepRound ⟨two_delta, pf, pg, fl⟩  -- divstep!(), invocation 58
  let two_delta := step58.two_delta  -- divstep!(), invocation 58 output
  let pf := step58.f            -- divstep!(), invocation 58 output
  let pg := step58.g            -- divstep!(), invocation 58 output
  let fl := step58.fl           -- divstep!(), invocation 58 output
  let step59 := divstepLast ⟨two_delta, pf, pg, fl⟩  -- divstep!(last), invocation 59
  let two_delta := step59.two_delta  -- divstep!(last), invocation 59 output
  let pf := step59.f            -- divstep!(last), invocation 59 output
  let pg := step59.g            -- divstep!(last), invocation 59 output
  -- divstep!(last), invocation 59 output: fl = step59.fl is never read
  let b00 := addw pf 1048576    -- add b00,pf,#0x100,lsl #12
  let b00 := sbfx b00 22 21     -- sbfx b00,b00,#22,#21
  let b11 := 1048576            -- mov b11,#0x100000
  let b11 := addw b11 (lsl b11 21)  -- add b11,b11,b11,lsl #21
  let b01 := addw pf b11        -- add b01,pf,b11
  let b01 := asr b01 43         -- asr b01,b01,#43
  let b10 := addw pg 1048576    -- add b10,pg,#0x100,lsl #12
  let b10 := sbfx b10 22 21     -- sbfx b10,b10,#22,#21
  let b11 := addw pg b11        -- add b11,pg,b11
  let b11 := asr b11 43         -- asr b11,b11,#43
  let f := mneg b00 a00         -- mneg f,b00,a00
  let g := mneg b00 a01         -- mneg g,b00,a01
  let pf := mneg b10 a00        -- mneg pf,b10,a00
  let pg := mneg b10 a01        -- mneg pg,b10,a01
  let u := msub b01 c10 f       -- msub u,b01,c10,f
  let v := msub b01 c11 g       -- msub v,b01,c11,g
  let q := msub b11 c10 pf      -- msub q,b11,c10,pf
  let r := msub b11 c11 pg      -- msub r,b11,c11,pg
  ⟨two_delta, u, v, q, r⟩

/-- The result of `signMagBlock`: the magnitudes `u`, `v`, `q`, and `r` of the matrix entries and
their sign masks `su`, `sv`, `sq`, and `sr`. -/
structure SignMag where
  u : Nat
  v : Nat
  q : Nat
  r : Nat
  su : Nat
  sv : Nat
  sq : Nat
  sr : Nat
  deriving DecidableEq, Repr

/-- The inline `asm!` block of `sign_mag`: the sign-magnitude form of the four entries of a
transition matrix, each entry's magnitude and its sign as a mask (all ones when negative, else
zero), which the row blocks take. -/
def signMagBlock (u v q r : Nat) : SignMag :=
  let u := u                    -- argument
  let v := v                    -- argument
  let q := q                    -- argument
  let r := r                    -- argument
  let fl := cmpFlags u 0        -- cmp u,xzr
  let su := csetmMi fl          -- csetm su,mi
  let u := cnegMi fl u          -- cneg u,u,mi
  let fl := cmpFlags v 0        -- cmp v,xzr
  let sv := csetmMi fl          -- csetm sv,mi
  let v := cnegMi fl v          -- cneg v,v,mi
  let fl := cmpFlags q 0        -- cmp q,xzr
  let sq := csetmMi fl          -- csetm sq,mi
  let q := cnegMi fl q          -- cneg q,q,mi
  let fl := cmpFlags r 0        -- cmp r,xzr
  let sr := csetmMi fl          -- csetm sr,mi
  let r := cnegMi fl r          -- cneg r,r,mi
  ⟨u, v, q, r, su, sv, sq, sr⟩

end PastaCurves.AArch64
