[book]
authors = [
    "Jack Grigg",
    "Sean Bowe",
    "Daira Hopwood",
    "Ying Tong Lai",
    "Danny Willems",
    "Kris Nuttycombe",
]
language = "en"
src = "src"
title = "The Pasta Book"

[preprocessor.katex]
